Repository erlang/otp, pull requests merged in 2018-07, with the labels that each got.

#1854 Allow carrier migration between different allocator types
  erts/doc/src/erts_alloc.xml
  erts/emulator/beam/erl_alloc.c
  erts/emulator/beam/erl_alloc.h
  erts/emulator/beam/erl_alloc_util.c
  erts/emulator/beam/erl_alloc_util.h
  erts/emulator/beam/erl_ao_firstfit_alloc.c
  erts/emulator/beam/erl_ao_firstfit_alloc.h
  erts/emulator/internal_doc/CarrierMigration.md
  erts/emulator/test/alloc_SUITE.erl
  erts/emulator/test/driver_SUITE.erl
  erts/emulator/test/erts_debug_SUITE.erl
  erts/emulator/test/process_SUITE.erl
  erts/emulator/test/system_info_SUITE.erl
  erts/preloaded/ebin/erlang.beam
  erts/preloaded/src/erlang.erl
  lib/kernel/src/erts_debug.erl
  lib/stdlib/test/ets_SUITE.erl
  lib/tools/doc/src/instrument.xml
  lib/tools/test/instrument_SUITE.erl
Labels: enhancement, team:VM

#1865 fix some errors in code samples for gen_statem behaviour
  system/doc/design_principles/statem.xml
Labels: team:PS

#1851 beam_type: Fix unsafe optimization
  lib/compiler/src/beam_type.erl
  lib/compiler/test/beam_type_SUITE.erl
Labels: fix, team:VM, testing

#1852 Fix internal compiler error for map_get/2
  lib/compiler/src/beam_validator.erl
  lib/compiler/test/map_SUITE.erl
Labels: fix, team:VM, testing

#1856 Eliminate a crash in the beam_jump pass
  lib/compiler/src/beam_utils.erl
  lib/compiler/test/beam_utils_SUITE.erl
Labels: fix, team:VM, testing

#1859 Include question mark in query string on redirect
  lib/inets/src/http_client/httpc_response.erl
Labels: team:PS

#1866 Ingela/ssl/psk hash sign selection/erl 641
  lib/ssl/doc/src/ssl.xml
  lib/ssl/src/ssl_connection.erl
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/test/ssl_basic_SUITE.erl
  lib/ssl/test/ssl_test_lib.erl
Labels: team:PS, testing

#1867 Ingela/ssl/no ca sign restriction tls 1.2/erl 381/otp 15173
  lib/ssl/src/ssl_cipher.erl
  lib/ssl/src/ssl_connection.erl
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/test/ssl_ECC_SUITE.erl
  lib/ssl/test/ssl_ECC_openssl_SUITE.erl
  lib/ssl/test/ssl_test_lib.erl
Labels: team:PS, testing

#1862 httpc 301 redirect: Do not assert scheme ports are equal
  lib/inets/src/http_client/httpc_response.erl
  lib/inets/test/httpc_SUITE.erl
Labels: team:PS

#1869 ssl: Improve error handling
  lib/ssl/doc/src/ssl.xml
  lib/ssl/src/dtls_connection.erl
  lib/ssl/src/ssl_connection.erl
  lib/ssl/src/tls_connection.erl
  lib/ssl/test/ssl_basic_SUITE.erl
Labels: team:PS, testing

#1870 Fix net_kernel:connect_node/1 to local node
  lib/kernel/doc/src/net_kernel.xml
  lib/kernel/src/net_kernel.erl
  lib/kernel/test/erl_distribution_SUITE.erl
Labels: fix, team:VM, testing

#1873 Fix typo in logger docs
  lib/kernel/doc/src/logger_chapter.xml
Labels: team:MW, testing

#1871 Preprend PERL with /usr/bin/env
  make/make_emakefile.in
Labels: fix, team:VM, testing

#1812 Optimise creation of anonymous functions
  erts/doc/src/erlang.xml
  erts/emulator/beam/beam_load.c
  erts/emulator/beam/break.c
  erts/emulator/beam/erl_init.c
  erts/emulator/beam/erl_process_dump.c
  erts/emulator/test/code_SUITE.erl
  erts/emulator/test/code_SUITE_data/literals.erl
  erts/emulator/test/fun_SUITE.erl
  lib/stdlib/test/lists_SUITE.erl
Labels: enhancement, team:VM, testing

#1875 Fix a crash when compiling variable-sized binary comprehensions
  lib/compiler/src/v3_core.erl
  lib/compiler/test/bs_bincomp_SUITE.erl
Labels: fix, team:VM, testing

#1881 fix return type of mnesia:change_config
  lib/mnesia/src/mnesia.erl
Labels: fix, team:MW, testing, waiting

#1887 Fix typo in xmerl_scan:string/1
  lib/xmerl/src/xmerl_scan.erl
Labels: fix, team:PS

#1886 Refactor maps.erl
  lib/dialyzer/test/small_SUITE_data/results/maps_sum
  lib/stdlib/doc/src/maps.xml
  lib/stdlib/src/maps.erl
Labels: enhancement, team:VM, testing

#1877 erts: Fix bug where break would not trigger on windows
  erts/emulator/sys/win32/erl_poll.c
Labels: team:VM

#1897 erl_alloc: align ErtsAllocatorState_t
  erts/emulator/beam/erl_alloc.c
Labels: fix, team:VM, testing
