Repository erlang/otp, pull requests merged in 2018-05, with the labels that each got.

#1766 Move erl_types test into a common_test suite
  lib/hipe/cerl/erl_types.erl
  lib/hipe/test/Makefile
  lib/hipe/test/erl_types_SUITE.erl
Labels: team:MW, testing

#1802 Introduce is_map_key/2 guard BIF
  erts/doc/src/erlang.xml
  erts/doc/src/match_spec.xml
  erts/emulator/beam/bif.tab
  erts/emulator/beam/erl_db_util.c
  erts/emulator/beam/erl_map.c
  erts/emulator/test/map_SUITE.erl
  erts/emulator/test/match_spec_SUITE.erl
  erts/preloaded/src/erlang.erl
  lib/compiler/src/beam_dead.erl
  lib/compiler/src/beam_peep.erl
  lib/compiler/src/beam_type.erl
  lib/compiler/src/erl_bifs.erl
  lib/compiler/src/v3_codegen.erl
  lib/compiler/test/map_SUITE.erl
  lib/hipe/cerl/erl_bif_types.erl
  lib/stdlib/src/erl_internal.erl
  lib/stdlib/src/ms_transform.erl
  lib/tools/emacs/erlang.el
Labels: feature, team:VM, testing

#1800 Fix syntactic issues in EDoc comments across some libs
  lib/compiler/src/cerl_trees.erl
  lib/edoc/src/edoc_doclet.erl
  lib/kernel/src/hipe_unified_loader.erl
Labels: team:MW, testing

#1813 Fix typos in erl_driver.xml
  erts/doc/src/erl_driver.xml
Labels: team:VM

#1811 Disable the use of floating point exceptions
  erts/configure.in
  erts/emulator/Makefile.in
Labels: fix, team:VM, testing

#1694 epmd: allow alternative to dns resolving for nodename
  erts/doc/src/Makefile
  erts/doc/src/alt_disco.xml
  erts/doc/src/part.xml
  erts/emulator/test/distribution_SUITE.erl
  lib/kernel/doc/src/Makefile
  lib/kernel/doc/src/erl_epmd.xml
  lib/kernel/doc/src/ref_man.xml
  lib/kernel/doc/src/specs.xml
  lib/kernel/src/erl_epmd.erl
  lib/kernel/src/inet_tcp_dist.erl
  lib/ssl/src/inet_tls_dist.erl
Labels: feature, team:VM, testing

#1817 Optimize string lowercase, uppercase and casefold for ASCII characters
  lib/stdlib/src/string.erl
  lib/stdlib/test/string_SUITE.erl
Labels: team:MW, testing

#1819 Fix bug in enif_binary_to_term for immediates
  erts/emulator/beam/erl_nif.c
  erts/emulator/test/nif_SUITE.erl
  erts/emulator/test/nif_SUITE_data/nif_SUITE.c
Labels: fix, team:VM, testing

#1810 Add ?OTP_RELEASE, -if and -elif to the preprocessor
  lib/stdlib/src/epp.erl
  lib/stdlib/test/epp_SUITE.erl
  lib/syntax_tools/src/epp_dodger.erl
  lib/syntax_tools/src/erl_prettypr.erl
  lib/syntax_tools/src/erl_syntax_lib.erl
  system/doc/reference_manual/macros.xml
Labels: team:VM, testing

#1818 dialyzer: Do not emit warnings for unreachable funs
  lib/dialyzer/src/dialyzer_dataflow.erl
  lib/dialyzer/test/small_SUITE_data/results/unused_funs
  lib/dialyzer/test/small_SUITE_data/src/unused_funs.erl
Labels: team:MW

#1788 public_key: PKCS8 encoded private key support
  lib/public_key/src/pubkey_pem.erl
  lib/public_key/src/public_key.erl
  lib/public_key/test/pbe_SUITE.erl
  lib/public_key/test/public_key_SUITE.erl
  lib/public_key/test/public_key_SUITE_data/dsa_key_pkcs8.pem
  lib/public_key/test/public_key_SUITE_data/ec_key_pkcs8.pem
  lib/public_key/test/public_key_SUITE_data/rsa_key_pkcs8.pem
Labels: team:PS, testing

#1821 ssl: Generalize DTLS packet multiplexing
  lib/ssl/src/Makefile
  lib/ssl/src/dtls_connection.erl
  lib/ssl/src/dtls_listener_sup.erl
  lib/ssl/src/dtls_packet_demux.erl
  lib/ssl/src/dtls_socket.erl
  lib/ssl/src/ssl.app.src
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_connection_sup.erl
  lib/ssl/src/ssl_internal.hrl
Labels: team:PS, testing
