Repository erlang/otp, pull requests merged in 2018-03, with the labels that each got.

#1718 Inline more type test BIFs in HiPE
  lib/hipe/icode/hipe_icode_inline_bifs.erl
Labels: enhancement, team:VM, testing

#1702 ERL-558 Add the missing function clause for string:prefix
  lib/stdlib/src/string.erl
  lib/stdlib/test/string_SUITE.erl
Labels: team:MW, testing

#1731 Fix beam_utils bugs that could cause problems in the future
  lib/compiler/src/beam_utils.erl
Labels: fix, team:VM, testing

#1560 add option to not check sys.config file when building tarball
  lib/sasl/doc/src/release_handler.xml
  lib/sasl/doc/src/systools.xml
  lib/sasl/src/systools_make.erl
  lib/sasl/test/systools_SUITE.erl
  system/doc/design_principles/release_structure.xml
  system/doc/system_principles/create_target.xmlsrc
Labels: team:MW, testing

#1724 Export types documented for http_uri module
  lib/inets/doc/src/http_uri.xml
  lib/inets/src/http_lib/http_uri.erl
Labels: team:PS

#1733 Cleanup erlang:system_info docs
  erts/doc/src/erlang.xml
  erts/doc/src/notes.xml
  erts/preloaded/src/erlang.erl
Labels: enhancement, team:VM

#1730 Ignore SIGTERM in erl_child_setup
  erts/emulator/sys/unix/erl_child_setup.c
Labels: fix, team:VM

#1732 Refactor and fix minor bugs in beam_type
  lib/compiler/src/beam_block.erl
  lib/compiler/src/beam_type.erl
  lib/compiler/test/beam_type_SUITE.erl
Labels: enhancement, team:VM, testing

#1737 Improve documentation of io:format ~p when Unicode is involved
  lib/stdlib/doc/src/io.xml
Labels: enhancement, team:MW, testing

#1741 Do not treat binaries as top level in dbg_ieval
  lib/debugger/src/dbg_ieval.erl
  lib/debugger/test/int_eval_SUITE.erl
  lib/debugger/test/int_eval_SUITE_data/my_int_eval_module.erl
Labels: team:MW, testing

#1735 Make io_lib:unscan_format/1 work with pad char and default precision
  lib/stdlib/src/io_lib_format.erl
  lib/stdlib/test/io_SUITE.erl
Labels: team:MW, testing

#1743 Allow multiple modifier characters in io:format control sequences
  lib/stdlib/doc/src/io.xml
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/src/io_lib_format.erl
  lib/stdlib/test/io_SUITE.erl
Labels: team:MW, testing

#1699 Remove low memory need for HiPE on x86_64
  erts/doc/src/erts_alloc.xml
  erts/emulator/beam/erl_alloc.c
  erts/emulator/beam/erl_alloc_util.c
  erts/emulator/beam/erl_alloc_util.h
  erts/emulator/sys/common/erl_mmap.c
  erts/emulator/sys/common/erl_mmap.h
  erts/emulator/sys/common/erl_mseg.c
  erts/emulator/sys/common/erl_mseg.h
Labels: feature, team:VM, testing

#1739 inets: fix scheme validation in http_uri:parse when binary URI
  lib/inets/src/http_lib/http_uri.erl
  lib/inets/test/uri_SUITE.erl
Labels: team:PS

#1745 make erlang:process_info/1 not retrieve messages
  erts/doc/src/erlang.xml
  erts/emulator/beam/erl_bif_info.c
  lib/common_test/src/test_server_ctrl.erl
  lib/dialyzer/test/r9c_SUITE_data/src/mnesia/mnesia_tm.erl
  lib/mnesia/src/mnesia_tm.erl
  lib/stdlib/src/c.erl
Labels: enhancement, team:VM, testing

#1748 More typos
  lib/common_test/src/test_server_ctrl.erl
  lib/kernel/src/disk_log_1.erl
  lib/xmerl/test/xmerl_SUITE_data/eventp/CMOM.xml
  lib/xmerl/test/xmerl_SUITE_data/eventp/CelloMOM.xml
Labels: team:MW, testing

#1742 Short-circuit code:ensure_loaded for already-loaded modules
  lib/kernel/src/code.erl
Labels: team:MW, testing

#1744 stdlib: Add function lists:search/2
  lib/stdlib/doc/src/lists.xml
  lib/stdlib/src/lists.erl
  lib/stdlib/test/lists_SUITE.erl
Labels: team:MW

#1705 kernel: in the group added processing of 'EXIT' signal from shell
  lib/kernel/src/group.erl
Labels: team:MW, team:PS

#1755 Point out the correct line in an exception for a bad generator
  lib/compiler/src/v3_core.erl
  lib/compiler/test/lc_SUITE.erl
Labels: fix, team:VM, testing

#1757 Documentation Typo
  lib/runtime_tools/doc/src/dbg.xml
Labels: team:VM

#1761 Stop the compiler from overflowing the atom table
  lib/compiler/src/beam_clean.erl
  lib/compiler/src/cerl_inline.erl
  lib/compiler/src/cerl_trees.erl
  lib/compiler/src/sys_core_fold.erl
  lib/compiler/src/v3_codegen.erl
  lib/compiler/src/v3_core.erl
  lib/compiler/src/v3_kernel.erl
  lib/dialyzer/test/small_SUITE_data/results/fun_arity
Labels: enhancement, team:VM, testing

#1760 Lift the type restrictions on seq_trace token labels
  erts/emulator/beam/dist.c
  erts/emulator/beam/dist.h
  erts/emulator/beam/erl_bif_trace.c
  erts/emulator/beam/erl_db_util.c
  erts/emulator/beam/erl_message.c
  erts/emulator/beam/erl_proc_sig_queue.c
  erts/emulator/beam/erl_process.h
  erts/emulator/beam/erlang_dtrace.d
  erts/emulator/beam/msg_instrs.tab
  erts/emulator/beam/sys.h
  lib/kernel/doc/src/seq_trace.xml
  lib/kernel/include/dist.hrl
  lib/kernel/src/dist_util.erl
  lib/kernel/src/seq_trace.erl
  lib/kernel/test/seq_trace_SUITE.erl
Labels: team:VM, testing
