Repository erlang/otp, pull requests merged in 2018-06, with the labels that each got.

#1806 Fix typos in erlang.xml
  erts/doc/src/erlang.xml
Labels: team:VM, testing

#1827 dialyzer: Refine the test for overspecified functions
  lib/dialyzer/src/dialyzer.erl
  lib/dialyzer/src/dialyzer_contracts.erl
  lib/dialyzer/src/typer.erl
  lib/dialyzer/test/overspecs_SUITE_data/dialyzer_options
  lib/dialyzer/test/overspecs_SUITE_data/results/iodata
  lib/dialyzer/test/overspecs_SUITE_data/results/iolist
  lib/dialyzer/test/overspecs_SUITE_data/src/iodata.erl
  lib/dialyzer/test/overspecs_SUITE_data/src/iolist.erl
  lib/dialyzer/test/specdiffs_SUITE_data/dialyzer_options
  lib/dialyzer/test/specdiffs_SUITE_data/results/iodata
  lib/dialyzer/test/specdiffs_SUITE_data/results/iolist
  lib/dialyzer/test/specdiffs_SUITE_data/src/iodata.erl
  lib/dialyzer/test/specdiffs_SUITE_data/src/iolist.erl
Labels: team:MW

#1823 ERL-629 Do not free() module buffer until it has been used
  lib/erl_interface/src/prog/erl_call.c
Labels: fix, team:VM, testing

#1828 do not call abort_signal_task() with invalid data
  erts/emulator/beam/erl_port_task.c
Labels: fix, team:VM, testing

#1832 Revert "Run the sharing optimisation in beam_jump until fixpoint"
  lib/compiler/src/beam_jump.erl
Labels: fix, team:VM, testing

#1834 stdlib: Make pP insert no line breaks with field width zero
  lib/stdlib/doc/src/io.xml
  lib/stdlib/src/io_lib_pretty.erl
  lib/stdlib/test/io_SUITE.erl
Labels: team:MW

#1815 Maps inconsistency from 20.0 to OTP-21.0-rc1-84-gfefb15c576
  lib/stdlib/test/maps_SUITE.erl
Labels: fix, team:VM, testing

#1826 Fix use-after-free on Windows in escript
  erts/etc/common/escript.c
Labels: fix, team:VM, testing

#1808 Add how-to for cross compilation to Raspberry Pi 3
  HOWTO/INSTALL-RASPBERRYPI3.md
  xcomp/erl-xcomp-armv8-rpi3-linux-gnueabihf.conf
Labels: enhancement, team:VM, testing

#1771 Explain why the AM becomes group leader
  erts/doc/src/erlang.xml
  lib/kernel/doc/src/application.xml
  lib/kernel/src/application_master.erl
  system/doc/design_principles/applications.xml
Labels: team:MW, testing

#1837 Fix a crash in HiPE's lazy code motion pass
  lib/hipe/rtl/hipe_rtl_lcm.erl
  lib/hipe/test/basic_SUITE_data/basic_issues_hipe.erl
Labels: fix, team:VM, testing

#1840 uri_string: support key without value in query string
  lib/stdlib/src/uri_string.erl
  lib/stdlib/test/uri_string_SUITE.erl
Labels: team:PS, testing

#1833 Optimise beam_jump
  lib/compiler/src/beam_jump.erl
Labels: enhancement, team:VM, testing

#1717 Fold is_function/1,2 during compilation
  lib/compiler/src/erl_bifs.erl
  lib/compiler/src/sys_core_fold.erl
  lib/compiler/test/core_fold_SUITE.erl
Labels: enhancement, team:VM, testing

#1848 Add missing bracket to erlang:spawn_opt/4 docs priority tuple option
  erts/doc/src/erlang.xml
Labels: team:MW, testing

#1844 Use erlang:system_info(ets_count) and improve docs
  erts/doc/src/erlang.xml
  erts/preloaded/src/erlang.erl
  lib/runtime_tools/src/observer_backend.erl
  lib/stdlib/test/beam_lib_SUITE.erl
  lib/tools/test/xref_SUITE.erl
Labels: fix, team:VM, testing

#1853 Fix typo in erl_parse type unary_op()
  lib/stdlib/src/erl_parse.yrl
Labels: team:MW, testing

#1842 Small fixes in syntax_tools
  lib/syntax_tools/src/erl_syntax.erl
  lib/syntax_tools/test/syntax_tools_SUITE.erl
Labels: team:MW, testing
