Repository erlang/otp, pull requests merged in 2018-02, with the labels that each got.

#1709 ssl: Add the unexpected message to #alert{}
  lib/ssl/src/ssl_connection.erl
Labels: team:PS, testing

#1713 Fix unsafe use of 'allocate' where 'allocate_zero' should be used
  lib/compiler/src/beam_block.erl
  lib/compiler/src/beam_utils.erl
Labels: fix, team:VM, testing

#1712 Check that the stack is initialized when an exception may occur
  lib/compiler/src/beam_validator.erl
Labels: fix, team:VM

#1700 Combine blocks when running beam_block the second time
  lib/compiler/src/beam_block.erl
  lib/compiler/src/beam_clean.erl
  lib/compiler/src/beam_flatten.erl
  lib/compiler/src/beam_split.erl
Labels: enhancement, team:VM, testing

#1716 Reject loading modules with slash in name
  erts/preloaded/ebin/erl_prim_loader.beam
  erts/preloaded/src/erl_prim_loader.erl
  lib/kernel/src/code_server.erl
  lib/kernel/src/kernel.app.src
Labels: fix, team:VM, testing

#1708 Optimize non-strict equality check of binaries differing in size
  erts/emulator/beam/utils.c
Labels: enhancement, team:VM, testing

#1723 Add ets:whereis/1 for resolving table names -> tid()
  erts/emulator/beam/bif.tab
  erts/emulator/beam/erl_db.c
  lib/stdlib/doc/src/ets.xml
  lib/stdlib/src/ets.erl
  lib/stdlib/test/ets_SUITE.erl
Labels: team:VM, testing

#1719 Compute MD5s in dialyzer using the .beam file
  lib/dialyzer/src/dialyzer_plt.erl
  lib/stdlib/src/beam_lib.erl
Labels: team:MW, testing

#1726 Fix example MIB in the documentation
  lib/snmp/doc/src/snmp_impl_example_agent.xml
Labels: team:PS, testing
