Repository erlang/otp, pull requests merged in 2018-12, with the labels that each got.

#2039 erts: Fix copy of literal msg during gc
  erts/emulator/beam/erl_gc.c
  lib/kernel/test/seq_trace_SUITE.erl
Labels: fix, team:VM, testing

#2042 Fix unsafe optimization of stack trace building
  lib/compiler/src/sys_core_fold.erl
  lib/compiler/test/trycatch_SUITE.erl
Labels: fix, team:VM

#2043 beam_ssa_pre_codegen: Fix an internal consistency failure
  lib/compiler/src/beam_ssa_pre_codegen.erl
  lib/compiler/test/beam_ssa_SUITE.erl
Labels: fix, team:VM

#2046 Mark free blocks in pooled carriers as unused
  erts/configure.in
  erts/emulator/beam/erl_afit_alloc.c
  erts/emulator/beam/erl_alloc_util.c
  erts/emulator/beam/erl_alloc_util.h
  erts/emulator/beam/erl_ao_firstfit_alloc.c
  erts/emulator/beam/erl_bestfit_alloc.c
  erts/emulator/beam/erl_goodfit_alloc.c
  erts/emulator/sys/common/erl_mmap.h
  erts/emulator/sys/win32/sys.c
Labels: enhancement, team:VM

#2041 Fix --without-APP config option
  configure.src
Labels: fix, team:VM, testing

#2051 Fix reading beyond end of bignum in integer squaring
  erts/emulator/beam/big.c
  erts/emulator/test/big_SUITE.erl
Labels: fix, team:VM

#2047 Simplify implementation of GC BIFs
  erts/emulator/beam/arith_instrs.tab
  erts/emulator/beam/beam_debug.c
  erts/emulator/beam/beam_emu.c
  erts/emulator/beam/beam_load.c
  erts/emulator/beam/bif.tab
  erts/emulator/beam/bif_instrs.tab
  erts/emulator/beam/erl_arith.c
  erts/emulator/beam/erl_bif_binary.c
  erts/emulator/beam/erl_bif_guard.c
  erts/emulator/beam/erl_binary.h
  erts/emulator/beam/erl_map.c
  erts/emulator/beam/erl_vm.h
  erts/emulator/beam/ops.tab
  erts/emulator/utils/beam_makeops
Labels: enhancement, team:VM, testing

#2050 Fix typos in atomics.xml and counters.xml
  erts/doc/src/atomics.xml
  erts/doc/src/counters.xml
Labels: fix, team:VM, testing

#2057 Add missing annotations in instrs.tab
  erts/emulator/beam/instrs.tab
Labels: enhancement, team:VM, testing

#2053 Make length/1 yielding
  erts/emulator/beam/bif_instrs.tab
  erts/emulator/beam/erl_bif_guard.c
  erts/emulator/beam/erl_db_util.c
  erts/emulator/beam/erl_init.c
  erts/emulator/beam/erl_vm.h
  erts/emulator/beam/global.h
  erts/emulator/beam/ops.tab
  erts/emulator/test/bif_SUITE.erl
Labels: enhancement, team:VM, testing

#2061 erts: Fix possible heap corruption getting atomics
  erts/emulator/beam/erl_bif_atomics.c
  erts/emulator/test/atomics_SUITE.erl
Labels: fix, team:VM

#2064 Observer: fix crash bug when expanding term
  lib/observer/src/cdv_html_wx.erl
Labels: team:MW, testing
