Repository erlang/otp, pull requests merged in 2018-08, with the labels that each got.

#1876 Fix inet driver realloc bug
  erts/emulator/drivers/common/inet_drv.c
  lib/kernel/doc/src/inet.xml
  lib/kernel/test/gen_udp_SUITE.erl
Labels: fix, team:VM

#1846 Fix seq_trace to not clear token for system messages
  erts/emulator/beam/beam_bif_load.c
  erts/emulator/beam/beam_debug.c
  erts/emulator/beam/bif.c
  erts/emulator/beam/dist.c
  erts/emulator/beam/erl_db.c
  erts/emulator/beam/erl_message.c
  erts/emulator/beam/erl_message.h
  erts/emulator/beam/erl_nif.c
  erts/emulator/beam/erl_proc_sig_queue.c
  erts/emulator/beam/erl_process.c
  erts/emulator/beam/io.c
  erts/emulator/sys/common/erl_check_io.c
  erts/emulator/test/nif_SUITE.erl
  lib/kernel/test/seq_trace_SUITE.erl
Labels: fix, team:VM

#1807 Improve Cover HTML page
  lib/tools/priv/styles.css
  lib/tools/src/Makefile
  lib/tools/src/cover.erl
Labels: team:MW, testing

#1872 Fix kernel_app doc logger_level defaults
  lib/kernel/doc/src/kernel_app.xml
Labels: team:MW, testing

#1906 Update documentation for ct:timetrap/1
  lib/common_test/doc/src/ct.xml
Labels: team:MW

#1904 Rewrite erlang:get_stacktrace calls to primop when safe
  lib/compiler/src/sys_core_fold.erl
Labels: enhancement, team:VM, testing

#1910 Fix side-effect optimization when compiling from Core Erlang
  lib/compiler/src/sys_core_fold.erl
  lib/compiler/test/core_SUITE.erl
  lib/compiler/test/core_SUITE_data/fun_letrec_effect.core
  lib/compiler/test/core_fold_SUITE.erl
Labels: fix, team:VM, testing

#1902 Ref ordering fix (ERL-690)
  erts/emulator/beam/utils.c
  erts/emulator/test/ref_SUITE.erl
Labels: fix, team:VM, testing

#1917 Document how utf8 atoms are ordered
  system/doc/reference_manual/expressions.xml
Labels: team:VM

#1899 Fixes ERL-675
  lib/crypto/c_src/crypto.c
Labels: fix, team:PS, testing

#1919 Correct error behavior of is_map_key/2 in guards
  lib/compiler/src/v3_codegen.erl
  lib/compiler/test/map_SUITE.erl
  lib/stdlib/src/erl_internal.erl
Labels: fix, team:VM, testing

#1836 Fix some unmatched_return warnings
  lib/common_test/src/ct_release_test.erl
  lib/common_test/src/ct_util.erl
  lib/common_test/src/cth_log_redirect.erl
Labels: team:MW, testing

#1858 Fix delete_object and write convergence in transaction.
  lib/mnesia/src/mnesia.erl
  lib/mnesia/test/mnesia_isolation_test.erl
Labels: team:MW, testing

#1843 Add logger:set_application_level/2
  lib/kernel/doc/src/logger.xml
  lib/kernel/src/logger.erl
  lib/kernel/src/logger_server.erl
  lib/kernel/test/logger_SUITE.erl
Labels: feature, testing

#1918 erts: Delete fd from poll-set when closing fd_driver port
  erts/emulator/sys/unix/sys_drivers.c
Labels: fix, team:VM, testing

#1927 Fix compiler crash when compiling double receives
  lib/compiler/src/beam_utils.erl
  lib/compiler/test/receive_SUITE.erl
Labels: fix, team:VM, testing

#1803 Optimize binary match from 10% up to 70x
  erts/emulator/beam/erl_bif_binary.c
  lib/stdlib/test/stdlib.spec
  lib/stdlib/test/stdlib_bench_SUITE.erl
Labels: enhancement, team:VM, testing

#1728 Add Erlang alignment regexps
  lib/tools/emacs/erlang.el
Labels: team:MW, testing

#1934 erts/time_correction.xml: remove extra closing parenthesis
  erts/doc/src/time_correction.xml
Labels: team:VM

#1569 Prevent BEAM crash when message being sent via dist is larger than 2Gb
  erts/emulator/beam/bif.c
  erts/emulator/beam/dist.c
  erts/emulator/beam/dist.h
Labels: enhancement, team:VM, testing

#1932 Do not allocate good and bad shifts for single byte lookups
  erts/emulator/beam/erl_bif_binary.c
Labels: feature, team:VM, testing

#1863 Document allowed integer ops in types
  system/doc/reference_manual/typespec.xml
Labels: team:MW, testing

#1940 stdlib: Let dets:open_file() crash when given raw file name
  lib/stdlib/src/dets.erl
  lib/stdlib/test/dets_SUITE.erl
Labels: team:MW

#1936 Fix kernel_app doc logger_level default from info to notice
  lib/kernel/doc/src/logger_chapter.xml
Labels: team:MW, testing

#1894 Update httpc_manager.erl to fix typo
  lib/inets/src/http_client/httpc_manager.erl
Labels: fix, team:PS

#1944 dialyzer: Improve handling of complex guards
  lib/compiler/src/v3_core.erl
  lib/dialyzer/test/small_SUITE_data/results/left_assoc
  lib/dialyzer/test/small_SUITE_data/src/left_assoc.erl
Labels: team:MW
