Repository erlang/otp, pull requests merged in 2019-02, with the labels that each got.

#2117 Fix spec for erl_epmd:port_please
  lib/kernel/src/erl_epmd.erl
Labels: fix, team:VM, testing

#2122 Fix internal consistency failure caused by beam_except
  lib/compiler/src/beam_except.erl
  lib/compiler/test/beam_except_SUITE.erl
Labels: fix, team:VM, testing

#2095 crypto: revamp C code [WIP]
  lib/crypto/c_src/aead.c
  lib/crypto/c_src/aes.c
  lib/crypto/c_src/algorithms.c
  lib/crypto/c_src/block.c
  lib/crypto/c_src/bn.c
  lib/crypto/c_src/chacha20.c
  lib/crypto/c_src/check_erlang.cocci
  lib/crypto/c_src/check_openssl.cocci
  lib/crypto/c_src/cipher.c
  lib/crypto/c_src/cmac.c
  lib/crypto/c_src/common.h
  lib/crypto/c_src/crypto.c
  lib/crypto/c_src/crypto_callback.c
  lib/crypto/c_src/dh.c
  lib/crypto/c_src/digest.c
  lib/crypto/c_src/dss.c
  lib/crypto/c_src/ec.c
  lib/crypto/c_src/ecdh.c
  lib/crypto/c_src/eddsa.c
  lib/crypto/c_src/engine.c
  lib/crypto/c_src/evp.c
  lib/crypto/c_src/evp_compat.h
  lib/crypto/c_src/hash.c
  lib/crypto/c_src/hmac.c
  lib/crypto/c_src/info.c
  lib/crypto/c_src/info.h
  lib/crypto/c_src/math.c
  lib/crypto/c_src/openssl_config.h
  lib/crypto/c_src/otp_test_engine.c
  lib/crypto/c_src/pkey.c
  lib/crypto/c_src/poly1305.c
  lib/crypto/c_src/rand.c
  lib/crypto/c_src/rc4.c
  lib/crypto/c_src/rsa.c
  lib/crypto/c_src/srp.c
Labels: team:PS, waiting

#2125 Expand rr support in cerl and etp
  erts/etc/unix/Makefile
  erts/etc/unix/cerl.src
  erts/etc/unix/etp-commands.in
  erts/etc/unix/etp-rr-run-until-beam.py
Labels: enhancement, team:VM, testing

#2132 Keep track of tuple elements in type optimization pass
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/beam_ssa_pre_codegen.erl
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/src/beam_validator.erl
  lib/compiler/test/match_SUITE.erl
Labels: enhancement, team:VM

#2127 Add enif_make_monitor_term
  erts/doc/src/erl_nif.xml
  erts/emulator/beam/erl_nif.c
  erts/emulator/beam/erl_nif_api_funcs.h
  erts/emulator/test/nif_SUITE.erl
  erts/emulator/test/nif_SUITE_data/nif_SUITE.c
Labels: feature, team:VM, testing

#2129 Add hash function BLAKE2 to crypto:hash/hmac
  lib/crypto/c_src/algorithms.c
  lib/crypto/c_src/atoms.c
  lib/crypto/c_src/atoms.h
  lib/crypto/c_src/digest.c
  lib/crypto/c_src/openssl_config.h
  lib/crypto/doc/src/crypto.xml
  lib/crypto/src/crypto.erl
  lib/crypto/test/crypto_SUITE.erl
Labels: feature, team:PS, testing

#2135 Optimize ssa_opt_sink for huge functions
  lib/compiler/src/beam_ssa.erl
  lib/compiler/src/beam_ssa_bsm.erl
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/beam_ssa_pre_codegen.erl
Labels: enhancement, team:VM, testing

#2134 beam_ssa_type: Propagate the 'none' type from calls
  lib/compiler/src/beam_ssa_type.erl
  lib/debugger/test/int_eval_SUITE.erl
  lib/stdlib/test/erl_eval_SUITE.erl
Labels: enhancement, team:VM, testing

#2067 reltool: Add load_dot_erlang rel option
  lib/reltool/doc/src/reltool.xml
  lib/reltool/doc/src/reltool_examples.xml
  lib/reltool/src/reltool.hrl
  lib/reltool/src/reltool_server.erl
  lib/reltool/src/reltool_target.erl
  lib/reltool/test/reltool_server_SUITE.erl
Labels: team:MW, testing

#2121 Optimize calendar:gregorian_days_to_date/1
  lib/stdlib/src/calendar.erl
  lib/stdlib/test/calendar_SUITE.erl
Labels: team:MW

#2137 Use the counters module to speed up cover
  lib/common_test/src/ct_cover.erl
  lib/common_test/src/ct_run.erl
  lib/common_test/src/ct_util.hrl
  lib/compiler/test/compiler.cover
  lib/tools/doc/src/cover.xml
  lib/tools/src/cover.erl
  lib/tools/test/cover_SUITE.erl
Labels: enhancement, team:VM, testing

#2113 Optional tuple calls
  erts/doc/src/erl.xml
  erts/emulator/beam/beam_emu.c
  erts/emulator/beam/erl_init.c
  erts/emulator/beam/erl_vm.h
  erts/etc/common/erlexec.c
Labels: fix, team:VM, testing

#2118 Fix bug in binary:encode_unsigned causing a read of uninitialized memory
  erts/emulator/beam/erl_bif_binary.c
  lib/stdlib/test/binary_module_SUITE.erl
Labels: team:VM, testing

#2141 Make dialyzer faster for left-associative andalso/orelse expressions
  lib/compiler/src/v3_core.erl
Labels: fix, team:VM, testing

#2140 Add persistent_term:get(Key, DefaultValue)
  erts/doc/src/persistent_term.xml
  erts/emulator/beam/bif.tab
  erts/emulator/beam/erl_bif_persistent.c
  erts/emulator/test/persistent_term_SUITE.erl
  erts/preloaded/ebin/persistent_term.beam
  erts/preloaded/src/persistent_term.erl
Labels: feature, team:VM, testing

#2142 Remove support for optional tuple calls
  erts/doc/src/erl.xml
  erts/emulator/beam/beam_emu.c
  erts/emulator/beam/erl_init.c
  erts/emulator/beam/erl_vm.h
  erts/etc/common/erlexec.c
Labels: feature, team:VM, testing

#2139 Add ETS docs about partially bound key traversal
  lib/stdlib/doc/src/ets.xml
Labels: enhancement, team:VM, testing

#2102 Optimise ext table dumping
  lib/mnesia/src/mnesia_dumper.erl
Labels: team:MW, testing

#2136 dialyzer: Fix a bug regarding contracts
  lib/dialyzer/src/dialyzer_codeserver.erl
  lib/dialyzer/src/dialyzer_contracts.erl
  lib/dialyzer/src/dialyzer_utils.erl
  lib/dialyzer/test/small_SUITE_data/results/spec_other_module
  lib/dialyzer/test/small_SUITE_data/src/spec_other_module.erl
Labels: fix, team:MW

#2146 Do the destructive setelement optimization in SSA
  lib/compiler/src/Makefile
  lib/compiler/src/beam_kernel_to_ssa.erl
  lib/compiler/src/beam_ssa.erl
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/beam_ssa_pre_codegen.erl
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/src/compile.erl
  lib/compiler/src/compiler.app.src
  lib/compiler/src/sys_core_dsetel.erl
  lib/compiler/src/v3_kernel.erl
  lib/compiler/test/compile_SUITE.erl
  lib/compiler/test/misc_SUITE.erl
Labels: enhancement, team:VM, testing

#2144 Improve term_to_binary for list strings
  erts/emulator/beam/external.c
Labels: enhancement, team:VM, testing

#2149 Miscellaneous compiler improvements
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/src/erl_bifs.erl
  lib/compiler/src/v3_core.erl
Labels: enhancement, team:VM, testing

#2148 Fix a particular sed invocation in otp_build
  lib/common_test/test_server/configure.in
Labels: fix, team:VM, testing

#2152 beam_ssa_type: Use types from some 'lists' functions
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/src/beam_validator.erl
Labels: enhancement, team:VM

#2153 Clarify the atomic guarantees for ets:update_counter()
  lib/stdlib/doc/src/ets.xml
Labels: fix, team:VM, testing

#2147 Add enif_set_pid_undefined & enif_is_pid_undefined
  erts/doc/src/erl_nif.xml
  erts/emulator/beam/erl_nif.c
  erts/emulator/beam/erl_nif_api_funcs.h
  erts/emulator/sys/common/erl_check_io.c
  erts/emulator/test/nif_SUITE.erl
  erts/emulator/test/nif_SUITE_data/nif_SUITE.c
Labels: feature, team:VM, testing

#2138 gen_tcp, gen_udp: Update specs
  lib/kernel/src/gen_tcp.erl
  lib/kernel/src/gen_udp.erl
Labels: team:PS, testing

#2155 erts: Fix macro redefinition
  erts/emulator/beam/erl_ao_firstfit_alloc.c
  erts/emulator/beam/erl_bestfit_alloc.c
Labels: team:VM

#2156 Fix missing double quote in filename documentation
  lib/stdlib/doc/src/filename.xml
Labels: team:MW

#2056 gen_statem exports types related to starting & naming
  lib/stdlib/src/gen_statem.erl
Labels: team:PS, testing

#2124 Make iolist_size/1 yield
  erts/emulator/beam/bif.c
  erts/emulator/beam/erl_alloc.types
  erts/emulator/beam/erl_dirty_bif.tab
  erts/emulator/test/binary_SUITE.erl
  erts/emulator/test/emulator_bench.spec
Labels: enhancement, team:VM

#2150 edoc: Print a helpful message if reading source file fails
  lib/edoc/src/edoc.erl
Labels: team:MW
