Repository erlang/otp, pull requests merged in 2019-06, with the labels that each got.

#2246 Support printing of maps and funs in ei_print_term()
  lib/erl_interface/src/decode/decode_fun.c
  lib/erl_interface/src/decode/decode_skip.c
  lib/erl_interface/src/misc/ei_printterm.c
  lib/erl_interface/test/ei_decode_encode_SUITE.erl
  lib/erl_interface/test/ei_decode_encode_SUITE_data/ei_decode_encode_test.c
  lib/erl_interface/test/ei_print_SUITE.erl
  lib/erl_interface/test/ei_print_SUITE_data/ei_print_test.c
Labels: fix, team:VM, testing

#2269 ssl: Fix broken return value
  lib/ssl/src/ssl_connection.erl
  lib/ssl/test/ssl_test_lib.erl
Labels: team:PS, testing

#2268 ssl: Change check of DTLS record version
  lib/ssl/src/dtls_connection.erl
  lib/ssl/src/dtls_record.erl
Labels: team:PS, testing

#2264 Store file name as absolute path in logger_std_h
  lib/kernel/src/logger_std_h.erl
  lib/kernel/test/logger_std_h_SUITE.erl
Labels: team:MW

#2273 Fix SEGV crash on shell break (p)roc info
  erts/emulator/beam/break.c
Labels: fix, team:VM, testing

#2266 Fix hipe_flush_icache_range for FreeBSD on ARM
  erts/emulator/hipe/hipe_arm.c
Labels: fix, team:VM, testing

#2276 Implement ALPN in TLS 1.3
  lib/ssl/doc/src/standards_compliance.xml
  lib/ssl/src/ssl_connection.hrl
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/src/tls_connection_1_3.erl
  lib/ssl/src/tls_handshake_1_3.erl
  lib/ssl/test/ssl_basic_SUITE.erl
  lib/ssl/test/ssl_certificate_verify_SUITE.erl
  lib/ssl/test/ssl_test_lib.erl
Labels: team:PS

#2277 Fix SSL cb_info missing underscore in default
  lib/ssl/src/ssl.erl
Labels: team:PS

#2282 Fix some documentation typos
  erts/doc/src/crash_dump.xml
  erts/doc/src/driver.xml
  erts/doc/src/erl_ext_dist.xml
  erts/doc/src/zlib.xml
Labels: fix, team:VM, testing

#2281 Fix duplicated word "to" on Common Caveats doc
  system/doc/efficiency_guide/commoncaveats.xml
Labels: fix, team:VM, testing

#2274 cerl: Fix spelling error in a case of ctype()
  lib/compiler/src/cerl.erl
Labels: team:VM, testing

#2279 [trivial] specs_gen script fix error message
  lib/erl_docgen/priv/bin/specs_gen.escript
Labels: team:MW

#2261 Fix wxe_driver improper realloc call
  lib/wx/c_src/wxe_driver.c
Labels: testing

#2283 Allow native compilation when calling Dialyzer from Erlang
  lib/dialyzer/doc/src/dialyzer.xml
  lib/dialyzer/src/dialyzer.hrl
  lib/dialyzer/src/dialyzer_cl.erl
  lib/dialyzer/src/dialyzer_cl_parse.erl
  lib/dialyzer/src/dialyzer_options.erl
Labels: team:MW

#2206 inets: httpd_request - honor RFC2616 LF only as header line terminator
  lib/inets/src/http_server/httpd_request.erl
  lib/inets/test/http_format_SUITE.erl
Labels: team:PS, testing

#2272 Fix {active,N} close race condition on windows
  erts/emulator/drivers/common/inet_drv.c
  lib/kernel/test/gen_tcp_misc_SUITE.erl
Labels: fix, team:VM, testing

#2271 alt_dist docs: Correct the mf_getstat description
  erts/doc/src/alt_dist.xml
Labels: team:VM

#2270 Return real pend value in erlang:dist_get_stat/1
  erts/emulator/beam/dist.c
  erts/preloaded/src/erlang.erl
Labels: team:VM

#2110 Wake AIX up from coma
  erts/aclocal.m4
  erts/configure.in
  erts/emulator/beam/sys.h
  erts/emulator/beam/utils.c
  erts/emulator/nifs/common/socket_nif.c
  erts/emulator/sys/unix/erl_child_setup.c
  erts/emulator/sys/unix/sys.c
  erts/etc/unix/run_erl.c
  lib/erl_interface/include/ei.h
  lib/erl_interface/src/connect/ei_resolve.c
  lib/erl_interface/src/misc/ei_portio.c
Labels: feature, team:VM, testing

#2250 re unicode validation
  erts/emulator/beam/bif.tab
  erts/emulator/beam/erl_bif_re.c
  erts/emulator/pcre/pcre.h
  erts/emulator/pcre/pcre_exec.c
  erts/emulator/pcre/pcre_internal.h
  erts/emulator/pcre/pcre_valid_utf8.c
  lib/stdlib/src/re.erl
  lib/stdlib/src/stdlib.app.src
  lib/stdlib/test/re_SUITE.erl
Labels: fix, team:VM

#2303 Fix typo in logger_chapter.xml
  lib/kernel/doc/src/logger_chapter.xml
Labels: team:MW

#2305 Fix slow compilation of huge functions
  lib/compiler/src/beam_ssa.erl
Labels: fix, team:VM, testing

#2296 crypto: Fix the build of static crypto nifs
  lib/crypto/c_src/Makefile.in
Labels: team:PS, testing

#2297 Remove unused SSH definitions
  lib/ssh/src/ssh.hrl
Labels: team:PS, testing

#2311 erts: Update etp-stackump, stackmap and disasm
  erts/etc/unix/etp-commands.in
Labels: enhancement, team:VM

#2306 Optimize ordsets:union/1
  lib/stdlib/src/ordsets.erl
Labels: enhancement, team:VM, testing

#2299 Support local sockets with inet:i/0
  lib/kernel/src/inet.erl
Labels: team:PS
