Repository erlang/otp, pull requests merged in 2019-07, with the labels that each got.

#2286 Implement support for ECDSA certificates in TLS 1.3
  lib/ssl/doc/src/standards_compliance.xml
  lib/ssl/src/ssl_cipher.erl
  lib/ssl/src/tls_handshake_1_3.erl
  lib/ssl/test/ssl_basic_SUITE.erl
Labels: team:PS

#2313 Infinite cycle fixed on try to change run queue (if it has already ch…
  erts/emulator/beam/erl_process.h
Labels: fix, team:VM, testing

#2308 ERL-989: Fix typo in httpc_SUITE:content_length/1
  lib/inets/test/httpc_SUITE.erl
Labels: team:PS, testing

#2314 Collect unused vars instead of used ones
  lib/compiler/src/beam_ssa.erl
  lib/compiler/src/beam_ssa_pre_codegen.erl
Labels: team:VM, testing

#2318 Extend the compiler's type representation
  lib/compiler/src/beam_call_types.erl
  lib/compiler/src/beam_kernel_to_ssa.erl
  lib/compiler/src/beam_ssa.erl
  lib/compiler/src/beam_ssa.hrl
  lib/compiler/src/beam_ssa_bsm.erl
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/beam_ssa_pre_codegen.erl
  lib/compiler/src/beam_ssa_share.erl
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/src/beam_types.erl
  lib/compiler/src/beam_types.hrl
  lib/compiler/src/beam_validator.erl
  lib/compiler/test/beam_types_SUITE.erl
  lib/compiler/test/beam_validator_SUITE.erl
  lib/compiler/test/property_test/beam_types_prop.erl
Labels: enhancement, team:VM
