Repository erlang/otp, pull requests merged in 2019-03, with the labels that each got.

#2165 Optimize v3_kernel for thousands of clauses
  lib/compiler/src/v3_kernel.erl
Labels: enhancement, team:VM, testing

#2166 Optimize the beam_ssa_dead sub pass
  lib/compiler/src/beam_ssa_dead.erl
Labels: enhancement, team:VM, testing

#2167 Tune BEAM instructions for the new compiler (part 1)
  erts/emulator/beam/beam_load.c
  erts/emulator/beam/instrs.tab
  erts/emulator/beam/ops.tab
  erts/emulator/internal_doc/CountingInstructions.md
  lib/compiler/src/beam_ssa_opt.erl
Labels: enhancement, team:VM, testing

#2168 Move size=all binary clause pruning to v3_kernel
  lib/compiler/src/beam_kernel_to_ssa.erl
  lib/compiler/src/v3_kernel.erl
Labels: enhancement, team:VM, testing

#2164 Add application:set_env/1 and application:set_env/2
  lib/kernel/doc/src/application.xml
  lib/kernel/src/application.erl
  lib/kernel/src/application_controller.erl
  lib/kernel/test/application_SUITE.erl
Labels: feature, fix, team:MW, testing

#2158 Rewords one sentence in common_test documentation
  lib/common_test/doc/src/basics_chapter.xml
Labels: team:MW, testing

#2154 Change Logger timestamps from erlang:system_time to os:system_time
  erts/emulator/beam/utils.c
  erts/preloaded/src/erl_prim_loader.erl
  erts/preloaded/src/init.erl
  erts/preloaded/src/prim_file.erl
  lib/kernel/doc/src/logger.xml
  lib/kernel/src/code_server.erl
  lib/kernel/src/logger.erl
  lib/kernel/src/logger_h_common.erl
  lib/kernel/src/logger_simple_h.erl
  lib/kernel/test/logger_SUITE.erl
  lib/kernel/test/logger_formatter_SUITE.erl
Labels: team:MW

#2066 inet_db: fix a bug when .hosts file is never reloaded
  lib/kernel/src/inet_db.erl
  lib/kernel/test/inet_SUITE.erl
Labels: team:PS, testing, waiting

#2161 Remove 7-bit ASCII limitation in to_erl
  erts/etc/unix/to_erl.c
Labels: fix, team:VM, testing

#2163 Clarify in the docs that (NEW_)FLOAT_EXT must be finite
  erts/doc/src/erl_ext_dist.xml
Labels: fix, team:VM, testing

#2173 Add crypto:cipher_info/1 and crypto:hash_info/1
  lib/crypto/c_src/atoms.c
  lib/crypto/c_src/atoms.h
  lib/crypto/c_src/cipher.c
  lib/crypto/c_src/cipher.h
  lib/crypto/c_src/crypto.c
  lib/crypto/c_src/hash.c
  lib/crypto/c_src/hash.h
  lib/crypto/src/crypto.erl
  lib/crypto/test/crypto_SUITE.erl
Labels: team:PS, testing

#2174 Tune BEAM instructions for the new compiler (part 2)
  erts/emulator/beam/arith_instrs.tab
  erts/emulator/beam/beam_emu.c
  erts/emulator/beam/beam_load.c
  erts/emulator/beam/bif_instrs.tab
  erts/emulator/beam/bs_instrs.tab
  erts/emulator/beam/instrs.tab
  erts/emulator/beam/ops.tab
  erts/emulator/beam/sys.h
  erts/emulator/utils/beam_makeops
Labels: enhancement, team:VM

#2088 Add start_distribution to kernel environment
  lib/kernel/doc/src/kernel_app.xml
  lib/kernel/src/kernel.erl
  lib/kernel/test/kernel_config_SUITE.erl
Labels: team:MW, team:VM, testing

#2175 erts: Add enif_term_type
  erts/doc/src/erl_nif.xml
  erts/emulator/beam/erl_nif.c
  erts/emulator/beam/erl_nif.h
  erts/emulator/beam/erl_nif_api_funcs.h
  erts/emulator/test/nif_SUITE.erl
  erts/emulator/test/nif_SUITE_data/nif_SUITE.c
Labels: feature, team:VM, testing

#2176 Clarify beam_load error message on file/module mismatch
  erts/emulator/beam/beam_load.c
Labels: enhancement, team:VM, testing

#2178 Update HOWTO for Raspberry Pi3 cross compilation
  HOWTO/INSTALL-RASPBERRYPI3.md
Labels: team:PS

#2177 Optimize tail-recursive calls of BIFs
  erts/emulator/beam/bif.c
  erts/emulator/beam/bif_instrs.tab
  erts/emulator/beam/ops.tab
  erts/emulator/test/trace_local_SUITE.erl
  lib/compiler/test/beam_except_SUITE.erl
Labels: enhancement, team:VM

#2114 Allow list of chunks to be given to strip*()
  lib/stdlib/doc/src/beam_lib.xml
  lib/stdlib/src/beam_lib.erl
  lib/stdlib/test/beam_lib_SUITE.erl
Labels: team:VM, testing

#2180 public_key: Add AES 256 encryption for old PEM encryption mechanism
  lib/public_key/src/pubkey_pbe.erl
  lib/public_key/src/pubkey_pem.erl
  lib/public_key/test/pbe_SUITE.erl
  lib/public_key/test/pbe_SUITE_data/old_aes_128_cbc.pem
  lib/public_key/test/pbe_SUITE_data/old_aes_256_cbc.pem
Labels: team:PS, testing

#2162 public_key: allowed 3 letters country code to be valid
  lib/public_key/asn1/OTP-PKIX.asn1
Labels: team:PS

#2179 Array fixup
  lib/stdlib/src/array.erl
Labels: team:MW, testing

#1695 first stab at fixing index_[read|match_object] w plugins
  lib/mnesia/src/mnesia.erl
  lib/mnesia/src/mnesia_index.erl
  lib/mnesia/test/Makefile
  lib/mnesia/test/mnesia_SUITE.erl
  lib/mnesia/test/mnesia_index_plugin_test.erl
  lib/mnesia/test/mt.erl
Labels: team:MW, testing

#2188 Tune BEAM instructions for the new compiler (part 3)
  erts/emulator/beam/beam_debug.c
  erts/emulator/beam/beam_load.c
  erts/emulator/beam/instrs.tab
  erts/emulator/beam/map_instrs.tab
  erts/emulator/beam/ops.tab
  erts/emulator/utils/beam_makeops
Labels: enhancement, team:VM, testing

#2170 Error on duplicated config apps/keys in -config
  lib/kernel/src/application_controller.erl
  lib/kernel/test/application_SUITE.erl
Labels: team:MW, testing

#2185 Remove asn1/test items from .gitignore
  .gitignore
Labels: team:PS, testing

#2159 ASN.1: fix various problems with value definitions
  lib/asn1/src/asn1ct_check.erl
  lib/asn1/test/Makefile
  lib/asn1/test/asn1_SUITE.erl
  lib/asn1/test/asn1_SUITE_data/ChoExtension.asn1
  lib/asn1/test/asn1_SUITE_data/DefaultOctetString.asn
  lib/asn1/test/asn1_SUITE_data/SeqOfChoExt.asn1
  lib/asn1/test/testChoExtension.erl
  lib/asn1/test/testDefaultOctetString.erl
  lib/asn1/test/testSeqOfChoExt.erl
Labels: team:PS, testing

#2186 Make crypto:cipher_info work for all ciphers and aliases
  lib/crypto/c_src/atoms.c
  lib/crypto/c_src/atoms.h
  lib/crypto/c_src/cipher.c
  lib/crypto/src/crypto.erl
  lib/crypto/test/crypto_SUITE.erl
Labels: team:PS, testing

#2184 Emacs erldoc updates
  lib/tools/emacs/erldoc.el
Labels: team:MW, testing

#2192 ssl: Enhance testing
  lib/ssl/test/Makefile
  lib/ssl/test/ssl_basic_SUITE.erl
  lib/ssl/test/ssl_cipher_suite_SUITE.erl
  lib/ssl/test/ssl_test_lib.erl
Labels: team:PS, testing

#2193 Fix unsafe optimization made by the loader
  erts/emulator/beam/beam_load.c
  erts/emulator/beam/ops.tab
Labels: fix, team:VM, testing

#2169 tty: document ^] keystroke
  erts/doc/src/tty.xml
Labels: team:MW, testing
