Repository erlang/otp, pull requests merged in 2019-11, with the labels that each got.

#2447 fix af_import() type in erl_parse.yrl
  lib/stdlib/src/erl_parse.yrl
Labels: team:VM

#2438 erl_child_setup: reduce number of calls to close()
  erts/emulator/sys/unix/erl_child_setup.c
Labels: enhancement, team:VM, testing

#2424 eunit: Allow test cases to retrieve output captured by EUnit
  lib/eunit/doc/overview.edoc
  lib/eunit/include/eunit.hrl
  lib/eunit/src/eunit_proc.erl
  lib/eunit/src/eunit_tests.erl
Labels: team:PS, testing

#2443 Allow linewidth and indent to be given to erl_pp
  lib/stdlib/doc/src/erl_pp.xml
  lib/stdlib/src/erl_pp.erl
  lib/stdlib/test/erl_pp_SUITE.erl
Labels: team:VM, testing

#2446 Fix bug for --enable-sharing-preserving and bit strings
  erts/emulator/beam/copy.c
  erts/emulator/test/binary_SUITE.erl
Labels: fix, team:VM, testing

#2435 Add function/arity to shadow clauses warnings when possible
  lib/compiler/src/sys_core_fold.erl
  lib/compiler/src/v3_core.erl
  lib/compiler/test/warnings_SUITE.erl
Labels: enhancement, team:VM, testing

#2441 Do not merge maps when the value is the same
  erts/emulator/beam/erl_map.c
  lib/stdlib/test/maps_SUITE.erl
Labels: enhancement, team:VM, testing

#2448 Add openssh vendor extension to sftp rename.
  lib/ssh/src/ssh_xfer.erl
Labels: team:PS, waiting

#2437 httpc: do not pass error tuple to uri_string:parse/1
  lib/inets/src/http_client/httpc.erl
  lib/inets/test/httpc_SUITE.erl
Labels: team:PS, testing

#2433 Fix typo
  erts/doc/src/socket.xml
Labels: team:PS, testing

#2452 Document the return value details for rpc:call/4 and friends
  lib/kernel/doc/src/rpc.xml
Labels: fix, team:VM, testing

#2458 Added s390x support for Travis CI
  .travis.yml
Labels: feature, team:VM

#2464 Fix typos
  lib/kernel/doc/src/logger_cookbook.xml
Labels: team:VM

#2463 Fix uri_string:recompose/1 example in docs
  lib/stdlib/doc/src/uri_string.xml
Labels: team:PS
