Repository erlang/otp, pull requests merged in 2019-08, with the labels that each got.

#2329 Add ed25519 & ed448 support to crypto:generate_key
  lib/crypto/c_src/atoms.c
  lib/crypto/c_src/atoms.h
  lib/crypto/c_src/crypto.c
  lib/crypto/c_src/evp.c
  lib/crypto/src/crypto.erl
  lib/crypto/test/crypto_SUITE.erl
Labels: team:PS

#2334 Fix compiler crash when compiling with +no_type_opt
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/compile.erl
  lib/compiler/test/Makefile
  lib/compiler/test/test_lib.erl
Labels: fix, team:VM, testing

#2335 Eliminate a crash in the type optimizer pass
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/test/beam_type_SUITE.erl
Labels: fix, team:VM, testing

#2336 Avoid extremely long compilation times for huge functions
  lib/compiler/src/beam_ssa_dead.erl
Labels: fix, team:VM, testing

#2327 Optimize is_subset and is_disjoint in cerl_sets
  lib/compiler/src/cerl_sets.erl
Labels: enhancement, team:VM, testing

#2337 Ensure that the stack slots are initialized when matching maps
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/src/beam_validator.erl
  lib/compiler/test/beam_ssa_SUITE.erl
Labels: fix, team:VM, testing

#2333 erts: Do not use named no_cpuid label in asm
  erts/lib_src/pthread/ethread.c
Labels: fix, team:VM, testing

#2319 Fix syntax error in logger_disk_log_h.xml
  lib/kernel/doc/src/logger_disk_log_h.xml
Labels: team:MW

#2340 Fix sscanf to use %llu instead of gnu specific %Lu
  lib/os_mon/c_src/cpu_sup.c
Labels: fix, team:VM, testing

#2226 Expand and squeeze literal integers/utf8 bin segments
  lib/compiler/src/v3_kernel.erl
  lib/compiler/test/bs_match_SUITE.erl
Labels: enhancement, team:VM, testing

#2341 Escape module/function names in erlang:fun_to_list/1
  erts/emulator/beam/erl_printf_term.c
  erts/emulator/test/fun_SUITE.erl
Labels: fix, team:VM, testing

#2312 mnesia: Fix deadlock caused by add_table_copy
  lib/mnesia/src/mnesia_controller.erl
  lib/mnesia/src/mnesia_schema.erl
  lib/mnesia/test/mnesia_isolation_test.erl
Labels: team:MW

#2201 Handle clicking links more than once in Observer's "Expanded term"
  lib/observer/src/cdv_html_wx.erl
Labels: team:MW

#2332 Correct documentation on dump_log_write_threshold default value
  lib/mnesia/doc/src/Mnesia_chap7.xmlsrc
Labels: team:MW

#2325 Fix documentation for erlang:is_map_key/2
  erts/doc/src/erlang.xml
Labels: fix, team:VM, testing

#2347 Fix compiler crash when compiling some receive statements
  lib/compiler/src/beam_ssa_pre_codegen.erl
  lib/compiler/test/receive_SUITE.erl
Labels: fix, team:VM, testing

#2343 Document file:open/2 monitors the owner process
  lib/kernel/doc/src/file.xml
Labels: fix, team:VM

#2349 Fix an internal consistency check failure caused by beam_except
  lib/compiler/src/beam_except.erl
  lib/compiler/test/beam_except_SUITE.erl
Labels: fix, team:VM, testing

#2322 fun2ms: accept ++ in function head when called from shell
  lib/stdlib/src/ms_transform.erl
  lib/stdlib/test/ms_transform_SUITE.erl
Labels: team:MW

#2316 ERL-991 Strip control codes from eunit_surefire output
  lib/eunit/src/eunit_surefire.erl
  lib/eunit/test/Makefile
  lib/eunit/test/eunit_SUITE.erl
  lib/eunit/test/tc0.erl
Labels: team:MW

#2331 Close log files properly in case of inode change
  lib/kernel/src/logger_std_h.erl
Labels: fix, team:MW, testing

#2317 Remove inets dependency from edoc
  lib/edoc/src/edoc.app.src
  lib/edoc/src/edoc.erl
  lib/edoc/src/edoc_lib.erl
Labels: team:VM

#2351 Optimize continuation pointer management
  erts/emulator/beam/beam_bif_load.c
  erts/emulator/beam/beam_bp.c
  erts/emulator/beam/beam_emu.c
  erts/emulator/beam/bif.c
  erts/emulator/beam/bif_instrs.tab
  erts/emulator/beam/erl_bif_info.c
  erts/emulator/beam/erl_db_util.c
  erts/emulator/beam/erl_gc.c
  erts/emulator/beam/erl_nfunc_sched.c
  erts/emulator/beam/erl_nfunc_sched.h
  erts/emulator/beam/erl_nif.c
  erts/emulator/beam/erl_process.c
  erts/emulator/beam/erl_process.h
  erts/emulator/beam/erl_trace.h
  erts/emulator/beam/instrs.tab
  erts/emulator/beam/macros.tab
  erts/emulator/beam/ops.tab
  erts/emulator/beam/trace_instrs.tab
  erts/emulator/hipe/hipe_debug.c
  erts/emulator/hipe/hipe_instrs.tab
  erts/emulator/hipe/hipe_mode_switch.c
  erts/emulator/test/bif_SUITE.erl
  erts/emulator/test/hibernate_SUITE.erl
  erts/etc/unix/etp-commands.in
Labels: enhancement, fix, team:VM, testing

#2301 Start up of SASl when compared log level is all
  lib/kernel/src/logger.erl
  lib/kernel/src/logger_internal.hrl
  lib/kernel/test/logger_SUITE.erl
Labels: team:VM, testing, waiting

#2345 Change internal hash table implementation
  erts/emulator/beam/erl_bif_port.c
  erts/emulator/beam/erl_fun.c
  erts/emulator/beam/export.c
  erts/emulator/beam/hash.c
  erts/emulator/beam/hash.h
  erts/emulator/beam/index.c
  erts/emulator/beam/register.c
  erts/emulator/beam/register.h
  erts/emulator/beam/sys.h
  erts/emulator/sys/common/erl_osenv.h
  erts/emulator/sys/unix/erl_child_setup.c
  erts/emulator/sys/unix/sys_drivers.c
  erts/emulator/sys/win32/sys.c
  erts/emulator/sys/win32/sys_env.c
Labels: enhancement, team:VM

#2353 Fix filelib:wildcard/1,2 for patterns containing ".." and/or "@"
  lib/stdlib/src/filelib.erl
  lib/stdlib/test/filelib_SUITE.erl
Labels: fix, team:VM, testing

#2357 Clarify that digraphs are implemented using ETS tables
  lib/stdlib/doc/src/digraph.xml
Labels: enhancement, team:VM, testing

#2002 Nodes info improvements
  lib/kernel/src/net_kernel.erl
Labels: fix, team:VM, testing

#2360 kernel: Fix typo in gen_tcp_dist documentation
  lib/kernel/examples/gen_tcp_dist/src/gen_tcp_dist.erl
Labels: team:VM

#2362 Improve erl_nif documentation about on_load and stubs
  erts/doc/src/erl_nif.xml
Labels: enhancement, team:VM, testing

#2358 Add arity-1 versions of atom_to_binary, binary_to_atom and binary_to_existing_atom
  erts/doc/src/erlang.xml
  erts/emulator/test/bif_SUITE.erl
  erts/preloaded/ebin/erlang.beam
  erts/preloaded/src/erlang.erl
  lib/compiler/src/erl_bifs.erl
  lib/stdlib/src/erl_internal.erl
Labels: feature, team:VM, testing

#2145 ct_property_test: add init_tool/1
  lib/common_test/src/ct_property_test.erl
Labels: team:PS
