Repository erlang/otp, pull requests merged in 2019-10, with the labels that each got.

#2229 Decentralized counters for all ETS table types and an option to disable decentralized counters
  erts/emulator/beam/atom.names
  erts/emulator/beam/erl_alloc.types
  erts/emulator/beam/erl_bif_info.c
  erts/emulator/beam/erl_db.c
  erts/emulator/beam/erl_db_hash.c
  erts/emulator/beam/erl_db_hash.h
  erts/emulator/beam/erl_db_tree.c
  erts/emulator/beam/erl_db_util.h
  erts/emulator/beam/erl_flxctr.c
  erts/emulator/beam/erl_flxctr.h
  erts/emulator/beam/erl_process.h
  lib/stdlib/doc/src/ets.xml
  lib/stdlib/src/ets.erl
  lib/stdlib/test/ets_SUITE.erl
Labels: team:VM

#2398 Implement a separate test for stack direction for the re module
  erts/emulator/beam/erl_bif_re.c
  erts/emulator/beam/global.h
  erts/emulator/beam/utils.c
Labels: fix, team:VM, testing

#2409 Repeat optimization passes until a fixpoint is reached
  erts/emulator/test/beam_SUITE.erl
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/src/beam_types.erl
Labels: enhancement, team:VM

#2408 Change efile_allocate in Linux to also change file size
  erts/emulator/nifs/unix/unix_prim_file.c
  lib/kernel/doc/src/file.xml
  lib/kernel/test/file_SUITE.erl
Labels: team:VM, testing

#2380 ERL-1030 SSL failing to handle a 'cRLIssuer' entry in a CRL distribution point extension
  lib/public_key/src/pubkey_crl.erl
  lib/ssl/src/ssl_crl_cache.erl
  lib/ssl/src/ssl_crl_cache_api.erl
  lib/ssl/src/ssl_crl_hash_dir.erl
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/test/make_certs.erl
  lib/ssl/test/ssl_crl_SUITE.erl
Labels: team:PS, testing, waiting

#2394 Allow ICMP over DGRAM socket
  erts/preloaded/src/socket.erl
Labels: team:PS

#2400 socket_nif: improve support for sendmsg ctrl types
  erts/emulator/nifs/common/socket_nif.c
  erts/preloaded/src/socket.erl
Labels: team:PS, testing

#2413 Fix failure to build OTP on macOS Catalina (10.15)
  erts/configure.in
Labels: fix, team:VM, testing

#2418 Always run the core_lint pass when compiling from Core Erlang
  lib/compiler/src/compile.erl
  lib/compiler/test/core_SUITE_data/fun_letrec_effect.core
Labels: fix, team:VM

#2416 erts: Fix missing persistent_term from erts.app
  erts/preloaded/src/erts.app.src
Labels: team:VM, testing

#2422 beam_ssa_pre_codegen: Improve determination of the common exit block
  lib/compiler/src/beam_ssa_pre_codegen.erl
  lib/compiler/test/beam_ssa_SUITE.erl
Labels: fix, team:VM

#2401 Fix return from call_time traced function
  erts/emulator/beam/beam_bp.c
  erts/emulator/beam/beam_bp.h
  erts/emulator/beam/trace_instrs.tab
  erts/emulator/test/trace_call_time_SUITE.erl
Labels: fix, team:VM, testing

#2411 fix: gen_server:reply/2
  lib/kernel/src/global.erl
  lib/stdlib/doc/src/gen_server.xml
  lib/stdlib/src/gen_server.erl
Labels: testing

#2389 Optimize persistent_term:put/2 and erase/1
  erts/emulator/beam/erl_bif_info.c
  erts/emulator/beam/erl_bif_persistent.c
  erts/emulator/beam/global.h
  erts/emulator/test/Makefile
  erts/emulator/test/erts_test_destructor.erl
  erts/emulator/test/persistent_term_SUITE.erl
  erts/emulator/test/persistent_term_SUITE_data/Makefile.src
  erts/emulator/test/persistent_term_SUITE_data/erts_test_destructor.c
Labels: enhancement, team:VM, testing

#2434 Fix unsafe optimization of receives
  lib/compiler/src/beam_a.erl
  lib/compiler/src/beam_ssa_recv.erl
  lib/compiler/test/receive_SUITE.erl
  lib/compiler/test/receive_SUITE_data/ref_opt/no_6.erl
  lib/compiler/test/receive_SUITE_data/ref_opt/yes_15.erl
  lib/compiler/test/receive_SUITE_data/ref_opt/yes_16.erl
Labels: fix, team:VM
