Repository erlang/otp, pull requests merged in 2019-09, with the labels that each got.

#2364 stdlib: Handle bad I/O server in escripts
  lib/stdlib/src/escript.erl
  lib/stdlib/test/escript_SUITE.erl
  lib/stdlib/test/escript_SUITE_data/bad_io_server
Labels: team:VM

#2366 Correct ETS documentation about compiled match specs
  lib/stdlib/doc/src/ets.xml
Labels: enhancement, team:VM, testing

#2371 Add units to all crash dump doc memory slogans
  erts/doc/src/crash_dump.xml
Labels: enhancement, team:VM, testing

#2259 inet: Remove non-existing send_dvi; document send_pend
  lib/kernel/doc/src/inet.xml
Labels: team:PS, testing

#2228 Fix syntax error in megaco test file
  lib/megaco/test/megaco_mess_test.erl
Labels: team:PS, testing

#2302 Do not crash/warn in group_history during disk_log shutdown
  lib/kernel/src/group_history.erl
  lib/kernel/test/interactive_shell_SUITE.erl
Labels: team:VM, testing

#2372 Fix dbg:stop_clear to remove trace events as well
  lib/runtime_tools/src/dbg.erl
  lib/runtime_tools/test/dbg_SUITE.erl
Labels: fix, team:VM, testing

#2368 Supervisor tree for SSH client side
  lib/ssh/src/Makefile
  lib/ssh/src/ssh.app.src
  lib/ssh/src/ssh.erl
  lib/ssh/src/ssh_channel_sup.erl
  lib/ssh/src/ssh_connection.erl
  lib/ssh/src/ssh_connection_handler.erl
  lib/ssh/src/ssh_info.erl
  lib/ssh/src/ssh_sftp.erl
  lib/ssh/src/ssh_subsystem_sup.erl
  lib/ssh/src/ssh_system_sup.erl
  lib/ssh/src/sshc_sup.erl
  lib/ssh/src/sshd_sup.erl
  lib/ssh/test/ssh_sup_SUITE.erl
Labels: enhancement, team:PS, testing

#2377 Fix grammatical error in erl_nif documentation
  erts/doc/src/erl_nif.xml
Labels: fix, team:VM

#2381 Refactor BIF tracing
  erts/emulator/Makefile.in
  erts/emulator/beam/atom.names
  erts/emulator/beam/beam_bif_load.c
  erts/emulator/beam/beam_bp.c
  erts/emulator/beam/beam_bp.h
  erts/emulator/beam/beam_debug.c
  erts/emulator/beam/beam_emu.c
  erts/emulator/beam/beam_load.c
  erts/emulator/beam/beam_load.h
  erts/emulator/beam/bif.c
  erts/emulator/beam/bif.tab
  erts/emulator/beam/bif_instrs.tab
  erts/emulator/beam/erl_alloc.c
  erts/emulator/beam/erl_alloc.types
  erts/emulator/beam/erl_bif_info.c
  erts/emulator/beam/erl_bif_lists.c
  erts/emulator/beam/erl_bif_trace.c
  erts/emulator/beam/erl_gc.c
  erts/emulator/beam/erl_init.c
  erts/emulator/beam/erl_nfunc_sched.c
  erts/emulator/beam/erl_nfunc_sched.h
  erts/emulator/beam/erl_nif.c
  erts/emulator/beam/erl_process.c
  erts/emulator/beam/erl_process.h
  erts/emulator/beam/erl_trace.h
  erts/emulator/beam/error.h
  erts/emulator/beam/export.c
  erts/emulator/beam/export.h
  erts/emulator/beam/global.h
  erts/emulator/beam/instrs.tab
  erts/emulator/beam/macros.tab
  erts/emulator/beam/ops.tab
  erts/emulator/hipe/hipe_instrs.tab
  erts/emulator/internal_doc/beam_makeops.md
  erts/emulator/test/call_trace_SUITE.erl
  erts/emulator/test/dirty_bif_SUITE.erl
  erts/emulator/test/match_spec_SUITE.erl
  erts/emulator/test/trace_call_time_SUITE.erl
  erts/emulator/utils/beam_makeops
  erts/emulator/utils/make_tables
  erts/preloaded/ebin/erlang.beam
  erts/preloaded/src/erlang.erl
  lib/compiler/src/beam_jump.erl
  lib/compiler/src/beam_ssa_pre_codegen.erl
  lib/compiler/src/beam_validator.erl
  lib/compiler/test/beam_validator_SUITE.erl
  lib/compiler/test/beam_validator_SUITE_data/call_last.S
  lib/compiler/test/beam_validator_SUITE_data/call_without_stack.S
  lib/compiler/test/beam_validator_SUITE_data/freg_uninit.S
  lib/compiler/test/beam_validator_SUITE_data/merge_undefined.S
Labels: fix, team:VM

#2339 Update to Unicode 12.1
  lib/stdlib/test/unicode_util_SUITE_data/GraphemeBreakTest.txt
  lib/stdlib/test/unicode_util_SUITE_data/LineBreakTest.txt
  lib/stdlib/test/unicode_util_SUITE_data/NormalizationTest.txt
  lib/stdlib/uc_spec/CaseFolding.txt
  lib/stdlib/uc_spec/CompositionExclusions.txt
  lib/stdlib/uc_spec/GraphemeBreakProperty.txt
  lib/stdlib/uc_spec/PropList.txt
  lib/stdlib/uc_spec/README-UPDATE.txt
  lib/stdlib/uc_spec/SpecialCasing.txt
  lib/stdlib/uc_spec/UnicodeData.txt
  lib/stdlib/uc_spec/emoji-data.txt
  lib/stdlib/uc_spec/gen_unicode_mod.escript
Labels: enhancement, team:PS, testing

#2320 Ensure create_table aborted reason is expected format
  lib/mnesia/src/mnesia.erl
Labels: team:PS, testing

#2388 Add missing dtrace return invocations
  erts/emulator/beam/beam_emu.c
  erts/emulator/beam/erlang_dtrace.d
  erts/emulator/beam/instrs.tab
  lib/runtime_tools/examples/function-calls.d
  lib/runtime_tools/examples/function-calls.systemtap
Labels: fix, team:VM, testing

#2386 Fix efile_allocate for Mac
  erts/emulator/nifs/unix/unix_prim_file.c
  lib/kernel/test/file_SUITE.erl
Labels: fix, team:VM, testing

#2387 Move guard optimizations from v3_kernel to a new beam_ssa_bool pass
  lib/compiler/src/Makefile
  lib/compiler/src/beam_kernel_to_ssa.erl
  lib/compiler/src/beam_ssa_bool.erl
  lib/compiler/src/beam_ssa_dead.erl
  lib/compiler/src/compile.erl
  lib/compiler/src/compiler.app.src
  lib/compiler/src/v3_core.erl
  lib/compiler/src/v3_kernel.erl
  lib/compiler/src/v3_kernel.hrl
  lib/compiler/src/v3_kernel_pp.erl
  lib/compiler/test/andor_SUITE.erl
  lib/compiler/test/compile_SUITE.erl
  lib/compiler/test/guard_SUITE.erl
  lib/compiler/test/lfe_andor_SUITE.core
  lib/compiler/test/lfe_guard_SUITE.core
  lib/compiler/test/misc_SUITE.erl
  lib/compiler/test/record_SUITE.erl
  lib/compiler/test/test_lib.erl
Labels: enhancement, team:VM

#2379 erl_tar: Fix typespec for create
  lib/stdlib/doc/src/erl_tar.xml
  lib/stdlib/src/erl_tar.erl
Labels: fix, team:VM

#2395 Clean up and simplify the v3_kernel compiler pass
  lib/compiler/src/beam_kernel_to_ssa.erl
  lib/compiler/src/cerl_sets.erl
  lib/compiler/src/v3_core.erl
  lib/compiler/src/v3_kernel.erl
  lib/compiler/src/v3_kernel.hrl
  lib/compiler/src/v3_kernel_pp.erl
Labels: enhancement, team:VM

#2399 Correct the documentation for proplists:substitute_negations/2
  lib/stdlib/doc/src/proplists.xml
  lib/stdlib/src/proplists.erl
  lib/stdlib/test/Makefile
  lib/stdlib/test/proplists_SUITE.erl
Labels: fix, team:VM, testing

#2293 Utilize I/O vectors for outgoing distribution data
  erts/doc/src/erlang.xml
  erts/emulator/beam/atom.names
  erts/emulator/beam/bif.c
  erts/emulator/beam/bif.tab
  erts/emulator/beam/dist.c
  erts/emulator/beam/dist.h
  erts/emulator/beam/erl_alloc.types
  erts/emulator/beam/erl_bif_info.c
  erts/emulator/beam/erl_node_tables.c
  erts/emulator/beam/erl_node_tables.h
  erts/emulator/beam/external.c
  erts/emulator/beam/external.h
  erts/emulator/hipe/hipe_bif_list.m4
  erts/emulator/test/binary_SUITE.erl
  erts/emulator/test/distribution_SUITE.erl
  erts/preloaded/ebin/erlang.beam
  erts/preloaded/src/erlang.erl
  lib/kernel/test/erl_distribution_SUITE.erl
  lib/ssl/src/tls_sender.erl
  lib/stdlib/src/erl_internal.erl
  lib/tools/emacs/erlang.el
Labels: enhancement, feature, team:VM

#2402 Eliminate the use of sets/dict in core parts of OTP
  lib/compiler/src/beam_dict.erl
  lib/compiler/src/beam_validator.erl
  lib/compiler/src/cerl_inline.erl
  lib/compiler/src/cerl_trees.erl
  lib/compiler/src/v3_core.erl
  lib/parsetools/src/yecc.erl
  lib/stdlib/src/erl_eval.erl
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/src/escript.erl
  lib/stdlib/src/proplists.erl
  lib/stdlib/src/qlc.erl
  lib/stdlib/src/qlc_pt.erl
  lib/stdlib/src/supervisor.erl
  lib/stdlib/test/dict_test_lib.erl
Labels: enhancement, team:VM

#2404 Fix enif_free_iovec documentation
  erts/doc/src/erl_nif.xml
Labels: fix, team:VM

#2403 Correct an internal compiler error
  lib/compiler/src/beam_ssa_bool.erl
  lib/compiler/test/guard_SUITE.erl
Labels: fix, team:VM

#2392 dialyzer: Handle maps:remove/2 better
  lib/dialyzer/test/map_SUITE_data/results/maps_remove
  lib/dialyzer/test/map_SUITE_data/src/maps_remove.erl
  lib/hipe/cerl/erl_bif_types.erl
  lib/hipe/cerl/erl_types.erl
  lib/stdlib/src/maps.erl
Labels: team:VM
