Repository erlang/otp, pull requests merged in 2019-04, with the labels that each got.

#2196 Emacs: Refine xref etags matches
  lib/tools/emacs/erlang-test.el
  lib/tools/emacs/erlang.el
  lib/tools/test/emacs_SUITE.erl
Labels: team:MW, testing

#2200 Add compiler option for suppressing warnings about removed functions/modules
  lib/compiler/doc/src/compile.xml
  lib/edoc/src/edoc_data.erl
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/src/otp_internal.erl
  lib/stdlib/test/erl_lint_SUITE.erl
Labels: enhancement, team:VM, testing

#2202 Optimize the i_minus instruction
  erts/emulator/beam/ops.tab
Labels: enhancement, team:VM, testing

#2204 erts: Optimize arithmetic ops using overflow intrinsics
  .gitignore
  erts/emulator/beam/arith_instrs.tab
  erts/emulator/test/Makefile
  erts/emulator/test/small_SUITE.erl
Labels: enhancement, team:VM

#2205 Issue an error for improper use of record_info/2 in a fun
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/test/erl_lint_SUITE.erl
Labels: fix, team:VM, testing

#2195 common_test: Fix typo in log options example
  lib/common_test/doc/src/run_test_chapter.xml
Labels: team:MW, testing

#2209 Optimize encoding of simple literals
  lib/compiler/src/beam_asm.erl
Labels: fix, team:VM, testing

#2208 Fix specs and type definitions in cpu_sup
  lib/os_mon/src/cpu_sup.erl
Labels: fix, team:VM, testing

#2210 `public_key:pem_decode` example wasn't using `pem_decode`
  lib/public_key/doc/src/public_key.xml
Labels: team:PS

#2191 Add a note about timeouts on gen_tcp:connect/3,4
  lib/kernel/doc/src/gen_tcp.xml
Labels: team:PS

#2214 dialyzer: Improve the warning tagged 'fun_app_args'
  lib/dialyzer/src/dialyzer.erl
  lib/dialyzer/src/dialyzer_dataflow.erl
  lib/dialyzer/test/small_SUITE_data/results/fun_app_args
  lib/dialyzer/test/small_SUITE_data/src/fun_app_args.erl
Labels: team:MW

#2221 Fix typo
  lib/stdlib/doc/src/queue.xml
Labels: team:MW
