Repository erlang/otp, pull requests merged in 2019-05, with the labels that each got.

#2219 Add hostname to -remsh if none is given
  erts/doc/src/erl.xml
  lib/kernel/src/user_drv.erl
Labels: feature, team:VM, testing

#2220 make.xml: Add reference to compile(3)
  lib/tools/doc/src/make.xml
Labels: team:MW

#2211 Use synchronous timer cancel in gen_statem
  lib/stdlib/src/gen_statem.erl
Labels: team:PS

#2223 Use file:name_all() on spawn_executable
  erts/preloaded/src/erlang.erl
Labels: team:VM

#2225 Update erlang.xml / map_get in guard tests
  erts/doc/src/erlang.xml
Labels: team:VM

#2237 Eliminate the beam_except pass
  lib/compiler/src/Makefile
  lib/compiler/src/beam_except.erl
  lib/compiler/src/beam_ssa.erl
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/src/beam_ssa_pre_codegen.erl
  lib/compiler/src/compile.erl
  lib/compiler/src/compiler.app.src
  lib/compiler/test/compile_SUITE.erl
  lib/compiler/test/misc_SUITE.erl
Labels: enhancement, team:VM, testing

#2242 Make the swap instruction known to the compiler
  erts/emulator/beam/beam_load.c
  erts/emulator/beam/instrs.tab
  erts/emulator/beam/ops.tab
  lib/compiler/src/beam_block.erl
  lib/compiler/src/beam_clean.erl
  lib/compiler/src/beam_disasm.erl
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/src/beam_trim.erl
  lib/compiler/src/beam_validator.erl
  lib/compiler/src/compile.erl
  lib/compiler/src/genop.tab
  lib/compiler/test/compile_SUITE.erl
  lib/compiler/test/test_lib.erl
  lib/hipe/icode/hipe_beam_to_icode.erl
Labels: enhancement, team:VM, testing

#2243 Improve optimization of redundant tests
  lib/compiler/src/beam_ssa_dead.erl
  lib/compiler/test/beam_ssa_SUITE.erl
  lib/compiler/test/guard_SUITE.erl
Labels: enhancement, team:VM, testing

#2236 Fix compiler crash when funs were matched
  lib/compiler/src/v3_core.erl
  lib/compiler/test/fun_SUITE.erl
Labels: fix, team:VM, testing

#2245 Improve example for binary:referenced_byte_size/1
  lib/stdlib/doc/src/binary.xml
Labels: fix, team:VM, testing

#2247 Eliminate compiler crash when compiling complex receive statements
  lib/compiler/src/beam_ssa_pre_codegen.erl
  lib/compiler/test/receive_SUITE.erl
Labels: fix, team:VM, testing

#2212 file: allow open/2 to work on directories
  erts/emulator/nifs/common/prim_file_nif.c
  erts/emulator/nifs/common/prim_file_nif.h
  erts/emulator/nifs/unix/unix_prim_file.c
  erts/emulator/nifs/win32/win_prim_file.c
  lib/kernel/doc/src/file.xml
  lib/kernel/src/file.erl
  lib/kernel/test/file_SUITE.erl
Labels: team:VM, testing

#2234 Add basic TLS 1.3 client
  lib/ssl/doc/src/standards_compliance.xml
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/src/ssl_logger.erl
  lib/ssl/src/tls_connection.erl
  lib/ssl/src/tls_connection_1_3.erl
  lib/ssl/src/tls_handshake.erl
  lib/ssl/src/tls_handshake_1_3.erl
  lib/ssl/test/ssl_basic_SUITE.erl
Labels: team:PS

#2233 add Hygon Dhyana support to enable cmpxchg and sse2 support.
  erts/lib_src/common/ethr_aux.c
Labels: team:VM

#2249 Fix unsafe negative type inference
  lib/compiler/src/beam_ssa_type.erl
Labels: fix, team:VM

#2248 Move type-based optimizations from Core Erlang passes to SSA passes
  lib/compiler/src/beam_ssa.erl
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/src/sys_core_fold.erl
Labels: enhancement, team:VM, testing

#2182 Make erlang:phash2/1 and erlang:phash2/2 yield
  erts/emulator/beam/bif.c
  erts/emulator/beam/erl_alloc.types
  erts/emulator/beam/erl_utils.h
  erts/emulator/beam/sys.h
  erts/emulator/beam/utils.c
  erts/emulator/test/Makefile
  erts/emulator/test/emulator.spec
  erts/emulator/test/emulator_bench.spec
  erts/emulator/test/hash_SUITE.erl
  erts/emulator/test/hash_property_test_SUITE.erl
  erts/emulator/test/property_test/phash2_properties.erl
Labels: team:VM, testing

#2251 Fix compiler crash in beam_except
  lib/compiler/src/beam_except.erl
  lib/compiler/test/beam_except_SUITE.erl
Labels: fix, team:VM, testing

#2253 Fix unsafe optimizations where guard tests could be removed
  lib/compiler/src/beam_ssa_dead.erl
  lib/compiler/test/guard_SUITE.erl
Labels: fix, team:VM, testing

#2257 Fix loading of Core Erlang code for extracting a map element
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/test/core_SUITE.erl
  lib/compiler/test/core_SUITE_data/get_map_element.core
Labels: fix, team:VM, testing

#2189 Propagate seq_trace tokens to spawned processes
  erts/emulator/beam/bif.c
  erts/emulator/beam/dist.c
  erts/emulator/beam/erl_bif_trace.c
  erts/emulator/beam/erl_message.c
  erts/emulator/beam/erl_nif.c
  erts/emulator/beam/erl_proc_sig_queue.c
  erts/emulator/beam/erl_process.c
  erts/emulator/beam/erl_process.h
  erts/emulator/beam/erl_trace.c
  erts/emulator/beam/erl_trace.h
  lib/kernel/doc/src/seq_trace.xml
  lib/kernel/src/seq_trace.erl
  lib/kernel/test/seq_trace_SUITE.erl
  lib/observer/test/ttb_SUITE.erl
Labels: enhancement, team:VM

#2263 Eliminate crash in the beam_ssa_dead compiler pass
  lib/compiler/src/beam_ssa_dead.erl
  lib/compiler/test/beam_ssa_SUITE.erl
Labels: fix, team:VM, testing

#2252 Add missing attribute to debug variable
  erts/emulator/beam/erl_sched_spec_pre_alloc.h
Labels: fix, team:VM, testing

#2254 erts: don't loop indefinitely on --enable-pgo
  erts/configure.in
Labels: fix, team:VM, testing
