Repository erlang/otp, pull requests merged in 2020-08, with the labels that each got.

#2698 Implement fallback for inet_backend socket sendfile
  lib/kernel/src/file.erl
Labels: testing

#2705 Inline always required layer in raw_file_io
  bootstrap/lib/kernel/ebin/kernel.app
  lib/kernel/src/Makefile
  lib/kernel/src/kernel.app.src
  lib/kernel/src/raw_file_io.erl
  lib/kernel/src/raw_file_io_raw.erl
Labels: team:VM, testing

#2701 erl_check_io: do not discard ERTS_POLL_EV_IN from active_events
  erts/emulator/sys/common/erl_check_io.c
  lib/kernel/test/gen_tcp_misc_SUITE.erl
Labels: team:VM, testing

#2663 Fix for delete_object at read on a set table
  lib/mnesia/src/mnesia.erl
  lib/mnesia/test/mnesia_trans_access_test.erl
Labels: team:PS, testing

#2706 Use wxBG_STYLE_PAINT instead of STYLE_SYSTEM
  lib/observer/src/observer_app_wx.erl
  lib/observer/src/observer_perf_wx.erl
Labels: team:PS, testing

#2616 port_please/2 and port_please/3 can return closed
  lib/kernel/src/erl_epmd.erl
Labels: team:VM

#2673 Fixing crash in appmon_info:format for a closed port
  lib/runtime_tools/src/appmon_info.erl
Labels: fix, team:VM, testing

#2630 Drop remnants of elib_malloc (removed in R15)
  erts/doc/src/erlang.xml
  erts/doc/src/erts_alloc.xml
  erts/emulator/beam/atom.names
  erts/emulator/beam/erl_bif_info.c
  erts/etc/common/erlexec.c
  erts/preloaded/src/erlang.erl
  lib/hipe/cerl/erl_bif_types.erl
  lib/observer/test/crashdump_viewer_SUITE_data/old_format.dump
  lib/runtime_tools/src/system_information.erl
  lib/runtime_tools/test/system_information_SUITE_data/information_test_report.dat
Labels: team:VM, testing

#2665 break.c: Rephrase "Eh?"
  erts/emulator/beam/break.c
Labels: team:VM

#2709 Remove private ram_file:compress in favor of zlib:gzip
  erts/emulator/Makefile.in
  erts/emulator/drivers/common/gzio.c
  erts/emulator/drivers/common/gzio.h
  erts/emulator/drivers/common/gzio_zutil.h
  erts/emulator/drivers/common/ram_file_drv.c
  lib/kernel/src/ram_file.erl
  lib/kernel/test/ram_file_SUITE.erl
  lib/stdlib/src/beam_lib.erl
Labels: team:VM, testing

#2692 Update ssh_server_key_api.xml
  lib/ssh/doc/src/ssh_server_key_api.xml
Labels: team:PS

#2689 Update using_ssh.xml
  lib/ssh/doc/src/using_ssh.xml
Labels: team:PS

#2713 Use github actions instead of travis
  .github/dockerfiles/Dockerfile.32-bit
  .github/dockerfiles/Dockerfile.64-bit
  .github/dockerfiles/Dockerfile.cross-compile
  .github/dockerfiles/Dockerfile.debian-base
  .github/dockerfiles/Dockerfile.documentation
  .github/dockerfiles/Dockerfile.ubuntu-base
  .github/workflows/main.yaml
  .github/workflows/update-base.yaml
  .travis.yml
  prebuild.delete
  scripts/build-otp-tar
  scripts/bundle-otp
  scripts/run-dialyzer
  scripts/run-smoke-tests
Labels: enhancement, team:VM

#2710 Fix faulty debug assert in erts_fire_nif_monitor
  erts/emulator/beam/erl_nif.c
Labels: fix, team:VM, testing

#2680 Prepare for 64-bit pids
  erts/doc/src/erl_dist_protocol.xml
  erts/doc/src/erl_ext_dist.xml
  erts/emulator/beam/bif.c
  erts/emulator/beam/dist.c
  erts/emulator/beam/dist.h
  erts/emulator/beam/erl_monitor_link.c
  erts/emulator/beam/erl_node_container_utils.h
  erts/emulator/beam/erl_proc_sig_queue.c
  erts/emulator/beam/erl_process.c
  erts/emulator/beam/erl_term.c
  erts/emulator/beam/erl_term.h
  erts/emulator/beam/external.c
  erts/emulator/beam/sys.h
  erts/emulator/beam/utils.c
  erts/emulator/sys/unix/sys_drivers.c
  erts/emulator/test/node_container_SUITE.erl
  lib/erl_interface/src/connect/ei_connect.c
  lib/erl_interface/src/connect/ei_connect_int.h
  lib/erl_interface/src/decode/decode_pid.c
  lib/erl_interface/src/encode/encode_pid.c
  lib/jinterface/java_src/com/ericsson/otp/erlang/AbstractNode.java
Labels: feature, team:VM, testing

#2711 Remove unused and private ram_file functions
  erts/emulator/drivers/common/ram_file_drv.c
  lib/kernel/src/ram_file.erl
  lib/kernel/test/ram_file_SUITE.erl
Labels: team:VM, testing

#2708 Fix: Variadic function cast causing segfaults on Apple ARM64
  erts/emulator/beam/erl_db_util.c
Labels: fix, team:VM, testing

#2714 Name cipher suites consistently across ssl docs
  lib/ssl/doc/src/notes.xml
  lib/ssl/doc/src/ssl.xml
  lib/ssl/doc/src/using_ssl.xml
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_cipher.erl
  lib/ssl/src/tls_record.erl
  lib/ssl/test/ssl_ECC.erl
  lib/ssl/test/ssl_ECC_SUITE.erl
Labels: team:PS, testing

#2715 supervisor: Eliminate a subtle internal state corruption
  lib/stdlib/src/supervisor.erl
  lib/stdlib/test/supervisor_SUITE.erl
Labels: fix, team:VM, testing

#2702 Fix: ERL-1307 - dialyzer handling of letrec nested in values
  lib/dialyzer/src/dialyzer_dep.erl
  lib/dialyzer/test/plt_SUITE.erl
Labels: fix, team:VM, testing

#2650 Initial check in.
  lib/eldap/example/ad_expiring_account.erl
Labels: team:PS

#2704 win32: Use QPC timer on Windows
  erts/emulator/sys/win32/sys_time.c
Labels: team:PS, testing

#2719 Fix some typos and one grammatical mistake in the socket module
  lib/kernel/doc/src/socket.xml
Labels: team:PS

#2725 epp: Fix error return for an incorrect preprocessor -if directive
  lib/stdlib/src/epp.erl
  lib/stdlib/test/epp_SUITE.erl
Labels: fix, team:VM, testing

#2727 memsup: Return correct amount of total system memory on macOS
  lib/os_mon/c_src/memsup.c
  lib/os_mon/src/memsup.erl
Labels: fix, team:VM, testing

#2728 Do some minor cleanups of OS_Mon
  lib/os_mon/doc/src/disksup.xml
  lib/os_mon/doc/src/memsup.xml
  lib/os_mon/doc/src/notes.xml
  lib/os_mon/doc/src/nteventlog.xml
  lib/os_mon/doc/src/os_mon_app.xml
  lib/os_mon/doc/src/os_sup.xml
  lib/os_mon/src/cpu_sup.erl
  lib/os_mon/src/disksup.erl
  lib/os_mon/src/memsup.erl
  lib/os_mon/src/nteventlog.erl
  lib/os_mon/src/os_mon_sysinfo.erl
  lib/os_mon/src/os_sup.erl
Labels: enhancement, team:VM, testing

#2723 Raise badarg if both ram and raw are given to file:open
  lib/kernel/src/file.erl
  lib/kernel/test/file_SUITE.erl
Labels: fix, team:VM, testing

#2722 seq_trace: fix label spec missed in PR #1760
  erts/preloaded/src/erlang.erl
Labels: team:VM

#2726 Fix clang warnings "array index 1 is past the end"
  erts/emulator/beam/bif.c
  erts/emulator/beam/erl_term.h
  erts/emulator/beam/external.c
Labels: fix, team:VM, testing

#2724 Clarify file:pwrite/pread documentation about ram mode
  lib/kernel/doc/src/file.xml
Labels: enhancement, team:VM, testing
