Repository erlang/otp, pull requests merged in 2020-10, with the labels that each got.

#2776 Handle paths with spaces
  erts/etc/win32/wsl_tools/w32_path.sh
Labels: team:PS, testing

#2752 Suppress `xref` output for "unused export" on behaviour module's `behaviour_info/1`
  lib/tools/src/xref_reader.erl
  lib/tools/test/xref_SUITE.erl
  lib/tools/test/xref_SUITE_data/lib_test/bi.erl
  lib/tools/test/xref_SUITE_data/lib_test/no_bi.erl
Labels: team:VM, testing

#2779 compiler: Suppress stack traces for throw/1 when they're not used
  lib/compiler/src/Makefile
  lib/compiler/src/beam_ssa.erl
  lib/compiler/src/beam_ssa_throw.erl
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/src/beam_validator.erl
  lib/compiler/src/compile.erl
  lib/compiler/src/compiler.app.src
  lib/compiler/test/trycatch_SUITE.erl
Labels: enhancement, team:VM

#2782 Add creation of pre-built .tar files
  .github/scripts/create-artifacts.sh
  .github/scripts/init-pre-release.sh
  .github/scripts/release-docs.sh
  .github/scripts/sync-github-releases.sh
  .github/workflows/main.yaml
  .github/workflows/sync-github-releases.yaml
  scripts/Dockerfile.32
  scripts/Dockerfile.32.ubuntu
  scripts/Dockerfile.64
  scripts/Dockerfile.64.ubuntu
  scripts/Dockerfile.beamasm
  scripts/Dockerfile.x64cross
  scripts/build-docker-otp
Labels: team:VM, testing

#2783 Add format checks to CI
  .github/workflows/main.yaml
  Makefile.in
  erts/emulator/Makefile.in
  erts/emulator/beam/jit/beam_asm.hpp
  erts/emulator/beam/jit/instr_common.cpp
  make/run_make.mk
Labels: team:VM, testing

#2784 Document result from failed simplification of beam_ssa_bool.erl
  lib/compiler/src/beam_ssa_bool.erl
Labels: team:VM, testing

#2785 Simplify lint vts
  lib/stdlib/src/erl_lint.erl
Labels: enhancement, team:VM, testing

#2790 Optimize initialization of Y registers for the JIT
  erts/emulator/beam/emu/generators.tab
  erts/emulator/beam/emu/ops.tab
  erts/emulator/beam/jit/generators.tab
  erts/emulator/beam/jit/instr_common.cpp
  erts/emulator/beam/jit/ops.tab
  lib/compiler/src/beam_block.erl
  lib/compiler/src/beam_disasm.erl
  lib/compiler/src/beam_flatten.erl
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/src/beam_trim.erl
  lib/compiler/src/beam_validator.erl
  lib/compiler/src/beam_z.erl
  lib/compiler/src/compile.erl
  lib/compiler/src/genop.tab
  lib/compiler/test/compile_SUITE.erl
  lib/compiler/test/test_lib.erl
Labels: enhancement, team:VM

#2786 Fix ssl:peername/1 (DTLS client sockets)
  lib/ssl/src/dtls_socket.erl
  lib/ssl/src/ssl_connection.erl
  lib/ssl/test/ssl_api_SUITE.erl
Labels: team:PS

#2772 Fixes ERL-1335
  lib/common_test/src/ct_run.erl
Labels: team:PS, testing

#2787 Fix os_mon application (disksup). replace hardcoded path for 'df' command in linux environment
  lib/os_mon/src/disksup.erl
Labels: team:VM, testing

#2748 Escript errors to stderr
  lib/stdlib/src/escript.erl
  lib/stdlib/test/escript_SUITE.erl
Labels: team:VM, testing

#2777 Fix configuration procedure log
  configure.src
  erts/configure.in
  lib/crypto/configure.in
  lib/odbc/configure.in
  lib/wx/configure.in
Labels: team:PS, team:VM, testing

#2781 Expand the spec for erl_epmd:listen_port_please/2
  lib/kernel/src/erl_epmd.erl
Labels: team:VM, testing

#2802 Remove private ram_file:compress in favor of zlib:gzip
  erts/emulator/Makefile.in
  erts/emulator/drivers/common/gzio.c
  erts/emulator/drivers/common/gzio.h
  erts/emulator/drivers/common/gzio_zutil.h
  erts/emulator/drivers/common/ram_file_drv.c
  lib/kernel/src/ram_file.erl
  lib/kernel/test/ram_file_SUITE.erl
  lib/stdlib/src/beam_lib.erl
  lib/stdlib/src/erl_tar.erl
Labels: enhancement, team:VM

#2740 Add os:env/0
  erts/emulator/beam/bif.tab
  erts/emulator/beam/erl_bif_os.c
  lib/kernel/doc/src/os.xml
  lib/kernel/src/os.erl
  lib/kernel/test/os_SUITE.erl
Labels: feature, team:VM, testing

#2798 escript: Allow the user to request a particular emulator flavor
  erts/doc/src/escript_cmd.xml
Labels: team:VM

#2792 Read file rename race
  erts/emulator/nifs/common/prim_file_nif.c
  lib/kernel/test/prim_file_SUITE.erl
Labels: fix, team:VM, testing

#2801 Fix handling of deep lists in path component (uri_string:recompose/1)
  lib/stdlib/src/uri_string.erl
  lib/stdlib/test/uri_string_SUITE.erl
Labels: team:PS, testing

#2806 remove duplicated t_inf_list/3 from include
  lib/dialyzer/src/dialyzer_dataflow.erl
Labels: fix, team:VM, testing

#2814 Handle uncompressed binaries given as compressed to erl_tar
  lib/stdlib/src/erl_tar.erl
  lib/stdlib/test/tar_SUITE.erl
Labels: fix, team:VM, testing

#2817 beam_ssa_bool: Fix unsafe literal substitution
  lib/compiler/src/beam_ssa_bool.erl
  lib/compiler/test/guard_SUITE.erl
Labels: fix, team:VM, testing

#2804 Document the cache_size option applies only to dns lookups
  erts/doc/src/inet_cfg.xml
Labels: team:PS

#2811 beam_lib: Fix 'allow_missing_chunks' for named chunks
  lib/stdlib/src/beam_lib.erl
  lib/stdlib/test/beam_lib_SUITE.erl
Labels: fix, team:VM, testing

#2824 Add deprecate howto
  HOWTO/DEPRECATE.md
Labels: enhancement, team:VM

#2793 stdlib: Improve API and documentation of uri_string
  lib/stdlib/doc/src/Makefile
  lib/stdlib/doc/src/part.xml
  lib/stdlib/doc/src/uri_string.xml
  lib/stdlib/doc/src/uri_string_usage.xml
  lib/stdlib/src/uri_string.erl
  lib/stdlib/test/property_test/uri_string_recompose.erl
  lib/stdlib/test/uri_string_SUITE.erl
Labels: team:PS, testing

#2813 Implement zero time-outs with dedicated queue
  lib/stdlib/src/gen_statem.erl
  lib/stdlib/test/gen_statem_SUITE.erl
Labels: team:PS

#2807 logger.hrl: use fully qualifier call to erlang:apply
  lib/kernel/include/logger.hrl
  lib/kernel/test/logger_SUITE.erl
Labels: team:VM, testing

#2800 Since the string from strerror should never be modified, use const.
  erts/emulator/beam/erl_alloc.c
  erts/emulator/beam/erl_drv_thread.c
  erts/emulator/beam/erl_init.c
  erts/emulator/sys/unix/sys_time.c
  erts/etc/common/erlexec.c
  erts/lib_src/common/ethr_aux.c
  lib/erl_interface/src/connect/ei_connect.c
  lib/tools/c_src/erl_memory.c
Labels: team:VM, testing

#2762 Improvements to the documentation for the Erlang module
  erts/doc/src/erl_cmd.xml
  erts/doc/src/erlang.xml
  erts/preloaded/src/erlang.erl
  system/doc/general_info/DEPRECATIONS
  system/doc/reference_manual/data_types.xml
Labels: enhancement, team:VM, testing

#2743 Added wxTaskBarIcon:new/1 to create popupmenu
  lib/wx/api_gen/wx_extra/wxTaskBarIcon.c_src
  lib/wx/api_gen/wx_extra/wxTaskBarIcon.erl
  lib/wx/api_gen/wxapi.conf
  lib/wx/c_src/gen/wxe_derived_dest.h
  lib/wx/c_src/gen/wxe_funcs.cpp
  lib/wx/c_src/wxe_callback_impl.cpp
  lib/wx/examples/simple/menu.erl
  lib/wx/src/gen/wxTaskBarIcon.erl
Labels: team:PS, testing

#2815 Write the api footprint
  lib/wx/api_gen/wx_gen.erl
  lib/wx/api_gen/wx_gen_erl.erl
Labels: team:PS, testing

#2810 Fixed using unitialized variable when environment var is too big
  lib/wx/c_src/wxe_ps_init.c
Labels: team:PS, testing

#2808 Using WX_APP_TITLE for wxEntry()
  lib/wx/c_src/wxe_main.cpp
Labels: team:PS, testing

#2780 Fix distribution race bug ERL-1337
  erts/emulator/beam/dist.c
  erts/emulator/beam/erl_monitor_link.c
  erts/emulator/beam/erl_monitor_link.h
  erts/emulator/beam/erl_process.c
  erts/emulator/beam/erl_process.h
  erts/emulator/beam/external.c
  erts/emulator/beam/external.h
Labels: fix, team:VM, testing

#2830 jit: Fix overflow check in 64-bit bs_get_integer
  erts/emulator/beam/jit/instr_bs.cpp
  erts/emulator/test/bs_match_int_SUITE.erl
Labels: fix, team:VM, testing

#2794 Make ct a behaviour for test suites (original by richcarl)
  lib/common_test/doc/src/Makefile
  lib/common_test/doc/src/common_test_app.xml
  lib/common_test/doc/src/ct.xml
  lib/common_test/doc/src/ct_hooks.xml
  lib/common_test/doc/src/ct_hooks_chapter.xml
  lib/common_test/doc/src/ct_property_test.xml
  lib/common_test/doc/src/ct_suite.xml
  lib/common_test/doc/src/dependencies_chapter.xml
  lib/common_test/doc/src/ref_man.xml
  lib/common_test/doc/src/specs.xml
  lib/common_test/doc/src/test_structure_chapter.xml
  lib/common_test/doc/src/write_test_chapter.xml
  lib/common_test/src/Makefile
  lib/common_test/src/common_test.app.src
  lib/common_test/src/ct_suite.erl
  lib/ssl/test/ssl_ECC.erl
  lib/ssl/test/ssl_ECC_SUITE.erl
  lib/ssl/test/ssl_alert_SUITE.erl
  lib/ssl/test/ssl_alpn_SUITE.erl
  lib/ssl/test/ssl_api_SUITE.erl
  lib/ssl/test/ssl_app_env_SUITE.erl
  lib/ssl/test/ssl_basic_SUITE.erl
  lib/ssl/test/ssl_bench_SUITE.erl
  lib/ssl/test/ssl_bench_test_lib.erl
  lib/ssl/test/ssl_cert_SUITE.erl
  lib/ssl/test/ssl_cert_tests.erl
  lib/ssl/test/ssl_cipher_SUITE.erl
  lib/ssl/test/ssl_cipher_suite_SUITE.erl
  lib/ssl/test/ssl_crl_SUITE.erl
  lib/ssl/test/ssl_dist_SUITE.erl
  lib/ssl/test/ssl_dist_bench_SUITE.erl
  lib/ssl/test/ssl_dist_test_lib.erl
  lib/ssl/test/ssl_engine_SUITE.erl
  lib/ssl/test/ssl_eqc_SUITE.erl
  lib/ssl/test/ssl_handshake_SUITE.erl
  lib/ssl/test/ssl_key_update_SUITE.erl
  lib/ssl/test/ssl_mfl_SUITE.erl
  lib/ssl/test/ssl_npn_SUITE.erl
  lib/ssl/test/ssl_npn_hello_SUITE.erl
  lib/ssl/test/ssl_packet_SUITE.erl
  lib/ssl/test/ssl_payload_SUITE.erl
  lib/ssl/test/ssl_pem_cache_SUITE.erl
  lib/ssl/test/ssl_renegotiate_SUITE.erl
  lib/ssl/test/ssl_rfc_5869_SUITE.erl
  lib/ssl/test/ssl_session_SUITE.erl
  lib/ssl/test/ssl_session_cache_SUITE.erl
  lib/ssl/test/ssl_session_ticket_SUITE.erl
  lib/ssl/test/ssl_sni_SUITE.erl
  lib/ssl/test/ssl_socket_SUITE.erl
  lib/ssl/test/ssl_test_lib.erl
  lib/ssl/test/ssl_upgrade_SUITE.erl
Labels: team:PS, testing
