Repository erlang/otp, pull requests merged in 2020-11, with the labels that each got.

#2836 compile: make select_passes clause order match the comment text
  lib/compiler/src/compile.erl
Labels: team:VM, testing

#2837 Also collapse strings in patterns
  lib/compiler/src/v3_core.erl
  lib/compiler/src/v3_kernel.erl
Labels: enhancement, team:VM, testing

#2791 Fold over queues
  lib/stdlib/doc/src/queue.xml
  lib/stdlib/src/queue.erl
  lib/stdlib/test/queue_SUITE.erl
Labels: team:VM, testing

#2821 Documentation of exit signals emitted by gen_statem
  lib/stdlib/doc/src/gen_statem.xml
Labels: team:PS

#2839 Expliticly pass in rpo as arguments
  lib/compiler/src/beam_ssa.erl
  lib/compiler/src/beam_ssa_bool.erl
  lib/compiler/src/beam_ssa_bsm.erl
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/beam_ssa_pre_codegen.erl
  lib/compiler/src/beam_ssa_recv.erl
Labels: enhancement, team:VM, testing

#2834 Skip literals on v3_core and sys_core_alias
  lib/compiler/src/cerl_trees.erl
  lib/compiler/src/sys_core_alias.erl
  lib/compiler/src/v3_core.erl
Labels: enhancement, team:VM, testing

#2838 Improve compile:forms/2 doc with newly exported type
  lib/compiler/doc/src/compile.xml
  lib/compiler/src/compile.erl
Labels: team:VM, testing

#1968 support for FTP over SSL
  lib/ftp/doc/src/ftp.xml
  lib/ftp/src/ftp.erl
  lib/ftp/test/ftp_SUITE.erl
  lib/ftp/test/ftp_SUITE_data/vsftpd.conf
Labels: team:PS, testing, waiting

#2847 Explicit pass RPO to beam_ssa functions (cont)
  lib/compiler/src/beam_ssa.erl
  lib/compiler/src/beam_ssa_bool.erl
  lib/compiler/src/beam_ssa_bsm.erl
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/beam_ssa_pre_codegen.erl
Labels: enhancement, team:VM, testing

#2842 erl_term.h: correct size of ExternalThing
  erts/emulator/beam/erl_term.h
  erts/emulator/test/erts_debug_SUITE.erl
Labels: fix, team:VM, testing

#2853 erts: Fix exception handling during tracing
  erts/emulator/beam/beam_emu.c
  erts/emulator/test/trace_call_time_SUITE.erl
Labels: fix, team:VM, testing

#2856 Typo fix in escript_cmd
  erts/doc/src/escript_cmd.xml
Labels: team:VM

#2823 Implement NSS-style keylog in ssl:connection_information/2
  lib/ssl/doc/src/ssl.xml
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_connection.erl
  lib/ssl/src/ssl_internal.hrl
  lib/ssl/src/tls_handshake_1_3.erl
  lib/ssl/test/ssl_api_SUITE.erl
Labels: team:PS

#2855 Ingela/ssl/cert handling/otp 16277
  lib/public_key/src/public_key.erl
  lib/ssl/doc/src/ssl.xml
  lib/ssl/doc/src/standards_compliance.xml
  lib/ssl/src/dtls_connection.erl
  lib/ssl/src/dtls_handshake.erl
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_certificate.erl
  lib/ssl/src/ssl_config.erl
  lib/ssl/src/ssl_connection.erl
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/src/ssl_handshake.hrl
  lib/ssl/src/ssl_internal.hrl
  lib/ssl/src/ssl_manager.erl
  lib/ssl/src/ssl_session.erl
  lib/ssl/src/tls_connection.erl
  lib/ssl/src/tls_handshake.erl
  lib/ssl/src/tls_handshake_1_3.erl
  lib/ssl/test/property_test/ssl_eqc_chain.erl
  lib/ssl/test/ssl_cert_tests.erl
  lib/ssl/test/ssl_eqc_SUITE.erl
  lib/ssl/test/ssl_handshake_SUITE.erl
Labels: team:PS, testing

#2858 otp: Remove all purify support
  erts/doc/src/erlang.xml
  erts/emulator/Makefile.in
  erts/emulator/beam/atom.names
  erts/emulator/beam/dist.c
  erts/emulator/beam/erl_alloc.c
  erts/emulator/beam/erl_bif_info.c
  erts/emulator/beam/erl_gc.c
  erts/emulator/beam/external.c
  erts/emulator/sys/unix/sys_drivers.c
  erts/emulator/test/mtx_SUITE.erl
  erts/epmd/src/Makefile.in
  erts/etc/common/Makefile.in
  erts/etc/unix/cerl.src
  erts/include/internal/ethread.h
  erts/include/internal/i386/ethr_dw_atomic.h
  erts/lib_src/Makefile.in
  erts/preloaded/src/erlang.erl
  erts/preloaded/src/init.erl
  erts/test/utils/gccifier.c
  lib/erl_interface/src/Makefile
  lib/erl_interface/src/Makefile.in
  lib/erl_interface/test/all_SUITE_data/gccifier.c
  lib/tools/c_src/Makefile.in
  lib/tools/c_src/erl_memory.c
  lib/tools/test/emem_SUITE.erl
  make/run_make.mk
Labels: team:VM, testing

#2852 Remove installed crypto/priv/obj directory and all its object files
  lib/crypto/c_src/Makefile.in
  lib/crypto/priv/Makefile
Labels: enhancement, testing

#2851 Clarify 'caller_env' arguments in erl_nif doc
  erts/doc/src/erl_nif.xml
Labels: enhancement, team:VM, testing

#2859 parsetools: Use types and specs for documentation
  lib/parsetools/doc/specs/.gitignore
  lib/parsetools/doc/src/Makefile
  lib/parsetools/doc/src/leex.xml
  lib/parsetools/doc/src/specs.xml
  lib/parsetools/doc/src/yecc.xml
  lib/parsetools/src/leex.erl
  lib/parsetools/src/yecc.erl
Labels: enhancement, team:VM

#2833 monitor_node/2: Raise 'notalive' instead of 'badarg'
  erts/doc/src/erlang.xml
  erts/emulator/beam/dist.c
Labels: enhancement, team:VM, testing

#2831 Allow "underscore variables" to suppress all warnings
  lib/compiler/src/v3_core.erl
  lib/compiler/test/warnings_SUITE.erl
  system/doc/reference_manual/expressions.xml
Labels: enhancement, team:VM, testing

#2861 jit: Make mov_imm(Gp, NIL) shorter
  erts/emulator/beam/erl_term.h
  erts/emulator/beam/jit/beam_asm.hpp
  erts/etc/unix/etp-commands.in
Labels: team:VM, testing

#2860 erts: Refactor code pointers
  erts/configure.in
  erts/emulator/beam/beam_bif_load.c
  erts/emulator/beam/beam_bp.c
  erts/emulator/beam/beam_catches.c
  erts/emulator/beam/beam_catches.h
  erts/emulator/beam/beam_code.h
  erts/emulator/beam/beam_common.c
  erts/emulator/beam/beam_common.h
  erts/emulator/beam/beam_debug.c
  erts/emulator/beam/beam_load.c
  erts/emulator/beam/beam_ranges.c
  erts/emulator/beam/bif.c
  erts/emulator/beam/bif.h
  erts/emulator/beam/code_ix.h
  erts/emulator/beam/dist.c
  erts/emulator/beam/emu/beam_emu.c
  erts/emulator/beam/emu/bif_instrs.tab
  erts/emulator/beam/emu/emu_load.c
  erts/emulator/beam/emu/macros.tab
  erts/emulator/beam/emu/trace_instrs.tab
  erts/emulator/beam/erl_bif_info.c
  erts/emulator/beam/erl_bif_trace.c
  erts/emulator/beam/erl_fun.c
  erts/emulator/beam/erl_fun.h
  erts/emulator/beam/erl_gc.c
  erts/emulator/beam/erl_nfunc_sched.c
  erts/emulator/beam/erl_nfunc_sched.h
  erts/emulator/beam/erl_nif.c
  erts/emulator/beam/erl_printf_term.c
  erts/emulator/beam/erl_process.c
  erts/emulator/beam/erl_process.h
  erts/emulator/beam/erl_process_dump.c
  erts/emulator/beam/erl_term.c
  erts/emulator/beam/erl_term.h
  erts/emulator/beam/erl_trace.c
  erts/emulator/beam/erl_trace.h
  erts/emulator/beam/erl_vm.h
  erts/emulator/beam/error.h
  erts/emulator/beam/export.c
  erts/emulator/beam/export.h
  erts/emulator/beam/external.c
  erts/emulator/beam/global.h
  erts/emulator/beam/jit/asm_load.c
  erts/emulator/beam/jit/beam_asm.cpp
  erts/emulator/beam/jit/beam_asm.h
  erts/emulator/beam/jit/beam_asm.hpp
  erts/emulator/beam/jit/beam_asm_global.cpp
  erts/emulator/beam/jit/beam_asm_module.cpp
  erts/emulator/beam/jit/instr_bif.cpp
  erts/emulator/beam/jit/instr_call.cpp
  erts/emulator/beam/jit/instr_common.cpp
  erts/emulator/beam/jit/instr_map.cpp
  erts/emulator/beam/jit/instr_msg.cpp
  erts/emulator/beam/jit/instr_trace.cpp
  erts/emulator/beam/jit/load.h
  erts/emulator/beam/jit/ops.tab
  erts/emulator/beam/lttng-wrapper.h
  erts/emulator/beam/sys.h
  erts/emulator/sys/unix/sys_drivers.c
  erts/emulator/utils/make_tables
Labels: enhancement, team:VM, testing

#2865 Fix the make configuration for macOS 11.0.1
  make/configure.in
Labels: team:VM, testing

#2848 Reset inet_db timer even if file is up to date
  lib/kernel/src/inet_db.erl
Labels: team:PS

#2841 Add rendering config to shell_docs
  lib/kernel/doc/src/code.xml
  lib/kernel/doc/src/eep48_chapter.xml
  lib/stdlib/doc/src/shell_docs.xml
  lib/stdlib/src/shell_docs.erl
  lib/stdlib/test/shell_docs_SUITE.erl
Labels: enhancement, team:VM, testing

#2844 erl_docgen: Fix github links and title links to work again
  .github/dockerfiles/Dockerfile.documentation
  lib/erl_docgen/priv/css/otp_doc.css
  lib/erl_docgen/priv/xsl/db_html.xsl
  scripts/otp_html_check
Labels: fix, team:VM, testing

#2869 port_please/2 returns {port, _, _}, not {ok, _, _}
  lib/kernel/src/erl_epmd.erl
Labels: fix, team:VM, testing

#2832 erlexec: Improve error message when unable to open included args_file
  erts/etc/common/erlexec.c
  erts/test/erlexec_SUITE.erl
Labels: team:VM, testing

#2491 Allow binaries as parts of logger_formatter template
  lib/kernel/src/logger_formatter.erl
  lib/kernel/test/logger_formatter_SUITE.erl
Labels: team:VM, testing

#2871 macOS: Remove version check in configure script
  make/configure.in
Labels: fix, team:VM, testing

#2874 erts: Disable native stack if we can't make it signal-safe
  erts/configure.in
Labels: team:VM, testing

#2829 Make printing of floats more user friendly
  erts/doc/src/erlang.xml
  lib/stdlib/src/io_lib_format.erl
  lib/stdlib/test/io_SUITE.erl
  system/doc/reference_manual/data_types.xml
Labels: enhancement, team:VM, testing

#2875 ssl: Improve active emulation
  lib/ssl/src/ssl_connection.erl
  lib/ssl/src/tls_connection.erl
  lib/ssl/test/tls_api_SUITE.erl
Labels: team:PS, testing

#2880 Raise nicer exceptions for bad generator and filters in comprehensions
  lib/compiler/src/Makefile
  lib/compiler/src/beam_kernel_to_ssa.erl
  lib/compiler/src/beam_ssa_bc_size.erl
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/src/beam_types.erl
  lib/compiler/src/cerl_inline.erl
  lib/compiler/src/compile.erl
  lib/compiler/src/compiler.app.src
  lib/compiler/src/v3_core.erl
  lib/compiler/test/beam_except_SUITE.erl
  lib/compiler/test/bs_bincomp_SUITE.erl
  lib/compiler/test/lc_SUITE.erl
  lib/compiler/test/misc_SUITE.erl
Labels: enhancement, team:VM

#2863 Support ROOTDIR passed as an environment variable in erl and start scripts
  erts/etc/unix/erl.src.src
  erts/etc/unix/start.src
Labels: team:VM, testing

#2876 Allow building VM with static and gprof-enabled crypto NIF
  erts/emulator/utils/make_driver_tab
  lib/crypto/c_src/Makefile.in
Labels: fix, team:PS, testing

#2866 pg: fix 'foldl' that keeps remotely left pids from removal.
  lib/kernel/src/pg.erl
  lib/kernel/test/pg_SUITE.erl
Labels: team:VM, testing

#2850 Add queue:all/2, queue:any/2, queue:delete/2, and queue:delete_r/2
  lib/stdlib/doc/src/queue.xml
  lib/stdlib/src/queue.erl
  lib/stdlib/test/queue_SUITE.erl
Labels: team:PS, team:VM
