Repository erlang/otp, pull requests merged in 2020-04, with the labels that each got.

#2581 beam_validator: Improve type inference for '=/='
  lib/compiler/src/beam_validator.erl
  lib/compiler/test/beam_validator_SUITE.erl
Labels: fix, team:VM

#2571 Prevent left nav overlapping content during scroll
  lib/erl_docgen/priv/css/otp_doc.css
Labels: team:PS, testing

#2580 Update erl_prim_loader.erl
  erts/preloaded/src/erl_prim_loader.erl
Labels: team:VM

#2578 Fix crash in string printing
  lib/debugger/src/dbg_wx_win.erl
Labels: team:PS, testing

#2582 docs: fix recommend vs recommended errors
  lib/inets/doc/src/http_uri.xml
  lib/tools/doc/src/erlang_mode_chapter.xml
  lib/tools/emacs/internal_doc/emacs.sgml
Labels: team:PS

#2576 Fix handling of receive marker
  erts/emulator/beam/erl_bif_info.c
  erts/emulator/beam/erl_gc.c
  erts/emulator/beam/erl_message.c
  erts/emulator/beam/erl_message.h
  erts/emulator/beam/erl_proc_sig_queue.c
  erts/emulator/beam/erl_process.c
  erts/emulator/test/receive_SUITE.erl
Labels: fix, team:VM

#2590 ssl: Make benchmarks work again
  lib/ssl/test/ssl_bench_SUITE.erl
Labels: team:PS, testing

#2591 Remove old bifs from erl_internal
  lib/stdlib/src/erl_internal.erl
Labels: team:VM, testing

#2595 Document dynamic node names and dist_listen false
  erts/doc/src/erl_cmd.xml
  lib/kernel/doc/src/kernel_app.xml
  lib/kernel/src/net_kernel.erl
  lib/kernel/src/user_drv.erl
  lib/stdlib/doc/src/shell.xml
Labels: enhancement, team:VM

#2583 More EEP-48 improvements
  erts/doc/src/erl_dist_protocol.xml
  lib/erl_docgen/Makefile
  lib/erl_docgen/doc/src/doc_storage.xml
  lib/erl_docgen/priv/bin/specs_gen.escript
  lib/erl_docgen/priv/dtd/common.dtd
  lib/erl_docgen/src/docgen_xml_to_chunk.erl
  lib/kernel/doc/src/Makefile
  lib/kernel/doc/src/code.xml
  lib/kernel/doc/src/eep48_chapter.xml
  lib/kernel/doc/src/part.xml
  lib/kernel/src/code.erl
  lib/mnesia/doc/src/Mnesia_chap2.xmlsrc
  lib/mnesia/doc/src/Mnesia_chap4.xmlsrc
  lib/stdlib/doc/src/gen_statem.xml
  lib/stdlib/doc/src/shell.xml
  lib/stdlib/doc/src/shell_docs.xml
  lib/stdlib/src/c.erl
  lib/stdlib/src/otp_internal.hrl
  lib/stdlib/src/shell_default.erl
  lib/stdlib/src/shell_docs.erl
  lib/stdlib/test/property_test/shell_docs_prop.erl
  lib/stdlib/test/shell_docs_SUITE.erl
  scripts/build-otp
  scripts/otp_html_check
Labels: feature, team:VM

#2592 ssl: fix documentation of option `crl_cache`
  lib/ssl/src/ssl.erl
Labels: team:PS, testing

#2593 Fix misspelling in ssl test cases
  lib/ssl/test/openssl_npn_SUITE.erl
Labels: team:PS, testing, waiting

#2596 ssl: fix documentation of option verify_fun
  lib/ssl/doc/src/ssl.xml
Labels: team:PS

#2594 Fix slow lists:mapfoldl/3
  erts/emulator/beam/ops.tab
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/beam_trim.erl
  lib/compiler/test/beam_ssa_SUITE.erl
Labels: fix, team:VM

#2600 socket-nif: Fix string argument passing for setsockopt
  erts/emulator/nifs/common/prim_socket_nif.c
Labels: team:PS, testing

#2603 Optimize tail calls created during optimization
  lib/compiler/src/beam_ssa_opt.erl
Labels: fix, team:VM

#2604 Added a fun/4 with State access for keyboard-interactive
  lib/ssh/doc/src/ssh.xml
  lib/ssh/src/ssh.hrl
  lib/ssh/src/ssh_auth.erl
  lib/ssh/src/ssh_options.erl
Labels: feature, team:PS, testing

#2607 erl_call: Assume localhost if own hostname resolution fails
  lib/erl_interface/doc/src/erl_call_cmd.xml
  lib/erl_interface/src/prog/erl_call.c
  lib/erl_interface/test/erl_call_SUITE.erl
Labels: fix, team:VM, testing

#2608 ssl: Make sure client hostname check is run when client uses own veri…
  lib/ssl/src/ssl_certificate.erl
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/test/ssl_cert_SUITE.erl
  lib/ssl/test/ssl_cert_tests.erl
Labels: team:PS, testing

#2606 Fix SEGV while printing cancelled timer to crash dump
  erts/emulator/beam/erl_hl_timer.c
Labels: fix, team:VM

#2602 Add a cost for copying binaries with the binary syntax
  erts/emulator/beam/bs_instrs.tab
  erts/emulator/beam/erl_bits.c
  erts/emulator/beam/erl_bits.h
  erts/emulator/test/bs_construct_SUITE.erl
Labels: fix, team:VM, testing

#2605 Dgud/mnesia/pr 2488
  lib/mnesia/doc/specs/.gitignore
  lib/mnesia/doc/src/Makefile
  lib/mnesia/doc/src/Mnesia_chap4.xmlsrc
  lib/mnesia/doc/src/mnesia.xml
  lib/mnesia/doc/src/specs.xml
  lib/mnesia/src/mnesia.erl
Labels: team:PS, testing

#2430 edoc: support multiple clauses in -spec
  lib/edoc/src/edoc_data.erl
  lib/edoc/src/edoc_extract.erl
  lib/edoc/src/edoc_layout.erl
  lib/edoc/src/edoc_specs.erl
  lib/erl_docgen/src/docgen_edoc_xml_cb.erl
Labels: team:VM

#2615 Fix rpc usage (ERL-1238)
  lib/observer/src/observer_alloc_wx.erl
Labels: team:PS, testing

#2614 Copy erl_call to erts and filter tools from systools:make_tar
  erts/Makefile
  erts/emulator/test/port_bif_SUITE.erl
  erts/etc/common/Makefile.in
  erts/etc/unix/Install.src
  erts/etc/win32/Install.c
  lib/erl_interface/src/Makefile.in
  lib/sasl/doc/specs/.gitignore
  lib/sasl/doc/src/Makefile
  lib/sasl/doc/src/specs.xml
  lib/sasl/doc/src/systools.xml
  lib/sasl/src/systools.erl
  lib/sasl/src/systools_make.erl
  lib/sasl/test/systools_SUITE.erl
Labels: feature, team:VM, testing

#2390 [RFC] Make the HOME environment variable optional
  erts/etc/common/erlexec.c
Labels: enhancement, team:VM, testing

#2547 Implement RFC 6066 extension max_fragment_length
  lib/ssl/doc/src/ssl.xml
  lib/ssl/doc/src/standards_compliance.xml
  lib/ssl/src/dtls_connection.erl
  lib/ssl/src/dtls_handshake.erl
  lib/ssl/src/dtls_record.erl
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_connection.erl
  lib/ssl/src/ssl_connection.hrl
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/src/ssl_handshake.hrl
  lib/ssl/src/ssl_internal.hrl
  lib/ssl/src/ssl_record.erl
  lib/ssl/src/ssl_record.hrl
  lib/ssl/src/tls_connection.erl
  lib/ssl/src/tls_connection_1_3.erl
  lib/ssl/src/tls_handshake.erl
  lib/ssl/src/tls_handshake_1_3.erl
  lib/ssl/src/tls_record.erl
  lib/ssl/src/tls_record_1_3.erl
  lib/ssl/test/Makefile
  lib/ssl/test/ssl_mfl_SUITE.erl
  lib/ssl/test/ssl_session_SUITE.erl
  lib/ssl/test/ssl_test_lib.erl
  lib/ssl/test/tls_1_3_record_SUITE.erl
Labels: team:PS
