Repository erlang/otp, pull requests merged in 2020-03, with the labels that each got.

#2552 Use cerl_sets where appropriate in beam_ssa_bool
  lib/compiler/src/beam_ssa_bool.erl
Labels: enhancement, team:VM, testing

#2550 beam_ssa_opt: Add line numbers to all float conversions
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/test/float_SUITE.erl
Labels: fix, team:VM, testing

#2554 Add SSH agent support
  lib/ssh/doc/src/Makefile
  lib/ssh/doc/src/ref_man.xml
  lib/ssh/doc/src/specs.xml
  lib/ssh/doc/src/ssh_agent.xml
  lib/ssh/src/Makefile
  lib/ssh/src/ssh.app.src
  lib/ssh/src/ssh_agent.erl
  lib/ssh/src/ssh_agent.hrl
  lib/ssh/src/ssh_auth.erl
  lib/ssh/src/ssh_client_key_api.erl
  lib/ssh/test/Makefile
  lib/ssh/test/ssh_agent_SUITE.erl
  lib/ssh/test/ssh_agent_SUITE_data/authorized_keys
  lib/ssh/test/ssh_agent_SUITE_data/id_rsa
  lib/ssh/test/ssh_agent_SUITE_data/ssh_host_rsa_key
  lib/ssh/test/ssh_agent_mock_server.erl
Labels: feature, team:PS, waiting

#2365 Rename Service Discovery into Node Discovery in documentation
  erts/doc/src/alt_disco.xml
  erts/doc/src/notes.xml
  lib/kernel/doc/src/erl_epmd.xml
  lib/kernel/doc/src/notes.xml
Labels: team:VM, testing

#2557 pg: handle race condition between scope 'DOWN' and processes leaving
  lib/kernel/src/pg.erl
  lib/kernel/test/pg_SUITE.erl
Labels: fix, team:VM, testing

#2558 disk_log: fix typo in -spec
  lib/kernel/src/disk_log.erl
Labels: fix, team:VM, testing

#2328 Fix dead code in application_master
  lib/kernel/src/application_master.erl
Labels: fix, team:VM, testing

#2499 Re-phrase paragraphs
  system/doc/design_principles/statem.xml
Labels: team:PS, waiting

#2532 Add tty_exception_print_depth option to eunit:test
  lib/eunit/src/eunit.erl
  lib/eunit/src/eunit_lib.erl
  lib/eunit/src/eunit_tty.erl
Labels: team:PS, testing

#2564 beam_validator: Refactor exception handling
  lib/compiler/src/beam_validator.erl
Labels: team:VM, testing

#2562 compiler: Fix instruction order reversal in ssa_opt_try
  lib/compiler/src/beam_ssa_opt.erl
Labels: team:VM, testing

#2561 Fix ERL-1189
  lib/asn1/src/asn1ct.erl
  lib/asn1/test/asn1_SUITE.erl
  lib/asn1/test/asn1_SUITE_data/PartialDecChoExtension.asn
  lib/asn1/test/asn1_SUITE_data/PartialDecChoExtension.asn1config
  lib/asn1/test/test_selective_decode.erl
Labels: team:PS, testing

#2551 Allow sys_core_prepare to be skipped
  lib/compiler/src/compile.erl
  lib/compiler/test/compile_SUITE.erl
Labels: enhancement, team:VM, testing

#2560 Modify rpc to spawn non ram lookups
  lib/mnesia/src/mnesia_rpc.erl
Labels: fix, team:PS

#2567 compiler, beam_lib: Stop using deprecated crypto functions
  lib/compiler/src/compile.erl
  lib/stdlib/src/beam_lib.erl
Labels: fix, team:VM, testing

#2420 systools: support creating start.boot in make_script and adding files to make_tar
  lib/sasl/doc/src/systools.xml
  lib/sasl/src/systools_make.erl
  lib/sasl/test/systools_SUITE.erl
Labels: feature, team:VM, testing

#2523 Allow using custom IO devices in logger_std_h
  lib/kernel/doc/src/logger_std_h.xml
  lib/kernel/src/logger_std_h.erl
  lib/kernel/test/logger_std_h_SUITE.erl
Labels: team:VM, testing

#2565 add file:del_dir/2
  lib/kernel/doc/src/file.xml
  lib/kernel/src/file.erl
  lib/kernel/test/file_SUITE.erl
Labels: feature, team:VM

#2534 pg: ensure argument is expected local pid(s)
  lib/kernel/src/pg.erl
Labels: fix, team:VM, testing

#2570 Use effective UID and GID in checks
  erts/emulator/nifs/unix/unix_prim_file.c
Labels: team:VM, testing

#2575 erts: Fix external fun application of erlang:apply/3
  erts/emulator/beam/bif.c
  erts/emulator/beam/bif.tab
  erts/emulator/beam/instrs.tab
  erts/emulator/beam/ops.tab
  erts/emulator/test/bif_SUITE.erl
Labels: fix, team:VM, testing

#2577 Fix build of OTP with Xcode 11.4
  erts/configure.in
Labels: fix, team:VM
