Repository erlang/otp, pull requests merged in 2020-07, with the labels that each got.

#2666 release_handler more resilient of exiting processes during upgrade
  lib/sasl/src/release_handler_1.erl
Labels: fix, team:VM, testing

#2671 Spell out how bit strings are compared
  system/doc/reference_manual/expressions.xml
Labels: enhancement, team:VM, testing

#2678 Fix ei_get_type to set *size to zero for floats, pids, ports and refs
  lib/erl_interface/doc/src/ei.xml
  lib/erl_interface/src/misc/get_type.c
  lib/erl_interface/test/ei_decode_SUITE_data/ei_decode_test.c
  lib/erl_interface/test/ei_decode_encode_SUITE_data/ei_decode_encode_test.c
Labels: fix, team:VM, testing

#2683 Only compute vars and keys if we have patterns
  lib/compiler/src/sys_core_alias.erl
Labels: enhancement, team:VM, testing

#2681 sys_core_alias: Bail out when expressions get too deep
  lib/compiler/src/sys_core_alias.erl
  lib/compiler/test/core_alias_SUITE.erl
Labels: fix, team:VM, testing

#2679 Fix getting data from ssh-agent
  lib/ssh/src/ssh_agent.erl
Labels: fix, team:PS, testing

#2686 Correct typo in uri_string:normalize example doc
  lib/stdlib/doc/src/uri_string.xml
Labels: team:PS

#2687 Add missing include statements in in6addr tests
  erts/configure.in
Labels: fix, team:VM, testing

#2697 Fix stateless ticket window check. ERL-1316
  lib/ssl/doc/src/using_ssl.xml
  lib/ssl/src/tls_server_session_ticket.erl
  lib/ssl/test/ssl_session_ticket_SUITE.erl
Labels: team:PS

#2688 Fix documentation error
  lib/kernel/src/disk_log_1.erl
Labels: team:VM

#2694 erl_bits.hrl cleanup
  bootstrap/lib/stdlib/include/erl_bits.hrl
  lib/stdlib/include/erl_bits.hrl
Labels: enhancement, team:VM, testing
