Repository erlang/otp, pull requests merged in 2020-02, with the labels that each got.

#2486 Document noconnection error more prominently
  erts/doc/src/erlang.xml
  system/doc/reference_manual/errors.xml
Labels: team:VM

#2524 pg: distributed named process groups
  lib/kernel/doc/src/Makefile
  lib/kernel/doc/src/kernel_app.xml
  lib/kernel/doc/src/pg.xml
  lib/kernel/doc/src/ref_man.xml
  lib/kernel/doc/src/specs.xml
  lib/kernel/src/Makefile
  lib/kernel/src/kernel.app.src
  lib/kernel/src/kernel.erl
  lib/kernel/src/pg.erl
  lib/kernel/test/Makefile
  lib/kernel/test/pg_SUITE.erl
  lib/runtime_tools/src/observer_backend.erl
  system/doc/design_principles/distributed_applications.xml
  system/doc/tutorial/distribution.xml
  system/doc/tutorial/overview.xml
Labels: enhancement, team:VM, testing

#2521 EEP 52: Allow key and size expressions in map and binary matching
  .gitignore
  lib/compiler/src/Makefile
  lib/compiler/src/beam_kernel_to_ssa.erl
  lib/compiler/src/cerl_inline.erl
  lib/compiler/src/compile.erl
  lib/compiler/src/compiler.app.src
  lib/compiler/src/core_lib.erl
  lib/compiler/src/core_lint.erl
  lib/compiler/src/core_pp.erl
  lib/compiler/src/sys_core_fold.erl
  lib/compiler/src/sys_core_prepare.erl
  lib/compiler/src/v3_core.erl
  lib/compiler/src/v3_kernel.erl
  lib/compiler/src/v3_kernel.hrl
  lib/compiler/src/v3_kernel_pp.erl
  lib/compiler/test/Makefile
  lib/compiler/test/bs_bincomp_SUITE.erl
  lib/compiler/test/bs_match_SUITE.erl
  lib/compiler/test/bs_size_expr_SUITE.erl
  lib/compiler/test/core_SUITE.erl
  lib/compiler/test/core_SUITE_data/bs_shadowed_size_var.core
  lib/compiler/test/core_SUITE_data/receive_tests.core
  lib/compiler/test/error_SUITE.erl
  lib/compiler/test/map_SUITE.erl
  lib/compiler/test/receive_SUITE.erl
  lib/compiler/test/test_lib.erl
  lib/debugger/src/dbg_ieval.erl
  lib/debugger/src/dbg_iload.erl
  lib/debugger/test/Makefile
  lib/debugger/test/bs_size_expr_SUITE.erl
  lib/debugger/test/map_SUITE.erl
  lib/dialyzer/src/Makefile
  lib/dialyzer/src/dialyzer.app.src
  lib/dialyzer/src/dialyzer_clean_core.erl
  lib/dialyzer/src/dialyzer_dataflow.erl
  lib/dialyzer/src/dialyzer_dep.erl
  lib/dialyzer/src/dialyzer_typesig.erl
  lib/dialyzer/src/dialyzer_utils.erl
  lib/hipe/cerl/cerl_closurean.erl
  lib/stdlib/src/erl_eval.erl
  lib/stdlib/src/erl_expand_records.erl
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/src/eval_bits.erl
  lib/stdlib/test/erl_eval_SUITE.erl
  lib/stdlib/test/erl_lint_SUITE.erl
  lib/stdlib/test/shell_SUITE.erl
  system/doc/programming_examples/bit_syntax.xml
  system/doc/reference_manual/expressions.xml
Labels: enhancement, team:VM, testing

#2526 Optimize =:= when comparing maps
  erts/emulator/beam/utils.c
Labels: enhancement, team:VM, testing

#2525 net_kernel: improve performance of debugging functions, and fix race
  lib/kernel/src/dist_util.erl
  lib/kernel/src/net_kernel.erl
Labels: enhancement, team:VM, testing

#2508 lib/asn1: add missing build dependency to 'asn1ct_eval_ext.erl'
  lib/asn1/src/Makefile
Labels: team:PS, testing

#2514 Fix compile on systems without getifaddrs, add PASE getifaddrs
  erts/emulator/nifs/common/prim_net_nif.c
Labels: team:PS, testing

#2530 Fix ERL-1170
  lib/compiler/src/sys_core_fold.erl
  lib/compiler/test/core_fold_SUITE.erl
Labels: fix, team:VM, testing

#2535 Clarify try-of documentation
  system/doc/reference_manual/expressions.xml
Labels: enhancement, team:VM

#2531 gen_statem: change callback module
  lib/stdlib/doc/src/gen_statem.xml
  lib/stdlib/src/gen_statem.erl
  lib/stdlib/test/gen_statem_SUITE.erl
  lib/stdlib/test/gen_statem_SUITE_data/oc_statem.erl
  system/doc/design_principles/statem.xml
Labels: team:PS

#2539 stdlib: Mark zip files as Unix-compatible
  lib/stdlib/src/zip.erl
  lib/stdlib/test/zip_SUITE.erl
Labels: fix, team:VM, testing

#2536 Remove package support from ms_transform
  lib/stdlib/src/ms_transform.erl
Labels: fix, team:VM, testing

#2538 cover: Suppress compilation warnings when instrumenting andalso/orelse
  lib/tools/src/cover.erl
  lib/tools/test/cover_SUITE.erl
  lib/tools/test/cover_SUITE_data/otp_16476/obvious_booleans.erl
Labels: fix, team:VM, testing

#2537 Eliminate crash in compilation of native code
  lib/hipe/icode/hipe_icode_primops.erl
  lib/hipe/test/basic_SUITE_data/basic_exceptions.erl
Labels: fix, team:VM, testing

#2516 inet_db, inet_hosts: improve inet_db behaviour when .hosts file changes
  lib/kernel/src/inet_db.erl
  lib/kernel/src/inet_hosts.erl
  lib/kernel/test/inet_SUITE.erl
Labels: team:PS

#2527 Fix invalid xml closing tag in proplists.erl edoc
  lib/stdlib/src/proplists.erl
Labels: team:VM

#2540 Adjust spawn_request() features
  erts/doc/src/erlang.xml
  erts/emulator/beam/atom.names
  erts/emulator/beam/beam_emu.c
  erts/emulator/beam/bif.c
  erts/emulator/beam/bif.tab
  erts/emulator/beam/dist.c
  erts/emulator/beam/erl_hl_timer.c
  erts/emulator/beam/erl_hl_timer.h
  erts/emulator/beam/erl_monitor_link.h
  erts/emulator/beam/erl_proc_sig_queue.c
  erts/emulator/beam/erl_process.c
  erts/emulator/beam/erl_process.h
  erts/emulator/beam/error.h
  erts/emulator/test/process_SUITE.erl
  erts/preloaded/ebin/erlang.beam
  erts/preloaded/src/erlang.erl
  lib/stdlib/src/erl_internal.erl
  lib/tools/emacs/erlang.el
Labels: enhancement, feature, team:VM

#2528 Make hstring & bstring lexical items conform to ITU-T X.680 (08/2015)
  lib/asn1/src/asn1ct_tok.erl
  lib/asn1/test/asn1_SUITE_data/ValueTest.asn
  lib/asn1/test/testValueTest.erl
Labels: team:PS, testing

#2541 Improvements of the rpc module
  lib/kernel/doc/src/Makefile
  lib/kernel/doc/src/erpc.xml
  lib/kernel/doc/src/ref_man.xml
  lib/kernel/doc/src/rpc.xml
  lib/kernel/doc/src/specs.xml
  lib/kernel/src/Makefile
  lib/kernel/src/erpc.erl
  lib/kernel/src/kernel.app.src
  lib/kernel/src/rpc.erl
  lib/kernel/test/Makefile
  lib/kernel/test/erpc_SUITE.erl
  lib/kernel/test/global_SUITE.erl
  lib/kernel/test/rpc_SUITE.erl
  lib/kernel/test/seq_trace_SUITE.erl
  lib/observer/test/crashdump_helper.erl
  lib/sasl/test/release_handler_SUITE_data/lib/many_mods-1.0/src/m.erl
  lib/sasl/test/release_handler_SUITE_data/lib/many_mods-1.1/src/m.erl
  lib/sasl/test/release_handler_SUITE_data/lib/many_mods-2.0/src/m.erl
Labels: enhancement, feature, team:VM

#2461 Allow changing the -mode when the system restarts
  erts/doc/src/init.xml
  erts/preloaded/src/init.erl
  lib/kernel/test/init_SUITE.erl
Labels: team:VM

#2546 Don't keep stacktraces forever
  erts/doc/src/erlang.xml
  erts/emulator/beam/beam_emu.c
  erts/emulator/beam/bif.c
  erts/emulator/beam/erl_gc.c
  erts/emulator/beam/instrs.tab
  erts/emulator/hipe/hipe_bif2.c
  erts/emulator/test/code_SUITE_data/call_purged_fun_tester.erl
  erts/emulator/test/exception_SUITE.erl
  erts/emulator/test/hipe_SUITE.erl
  erts/emulator/test/hipe_SUITE_data/trycatch_1.erl
  erts/emulator/test/trace_local_SUITE.erl
  lib/compiler/src/sys_core_fold.erl
  lib/compiler/test/trycatch_SUITE.erl
  lib/debugger/src/dbg_ieval.erl
  lib/debugger/src/dbg_iload.erl
  lib/debugger/test/exception_SUITE.erl
  lib/debugger/test/int_eval_SUITE_data/stacktrace.erl
  lib/debugger/test/line_number_SUITE.erl
  lib/dialyzer/test/small_SUITE_data/results/stacktrace
  lib/dialyzer/test/small_SUITE_data/src/stacktrace.erl
  lib/hipe/icode/hipe_beam_to_icode.erl
  lib/inets/test/httpd_SUITE.erl
  lib/inets/test/httpd_test_lib.erl
  system/doc/reference_manual/errors.xml
Labels: enhancement, team:VM, testing

#2427 Support for start_monitor() in proc_lib and OTPs gen_* behaviors
  erts/doc/src/erlang.xml
  erts/preloaded/ebin/erlang.beam
  erts/preloaded/src/erlang.erl
  lib/stdlib/doc/src/gen_event.xml
  lib/stdlib/doc/src/gen_server.xml
  lib/stdlib/doc/src/gen_statem.xml
  lib/stdlib/doc/src/proc_lib.xml
  lib/stdlib/src/gen.erl
  lib/stdlib/src/gen_event.erl
  lib/stdlib/src/gen_server.erl
  lib/stdlib/src/gen_statem.erl
  lib/stdlib/src/proc_lib.erl
  lib/stdlib/test/gen_event_SUITE.erl
  lib/stdlib/test/gen_server_SUITE.erl
  lib/stdlib/test/gen_statem_SUITE.erl
  lib/stdlib/test/proc_lib_SUITE.erl
Labels: team:VM

#2553 Make sure that 'fail' in a guard makes the guard fail
  lib/compiler/src/beam_ssa_bool.erl
  lib/compiler/test/guard_SUITE.erl
Labels: fix, team:VM
