Repository erlang/otp, pull requests merged in 2020-06, with the labels that each got.

#2633 Fix various small typos in the OTP Design Principles
  system/doc/design_principles/applications.xml
  system/doc/design_principles/des_princ.xml
  system/doc/design_principles/events.xml
  system/doc/design_principles/release_handling.xml
  system/doc/design_principles/release_structure.xml
  system/doc/design_principles/statem.xml
  system/doc/design_principles/sup_princ.xml
Labels: team:PS, testing

#2643 Fix system restart when installing in silent mode
  erts/etc/win32/nsis/erlang20.nsi
Labels: team:PS, testing

#2644 Fix minor typo in IPv6 example
  lib/kernel/doc/src/inet.xml
Labels: team:PS

#2649 Fix bug in erlang:load_nif/2 sometimes throwing badarg
  erts/emulator/beam/bif_instrs.tab
Labels: fix, team:VM, testing

#2647 Fix line number for failing map update
  erts/emulator/test/exception_SUITE.erl
  lib/compiler/src/beam_ssa_codegen.erl
Labels: fix, team:VM, testing

#2651 Eliminate compiler crash for repeated is_map_key/2 calls
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/test/beam_ssa_SUITE.erl
Labels: fix, team:VM

#2655 erts: set quota to 1 if cpu quota is less than 1
  erts/lib_src/common/erl_misc_utils.c
Labels: fix, team:VM, testing

#2646 Refix doc overlapping during horizontal scroll
  lib/erl_docgen/priv/css/otp_doc.css
  lib/erl_docgen/priv/xsl/db_html.xsl
  system/doc/top/templates/index.html.src
Labels: fix, team:VM, testing

#2657 Clarify how to make contributions
  CONTRIBUTING.md
Labels: team:PS, team:VM

#2661 erts: Revert small doc change
  erts/doc/src/erlang.xml
Labels: fix, team:VM

#2642 Fix grammar in mnesia:dirty_update_counter/3 docs
  lib/mnesia/doc/src/mnesia.xml
Labels: team:PS

#2659 Fix typo in edoc for erl_syntax:operator/1
  lib/syntax_tools/src/erl_syntax.erl
Labels: team:VM, testing

#2662 Allow variables bound in 'try' to be used in 'of' clauses
  lib/compiler/src/v3_core.erl
  lib/compiler/test/trycatch_SUITE.erl
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/test/erl_lint_SUITE.erl
Labels: feature, team:VM, testing

#2669 HiPE: fix typo in doc
  lib/hipe/doc/src/HiPE_app.xml
Labels: fix, team:VM

#2670 Socket: open any protocol. OTP-14601
  erts/configure.in
  erts/emulator/nifs/common/prim_net_nif.c
  erts/emulator/nifs/common/prim_socket_nif.c
  erts/emulator/nifs/common/socket_int.h
  erts/emulator/nifs/common/socket_util.c
  erts/emulator/nifs/common/socket_util.h
  erts/preloaded/ebin/prim_socket.beam
  erts/preloaded/src/prim_socket.erl
  lib/kernel/doc/src/socket.xml
  lib/kernel/src/socket.erl
Labels: team:PS

#2667 beam_ssa_type: Fix endless loop
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/test/beam_type_SUITE.erl
Labels: fix, team:VM, testing

#2668 doc: Update The Abstract Format to use ANNO instaed of LINE
  erts/doc/src/absform.xml
Labels: team:VM

#2653 Remove doc reference to get_stacktrace/0 from erlang:raise/3
  erts/doc/src/erlang.xml
Labels: fix, team:VM, testing
