Repository erlang/otp, pull requests merged in 2021-02, with the labels that each got.

#3007 compiler: Stop emitting the fclearerror and fcheckerror instructions
  lib/compiler/src/beam_block.erl
  lib/compiler/src/beam_flatten.erl
  lib/compiler/src/beam_jump.erl
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/beam_ssa_pre_codegen.erl
  lib/compiler/src/beam_validator.erl
  lib/compiler/src/compile.erl
  lib/compiler/src/genop.tab
  lib/compiler/test/beam_validator_SUITE.erl
  lib/compiler/test/beam_validator_SUITE_data/freg_range.S
  lib/compiler/test/beam_validator_SUITE_data/freg_uninit.S
Labels: enhancement, fix, team:VM

#3012 Make the SSA instruction bs_put conform to failure conventions
  lib/compiler/src/beam_kernel_to_ssa.erl
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/beam_ssa_pre_codegen.erl
  lib/compiler/src/beam_ssa_recv.erl
  lib/compiler/test/bs_construct_SUITE.erl
Labels: enhancement, fix, team:VM

#3013 logger: Fix typos
  lib/kernel/doc/src/logger.xml
Labels: team:VM

#2950 Remove erl_interface registry
  lib/erl_interface/doc/src/Makefile
  lib/erl_interface/doc/src/ei_users_guide.xml
  lib/erl_interface/doc/src/notes.xml
  lib/erl_interface/doc/src/ref_man.xml
  lib/erl_interface/doc/src/registry.xml
  lib/erl_interface/include/ei.h
  lib/erl_interface/src/Makefile.in
  lib/erl_interface/src/README.internal
  lib/erl_interface/src/registry/hash.h
  lib/erl_interface/src/registry/hash_dohash.c
  lib/erl_interface/src/registry/hash_foreach.c
  lib/erl_interface/src/registry/hash_freetab.c
  lib/erl_interface/src/registry/hash_insert.c
  lib/erl_interface/src/registry/hash_isprime.c
  lib/erl_interface/src/registry/hash_lookup.c
  lib/erl_interface/src/registry/hash_newtab.c
  lib/erl_interface/src/registry/hash_remove.c
  lib/erl_interface/src/registry/hash_resize.c
  lib/erl_interface/src/registry/hash_rlookup.c
  lib/erl_interface/src/registry/reg.h
  lib/erl_interface/src/registry/reg_close.c
  lib/erl_interface/src/registry/reg_delete.c
  lib/erl_interface/src/registry/reg_dirty.c
  lib/erl_interface/src/registry/reg_dump.c
  lib/erl_interface/src/registry/reg_free.c
  lib/erl_interface/src/registry/reg_get.c
  lib/erl_interface/src/registry/reg_getf.c
  lib/erl_interface/src/registry/reg_geti.c
  lib/erl_interface/src/registry/reg_getp.c
  lib/erl_interface/src/registry/reg_gets.c
  lib/erl_interface/src/registry/reg_make.c
  lib/erl_interface/src/registry/reg_open.c
  lib/erl_interface/src/registry/reg_purge.c
  lib/erl_interface/src/registry/reg_resize.c
  lib/erl_interface/src/registry/reg_restore.c
  lib/erl_interface/src/registry/reg_set.c
  lib/erl_interface/src/registry/reg_setf.c
  lib/erl_interface/src/registry/reg_seti.c
  lib/erl_interface/src/registry/reg_setp.c
  lib/erl_interface/src/registry/reg_sets.c
  lib/erl_interface/src/registry/reg_stat.c
  lib/erl_interface/src/registry/reg_tabstat.c
  system/doc/general_info/deprecations_23.inc
  system/doc/general_info/removed_24.inc
  system/doc/general_info/scheduled_for_removal_24.inc
Labels: team:VM

#3005 jinterface: make OtpErlangExternalFun transparent
  lib/jinterface/java_src/com/ericsson/otp/erlang/OtpErlangExternalFun.java
Labels: team:VM, testing

#3011 Explain {continue,Continue} in gen_server:Module:init/1 doc
  lib/stdlib/doc/src/gen_server.xml
  lib/stdlib/src/gen_server.erl
Labels: team:VM

#3017 otp: Require complete build when updating deprecations
  lib/stdlib/scripts/update_deprecations
Labels: enhancement, team:VM

#3015 Reduce compilation times for some huge modules
  lib/compiler/src/beam_ssa_recv.erl
  lib/compiler/src/compile.erl
Labels: enhancement, team:VM

#3019 Make compiler accept abstract format as input
  lib/compiler/doc/src/compile.xml
  lib/compiler/src/compile.erl
  lib/stdlib/src/erl_compile.erl
Labels: team:VM, testing

#3016 Deprecate all functions in erl_tidy
  bootstrap/lib/stdlib/ebin/otp_internal.beam
  lib/stdlib/src/otp_internal.erl
  lib/syntax_tools/src/erl_tidy.erl
  system/doc/general_info/DEPRECATIONS
Labels: team:VM, testing

#3025 beam_validator: Fix bitstring unit inference
  lib/compiler/src/beam_validator.erl
  lib/compiler/test/bs_match_SUITE.erl
Labels: fix, team:VM, testing

#3023 Stop allowing latin-1 files without an explicit comment
  lib/compiler/src/compile.erl
  lib/compiler/test/error_SUITE.erl
  lib/compiler/test/warnings_SUITE.erl
  system/doc/general_info/removed_24.inc
  system/doc/general_info/scheduled_for_removal_24.inc
Labels: enhancement, team:VM, testing

#3001 Make sure that math:{acos,asin}/1 consistently fail for domain errors
  erts/aclocal.m4
  erts/configure.in
  erts/emulator/beam/erl_math.c
  lib/stdlib/src/erl_stdlib_errors.erl
  lib/stdlib/test/math_SUITE.erl
Labels: fix, team:VM, testing

#3022 Allow maps as erl_eval bindings
  lib/stdlib/doc/src/erl_eval.xml
  lib/stdlib/src/erl_eval.erl
  lib/stdlib/test/erl_eval_SUITE.erl
Labels: enhancement, team:VM, testing

#2990 Add wxWebView to base images
  .github/dockerfiles/Dockerfile.debian-base
  .github/dockerfiles/Dockerfile.ubuntu-base
Labels: team:PS, team:VM

#3003 Reconnect to epmd
  erts/doc/src/erl_dist_protocol.xml
  lib/kernel/doc/src/erl_epmd.xml
  lib/kernel/src/erl_epmd.erl
  lib/kernel/test/erl_distribution_SUITE.erl
Labels: enhancement, team:VM, testing

#3028 Add link to Removed Functionality on the top page
  system/doc/top/templates/index.html.src
Labels: enhancement, team:VM, testing

#2883 Drop the erl_tidy and igor modules from syntax_tools
  bootstrap/lib/stdlib/ebin/otp_internal.beam
  lib/stdlib/src/otp_internal.erl
  lib/syntax_tools/doc/overview.edoc
  lib/syntax_tools/doc/src/Makefile
  lib/syntax_tools/doc/src/ref_man.xml
  lib/syntax_tools/doc/src/specs.xml
  lib/syntax_tools/src/Makefile
  lib/syntax_tools/src/erl_tidy.erl
  lib/syntax_tools/src/igor.erl
  lib/syntax_tools/src/syntax_tools.app.src
  lib/syntax_tools/test/syntax_tools_SUITE.erl
  lib/syntax_tools/test/syntax_tools_SUITE_data/empty.erl
  lib/syntax_tools/test/syntax_tools_SUITE_data/erl_tidy_tilde.erl
  lib/syntax_tools/test/syntax_tools_SUITE_data/igor_type_specs.erl
  lib/syntax_tools/test/syntax_tools_SUITE_data/m1.erl
  lib/syntax_tools/test/syntax_tools_SUITE_data/m2.erl
  system/doc/general_info/DEPRECATIONS
  system/doc/general_info/removed_24.inc
Labels: team:VM, testing

#3024 dialyzer: Use types and specs for documentation
  lib/dialyzer/doc/.gitignore
  lib/dialyzer/doc/manual.txt
  lib/dialyzer/doc/specs/.gitignore
  lib/dialyzer/doc/src/Makefile
  lib/dialyzer/doc/src/dialyzer.xml
  lib/dialyzer/doc/src/specs.xml
  lib/dialyzer/src/dialyzer.erl
  lib/dialyzer/src/dialyzer.hrl
  lib/dialyzer/src/dialyzer_cl.erl
  lib/dialyzer/src/dialyzer_cl_parse.erl
  lib/dialyzer/src/dialyzer_options.erl
Labels: team:VM

#2995 compiler: Warn about matching underscore-prefixed variables
  bootstrap/lib/compiler/ebin/beam_ssa_bc_size.beam
  bootstrap/lib/compiler/ebin/beam_validator.beam
  bootstrap/lib/compiler/ebin/compile.beam
  bootstrap/lib/kernel/ebin/application_controller.beam
  bootstrap/lib/stdlib/ebin/erl_eval.beam
  bootstrap/lib/stdlib/ebin/erl_lint.beam
  bootstrap/lib/stdlib/ebin/erl_parse.beam
  bootstrap/lib/stdlib/ebin/erl_stdlib_errors.beam
  bootstrap/lib/stdlib/include/assert.hrl
  lib/asn1/src/asn1ct.erl
  lib/common_test/src/ct_logs.erl
  lib/compiler/doc/src/compile.xml
  lib/et/examples/et_demo.erl
  lib/inets/src/http_lib/http_util.erl
  lib/inets/src/http_server/httpd_util.erl
  lib/inets/src/http_server/mod_auth.erl
  lib/kernel/src/application_controller.erl
  lib/snmp/src/agent/snmpa_vacm.erl
  lib/stdlib/include/assert.hrl
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/test/erl_lint_SUITE.erl
  lib/xmerl/src/xmerl_sax_parser_base.erlsrc
Labels: team:VM, testing

#3030 Reduce confusion by rephrasing some compiler warnings
  lib/compiler/src/sys_core_fold.erl
  lib/compiler/test/warnings_SUITE.erl
Labels: enhancement, team:VM, testing

#3036 Correct code generation for "receive after infinity..." in try/catch
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/test/receive_SUITE.erl
Labels: fix, team:VM, testing

#3034 beam_validator: More bit syntax alignment fixes
  lib/compiler/src/beam_validator.erl
  lib/compiler/test/bs_match_SUITE.erl
Labels: team:VM, testing

#2996 Erlang doc fixes
  erts/doc/src/erlang.xml
Labels: team:VM, testing

#3002 shell: read records from module in escript/archive
  lib/stdlib/src/shell.erl
  lib/stdlib/test/shell_SUITE.erl
Labels: fix, team:VM, testing

#3020 Quote source as part of error messages
  erts/test/erlc_SUITE.erl
  lib/compiler/doc/src/compile.xml
  lib/compiler/src/Makefile
  lib/compiler/src/compile.erl
  lib/compiler/src/compiler.app.src
  lib/compiler/src/sys_messages.erl
  lib/compiler/test/compile_SUITE.erl
  lib/compiler/test/compile_SUITE_data/bad_enc.erl
  lib/compiler/test/compile_SUITE_data/col_lat1.erl
  lib/compiler/test/compile_SUITE_data/col_utf8.erl
  lib/debugger/test/int_SUITE.erl
  lib/stdlib/test/escript_SUITE.erl
Labels: enhancement, team:VM, testing

#3032 dialyzer: Add option 'error_location'
  lib/dialyzer/doc/src/dialyzer.xml
  lib/dialyzer/src/dialyzer.erl
  lib/dialyzer/src/dialyzer.hrl
  lib/dialyzer/src/dialyzer_cl.erl
  lib/dialyzer/src/dialyzer_cl_parse.erl
  lib/dialyzer/src/dialyzer_gui_wx.erl
  lib/dialyzer/src/dialyzer_options.erl
  lib/dialyzer/test/line_SUITE_data/dialyzer_options
  lib/dialyzer/test/line_SUITE_data/results/trec
  lib/dialyzer/test/line_SUITE_data/src/trec.erl
  lib/dialyzer/test/small_SUITE_data/dialyzer_options
Labels: team:VM

#3040 Remove old mac init code
  lib/wx/c_src/wxe_ps_init.c
Labels: team:PS, testing

#3048 erl_lint: Eliminate type violation
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/src/erl_parse.yrl
Labels: fix, team:VM, testing

#3046 beam_jump: Eliminate 'undecided_allocation' failure
  lib/compiler/src/beam_jump.erl
  lib/compiler/test/beam_jump_SUITE.erl
Labels: fix, team:VM, testing

#3008 Add warning in erl_nif doc about match state problem
  erts/doc/src/erl_nif.xml
Labels: enhancement, team:VM

#2675 Add optional_applications to .app resource files
  lib/kernel/doc/src/app.xml
  lib/kernel/doc/src/application.xml
  lib/kernel/src/application.erl
  lib/kernel/src/application_controller.erl
  lib/kernel/test/application_SUITE.erl
  lib/reltool/src/reltool.hrl
  lib/reltool/src/reltool_server.erl
  lib/reltool/src/reltool_target.erl
  lib/reltool/test/reltool_server_SUITE.erl
  lib/reltool/test/reltool_server_SUITE_data/sort_apps/z-1.0/ebin/z.app
  lib/sasl/src/systools.hrl
  lib/sasl/src/systools_make.erl
  lib/sasl/test/systools_SUITE.erl
  lib/sasl/test/systools_SUITE_data/d_opt_apps/lib/app1-1.0/ebin/app1.app
  lib/sasl/test/systools_SUITE_data/d_opt_apps/lib/app1-1.0/src/myapp1.erl
  lib/sasl/test/systools_SUITE_data/d_opt_apps/lib/app2-1.0/ebin/app2.app
  lib/sasl/test/systools_SUITE_data/d_opt_apps/lib/app2-1.0/src/myapp2.erl
Labels: team:VM, testing

#3035 odbc: Fix odbcserver not terminated at timeout
  lib/odbc/c_src/odbcserver.c
Labels: team:PS, testing

#2984 Add maps:foreach/2 function
  lib/stdlib/doc/src/maps.xml
  lib/stdlib/src/erl_stdlib_errors.erl
  lib/stdlib/src/maps.erl
  lib/stdlib/test/maps_SUITE.erl
Labels: team:VM, testing

#3051 sys_core_fold: Emit {eval_failure|result_ignored, {M, F, A}}
  lib/compiler/src/sys_core_fold.erl
  lib/compiler/test/warnings_SUITE.erl
Labels: enhancement, team:VM, testing

#3031 Make emulator terminate if erlsrv does (windows)
  erts/etc/win32/erlsrv/erlsrv_service.c
Labels: fix, team:VM, testing

#3050 dialyzer: Clarify how to declare records used in match patterns
  system/doc/reference_manual/typespec.xml
Labels: team:VM

#3049 ssh: Add longname field in sftp version 3
  lib/ssh/src/ssh_sftpd.erl
  lib/ssh/src/ssh_xfer.erl
Labels: team:PS, testing

#2457 Add support for default metadata to the logger
  lib/kernel/doc/src/kernel_app.xml
  lib/kernel/doc/src/logger.xml
  lib/kernel/doc/src/logger_chapter.xml
  lib/kernel/src/logger.erl
  lib/kernel/src/logger_backend.erl
  lib/kernel/src/logger_config.erl
  lib/kernel/src/logger_server.erl
  lib/kernel/test/logger_SUITE.erl
Labels: enhancement, team:VM, testing

#2721 Allow metadata and ignore to be computed in logger funs
  lib/kernel/doc/src/logger.xml
  lib/kernel/doc/src/logger_chapter.xml
  lib/kernel/src/logger.erl
  lib/kernel/test/logger_SUITE.erl
Labels: team:VM, testing

#2658 Document epp:scan_erl_form/1 and add epp:scan_file/2
  lib/stdlib/doc/src/epp.xml
  lib/stdlib/src/epp.erl
  lib/stdlib/src/erl_scan.erl
  lib/stdlib/test/epp_SUITE.erl
Labels: team:VM, testing

#4506 Improve test coverage of the compiler application
  lib/compiler/src/beam_block.erl
  lib/compiler/src/beam_flatten.erl
  lib/compiler/src/beam_jump.erl
  lib/compiler/src/beam_kernel_to_ssa.erl
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/src/beam_trim.erl
  lib/compiler/src/compile.erl
  lib/compiler/test/Makefile
  lib/compiler/test/beam_ssa_SUITE.erl
  lib/compiler/test/bif_SUITE.erl
  lib/compiler/test/bs_bincomp_SUITE.erl
  lib/compiler/test/bs_match_SUITE.erl
  lib/compiler/test/compile_SUITE.erl
  lib/compiler/test/compile_SUITE_data/bad_core.core
  lib/compiler/test/compile_SUITE_data/bad_core_tokens.core
  lib/compiler/test/compile_SUITE_data/column_pt.erl
  lib/compiler/test/compile_SUITE_data/cover_messages.erl
  lib/compiler/test/compile_SUITE_data/generic_pt.erl
  lib/compiler/test/compile_SUITE_data/line_pt.erl
  lib/compiler/test/compile_SUITE_data/needs_defines.erl
  lib/compiler/test/core_fold_SUITE.erl
  lib/compiler/test/fun_SUITE.erl
  lib/compiler/test/guard_SUITE.erl
  lib/compiler/test/misc_SUITE.erl
  lib/compiler/test/receive_SUITE.erl
  lib/compiler/test/record_SUITE.erl
  lib/compiler/test/trycatch_SUITE.erl
Labels: enhancement, team:VM

#4516 Fix incorrect links on erpc docs
  lib/kernel/doc/src/erpc.xml
Labels: team:VM, testing

#3043 jit: Optimized code generation for select_val
  erts/emulator/beam/jit/beam_asm.hpp
  erts/emulator/beam/jit/instr_select.cpp
Labels: enhancement, team:VM, testing

#4519 Reduce register shuffling
  lib/compiler/src/beam_block.erl
  lib/compiler/src/beam_ssa_pre_codegen.erl
Labels: enhancement, team:VM

#4528 compile: Refactor handling of internal errors
  lib/compiler/src/compile.erl
  lib/compiler/test/compile_SUITE.erl
  lib/compiler/test/compile_SUITE_data/generic_pt.erl
Labels: enhancement, team:VM

#4505 Improved memory barrier usage on ARMv8, and specifically for Apple silicon
  erts/aclocal.m4
  erts/include/internal/ethread_header_config.h.in
  erts/include/internal/gcc/ethr_membar.h
  erts/include/internal/gcc/ethread.h
Labels: enhancement, team:VM, testing

#4510 Improved memory barrier usage on 64-bit PowerPC
  erts/aclocal.m4
  erts/include/internal/ethread_header_config.h.in
  erts/include/internal/gcc/ethread.h
Labels: enhancement, team:VM, testing

#3045 Error message types
  lib/compiler/src/compile.erl
  lib/compiler/src/core_lint.erl
  lib/compiler/src/sys_messages.erl
  lib/compiler/test/core_SUITE.erl
  lib/compiler/test/core_fold_SUITE.erl
  lib/stdlib/doc/src/erl_lint.xml
  lib/stdlib/src/erl_lint.erl
Labels: enhancement, team:VM, testing

#4531 jit: Generate multi-byte NOPs in the way GAS does
  erts/emulator/beam/jit/beam_asm.cpp
  erts/emulator/beam/jit/beam_asm.hpp
Labels: enhancement, team:VM, testing

#2890 Support IEEE 754-2008 16-bits floats in bitstrings
  erts/configure.in
  erts/emulator/beam/erl_bits.c
  erts/emulator/beam/erl_bits_f16.h
  erts/emulator/test/bs_construct_SUITE.erl
  erts/emulator/test/bs_match_misc_SUITE.erl
  lib/compiler/src/sys_core_fold.erl
  lib/compiler/test/bs_construct_SUITE.erl
  lib/debugger/test/bs_match_misc_SUITE.erl
  lib/stdlib/src/erl_lint.erl
  system/COPYRIGHT
  system/doc/reference_manual/expressions.xml
Labels: enhancement, stalled, team:VM, testing

#4532 runtime_tools: Clarify scheduler utilization docs
  lib/runtime_tools/doc/src/scheduler.xml
Labels: documentation, enhancement, team:VM, testing

#3039 erts: Fix seq_trace token gc
  erts/emulator/beam/erl_bif_trace.c
  erts/emulator/beam/erl_process.c
  lib/kernel/test/seq_trace_SUITE.erl
Labels: team:VM, testing

#4534 Rewrite erpc:multicall() to utilize new receive optimization
  lib/kernel/src/erpc.erl
  lib/kernel/test/erpc_SUITE.erl
Labels: enhancement, team:VM, testing

#2960 Use Ryu for io_lib_format:fwrite_g/1
  lib/stdlib/scripts/generate_ryu_table.escript
  lib/stdlib/src/Makefile
  lib/stdlib/src/io_lib_format.erl
  lib/stdlib/src/io_lib_format_ryu_table.erl
  lib/stdlib/src/stdlib.app.src
  lib/stdlib/test/io_SUITE.erl
Labels: team:VM, testing

#4508 Replace uses of maps:map and maps:fold with maps:foreach
  lib/kernel/src/net_kernel.erl
  lib/kernel/src/pg.erl
  lib/stdlib/src/shell_docs.erl
  lib/stdlib/src/supervisor.erl
Labels: enhancement, team:VM, testing

#4513 Dgud/wx/fix queue
  lib/wx/api_gen/wx_extra/wxTaskBarIcon.c_src
  lib/wx/c_src/gen/wxe_derived_dest.h
  lib/wx/c_src/wxe_callback_impl.cpp
  lib/wx/c_src/wxe_gl.cpp
  lib/wx/c_src/wxe_helpers.cpp
  lib/wx/c_src/wxe_helpers.h
  lib/wx/c_src/wxe_impl.cpp
Labels: team:PS, testing

#4539 Fix punctuation, wording
  erts/doc/src/erl_cmd.xml
Labels: fix, team:VM

#3027 Add wxWebView
  HOWTO/INSTALL-WIN32.md
  lib/wx/api_gen/Makefile
  lib/wx/api_gen/interface/wx/webview.h
  lib/wx/api_gen/wx_extra/wx_misc.erl
  lib/wx/api_gen/wx_gen_cpp.erl
  lib/wx/api_gen/wx_gen_erl.erl
  lib/wx/api_gen/wx_gen_nif.erl
  lib/wx/api_gen/wxapi.conf
  lib/wx/c_src/gen/wxe_events.cpp
  lib/wx/c_src/gen/wxe_func_table.cpp
  lib/wx/c_src/gen/wxe_init.cpp
  lib/wx/c_src/gen/wxe_macros.h
  lib/wx/c_src/gen/wxe_wrapper_8.cpp
  lib/wx/configure.in
  lib/wx/doc/src/wxHtmlWindow.xml
  lib/wx/doc/src/wxWebView.xml
  lib/wx/doc/src/wxWebViewEvent.xml
  lib/wx/examples/demo/Makefile
  lib/wx/examples/demo/demo.erl
  lib/wx/examples/demo/ex_notificationMessage.erl
  lib/wx/examples/demo/ex_webview.erl
  lib/wx/include/wx.hrl
  lib/wx/src/gen/wxWebView.erl
  lib/wx/src/gen/wxWebViewEvent.erl
  lib/wx/src/gen/wx_misc.erl
  lib/wx/src/gen/wxe_funcs.hrl
  lib/wx/wxwin-2.8.m4
  lib/wx/wxwin-nothrow.m4
Labels: team:PS, testing

#2964 Handle macros in patterns
  lib/syntax_tools/src/epp_dodger.erl
  lib/syntax_tools/test/syntax_tools_SUITE.erl
  lib/syntax_tools/test/syntax_tools_SUITE_data/epp_dodger_clever.erl
  lib/syntax_tools/test/syntax_tools_SUITE_data/syntax_tools_test.erl
Labels: fix, team:VM, testing

#4535 beam_lib, cover: Don't crash when an abstract code backend is missing
  lib/stdlib/src/beam_lib.erl
  lib/stdlib/test/beam_lib_SUITE.erl
  lib/tools/doc/src/cover.xml
  lib/tools/src/cover.erl
  lib/tools/test/cover_SUITE.erl
Labels: fix, team:VM, testing

#4536 Encode generated dependency files in UTF-8
  lib/compiler/doc/src/compile.xml
  lib/compiler/src/compile.erl
Labels: fix, team:VM, testing

#4538 Further memory barrier improvements for ARMv8
  erts/aclocal.m4
  erts/include/internal/gcc/ethr_membar.h
  erts/include/internal/gcc/ethread.h
Labels: enhancement, team:VM, testing

#2654 inet_tls_dist: make TLS handshake concurrent
  lib/ssl/src/inet_tls_dist.erl
  lib/ssl/test/ssl_dist_SUITE.erl
Labels: team:PS, testing

#3041 Do not centralize type/cname lookups through inet_db
  lib/kernel/src/inet_db.erl
Labels: team:PS, testing

#2989 inet_tcp, inet6_tcp: do not bind connecting sockets by default
  lib/kernel/src/inet6_tcp.erl
  lib/kernel/src/inet_int.hrl
  lib/kernel/src/inet_tcp.erl
  lib/kernel/src/local_tcp.erl
Labels: team:PS, testing

#4542 tools: Fix emacs compiler warnings (#4451)
  lib/tools/emacs/erlang-eunit.el
  lib/tools/emacs/erlang-test.el
  lib/tools/emacs/erlang.el
  lib/tools/emacs/erldoc.el
  lib/tools/test/emacs_SUITE.erl
Labels: team:PS, testing

#4511 Refine Mnesia guide Overview
  lib/mnesia/doc/src/Mnesia_overview.xml
Labels: team:PS

#4550 Fix C++ 11 extension warning/error
  lib/wx/c_src/wxe_memory.h
Labels: team:PS, testing

#4551 re: Document [:ascii:] character class deficiency
  lib/stdlib/doc/src/re.xml
Labels: bug, documentation, fix, team:VM, testing

#4547 cover: Ensure that LC filters are compiled in guard context
  lib/tools/src/cover.erl
  lib/tools/test/cover_SUITE.erl
Labels: fix, team:VM, testing

#4545 Inline funs that are immediately used
  lib/compiler/src/sys_core_fold.erl
  lib/compiler/test/fun_SUITE.erl
  lib/debugger/test/int_eval_SUITE_data/stacktrace.erl
  lib/stdlib/test/qlc_SUITE.erl
Labels: bug, fix, team:VM, testing
