Repository erlang/otp, pull requests merged in 2021-08, with the labels that each got.

#5066 compiler: Comment BEAM assembly with callee names in clear-text
  lib/compiler/src/beam_listing.erl
  lib/compiler/test/compile_SUITE.erl
  lib/compiler/test/compile_SUITE_data/asm_labels.erl
Labels: team:VM

#5076 compiler: Pretty print types in SSA-dumps
  lib/compiler/src/beam_ssa_pp.erl
  lib/compiler/test/compile_SUITE.erl
  lib/compiler/test/compile_SUITE_data/types_pp.erl
Labels: team:VM

#5077 compiler: Remove duplicated directory name construction in test
  lib/compiler/test/compile_SUITE.erl
Labels: team:VM

#5101 Add is_map_key/2 as a guard BIF to the reference documentation
  system/doc/reference_manual/expressions.xml
Labels: team:VM, enhancement, testing, documentation

#5032 Do not unload modules during stop
  erts/preloaded/src/init.erl
Labels: team:VM

#5008 Fail early when calling_self
  lib/stdlib/src/erl_error.erl
  lib/stdlib/src/erl_stdlib_errors.erl
  lib/stdlib/src/gen.erl
  lib/stdlib/src/io.erl
  lib/stdlib/test/gen_server_SUITE.erl
  lib/stdlib/test/io_SUITE.erl
Labels: team:VM, testing

#5043 ci: Cache wxWidgets on Windows
  .github/workflows/main.yaml
Labels: team:VM

#5105 erts: Fix FRAME_POINTER to be valid when stack adjusted
  erts/emulator/beam/beam_common.c
Labels: team:VM, fix, testing

#5078 Fix process_info that can hang waiting for reply
  erts/emulator/beam/erl_proc_sig_queue.c
  erts/emulator/test/bif_SUITE.erl
  erts/etc/unix/etp-commands.in
Labels: team:VM, testing

#4955 Refactoring of logger_disk_log_h
  lib/kernel/src/logger_disk_log_h.erl
Labels: team:VM

#5099 Add a chapter about maps to the Efficiency Guide
  lib/stdlib/doc/src/maps.xml
  system/doc/efficiency_guide/maps.xml
  system/doc/efficiency_guide/part.xml
  system/doc/efficiency_guide/xmlfiles.mk
Labels: team:VM, enhancement

#5096 erts: Remove blank line from ./Install script output
  erts/etc/unix/Install.src
Labels: team:VM

#5104 Reduce the size of the JITted code for try_case
  erts/emulator/beam/beam_common.c
  erts/emulator/beam/emu/instrs.tab
  erts/emulator/beam/jit/arm/instr_common.cpp
  erts/emulator/beam/jit/x86/instr_common.cpp
Labels: team:VM, enhancement, testing

#5027 Allow binary bifs in match_spec and trace pattern guards
  erts/doc/src/match_spec.xml
  erts/emulator/beam/erl_db_util.c
  lib/stdlib/doc/src/ms_transform.xml
  lib/stdlib/src/ms_transform.erl
  lib/stdlib/test/ms_transform_SUITE.erl
Labels: team:VM, enhancement, testing

#5023 edoc: Add source file to the warning on skipped tag
  lib/edoc/src/edoc_layout_chunks.erl
Labels: team:VM, testing

#5110 edoc: Use local definition of context
  lib/edoc/src/edoc_extract.erl
Labels: team:VM, testing, bug

#5108 jit: Fix various frame pointer issues (+JPperf true)
  erts/emulator/beam/erl_gc.c
  erts/emulator/beam/jit/x86/instr_trace.cpp
  erts/emulator/test/hello_SUITE_data/hello.erl
Labels: team:VM, testing, bug

#5091 crypto: Add /opt/homebrew/opt/openssl to standard locations
  lib/crypto/configure
  lib/crypto/configure.ac
Labels: team:PS

#5123 erts: Fix memcpy buffer overwrite
  erts/emulator/drivers/unix/ttsl_drv.c
Labels: team:VM, testing, bug

#4719 Adding `short` to float_to_list/float_to_binary
  erts/doc/src/erlang.xml
  erts/emulator/Makefile.in
  erts/emulator/beam/atom.names
  erts/emulator/beam/bif.c
  erts/emulator/ryu/README.ryu_update.md
  erts/emulator/ryu/common.h
  erts/emulator/ryu/d2s.c
  erts/emulator/ryu/d2s_full_table.h
  erts/emulator/ryu/d2s_intrinsics.h
  erts/emulator/ryu/digit_table.h
  erts/emulator/ryu/ryu.h
  erts/emulator/ryu/ryu.mk
  erts/emulator/test/num_bif_SUITE.erl
  erts/preloaded/ebin/atomics.beam
  erts/preloaded/ebin/counters.beam
  erts/preloaded/ebin/erl_init.beam
  erts/preloaded/ebin/erl_prim_loader.beam
  erts/preloaded/ebin/erl_tracer.beam
  erts/preloaded/ebin/erlang.beam
  erts/preloaded/ebin/erts_code_purger.beam
  erts/preloaded/ebin/erts_dirty_process_signal_handler.beam
  erts/preloaded/ebin/erts_internal.beam
  erts/preloaded/ebin/erts_literal_area_collector.beam
  erts/preloaded/ebin/init.beam
  erts/preloaded/ebin/persistent_term.beam
  erts/preloaded/ebin/prim_buffer.beam
  erts/preloaded/ebin/prim_eval.beam
  erts/preloaded/ebin/prim_file.beam
  erts/preloaded/ebin/prim_inet.beam
  erts/preloaded/ebin/prim_net.beam
  erts/preloaded/ebin/prim_socket.beam
  erts/preloaded/ebin/prim_zip.beam
  erts/preloaded/ebin/socket_registry.beam
  erts/preloaded/ebin/zlib.beam
  erts/preloaded/src/erlang.erl
  lib/stdlib/scripts/generate_ryu_table.escript
  lib/stdlib/src/Makefile
  lib/stdlib/src/io_lib_format.erl
  lib/stdlib/src/io_lib_format_ryu_table.erl
  lib/stdlib/src/stdlib.app.src
  lib/stdlib/test/stdlib_bench_SUITE.erl
Labels: team:VM, waiting

#5125 Add a section about accidental copying and loss of sharing
  system/doc/efficiency_guide/commoncaveats.xmlsrc
  system/doc/efficiency_guide/efficiency_guide.erl
  system/doc/efficiency_guide/processes.xmlsrc
Labels: team:VM, enhancement

#5111 Distribution handshake cleanup / clarification
  erts/doc/src/erl_cmd.xml
  erts/doc/src/erlang.xml
  erts/emulator/test/exception_SUITE.erl
  erts/preloaded/ebin/erlang.beam
  erts/preloaded/src/erlang.erl
  lib/kernel/src/auth.erl
  lib/kernel/src/dist_util.erl
  lib/kernel/src/erl_erts_errors.erl
  lib/kernel/test/erl_distribution_SUITE.erl
  system/doc/reference_manual/distributed.xml
Labels: team:VM

#5095 stdlib: Fix `erl_pp` rendering unary +/- operators
  lib/stdlib/src/erl_pp.erl
  lib/stdlib/test/erl_pp_SUITE.erl
Labels: team:VM, testing

#5098 Fix doc spelling
  lib/mnesia/src/mnesia_frag.erl
Labels: team:PS

#5114 Fix doc spelling
  lib/mnesia/src/mnesia_recover.erl
Labels: team:PS

#5113 Fix doc spelling
  lib/mnesia/src/mnesia_recover.erl
Labels: team:PS

#5112 Fix doc spelling
  lib/mnesia/src/mnesia_recover.erl
Labels: team:PS

#5109 Fix doc spelling
  lib/mnesia/src/mnesia_monitor.erl
Labels: team:PS

#5115 Fix maps in match specs
  erts/emulator/beam/erl_db_util.c
  erts/emulator/beam/erl_map.c
  erts/emulator/beam/erl_map.h
  erts/emulator/beam/erl_message.c
  erts/emulator/test/match_spec_SUITE.erl
Labels: team:VM, testing, bug

#4793 Adjust refc binary growth
  erts/emulator/beam/erl_bits.c
  erts/emulator/test/hash_SUITE.erl
Labels: team:VM, enhancement, testing

#5139 kernel: Do not crash when getting doc from escript
  lib/kernel/src/code.erl
Labels: team:VM, testing, bug

#5117 Document dbg acronym meanings
  lib/runtime_tools/doc/src/dbg.xml
Labels: team:VM, testing, documentation

#5119 Ingela/ssl/pss in tls 1.2/erlerl 625/gh 5029/otp 16590
  lib/ssl/doc/src/ssl.xml
  lib/ssl/doc/src/standards_compliance.xml
  lib/ssl/src/dtls_connection.erl
  lib/ssl/src/dtls_handshake.erl
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_certificate.erl
  lib/ssl/src/ssl_cipher.erl
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/src/tls_dtls_connection.erl
  lib/ssl/src/tls_handshake.erl
  lib/ssl/src/tls_handshake_1_3.erl
  lib/ssl/src/tls_v1.erl
  lib/ssl/test/ssl_cert_SUITE.erl
  lib/ssl/test/ssl_cert_tests.erl
  lib/ssl/test/ssl_handshake_SUITE.erl
  lib/ssl/test/ssl_test_lib.erl
  lib/ssl/test/tls_1_3_version_SUITE.erl
Labels: team:PS, enhancement, feature, testing

#5132 erl_docgen: Fix generating docs chunk entry for `<seeerl>`
  lib/erl_docgen/src/docgen_xml_to_chunk.erl
Labels: team:VM, testing, bug

#5144 stdlib: Fix result of shell_docs missing type
  lib/stdlib/src/shell_docs.erl
Labels: team:VM, testing, bug

#5161 ci: Fix typo
  .github/workflows/main.yaml
Labels: team:VM

#5127 Fix broken "make test" in erts/emulator
  erts/emulator/Makefile
Labels: team:VM

#5146 design principles doc fix
  system/doc/design_principles/events.xml
Labels: team:PS

#4983 Ingela/ssl/psk/gh 4978/otp 17501
  lib/ssl/doc/src/ssl.xml
  lib/ssl/src/dtls_v1.erl
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_cipher.erl
  lib/ssl/src/tls_v1.erl
  lib/ssl/test/ssl_api_SUITE.erl
  lib/ssl/test/ssl_basic_SUITE.erl
Labels: team:PS, testing

#4926 gen_statem: Make it possible to spec data
  lib/stdlib/doc/src/gen_statem.xml
  lib/stdlib/src/gen_statem.erl
Labels: team:VM, team:PS, testing

#5170 Fix ip_mreq spec to match implementation
  lib/kernel/src/socket.erl
Labels: team:PS, bug

#5145 Malformed DNS RRs shall result in parse errors
  lib/kernel/src/inet_dns.erl
Labels: team:PS

#5163 Eliminate a crash in beam_ssa_codegen
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/test/beam_type_SUITE.erl
Labels: team:VM, fix, testing, in progress

#5131 mnesia: Do not unconditionally delete index keys
  lib/mnesia/src/mnesia_index.erl
  lib/mnesia/test/mnesia_trans_access_test.erl
Labels: team:PS, testing
