Repository erlang/otp, pull requests merged in 2021-06, with the labels that each got.

#4921 Document the on_load result from erlang:load_module/2
  erts/doc/src/erlang.xml
Labels: fix, team:VM, testing

#4897 Small optimization in erts_qsort
  erts/emulator/beam/utils.c
  erts/emulator/sys/unix/erl_unix_sys_ddll.c
Labels: enhancement, team:VM, testing

#4919 Fix crash in c:ls/1
  lib/stdlib/src/c.erl
  lib/stdlib/test/c_SUITE.erl
Labels: fix, team:VM, testing

#4925 Correct printing of Unicode atoms in crash dumps
  erts/emulator/beam/erl_printf_term.c
  lib/observer/src/crashdump_viewer.erl
  lib/observer/src/observer_html_lib.erl
  lib/observer/test/crashdump_helper_unicode.erl
  lib/observer/test/crashdump_viewer_SUITE.erl
Labels: fix, team:VM, testing

#4932 Fix erlang:cancel_timer(_, [{info, false}])
  erts/emulator/beam/erl_hl_timer.c
  erts/emulator/test/timer_bif_SUITE.erl
Labels: fix, team:VM, testing

#4934 Fix hanging net_kernel
  lib/kernel/src/net_kernel.erl
Labels: fix, team:VM, testing

#4894 Fix maps internal sorting bug for gcc flag "-flto"
  erts/emulator/beam/beam_debug.c
  erts/emulator/beam/erl_bif_info.c
  erts/emulator/beam/erl_map.c
  erts/emulator/beam/global.h
  erts/emulator/beam/utils.c
  erts/emulator/test/erts_debug_SUITE.erl
Labels: fix, team:VM, testing

#4837 jinterface: Fix a NullPointerException in AbstractConnection
  lib/jinterface/java_src/com/ericsson/otp/erlang/AbstractConnection.java
Labels: fix, team:VM, testing

#4917 Make os:cmd compatible with Android
  lib/kernel/src/os.erl
Labels: fix, team:VM, testing

#4872 Fix race condition in proc_lib:stop/3 with small timeouts
  lib/stdlib/src/proc_lib.erl
  lib/stdlib/test/proc_lib_SUITE.erl
Labels: team:VM, testing

#4811 timer: modernization and improvements
  lib/stdlib/doc/src/timer.xml
  lib/stdlib/src/timer.erl
  lib/stdlib/test/timer_SUITE.erl
  lib/stdlib/test/timer_simple_SUITE.erl
  system/doc/efficiency_guide/commoncaveats.xml
Labels: enhancement, team:VM, testing

#4944 hasse/stdlib/linter_unused_types/OTP-17370/GH-4784
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/test/erl_lint_SUITE.erl
Labels: team:VM

#4957 Fix doc spelling
  lib/sasl/src/release_handler.erl
Labels: team:VM

#4909 fix ./configure script handling of expr(1) on BSD
  configure
  configure.src
Labels: team:VM, testing

#4961 supervisor: optimize restart intensity calculation
  lib/stdlib/src/supervisor.erl
Labels: enhancement, team:VM, testing

#4975 jit-x86: Provide reason for assertion failure in assembly listing
  erts/emulator/beam/jit/x86/beam_asm.hpp
  erts/emulator/beam/jit/x86/beam_asm_global.cpp
  erts/emulator/beam/jit/x86/instr_bif.cpp
  erts/emulator/beam/jit/x86/instr_common.cpp
  erts/emulator/beam/jit/x86/instr_fun.cpp
  erts/emulator/beam/jit/x86/process_main.cpp
Labels: enhancement, team:VM, testing

#4986 Clarify the Pred function in lists must return booleans
  lib/stdlib/doc/src/lists.xml
Labels: team:VM, testing

#4991 Use AC_PROG_CXX to find C++ compiler
  erts/configure
  erts/configure.ac
Labels: fix, team:VM, testing

#4923 Make max_transfer_size parameter configurable to optimise mnesia table loading time
  lib/mnesia/doc/src/mnesia.xml
  lib/mnesia/src/mnesia.erl
  lib/mnesia/src/mnesia_loader.erl
  lib/mnesia/src/mnesia_monitor.erl
  lib/mnesia/test/mnesia_evil_coverage_test.erl
Labels: team:PS, testing

#4994 parsetools: Fix compiler warning in generated code
  lib/parsetools/src/leex.erl
  lib/parsetools/test/leex_SUITE.erl
Labels: fix, team:VM

#4941 Ingela/ssl/alt certs/gh 4877/otp 17475
  lib/public_key/src/public_key.erl
  lib/ssl/src/ssl_certificate.erl
  lib/ssl/src/ssl_crl.erl
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/src/tls_handshake_1_3.erl
  lib/ssl/test/property_test/ssl_eqc_chain.erl
  lib/ssl/test/property_test/ssl_eqc_handshake.erl
  lib/ssl/test/ssl_cert_SUITE.erl
  lib/ssl/test/ssl_pem_cache_SUITE.erl
Labels: team:PS, testing

#4998 Clean up the help text for the emulator
  erts/emulator/beam/erl_init.c
Labels: fix, team:VM, testing

#4997 epp: Fix inconsistent handling of undefined pre-defined macros
  lib/stdlib/src/epp.erl
  lib/stdlib/test/epp_SUITE.erl
Labels: bug, team:VM, testing

#4982 Improve the readability of .asm-dumps
  erts/emulator/beam/beam_file.c
  erts/emulator/beam/beam_file.h
  erts/emulator/beam/beam_load.c
  erts/emulator/beam/jit/arm/beam_asm.hpp
  erts/emulator/beam/jit/arm/beam_asm_module.cpp
  erts/emulator/beam/jit/asm_load.c
  erts/emulator/beam/jit/beam_asm.h
  erts/emulator/beam/jit/beam_jit_main.cpp
  erts/emulator/beam/jit/x86/beam_asm.hpp
  erts/emulator/beam/jit/x86/beam_asm_module.cpp
  erts/emulator/test/Makefile
  erts/emulator/test/jit_SUITE.erl
Labels: enhancement, team:VM, testing

#4972 Clean up and support reuse of distribution capability bits
  erts/doc/src/erl_dist_protocol.xml
  erts/emulator/beam/dist.h
  erts/emulator/beam/erl_bif_info.c
  erts/emulator/beam/external.c
  erts/emulator/test/binary_SUITE.erl
  lib/erl_interface/src/connect/ei_connect.c
  lib/erl_interface/src/connect/ei_connect_int.h
  lib/erl_interface/src/misc/ei_compat.c
  lib/erl_interface/src/misc/ei_internal.h
  lib/erl_interface/test/ei_accept_SUITE.erl
  lib/erl_interface/test/ei_tmo_SUITE.erl
  lib/jinterface/java_src/com/ericsson/otp/erlang/AbstractConnection.java
  lib/jinterface/java_src/com/ericsson/otp/erlang/AbstractNode.java
  lib/kernel/include/dist.hrl
  lib/kernel/src/dist_util.erl
  lib/kernel/test/erl_distribution_wb_SUITE.erl
Labels: enhancement, team:VM

#4956 beam_ssa_throw: Remove assertion that caused crashes
  lib/compiler/src/beam_ssa_throw.erl
  lib/compiler/test/trycatch_SUITE.erl
Labels: bug, team:VM

#4990 Add a "Coming Potential Incompatibilities" page to the documentation
  erts/doc/src/erl_dist_protocol.xml
  system/doc/general_info/part.xml
  system/doc/general_info/upcoming_incompatibilities.xml
  system/doc/general_info/xmlfiles.mk
  system/doc/top/templates/index.html.src
Labels: enhancement, team:VM

#4980 Fix erlang:system_flag(schedulers_online, NewSchedsOnln)
  erts/emulator/beam/erl_process.c
  erts/emulator/test/scheduler_SUITE.erl
Labels: fix, team:VM, testing

#5000 dgud/erts/test target
  make/test_target_script.sh
  otp_build
Labels: team:PS
