Repository erlang/otp, pull requests merged in 2021-03, with the labels that each got.

#4555 Fix cover bug when there is an export named clauses
  lib/tools/src/cover.erl
  lib/tools/test/cover_SUITE.erl
Labels: fix, team:VM

#4554 Ensure that Xref does not see Debugger as a dependency for Kernel
  lib/kernel/src/error_handler.erl
Labels: fix, team:VM

#4530 Tweak inet keepalive option documentation
  lib/kernel/doc/src/inet.xml
Labels: team:PS

#4561 Fix erl.exe WSLPATH path addition
  erts/etc/win32/erl.c
Labels: team:PS, testing

#4557 Fix test of runtime dependencies
  erts/test/otp_SUITE.erl
  lib/erl_docgen/src/erl_docgen.app.src
  lib/ftp/src/ftp.app.src
  lib/kernel/src/kernel.app.src
  lib/ssh/src/ssh.app.src
  lib/ssl/src/ssl.app.src
  lib/tftp/src/tftp.app.src
Labels: fix, team:VM, testing

#4509 Fix servfail_retry_timeout to only be used when appropriate
  lib/kernel/doc/src/inet_res.xml
  lib/kernel/src/inet_res.erl
Labels: team:PS

#4543 erts: Fix fd leak when an active socket is closed remotely
  erts/emulator/drivers/common/inet_drv.c
  lib/kernel/test/sendfile_SUITE.erl
Labels: bug, fix, team:VM, testing

#4563 Enhance the optimization of the try/catch elimination optimization
  lib/compiler/src/beam_ssa_opt.erl
Labels: enhancement, team:VM, testing

#4565 kernel: Let option 'size' of disk_log:open/1 change size
  lib/kernel/doc/src/disk_log.xml
  lib/kernel/src/disk_log.erl
  lib/kernel/src/disk_log.hrl
  lib/kernel/src/group_history.erl
  lib/kernel/test/disk_log_SUITE.erl
Labels: team:VM

#4568 Refine process message queue data configuration documentation
  erts/doc/src/erl_cmd.xml
  erts/doc/src/erlang.xml
Labels: team:VM, testing

#4582 Extend CSE to eliminate list and tuple matching
  lib/compiler/src/beam_ssa_opt.erl
Labels: enhancement, team:VM

#4580 Make OpenSSL functions depend on the same conditions as their prototypes
  lib/crypto/c_src/otp_test_engine.c
Labels: bug, team:PS

#4593 Add a short note on reserved words cond and let
  system/doc/reference_manual/introduction.xml
Labels: enhancement, team:VM, testing

#4604 Fix inet:get_rc/0 host entries
  lib/kernel/src/inet_db.erl
  lib/kernel/test/inet_SUITE.erl
Labels: team:PS

#4596 Fix minor leaks in erlang:trace/3
  erts/emulator/beam/erl_bif_trace.c
  erts/emulator/test/trace_SUITE.erl
Labels: fix, team:VM, testing

#4564 inet_res: add option to include the DNS reply in nxdomain errors
  lib/kernel/doc/src/inet_res.xml
  lib/kernel/src/inet_res.erl
  lib/kernel/test/inet_res_SUITE.erl
Labels: in progress, team:PS, testing

#4609 Remove undocumented and partially broken ets:filter/3
  lib/kernel/src/application_controller.erl
  lib/stdlib/src/ets.erl
Labels: team:VM, testing

#4579 Show docs from any textual chunk in the shell
  lib/stdlib/doc/src/shell_docs.xml
  lib/stdlib/src/c.erl
  lib/stdlib/src/shell_docs.erl
  lib/stdlib/test/shell_docs_SUITE.erl
Labels: enhancement, team:VM, testing

#4598 Support suppressing opportunistic compiler warnings
  lib/compiler/doc/src/compile.xml
  lib/compiler/src/compile.erl
  lib/compiler/src/sys_core_fold.erl
  lib/compiler/src/v3_core.erl
  lib/compiler/src/v3_kernel.erl
  lib/compiler/test/warnings_SUITE.erl
  lib/stdlib/test/erl_expand_records_SUITE.erl
  lib/stdlib/test/erl_lint_SUITE.erl
  lib/stdlib/test/qlc_SUITE.erl
Labels: enhancement, team:VM

#4601 ssl: Refactor CRL functions to solve GH-4589
  lib/ssl/src/ssl_certificate.erl
  lib/ssl/src/ssl_crl.erl
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/test/ssl_crl_SUITE.erl
Labels: team:PS, testing

#4611 Make hostname check case insensitive
  lib/public_key/src/public_key.erl
  lib/public_key/test/public_key_SUITE.erl
Labels: team:PS, testing

#4613 Quote atom in types
  lib/mnesia/src/mnesia.erl
Labels: team:PS, testing

#4575 Optimise mnesia table loading time for busy tables
  lib/mnesia/src/mnesia_loader.erl
Labels: team:PS, testing

#4566 wxNotificationMessage macos & win polish
  erts/emulator/Makefile.in
  erts/etc/darwin/Info.plist
  lib/wx/api_gen/wxapi.conf
  lib/wx/c_src/gen/wxe_func_table.cpp
  lib/wx/c_src/gen/wxe_wrapper_5.cpp
  lib/wx/doc/src/wxNotificationMessage.xml
  lib/wx/src/gen/wxNotificationMessage.erl
  lib/wx/src/gen/wxe_funcs.hrl
Labels: team:PS, testing

#4602 ssl: fix docs for protocol_version and dtls_protocol_version application environment options
  lib/ssl/doc/src/ssl_app.xml
Labels: team:PS

#4623 Remove mentions of JIRA as bug reporting
  HOWTO/INSTALL-WIN32-OLD.md
  HOWTO/INSTALL-WIN32.md
  lib/tools/emacs/erlang.el
Labels: documentation, fix, team:VM, testing

#4553 fix: Handle SIGUSR1 even under +B i / +B d
  erts/emulator/sys/unix/sys.c
  erts/emulator/test/os_signal_SUITE.erl
Labels: team:VM, testing

#4627 Update autoconf aux files
  .gitignore
  erts/autoconf/config.guess
  erts/autoconf/config.sub
  erts/autoconf/install-sh
Labels: enhancement, team:VM, testing

#2979 ets: use initial salt different from phash2
  erts/emulator/beam/utils.c
  erts/emulator/test/map_SUITE.erl
  erts/emulator/test/persistent_term_SUITE.erl
  lib/stdlib/test/ets_SUITE.erl
Labels: enhancement, team:VM, testing

#4606 New link protocol
  erts/doc/src/erl_dist_protocol.xml
  erts/doc/src/erlang.xml
  erts/emulator/internal_doc/NewLinking.tla
  system/doc/reference_manual/processes.xml
Labels: fix, team:VM, testing

#4634 Do not allow mandatory apps to be disabled
  configure.src
Labels: bug, team:VM, testing

#4630 mnesia: Handle starting and stopping in connect_nodes
  lib/mnesia/src/mnesia_controller.erl
Labels: team:PS, testing

#4600 Increase cert chain duplicates
  lib/ssl/src/ssl_certificate.erl
  lib/ssl/test/ssl_cert_SUITE.erl
  lib/ssl/test/ssl_test_lib.erl
Labels: team:PS, testing

#4615 speed up pg:all_local_pids by using gen_server state
  lib/kernel/src/pg.erl
Labels: team:VM, testing

#4640 ssl: Correct signature algorithm selection for client certificate verify
  lib/ssl/src/tls_handshake_1_3.erl
  lib/ssl/test/property_test/ssl_eqc_chain.erl
  lib/ssl/test/ssl_eqc_SUITE.erl
Labels: team:PS, testing

#4644 Ingela/ssl/gh 4585
  lib/ssl/src/ssl.erl
  lib/ssl/test/tls_api_SUITE.erl
Labels: team:PS, testing

#4619 pg: fix empty group removal from internal pg state
  lib/kernel/src/pg.erl
  lib/kernel/test/pg_SUITE.erl
Labels: team:VM, testing

#4654 Add missing documentation for sending to aliases
  erts/doc/src/erlang.xml
  system/doc/reference_manual/expressions.xml
Labels: team:VM

#3014 Add hex encoding fonctions on the binary module
  lib/stdlib/doc/src/binary.xml
  lib/stdlib/src/binary.erl
  lib/stdlib/src/erl_stdlib_errors.erl
  lib/stdlib/test/binary_module_SUITE.erl
  lib/stdlib/test/error_info_lib.erl
Labels: enhancement, team:VM, testing

#4581 Shell history tests
  lib/kernel/src/group_history.erl
  lib/kernel/src/user_drv.erl
  lib/kernel/test/interactive_shell_SUITE.erl
Labels: enhancement, team:VM

#4653 zlib: Document 'default' compression level
  erts/doc/src/zlib.xml
Labels: team:VM

#4662 sys_core_fold: Fix typo in error message
  lib/compiler/src/sys_core_fold.erl
Labels: fix, team:VM

#4649 Refactor JIT source files
  erts/configure.in
  erts/emulator/Makefile.in
  erts/emulator/beam/erl_process.h
  erts/emulator/beam/jit/beam_jit_common.c
  erts/emulator/beam/jit/beam_jit_common.h
  erts/emulator/beam/jit/beam_jit_common.hpp
  erts/emulator/beam/jit/x86/beam_asm.cpp
  erts/emulator/beam/jit/x86/beam_asm.hpp
  erts/emulator/beam/jit/x86/beam_asm_global.cpp
  erts/emulator/beam/jit/x86/beam_asm_module.cpp
  erts/emulator/beam/jit/x86/beam_asm_perf.cpp
  erts/emulator/beam/jit/x86/generators.tab
  erts/emulator/beam/jit/x86/instr_arith.cpp
  erts/emulator/beam/jit/x86/instr_bif.cpp
  erts/emulator/beam/jit/x86/instr_bs.cpp
  erts/emulator/beam/jit/x86/instr_call.cpp
  erts/emulator/beam/jit/x86/instr_common.cpp
  erts/emulator/beam/jit/x86/instr_float.cpp
  erts/emulator/beam/jit/x86/instr_guard_bifs.cpp
  erts/emulator/beam/jit/x86/instr_map.cpp
  erts/emulator/beam/jit/x86/instr_msg.cpp
  erts/emulator/beam/jit/x86/instr_select.cpp
  erts/emulator/beam/jit/x86/instr_trace.cpp
  erts/emulator/beam/jit/x86/ops.tab
  erts/emulator/beam/jit/x86/predicates.tab
Labels: enhancement, team:VM, testing

#4632 Inform on how an end_per_testcase crash affects test results
  lib/common_test/doc/src/write_test_chapter.xml
Labels: team:PS

#4685 reltool: Generate files reproducibly
  lib/reltool/src/reltool_target.erl
Labels: team:VM, testing

#4684 sasl: Make release scripts build reproducibly
  lib/sasl/src/systools_make.erl
Labels: team:VM, testing

#4670 Fix lost error handling
  lib/kernel/src/net_kernel.erl
Labels: team:PS, testing

#4678 Remove a test for perl 4
  erts/aclocal.m4
Labels: enhancement, team:VM, testing

#4689 Perf and msacc JIT fixes
  erts/emulator/beam/erl_init.c
  erts/emulator/beam/global.h
  erts/emulator/beam/jit/x86/beam_asm.hpp
  erts/emulator/beam/jit/x86/beam_asm_perf.cpp
  erts/emulator/beam/jit/x86/instr_bif.cpp
Labels: fix, team:VM, testing

#4667 Document BEAM SSA invariants
  lib/compiler/doc/src/Makefile
  lib/compiler/doc/src/internal.xml
  lib/compiler/internal_doc/beam_ssa.md
  lib/erl_docgen/priv/xsl/db_html.xsl
Labels: team:VM, testing

#4674 Fix backend_init call check + add test case
  lib/mnesia/src/mnesia_schema.erl
  lib/mnesia/test/ext_test.erl
  lib/mnesia/test/mnesia_config_test.erl
  lib/mnesia/test/mnesia_test_lib.erl
Labels: team:PS, testing
