Repository erlang/otp, pull requests merged in 2021-04, with the labels that each got.

#4700 ssl: Make sure incomplete chain is a prefix of the new chain candidate
  lib/ssl/src/ssl_certificate.erl
  lib/ssl/test/ssl_basic_SUITE.erl
Labels: fix, team:PS, testing

#4660 erts: Fix bug in call time tracing
  erts/emulator/beam/beam_bp.c
  erts/emulator/test/trace_call_time_SUITE.erl
Labels: fix, team:VM

#4657 erts: Implement some etp macros for lldb
  erts/etc/unix/cerl.src
  erts/etc/unix/etp.py
Labels: feature, team:VM

#4695 eunit: ensure the output directory exist for surefire xml files
  lib/eunit/src/eunit_surefire.erl
  lib/eunit/test/eunit_SUITE.erl
Labels: team:VM, testing

#4659 Fix code checker warnings and cleanups in erl_call.c
  lib/erl_interface/src/Makefile.in
  lib/erl_interface/src/prog/erl_call.c
  lib/erl_interface/src/prog/erl_start.c
  lib/erl_interface/src/prog/erl_start.h
Labels: team:VM

#4709 msacc: fix segfault caused when extra MSACC states are enabled
  erts/emulator/beam/jit/x86/instr_bif.cpp
Labels: team:VM, testing

#4713 edoc: Re-instate ?NO_APP and deprecate it
  lib/edoc/include/edoc_doclet.hrl
  system/doc/general_info/deprecations_24.inc
Labels: fix, team:VM, testing

#4715 queue, maps, proplists: add since information to docs for new functions
  lib/stdlib/doc/src/maps.xml
  lib/stdlib/doc/src/proplists.xml
  lib/stdlib/doc/src/queue.xml
Labels: enhancement, testing

#4647 Fixes to problems reported by codechecker
  erts/emulator/beam/jit/x86/beam_asm_perf.cpp
  erts/etc/common/ct_run.c
  erts/etc/common/dialyzer.c
  erts/etc/common/erlc.c
  erts/etc/common/erlexec.c
  erts/etc/common/inet_gethost.c
  erts/etc/common/typer.c
  erts/etc/unix/jit-reader.c
Labels: team:VM

#4675 Fix ASSERT_IN_ENV for dirty NIFs
  erts/emulator/beam/erl_nif.c
Labels: fix, team:VM, testing

#4656 Do not allocate large map when value is the same
  erts/emulator/beam/erl_map.c
  erts/emulator/beam/erl_map.h
  lib/stdlib/test/maps_SUITE.erl
Labels: enhancement, team:VM, testing

#4651 Add fullsweep_after support in process_flag/2
  erts/doc/src/erlang.xml
  erts/emulator/beam/bif.c
  erts/emulator/test/process_SUITE.erl
  erts/preloaded/src/erlang.erl
Labels: feature, team:VM, testing

#4703 Fix handling of recv marker when serving a process_info request
  erts/emulator/beam/erl_proc_sig_queue.c
Labels: fix, team:VM, testing

#4716 EDoc: suggest {preprocess, true} when redundant spec assertion fails
  lib/edoc/src/edoc.erl
  lib/edoc/src/edoc.hrl
  lib/edoc/src/edoc_extract.erl
Labels: enhancement, team:VM, testing

#4712 Fix parse transform column handling
  erts/doc/src/absform.xml
  lib/compiler/doc/src/compile.xml
  lib/compiler/src/compile.erl
  lib/compiler/test/compile_SUITE.erl
  lib/compiler/test/compile_SUITE_data/column_pt.erl
  lib/compiler/test/compile_SUITE_data/line_pt.erl
  lib/stdlib/examples/erl_id_trans.erl
Labels: fix, team:VM, testing

#4723 Add missing digest none to crypto:sign/4 and verify/6
  lib/crypto/src/crypto.erl
Labels: fix, team:PS

#4686 Add aead attribute to map from crypto:cipher_info/1
  lib/crypto/c_src/atoms.c
  lib/crypto/c_src/atoms.h
  lib/crypto/c_src/cipher.c
  lib/crypto/doc/src/crypto.xml
  lib/crypto/src/crypto.erl
  lib/crypto/test/crypto_SUITE.erl
Labels: enhancement, team:PS

#4679 crypto: Remove OpenSSL search through uninstall
  lib/crypto/configure.in
Labels: team:PS, testing

#4639 erlexec: Add checks that next argument is valid
  erts/etc/common/erlexec.c
  erts/test/erlexec_SUITE.erl
  lib/kernel/src/erl_distribution.erl
  make/test_target_script.sh
Labels: fix, team:VM, testing

#4690 Base16 algorithm improvements
  lib/stdlib/src/binary.erl
  lib/stdlib/src/erl_stdlib_errors.erl
Labels: enhancement, team:VM, testing

#4605 Windows CI build
  .github/workflows/main.yaml
  HOWTO/INSTALL-WIN32.md
  erts/etc/win32/wsl_tools/SetupWSLcross.bat
Labels: team:PS, team:VM

#4721 Fix typo in ETS doc
  lib/stdlib/doc/src/ets.xml
Labels: documentation, fix, team:VM, testing

#4707 Update Unicode to 13.0
  lib/stdlib/test/unicode_util_SUITE_data/GraphemeBreakTest.txt
  lib/stdlib/test/unicode_util_SUITE_data/LineBreakTest.txt
  lib/stdlib/test/unicode_util_SUITE_data/NormalizationTest.txt
  lib/stdlib/uc_spec/CaseFolding.txt
  lib/stdlib/uc_spec/CompositionExclusions.txt
  lib/stdlib/uc_spec/GraphemeBreakProperty.txt
  lib/stdlib/uc_spec/PropList.txt
  lib/stdlib/uc_spec/README-UPDATE.txt
  lib/stdlib/uc_spec/SpecialCasing.txt
  lib/stdlib/uc_spec/UnicodeData.txt
  lib/stdlib/uc_spec/emoji-data.txt
  lib/stdlib/uc_spec/gen_unicode_mod.escript
Labels: team:PS, testing

#4730 Improve the 'Last calls' section included in crash dumps
  erts/emulator/beam/break.c
Labels: team:VM, testing

#4735 Improve the etp commands for lldb
  erts/etc/unix/etp.py
Labels: fix, team:VM, testing

#4699 jit: Add testcases to test perf support
  erts/emulator/internal_doc/BeamAsm.md
  erts/emulator/test/Makefile
  erts/emulator/test/perf_SUITE.erl
Labels: enhancement, team:VM, testing

#4732 Fix typo in erts_alloc
  erts/doc/src/erts_alloc.xml
Labels: documentation, fix, team:VM

#4638 Reference implementation for EEP 56
  lib/dialyzer/test/behaviour_SUITE_data/results/supervisor_incorrect_return
  lib/erl_docgen/src/docgen_xml_to_chunk.erl
  lib/sasl/test/release_handler_SUITE.erl
  lib/stdlib/doc/src/supervisor.xml
  lib/stdlib/src/supervisor.erl
  lib/stdlib/test/supervisor_SUITE.erl
  system/doc/design_principles/sup_princ.xml
Labels: enhancement, priority:high, team:PS, team:VM

#4743 TLS secrets require the keep_secrets option for TLS 1.3
  lib/ssl/doc/src/ssl.xml
Labels: team:PS

#2945 Document the -no_epmd option
  erts/doc/src/erl_cmd.xml
  erts/emulator/test/distribution_SUITE.erl
  erts/etc/common/erlexec.c
Labels: team:VM, testing

#4726 Fix typespec in gen.erl
  lib/stdlib/src/gen.erl
Labels: fix, team:VM, testing

#4688 SSL: Make the handshake fail when OCSP staple missing
  lib/ssl/src/ssl_gen_statem.erl
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/test/make_certs.erl
  lib/ssl/test/openssl_ocsp_SUITE.erl
  lib/ssl/test/ssl_test_lib.erl
Labels: team:PS, testing

#4741 Add enif_dynamic_resource_call
  erts/doc/src/erl_nif.xml
  erts/emulator/beam/erl_nif.c
  erts/emulator/beam/erl_nif.h
  erts/emulator/beam/erl_nif_api_funcs.h
  erts/emulator/test/nif_SUITE.erl
  erts/emulator/test/nif_SUITE_data/nif_SUITE.c
  erts/emulator/test/nif_SUITE_data/nif_mod.c
Labels: feature, team:VM

#4633 Remove race conditions on inet_db access
  lib/kernel/src/inet_db.erl
Labels: team:PS, testing

#4739 Add the hello module as a test case
  erts/emulator/test/Makefile
  erts/emulator/test/hello_SUITE.erl
  erts/emulator/test/hello_SUITE_data/hello.erl
Labels: enhancement, team:VM, testing

#4763 Correct extended error info for remote pids and ports
  erts/emulator/test/exception_SUITE.erl
  lib/kernel/src/erl_erts_errors.erl
Labels: fix, team:VM, testing

#4746 supervisor: refine error reasons for bad combinations of options
  lib/stdlib/src/supervisor.erl
  lib/stdlib/test/supervisor_SUITE.erl
Labels: enhancement, team:PS, team:VM, testing

#4751 supervisor: improve and augment docs for automatic shutdown
  lib/stdlib/doc/src/supervisor.xml
  system/doc/design_principles/Makefile
  system/doc/design_principles/sup-one_for_all.svg
  system/doc/design_principles/sup-one_for_one.svg
  system/doc/design_principles/sup-rest_for_one.svg
  system/doc/design_principles/sup4.fig
  system/doc/design_principles/sup4.gif
  system/doc/design_principles/sup5.fig
  system/doc/design_principles/sup5.gif
  system/doc/design_principles/sup_princ.xml
Labels: team:VM

#4748 Sendfile over NIF dyncall (OTP-17154)
  erts/emulator/nifs/common/prim_file_nif.c
  erts/emulator/nifs/common/prim_file_nif.h
  erts/emulator/nifs/common/prim_file_nif_dyncall.h
  erts/emulator/nifs/common/prim_socket_nif.c
  erts/emulator/nifs/common/socket_util.c
  erts/emulator/nifs/unix/unix_prim_file.c
  erts/emulator/nifs/win32/win_prim_file.c
  erts/preloaded/ebin/prim_file.beam
  erts/preloaded/ebin/prim_socket.beam
  erts/preloaded/ebin/socket_registry.beam
  erts/preloaded/src/prim_file.erl
  erts/preloaded/src/prim_socket.erl
  erts/preloaded/src/socket_registry.erl
  lib/kernel/doc/src/file.xml
  lib/kernel/doc/src/socket.xml
  lib/kernel/src/file.erl
  lib/kernel/src/gen_tcp.erl
  lib/kernel/src/gen_tcp_socket.erl
  lib/kernel/src/inet.erl
  lib/kernel/src/raw_file_io_compressed.erl
  lib/kernel/src/raw_file_io_delayed.erl
  lib/kernel/src/raw_file_io_list.erl
  lib/kernel/src/socket.erl
  lib/kernel/test/sendfile_SUITE.erl
Labels: team:PS, team:VM

#4711 [zip] Add execute permission to zipped directories (fix GH-4687)
  lib/stdlib/src/zip.erl
  lib/stdlib/test/zip_SUITE.erl
  lib/stdlib/test/zip_SUITE_data/test-zip-output/.keepdir
  lib/stdlib/test/zip_SUITE_data/test-zip/dir-1/file.txt
Labels: team:VM

#4683 snmp: Make snmp build reproducibly
  lib/snmp/src/compile/snmpc_mib_to_hrl.erl
Labels: team:PS, testing

#4765 Fix missing xml since attributes
  lib/common_test/doc/src/ct_property_test.xml
  lib/crypto/doc/src/crypto.xml
  lib/dialyzer/doc/src/dialyzer.xml
  lib/erl_interface/doc/src/ei_connect.xml
  lib/erl_interface/doc/src/ei_global.xml
  lib/kernel/doc/src/file.xml
  lib/public_key/doc/src/public_key.xml
  lib/snmp/doc/src/snmpa.xml
  lib/snmp/doc/src/snmpm.xml
  lib/ssh/doc/src/ssh.xml
  lib/ssh/doc/src/ssh_agent.xml
  lib/stdlib/doc/src/beam_lib.xml
  lib/stdlib/doc/src/maps.xml
Labels: documentation, fix, team:VM, testing

#4749 erl_docgen: fix ordered list rendering in HTML output
  lib/erl_docgen/priv/xsl/db_html.xsl
Labels: team:PS, testing

#4714 zlib: Fix edge case in state flushing
  erts/emulator/nifs/common/zlib_nif.c
  lib/kernel/test/zlib_SUITE.erl
Labels: bug, fix, team:VM

#4762 Add types nonempty_{binary,bitstring}()
  lib/dialyzer/src/erl_types.erl
  lib/dialyzer/test/indent2_SUITE_data/results/iodata
  lib/dialyzer/test/r9c_SUITE_data/results/asn1
  lib/dialyzer/test/small_SUITE_data/results/binary_nonempty
  lib/dialyzer/test/small_SUITE_data/results/binary_redef2
  lib/dialyzer/test/small_SUITE_data/src/binary_nonempty.erl
  lib/dialyzer/test/small_SUITE_data/src/binary_redef.erl
  lib/dialyzer/test/small_SUITE_data/src/binary_redef2.erl
  lib/dialyzer/test/specdiffs_SUITE_data/results/iodata
  lib/dialyzer/test/user_SUITE_data/results/wsp_pdu
  lib/edoc/src/edoc_types.erl
  lib/stdlib/src/erl_internal.erl
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/test/erl_lint_SUITE.erl
  system/doc/reference_manual/typespec.xml
Labels: team:VM

#4747 supervisor: allow 0 for shutdown
  lib/stdlib/src/supervisor.erl
  lib/stdlib/test/supervisor_SUITE.erl
Labels: team:PS, team:VM, testing
