Repository erlang/otp, pull requests merged in 2021-07, with the labels that each got.

#5012 Fix code generation in guard for not (X =:= true)
  lib/compiler/src/v3_core.erl
  lib/compiler/test/guard_SUITE.erl
  lib/dialyzer/test/indent_SUITE_data/results/guard_warnings
  lib/dialyzer/test/small_SUITE_data/results/guard_warnings
Labels: fix, team:VM

#5015 Fix for DistEntry write-after-free bug
  erts/emulator/beam/erl_bif_unique.h
  erts/emulator/beam/erl_node_tables.c
  erts/emulator/test/distribution_SUITE.erl
Labels: fix, team:VM, testing

#5013 Don't keep a stacktrace longer than necessary
  erts/emulator/beam/beam_common.c
  erts/emulator/beam/emu/instrs.tab
  erts/emulator/beam/jit/x86/instr_common.cpp
Labels: fix, team:VM, testing

#4960 Fix A Bug That Causes The Test System To Not Run
  Makefile.in
Labels: team:VM

#5028 Fix github actions cross compilation test
  .github/dockerfiles/Dockerfile.cross-compile
Labels: team:VM

#5017 Do not attempt to start children of running apps
  lib/kernel/src/application.erl
  lib/kernel/src/application_controller.erl
Labels: team:VM, testing

#5030 Ingela/ssl/downgrade/gh 5009/otp 17517
  lib/ssl/src/ssl_connection.hrl
  lib/ssl/src/ssl_gen_statem.erl
  lib/ssl/src/tls_connection.erl
  lib/ssl/src/tls_connection_1_3.erl
  lib/ssl/src/tls_gen_connection.erl
Labels: team:PS, testing

#4962 observer: add button to trace all processes and ports
  lib/observer/src/observer_trace_wx.erl
Labels: team:PS, testing

#5050 ssl: Use new inet:monitor/1 to monitor listen sockets
  lib/ssl/src/ssl_server_session_cache.erl
  lib/ssl/src/tls_server_session_ticket.erl
  lib/ssl/src/tls_socket.erl
  lib/ssl/test/tls_api_SUITE.erl
Labels: team:PS

#4928 Add lists:enumerate/1 and lists:enumerate/2
  lib/stdlib/doc/src/lists.xml
  lib/stdlib/src/lists.erl
  lib/stdlib/test/lists_SUITE.erl
Labels: team:VM, testing

#5047 ssl: tls_server_session_ticket unit tests added
  lib/ssl/test/Makefile
  lib/ssl/test/tls_server_session_ticket_SUITE.erl
Labels: team:PS

#4979 ssl: Fix signature algorithm selection for ECDSA
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/src/tls_handshake_1_3.erl
  lib/ssl/test/property_test/ssl_eqc_chain.erl
  lib/ssl/test/ssl_cert_SUITE.erl
  lib/ssl/test/ssl_test_lib.erl
Labels: team:PS, testing

#5019 Add no_return() spec to gen_statem:init/1 note
  lib/stdlib/doc/src/gen_statem.xml
Labels: team:PS

#4996 fix ssl:close with nif sockets
  lib/kernel/src/inet.erl
Labels: team:PS, testing

#4948 doc: Fix spelling errors
  lib/snmp/doc/src/snmp_config.xml
Labels: team:PS

#5064 Fixing test public_key_SUITE:rsa_pss_sign_verify()
  lib/public_key/test/public_key_SUITE.erl
Labels: team:PS, testing

#5059 'extprg' needs to be properly addressed
  system/doc/tutorial/c_port.xmlsrc
Labels: team:VM

#5057 Fixing #5054, public_key:pkix_sign for RSASSA-PSS signature
  lib/public_key/src/pubkey_cert.erl
  lib/public_key/src/public_key.erl
  lib/public_key/test/erl_make_certs.erl
  lib/public_key/test/public_key_SUITE.erl
Labels: team:PS, testing
