Repository erlang/otp, pull requests merged in 2021-05, with the labels that each got.

#4756 Ingela/ssl/eddsa/gh 4637/gh 4650/otp 17142
  lib/crypto/src/crypto.erl
  lib/public_key/Makefile
  lib/public_key/asn1/ECPrivateKey.asn1
  lib/public_key/asn1/PKCS-8.asn1
  lib/public_key/doc/src/public_key.xml
  lib/public_key/src/pubkey_cert.erl
  lib/public_key/src/pubkey_cert_records.erl
  lib/public_key/src/pubkey_pem.erl
  lib/public_key/src/public_key.erl
  lib/public_key/test/public_key_SUITE.erl
  lib/public_key/test/public_key_SUITE_data/eddsa_key_pkcs8.pem
  lib/public_key/test/public_key_SUITE_data/eddsa_key_rfc5958.pem
  lib/ssl/doc/src/standards_compliance.xml
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_certificate.erl
  lib/ssl/src/ssl_cipher.erl
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/src/tls_handshake_1_3.erl
  lib/ssl/src/tls_v1.erl
  lib/ssl/test/openssl_client_cert_SUITE.erl
  lib/ssl/test/openssl_server_cert_SUITE.erl
  lib/ssl/test/ssl_cert_SUITE.erl
  lib/ssl/test/ssl_test_lib.erl
Labels: team:PS, testing

#4782 Reduce super alignment on 64-bit
  erts/emulator/beam/erl_afit_alloc.c
  erts/emulator/beam/erl_alloc.c
  erts/emulator/beam/erl_alloc_util.c
  erts/emulator/beam/erl_alloc_util.h
  erts/emulator/beam/erl_ao_firstfit_alloc.c
  erts/emulator/beam/erl_bestfit_alloc.c
  erts/emulator/beam/erl_goodfit_alloc.c
  erts/emulator/beam/erl_process.h
  erts/emulator/sys/common/erl_mmap.h
Labels: enhancement, team:VM, testing

#4783 Make flaky tests less flaky
  erts/emulator/test/driver_SUITE.erl
  erts/emulator/test/timer_bif_SUITE.erl
Labels: team:VM

#4584 Make configure scripts fail on requests that cannot be satisfied
  .github/dockerfiles/Dockerfile.32-bit
  .github/dockerfiles/Dockerfile.64-bit
  .github/dockerfiles/Dockerfile.debian-base
  .github/dockerfiles/Dockerfile.ubuntu-base
  HOWTO/INSTALL.md
  erts/aclocal.m4
  erts/configure.in
  lib/crypto/c_src/Makefile.in
  lib/crypto/configure.in
  make/configure.in
  otp_build
Labels: enhancement, team:PS, team:VM

#4645 Makefile.in: Skip lib/jinterface/priv if missing
  Makefile.in
Labels: team:VM

#4789 Correct order of optimization passes
  lib/compiler/src/beam_ssa_bool.erl
  lib/compiler/src/compile.erl
  lib/compiler/test/guard_SUITE.erl
Labels: fix, team:VM

#4787 Do not bind sockets created from FDs
  lib/kernel/src/gen_tcp_socket.erl
Labels: team:PS, testing

#4795 Fix for build issue when USE_VM_PROBES is enabled.
  erts/emulator/beam/erl_proc_sig_queue.c
Labels: fix, team:VM, testing

#4791 Signal doc improvements
  erts/doc/src/communication.xml
  erts/doc/src/erl_dist_protocol.xml
  erts/doc/src/erlang.xml
  system/doc/reference_manual/data_types.xml
  system/doc/reference_manual/expressions.xml
  system/doc/reference_manual/processes.xml
Labels: documentation, enhancement, team:VM

#4776 beam_validator: Support subtraction in update_container_type/4
  lib/compiler/src/beam_validator.erl
  lib/compiler/test/beam_type_SUITE.erl
Labels: team:VM

#4786 Remove mentions of non-SMP emulator
  erts/doc/src/crash_dump.xml
  erts/doc/src/driver_entry.xml
  erts/doc/src/erl_driver.xml
  erts/doc/src/erl_nif.xml
  erts/doc/src/erts_alloc.xml
  erts/doc/src/escript_cmd.xml
  lib/stdlib/doc/src/ets.xml
  system/doc/efficiency_guide/commoncaveats.xml
  system/doc/efficiency_guide/processes.xml
Labels: documentation, enhancement, team:VM, testing

#4805 Ingela/ssl/public key/cert doc log enhancment/gh 4800/otp 17384
  lib/public_key/doc/src/public_key_records.xml
  lib/ssl/doc/src/ssl.xml
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_logger.erl
Labels: team:PS, testing

#4804 Fix stack overflow bug for certain match specs
  erts/emulator/beam/erl_db_util.c
  lib/stdlib/test/ets_SUITE.erl
Labels: fix, team:VM, testing

#4832 Document how to cross compile for Android x86_64
  HOWTO/INSTALL-ANDROID.md
Labels: team:VM

#4826 Remove travis support
  .travis.yml
  scripts/build-otp
Labels: team:VM, testing

#4767 Floats for ct multiply timetraps
  lib/common_test/doc/src/ct_run_cmd.xml
  lib/common_test/src/ct_run.erl
  lib/common_test/src/ct_testspec.erl
  lib/common_test/src/test_server_ctrl.erl
  lib/common_test/test/ct_error_SUITE.erl
  lib/common_test/test/ct_error_SUITE_data/error/test/timetrap_9_SUITE.erl
Labels: team:PS, testing

#4845 Expand group_leader, process_info and standard_io docs
  erts/doc/src/erlang.xml
  lib/stdlib/doc/src/io.xml
  system/doc/reference_manual/processes.xml
Labels: documentation, team:VM

#4829 ssl: Fix make deps
  lib/ssl/prebuild.skip
  lib/ssl/src/Makefile
Labels: fix, team:PS, team:VM, testing

#4803 Fix io_lib_pretty:printable_latin1_list/2
  lib/stdlib/src/io_lib_pretty.erl
  lib/stdlib/test/io_SUITE.erl
Labels: team:VM, testing

#4799 observer: Fix parsing of monitor_node/2 in cdv
  lib/observer/src/crashdump_viewer.erl
  lib/observer/test/crashdump_helper.erl
Labels: fix, team:VM, testing

#4841 wx: Fix compile error
  lib/wx/c_src/wxe_return.cpp
  lib/wx/c_src/wxe_return.h
Labels: team:PS

#4761 base64: fix spec to allow 0 as a character in ASCII string
  lib/stdlib/doc/src/base64.xml
  lib/stdlib/src/base64.erl
Labels: team:PS, waiting

#4854 Improve handling of exceptions from parse transforms
  lib/compiler/src/compile.erl
  lib/compiler/test/compile_SUITE.erl
  lib/compiler/test/compile_SUITE_data/generic_pt.erl
  lib/compiler/test/error_SUITE.erl
Labels: fix, team:VM, testing

#4867 Improve warnings for failing io:format() calls
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/test/erl_lint_SUITE.erl
  lib/stdlib/test/erl_lint_SUITE_data/format.erl
Labels: fix, team:VM, testing

#4857 erl_docgen: Translate type links in specs
  lib/erl_docgen/priv/bin/specs_gen.escript
  lib/erl_docgen/src/docgen_otp_specs.erl
Labels: bug, fix, team:VM, testing

#4737 ssl: avoid decoding certs several times
  lib/ssl/src/ssl_certificate.erl
  lib/ssl/src/ssl_crl.erl
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/src/ssl_internal.hrl
  lib/ssl/src/ssl_manager.erl
  lib/ssl/src/ssl_pkix_db.erl
  lib/ssl/src/tls_dtls_connection.erl
  lib/ssl/test/ssl_cert_SUITE.erl
Labels: team:PS

#4780 Completed list of handled MacOS wxApp events
  lib/wx/c_src/wxe_impl.cpp
  lib/wx/c_src/wxe_impl.h
  lib/wx/src/wx.erl
  lib/wx/src/wxe_master.erl
Labels: team:PS, testing

#4875 fix internal hash for external pids
  erts/doc/src/erl_ext_dist.xml
  erts/emulator/beam/utils.c
  erts/emulator/test/map_SUITE.erl
  erts/etc/unix/etp-commands.in
Labels: fix, team:VM, testing

#4797 cover:filter_options/1: preserve tuple_calls
  lib/tools/src/cover.erl
  lib/tools/test/cover_SUITE.erl
Labels: fix, team:VM, testing

#4878 Clarify the rules for variable shadowing in comprehensions
  system/doc/programming_examples/list_comprehensions.xml
  system/doc/reference_manual/expressions.xml
Labels: fix, team:VM, testing

#4879 Make warn_missing_spec warn for functions exported using export_all
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/test/erl_lint_SUITE.erl
Labels: fix, team:VM, testing

#4807 Improve receive docs
  erts/doc/src/erlang.xml
  system/doc/reference_manual/expressions.xml
  system/doc/reference_manual/processes.xml
Labels: documentation, enhancement, team:VM, testing

#4843 Seal memory leak of jit_code_entry
  erts/emulator/beam/erl_lock_check.c
  erts/emulator/beam/jit/x86/beam_asm.cpp
Labels: fix, team:VM, testing

#4883 cover:reset/1: correct -spec
  lib/tools/src/cover.erl
Labels: fix, team:VM, testing

#4889 Correct memsup:get_os_wordsize/0 on an M1 Mac
  lib/os_mon/src/memsup.erl
Labels: fix, team:VM, testing

#4891 ssl: Remove duplicate option documentation
  lib/ssl/src/ssl.erl
Labels: team:PS, testing

#4886 etp-commands: various small fixes
  erts/etc/unix/etp-commands.in
  erts/etc/unix/etp-thr.py
Labels: fix, team:VM

#4764 Extend and document exceptions and error_info
  erts/doc/src/erlang.xml
  erts/emulator/test/exception_SUITE.erl
  erts/preloaded/ebin/erlang.beam
  erts/preloaded/src/erlang.erl
  lib/erl_docgen/priv/bin/codeline_preprocessing.escript
  lib/kernel/src/erl_erts_errors.erl
  lib/kernel/src/erl_kernel_errors.erl
  lib/stdlib/doc/src/Makefile
  lib/stdlib/doc/src/erl_error.xml
  lib/stdlib/doc/src/erl_error.xmlsrc
  lib/stdlib/examples/my_error_module.erl
  lib/stdlib/src/erl_error.erl
  lib/stdlib/src/erl_stdlib_errors.erl
  lib/stdlib/test/Makefile
  lib/stdlib/test/binary_module_SUITE.erl
  lib/stdlib/test/error_info.spec
  lib/stdlib/test/error_info_lib.erl
  lib/stdlib/test/lists_SUITE.erl
  lib/stdlib/test/maps_SUITE.erl
  lib/stdlib/test/math_SUITE.erl
  lib/stdlib/test/re_SUITE.erl
  lib/stdlib/test/unicode_SUITE.erl
  make/doc.mk
  system/doc/reference_manual/errors.xml
Labels: enhancement, team:VM

#4850 Skip one extra uri_string:parse for httpc URL
  lib/inets/src/http_client/httpc.erl
Labels: team:PS, testing

#4901 Correct error message for binary_to_existing_atom/2
  erts/emulator/test/exception_SUITE.erl
  lib/kernel/src/erl_erts_errors.erl
Labels: fix, team:VM, testing

#4899 Eliminate incorrect warning for useless building
  lib/compiler/src/sys_core_fold.erl
  lib/compiler/test/warnings_SUITE.erl
Labels: fix, team:VM, testing

#4910 compiler: Document exception handling at the BEAM SSA level
  lib/compiler/internal_doc/beam_ssa.md
Labels: team:VM, testing

#4906 Correct error messages for timer BIFs
  erts/emulator/beam/erl_hl_timer.c
  erts/emulator/test/exception_SUITE.erl
  lib/kernel/src/erl_erts_errors.erl
Labels: fix, team:VM, testing

#4727 Reenable tls prf test
  lib/ssl/src/ssl_gen_statem.erl
  lib/ssl/src/tls_dtls_connection.erl
  lib/ssl/test/ssl_api_SUITE.erl
Labels: team:PS, testing

#4880 debug emulator build: clean up unused assertions
  erts/emulator/beam/jit/x86/beam_asm.cpp
  erts/emulator/beam/jit/x86/beam_asm_perf.cpp
Labels: fix, team:VM

#4893 dialyzer: Do not expose line number 0 in message locations
  lib/dialyzer/src/dialyzer_dataflow.erl
  lib/dialyzer/src/dialyzer_utils.erl
Labels: team:VM

#4665 alloc_SUITE, distribution_SUITE: fix race conditions
  erts/emulator/test/alloc_SUITE.erl
  erts/emulator/test/distribution_SUITE.erl
Labels: team:VM, testing

#4913 stdlib: Fix a loop when using io_lib option 'chars_limit'
  lib/stdlib/src/io_lib_pretty.erl
  lib/stdlib/test/io_SUITE.erl
Labels: team:VM

#4864 compiler: Fix code generation for `raw_raise`
  lib/compiler/src/beam_kernel_to_ssa.erl
  lib/compiler/test/trycatch_SUITE.erl
Labels: bug, team:VM

#4870 Fix GC of alias-signals
  erts/emulator/beam/erl_gc.c
  erts/emulator/test/gc_SUITE.erl
Labels: fix, team:VM, testing

#4914 Fix signal queue inconsistency
  erts/emulator/beam/erl_proc_sig_queue.c
  erts/emulator/beam/erl_process.h
  erts/etc/unix/etp-commands.in
Labels: fix, team:VM

#4903 Fix busy port handling in port_command()
  erts/emulator/beam/erl_bif_port.c
  erts/emulator/test/busy_port_SUITE.erl
Labels: fix, team:VM
