Repository erlang/otp, pull requests merged in 2021-09, with the labels that each got.

#5172 Correct extended error for binary_to_term/2
  erts/emulator/beam/external.c
  erts/emulator/test/exception_SUITE.erl
  lib/kernel/src/erl_erts_errors.erl
Labels: team:VM, fix, testing

#5168 debugger: Update runtime deps
  lib/debugger/src/debugger.app.src
Labels: team:PS, testing

#5152 wx: Fix color guards
  lib/wx/api_gen/wx_gen.erl
  lib/wx/api_gen/wx_gen_erl.erl
  lib/wx/api_gen/wx_gen_nif.erl
  lib/wx/api_gen/wxapi.conf
  lib/wx/c_src/gen/wxe_func_table.cpp
  lib/wx/c_src/gen/wxe_macros.h
  lib/wx/c_src/gen/wxe_wrapper_4.cpp
  lib/wx/c_src/gen/wxe_wrapper_7.cpp
  lib/wx/doc/src/wxImageList.xml
  lib/wx/doc/src/wxTextAttr.xml
  lib/wx/src/gen/wxAuiDockArt.erl
  lib/wx/src/gen/wxAuiTabArt.erl
  lib/wx/src/gen/wxBrush.erl
  lib/wx/src/gen/wxCalendarCtrl.erl
  lib/wx/src/gen/wxCalendarDateAttr.erl
  lib/wx/src/gen/wxColourData.erl
  lib/wx/src/gen/wxColourPickerCtrl.erl
  lib/wx/src/gen/wxDC.erl
  lib/wx/src/gen/wxFontData.erl
  lib/wx/src/gen/wxGraphicsContext.erl
  lib/wx/src/gen/wxGraphicsGradientStops.erl
  lib/wx/src/gen/wxGrid.erl
  lib/wx/src/gen/wxGridCellAttr.erl
  lib/wx/src/gen/wxImageList.erl
  lib/wx/src/gen/wxListCtrl.erl
  lib/wx/src/gen/wxListItem.erl
  lib/wx/src/gen/wxListItemAttr.erl
  lib/wx/src/gen/wxMask.erl
  lib/wx/src/gen/wxPen.erl
  lib/wx/src/gen/wxRegion.erl
  lib/wx/src/gen/wxStyledTextCtrl.erl
  lib/wx/src/gen/wxTextAttr.erl
  lib/wx/src/gen/wxTreeCtrl.erl
  lib/wx/src/gen/wxWindow.erl
  lib/wx/src/gen/wxe_funcs.hrl
  lib/wx/src/wxe.hrl
Labels: team:PS, testing

#5166 Make re copy small subbinaries
  erts/emulator/beam/erl_bif_re.c
Labels: team:VM, bug

#5149 Optimize off-heap list traversal during GC
  erts/emulator/beam/erl_binary.h
  erts/emulator/beam/erl_gc.c
Labels: team:VM, enhancement, testing

#5167 ssh: Handle eacces like enoent in ssh_sftpd:get_attrs/6
  lib/ssh/src/ssh_sftpd.erl
Labels: team:PS, fix, testing

#5151 Improve inet_backend = socket option parsing for gen_tcp (OTP-17580)
  lib/kernel/src/gen_tcp_socket.erl
  lib/kernel/test/gen_tcp_misc_SUITE.erl
Labels: team:PS

#5182 Update httpc.xml
  lib/inets/doc/src/httpc.xml
Labels: team:PS

#5173 Slightly simplify maps intersection functions
  lib/stdlib/src/maps.erl
Labels: team:VM, enhancement, testing

#5153 Ensure reproducible builds of Erlang code
  erts/doc/src/erlang.xml
  erts/emulator/beam/atom.names
  erts/emulator/beam/dist.h
  erts/emulator/beam/erl_alloc.types
  erts/emulator/beam/external.c
  erts/emulator/test/binary_SUITE.erl
  erts/emulator/test/map_SUITE.erl
  erts/preloaded/ebin/erlang.beam
  erts/preloaded/src/erlang.erl
  lib/compiler/src/beam_dict.erl
  lib/compiler/src/erl_bifs.erl
Labels: team:VM, fix

#5181 ssl: Correct type spec
  lib/ssl/src/ssl.erl
Labels: team:PS, testing

#5157 public_key: Fix EDDSA private key ASN-1 decode/encode
  lib/public_key/src/public_key.erl
  lib/public_key/test/public_key_SUITE.erl
Labels: team:PS, testing

#5185 eunit: Include a stacktrace when a test times out
  lib/eunit/src/eunit_lib.erl
  lib/eunit/src/eunit_proc.erl
  lib/eunit/src/eunit_surefire.erl
  lib/eunit/src/eunit_tty.erl
  lib/eunit/test/Makefile
  lib/eunit/test/eunit_SUITE.erl
  lib/eunit/test/ttimesout.erl
Labels: team:PS, testing

#5020 Optimize signal sending to processes with message_queue_data=off_heap enabled
  erts/emulator/beam/erl_alloc.c
  erts/emulator/beam/erl_alloc.types
  erts/emulator/beam/erl_bif_info.c
  erts/emulator/beam/erl_lock_check.c
  erts/emulator/beam/erl_message.c
  erts/emulator/beam/erl_message.h
  erts/emulator/beam/erl_proc_sig_queue.c
  erts/emulator/beam/erl_proc_sig_queue.h
  erts/emulator/beam/erl_process.c
  erts/emulator/beam/erl_process.h
  erts/emulator/beam/erl_process_dump.c
  erts/emulator/beam/erl_process_lock.h
  erts/test/Makefile
  erts/test/parallel_messages_SUITE.erl
  erts/test/parallel_messages_SUITE_data/visualize_throughput.html
Labels: team:VM

#5069 Add dist_util_spawn_options in kernel
  lib/kernel/doc/src/kernel_app.xml
  lib/kernel/src/inet_tcp_dist.erl
  lib/kernel/test/erl_distribution_SUITE.erl
  lib/ssl/src/inet_tls_dist.erl
  lib/ssl/test/ssl_dist_SUITE.erl
Labels: team:VM, testing

#5188 Improve typespec for `ssl:str_to_suite/1`
  lib/ssl/src/ssl.erl
Labels: team:PS, testing, waiting

#5038 Fix win32reg issues #5037 and #4702
  erts/emulator/drivers/win32/registry_drv.c
  lib/stdlib/src/win32reg.erl
  lib/stdlib/test/win32reg_SUITE.erl
Labels: team:VM, fix, testing

#4922 [inets] httpd directory listing improvements
  lib/inets/src/http_server/httpd_response.erl
  lib/inets/src/http_server/mod_dir.erl
Labels: team:PS, testing

#5191 dialyzer: Fix opaque type handling for `underspecs`/`overspecs`
  lib/dialyzer/src/dialyzer_contracts.erl
  lib/dialyzer/src/erl_types.erl
  lib/dialyzer/test/overspecs_SUITE_data/results/opaque
  lib/dialyzer/test/overspecs_SUITE_data/src/opaque.erl
  lib/dialyzer/test/underspecs_SUITE_data/results/opaque
  lib/dialyzer/test/underspecs_SUITE_data/src/opaque.erl
Labels: team:VM, testing, bug

#5190 Eliminate redundant tests
  lib/compiler/src/Makefile
  lib/compiler/src/beam_block.erl
  lib/compiler/src/beam_clean.erl
  lib/compiler/src/beam_jump.erl
  lib/compiler/src/beam_peep.erl
  lib/compiler/src/beam_ssa_dead.erl
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/beam_utils.erl
  lib/compiler/src/compile.erl
  lib/compiler/src/compiler.app.src
  lib/compiler/src/sys_core_fold.erl
  lib/compiler/test/beam_ssa_SUITE.erl
  lib/compiler/test/compile_SUITE.erl
  lib/compiler/test/guard_SUITE.erl
  lib/compiler/test/misc_SUITE.erl
Labels: team:VM, enhancement

#5189 Optimize compilation speed
  lib/compiler/src/beam_ssa_type.erl
Labels: team:VM, enhancement, testing

#5184 Fix doc typo
  lib/mnesia/src/mnesia_dumper.erl
Labels: team:PS, waiting

#5200 Fix incorrect error info for maps:get/2
  lib/stdlib/src/erl_stdlib_errors.erl
  lib/stdlib/test/maps_SUITE.erl
Labels: team:VM, fix, testing

#5202 ssl: Properly handle default session data storage
  lib/ssl/src/ssl_server_session_cache.erl
  lib/ssl/test/ssl_session_SUITE.erl
Labels: team:PS, testing

#5061 inet_res validate reply OTP-17323
  lib/kernel/src/inet_db.erl
  lib/kernel/src/inet_dns.hrl
  lib/kernel/src/inet_res.erl
  lib/kernel/test/inet_res_SUITE.erl
  lib/kernel/test/inet_res_SUITE_data/otptest/0.0.0.0.f.7.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa.zone
  lib/kernel/test/inet_res_SUITE_data/otptest/0.0.127.in-addr.arpa.zone
  lib/kernel/test/inet_res_SUITE_data/otptest/otptest.zone
Labels: team:PS, waiting

#5209 Do some spring cleaning of Dialyzer
  lib/dialyzer/src/Makefile
  lib/dialyzer/src/cerl_closurean.erl
  lib/dialyzer/src/cerl_lib.erl
  lib/dialyzer/src/cerl_pmatch.erl
  lib/dialyzer/src/cerl_typean.erl
  lib/dialyzer/src/dialyzer.app.src
  lib/dialyzer/src/dialyzer_analysis_callgraph.erl
  lib/dialyzer/src/dialyzer_callgraph.erl
  lib/dialyzer/src/dialyzer_cl.erl
  lib/dialyzer/src/dialyzer_clean_core.erl
  lib/dialyzer/src/dialyzer_codeserver.erl
  lib/dialyzer/src/dialyzer_contracts.erl
  lib/dialyzer/src/dialyzer_coordinator.erl
  lib/dialyzer/src/dialyzer_dataflow.erl
  lib/dialyzer/src/dialyzer_dep.erl
  lib/dialyzer/src/dialyzer_succ_typings.erl
  lib/dialyzer/src/dialyzer_typesig.erl
  lib/dialyzer/src/dialyzer_utils.erl
  lib/dialyzer/src/dialyzer_worker.erl
  lib/dialyzer/src/erl_types.erl
  lib/dialyzer/src/typer.erl
Labels: team:VM, enhancement

#5214 dialyzer: Add options for missing/extra range warnings
  lib/dialyzer/doc/src/dialyzer.xml
  lib/dialyzer/src/dialyzer.hrl
  lib/dialyzer/src/dialyzer_contracts.erl
  lib/dialyzer/src/dialyzer_options.erl
Labels: team:VM, testing

#5233 No longer support loading BEAM files compiled before OTP 22
  erts/emulator/beam/beam_file.c
  erts/emulator/beam/beam_file.h
  erts/emulator/beam/beam_load.c
  erts/emulator/beam/emu/bs_instrs.tab
  erts/emulator/beam/emu/map_instrs.tab
  erts/emulator/beam/emu/ops.tab
  erts/emulator/beam/emu/predicates.tab
  erts/emulator/beam/generators.tab
  erts/emulator/beam/jit/arm/instr_bs.cpp
  erts/emulator/beam/jit/arm/instr_map.cpp
  erts/emulator/beam/jit/arm/ops.tab
  erts/emulator/beam/jit/load.h
  erts/emulator/beam/jit/x86/instr_bs.cpp
  erts/emulator/beam/jit/x86/instr_map.cpp
  erts/emulator/beam/jit/x86/ops.tab
  erts/emulator/beam/predicates.tab
  erts/emulator/test/erts_test_utils.erl
  erts/emulator/test/map_SUITE.erl
  erts/emulator/test/map_SUITE_data/badmap_17.erl
  erts/test/upgrade_SUITE.erl
  lib/common_test/src/test_server_node.erl
  lib/compiler/src/beam_asm.erl
  lib/compiler/src/beam_block.erl
  lib/compiler/src/beam_dict.erl
  lib/compiler/src/beam_flatten.erl
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/src/beam_ssa_pre_codegen.erl
  lib/compiler/src/beam_validator.erl
  lib/compiler/src/beam_z.erl
  lib/compiler/src/compile.erl
  lib/compiler/src/genop.tab
  lib/compiler/test/Makefile
  lib/compiler/test/compile_SUITE.erl
  lib/compiler/test/compile_SUITE_data/funs.erl
  lib/compiler/test/test_lib.erl
  lib/kernel/test/kernel_SUITE.erl
  lib/kernel/test/seq_trace_SUITE.erl
  lib/observer/test/crashdump_helper.erl
  lib/sasl/test/sasl_SUITE.erl
  lib/stdlib/test/beam_lib_SUITE.erl
  lib/stdlib/test/stdlib_SUITE.erl
Labels: team:VM, enhancement

#5164 erts: Make bs_get_tail create a heapbin if possible
  erts/emulator/beam/emu/bs_instrs.tab
Labels: team:VM, testing

#5165 erts: Fix reduction count in re
  erts/emulator/pcre/pcre_exec.c
Labels: team:VM, testing, bug

#5227 mnesia.xml: Add missing closing parentheses
  lib/mnesia/doc/src/mnesia.xml
Labels: team:PS

#5011 Remove duplicated reference to install_fallback/1
  lib/mnesia/doc/src/mnesia.xml
Labels: team:PS

#5217 Fix doc typo
  lib/mnesia/src/mnesia_loader.erl
Labels: team:PS, priority:low

#5206 shell_docs: Fix signature rendering
  lib/stdlib/src/shell_docs.erl
  lib/stdlib/test/shell_docs_SUITE.erl
Labels: team:VM, testing

#5242 Common_test : Updated grammar for tests specifications
  lib/common_test/doc/src/run_test_chapter.xml
  lib/common_test/src/ct_groups.erl
  lib/common_test/src/ct_run.erl
  lib/common_test/test/ct_testspec_1_SUITE.erl
  lib/common_test/test/ct_testspec_1_SUITE_data/groups_1/groups_11_SUITE.erl
Labels: team:PS, testing

#5237 Improved inline multiplication in JIT for x86
  erts/emulator/beam/jit/x86/instr_arith.cpp
Labels: team:VM, enhancement, testing

#5186 Allow reconfiguration of logger
  lib/kernel/doc/src/logger.xml
  lib/kernel/src/logger.erl
  lib/kernel/test/logger_SUITE.erl
Labels: team:VM, testing

#5201 Keep supervisor children linked during shutdown
  lib/stdlib/src/supervisor.erl
  lib/stdlib/test/Makefile
  lib/stdlib/test/supervisor_4.erl
  lib/stdlib/test/supervisor_SUITE.erl
Labels: team:VM, testing

#5230 Fix demonitor of an alias
  erts/emulator/beam/bif.c
  erts/emulator/test/monitor_SUITE.erl
Labels: team:VM, fix, testing

#5232 Fix storage of tags in monitors
  erts/emulator/beam/erl_monitor_link.c
  erts/emulator/beam/erl_proc_sig_queue.c
  erts/emulator/test/monitor_SUITE.erl
Labels: team:VM, fix, testing

#5244 Fix handling of bad timeout value in receive
  erts/emulator/beam/emu/msg_instrs.tab
  erts/emulator/beam/erl_proc_sig_queue.c
  erts/emulator/beam/jit/beam_jit_common.c
  erts/emulator/beam/jit/x86/instr_msg.cpp
  erts/emulator/test/receive_SUITE.erl
Labels: team:VM, fix, testing

#5248 Fix bugs in handling of port signals
  erts/emulator/beam/io.c
  erts/emulator/test/port_SUITE.erl
  erts/emulator/test/port_SUITE_data/echo_drv.c
Labels: team:VM, fix, testing

#5195 Further optimize off-heap traversal during minor GC
  erts/emulator/beam/break.c
  erts/emulator/beam/erl_bits.c
  erts/emulator/beam/erl_gc.c
  erts/emulator/beam/erl_message.c
  erts/emulator/beam/erl_message.h
  erts/emulator/beam/erl_nfunc_sched.h
  erts/emulator/beam/erl_nif.c
  erts/emulator/beam/erl_process.c
  erts/emulator/beam/erl_process.h
Labels: team:VM, enhancement, testing
