Repository erlang/otp, pull requests merged in 2021-01, with the labels that each got.

#2954 Also generate SHA256 checksums for releases
  .github/workflows/main.yaml
Labels: team:VM

#2962 Remove unused atom from erts
  erts/emulator/beam/atom.names
Labels: testing

#2963 Simplify configuration of cross-compiling to Android x86_64
  xcomp/erl-xcomp-x86_64-android.conf
Labels: team:VM

#2965 Add various address sanitizer support
  HOWTO/INSTALL.md
  HOWTO/TESTING.md
  erts/emulator/Makefile.in
  erts/emulator/asan/asan_logs_to_html
  erts/emulator/asan/suppress
  erts/emulator/beam/erl_alloc.c
  erts/emulator/beam/erl_alloc.h
  erts/emulator/beam/erl_bif_info.c
  erts/emulator/beam/erl_binary.h
  erts/emulator/beam/erl_sched_spec_pre_alloc.c
  erts/emulator/sys/common/erl_mmap.c
  erts/emulator/sys/common/erl_mmap.h
  erts/emulator/sys/unix/sys.c
  erts/emulator/test/alloc_SUITE.erl
  erts/emulator/test/bif_SUITE.erl
  erts/emulator/test/erts_debug_SUITE.erl
  erts/emulator/test/hash_SUITE.erl
  erts/emulator/test/os_signal_SUITE.erl
  erts/etc/unix/cerl.src
  erts/lib_src/Makefile.in
  lib/common_test/src/test_server.erl
  lib/common_test/src/test_server_ctrl.erl
  lib/common_test/test_server/ts_run.erl
  lib/crypto/c_src/Makefile.in
  lib/crypto/c_src/crypto.c
  lib/crypto/c_src/info.c
  lib/crypto/doc/src/Makefile
  lib/crypto/src/Makefile
  lib/crypto/src/crypto.erl
  lib/runtime_tools/test/erts_alloc_config_SUITE.erl
  lib/tools/test/instrument_SUITE.erl
  make/otp_subdir.mk
  make/run_make.mk
Labels: feature, team:VM

#2929 Replace old test BIFs w/o is_ prefix in documentation code examples
  lib/tools/doc/src/fprof.xml
  system/doc/programming_examples/list_comprehensions.xml
  system/doc/programming_examples/records.xml
Labels: enhancement, team:VM, testing

#2949 shell history: allow configurable history module
  lib/kernel/doc/src/kernel_app.xml
  lib/kernel/src/group_history.erl
  lib/kernel/test/interactive_shell_SUITE.erl
Labels: feature, team:VM, testing

#2958 Typo on https://erlang.org/doc/oam/oam_intro.html#snmp-based-oam
  system/doc/oam/oam_intro.xml
Labels: team:PS

#2944 Detect repeated occurrences of the stacktrace variable in a try clause
  lib/compiler/test/trycatch_SUITE.erl
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/src/erl_parse.yrl
  lib/stdlib/test/erl_lint_SUITE.erl
Labels: fix, team:VM

#2969 Eliminate dialyzer crashing when analyzing try/catch
  lib/dialyzer/src/dialyzer_dataflow.erl
  lib/dialyzer/test/small_SUITE_data/results/try2
  lib/dialyzer/test/small_SUITE_data/src/try2.erl
Labels: fix, team:VM, testing

#2872 Add -Werror to github actions C/C++ compilation
  .github/dockerfiles/Dockerfile.32-bit
  .github/dockerfiles/Dockerfile.64-bit
  .github/dockerfiles/Dockerfile.cross-compile
  .github/dockerfiles/Dockerfile.ubuntu-base
  .github/scripts/init-pre-release.sh
  .github/workflows/main.yaml
  erts/configure.in
  erts/emulator/Makefile.in
  erts/emulator/beam/jit/beam_asm.hpp
  erts/emulator/beam/packet_parser.c
  erts/emulator/beam/sys.h
  erts/emulator/drivers/common/inet_drv.c
  erts/emulator/nifs/common/prim_socket_nif.c
  erts/emulator/nifs/common/socket_int.h
  erts/emulator/nifs/common/socket_util.c
  erts/emulator/nifs/common/socket_util.h
  lib/crypto/c_src/crypto_callback.c
  lib/odbc/c_src/odbcserver.c
  lib/wx/configure.in
Labels: fix, team:VM

#2885 logger: Make logger_simple print pretty reports
  erts/preloaded/src/init.erl
  lib/kernel/src/logger_simple_h.erl
Labels: fix, team:VM, testing

#2957 Document how to build for Android with OpenSSL linked statically
  HOWTO/INSTALL-ANDROID.md
Labels: team:PS

#2970 erts: Fix file write error check on windows
  erts/emulator/nifs/win32/win_prim_file.c
Labels: fix, team:VM, testing

#2940 Use maps:from_keys/2 and heuristics in new sets
  lib/stdlib/src/sets.erl
Labels: team:VM, testing

#2922 erts: Support cgroup2 CPU quotas
  erts/lib_src/common/erl_misc_utils.c
Labels: team:VM, testing

#2924 kernel: Remove pg2
  bootstrap/lib/stdlib/ebin/otp_internal.beam
  lib/kernel/doc/src/Makefile
  lib/kernel/doc/src/disk_log.xml
  lib/kernel/doc/src/global.xml
  lib/kernel/doc/src/kernel_app.xml
  lib/kernel/doc/src/notes.xml
  lib/kernel/doc/src/pg.xml
  lib/kernel/doc/src/pg2.xml
  lib/kernel/doc/src/ref_man.xml
  lib/kernel/doc/src/specs.xml
  lib/kernel/src/kernel.app.src
  lib/kernel/src/kernel.erl
  lib/kernel/src/pg2.erl
  lib/kernel/test/Makefile
  lib/kernel/test/pg2_SUITE.erl
  lib/stdlib/src/otp_internal.erl
  system/doc/general_info/DEPRECATIONS
  system/doc/general_info/deprecations_23.inc
  system/doc/general_info/scheduled_for_removal_24.inc
Labels: team:VM

#2959 inet_res: fix dns compression encoder for large responses
  lib/kernel/src/inet_dns.erl
  lib/kernel/test/inet_res_SUITE.erl
Labels: team:PS

#2974 os: Eliminate wrappers for BIFs
  bootstrap/lib/kernel/ebin/os.beam
  erts/emulator/beam/bif.tab
  erts/emulator/beam/erl_bif_os.c
  erts/preloaded/ebin/prim_socket.beam
  erts/preloaded/src/prim_socket.erl
  lib/kernel/src/os.erl
Labels: enhancement, team:VM, testing

#2975 compiler: Remove cerl_sets module
  lib/compiler/src/Makefile
  lib/compiler/src/beam_asm.erl
  lib/compiler/src/beam_clean.erl
  lib/compiler/src/beam_digraph.erl
  lib/compiler/src/beam_jump.erl
  lib/compiler/src/beam_ssa.erl
  lib/compiler/src/beam_ssa_bool.erl
  lib/compiler/src/beam_ssa_dead.erl
  lib/compiler/src/beam_ssa_funs.erl
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/beam_ssa_pre_codegen.erl
  lib/compiler/src/beam_ssa_throw.erl
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/src/beam_trim.erl
  lib/compiler/src/beam_validator.erl
  lib/compiler/src/cerl_sets.erl
  lib/compiler/src/compile.erl
  lib/compiler/src/compiler.app.src
  lib/compiler/src/sys_core_alias.erl
  lib/compiler/src/sys_core_fold.erl
  lib/compiler/src/v3_core.erl
  lib/compiler/src/v3_kernel.erl
Labels: enhancement, team:VM, testing

#2916 Implement early_data for TLS clients
  lib/ssl/doc/src/ssl.xml
  lib/ssl/doc/src/standards_compliance.xml
  lib/ssl/doc/src/using_ssl.xml
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_cipher.erl
  lib/ssl/src/ssl_connection.hrl
  lib/ssl/src/ssl_gen_statem.erl
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/src/ssl_internal.hrl
  lib/ssl/src/ssl_logger.erl
  lib/ssl/src/ssl_record.erl
  lib/ssl/src/tls_client_ticket_store.erl
  lib/ssl/src/tls_connection_1_3.erl
  lib/ssl/src/tls_handshake_1_3.erl
  lib/ssl/src/tls_handshake_1_3.hrl
  lib/ssl/src/tls_v1.erl
  lib/ssl/test/openssl_session_ticket_SUITE.erl
  lib/ssl/test/ssl_api_SUITE.erl
  lib/ssl/test/ssl_test_lib.erl
  lib/ssl/test/tls_1_3_record_SUITE.erl
Labels: team:PS

#2978 Clarify and simplify documentation for the os module
  lib/kernel/doc/src/os.xml
Labels: enhancement, team:VM, testing

#2973 Add extended error information for the remaining BIFs in STDLIB
  erts/emulator/beam/atom.names
  erts/emulator/beam/beam_common.c
  erts/emulator/beam/erl_bif_re.c
  erts/emulator/test/atomics_SUITE.erl
  erts/emulator/test/counters_SUITE.erl
  lib/stdlib/src/binary.erl
  lib/stdlib/src/erl_stdlib_errors.erl
  lib/stdlib/src/maps.erl
  lib/stdlib/src/re.erl
  lib/stdlib/src/unicode.erl
  lib/stdlib/test/Makefile
  lib/stdlib/test/binary_module_SUITE.erl
  lib/stdlib/test/error_info_lib.erl
  lib/stdlib/test/lists_SUITE.erl
  lib/stdlib/test/maps_SUITE.erl
  lib/stdlib/test/math_SUITE.erl
  lib/stdlib/test/re_SUITE.erl
  lib/stdlib/test/unicode_SUITE.erl
Labels: enhancement, team:VM

#2976 Bring HOWTO/BENCHMARKS.md formatting to modern markdown
  HOWTO/BENCHMARKS.md
Labels: team:VM

#2882 Fix appup removal order
  lib/common_test/src/test_server_node.erl
  lib/sasl/src/systools_relup.erl
  lib/sasl/test/systools_SUITE.erl
  lib/sasl/test/systools_SUITE_data/d_replace_app/lib/db-1.0/ebin/db.app
  lib/sasl/test/systools_SUITE_data/d_replace_app/lib/db-1.0/src/db1.erl
  lib/sasl/test/systools_SUITE_data/d_replace_app/lib/db-1.0/src/db2.erl
  lib/sasl/test/systools_SUITE_data/d_replace_app/lib/db-1.1/ebin/db.app
  lib/sasl/test/systools_SUITE_data/d_replace_app/lib/db-1.1/ebin/db.appup
  lib/sasl/test/systools_SUITE_data/d_replace_app/lib/db-1.1/src/db1.erl
  lib/sasl/test/systools_SUITE_data/d_replace_app/lib/db-1.1/src/db2.erl
  lib/sasl/test/systools_SUITE_data/d_replace_app/lib/fe-2.1/ebin/fe.app
  lib/sasl/test/systools_SUITE_data/d_replace_app/lib/fe-2.1/src/fe1.erl
  lib/sasl/test/systools_SUITE_data/d_replace_app/lib/fe-2.1/src/fe2.erl
  lib/sasl/test/systools_SUITE_data/d_replace_app/lib/fe-2.1/src/fe3.erl
  lib/sasl/test/systools_SUITE_data/d_replace_app/lib/gh-1.0/ebin/gh.app
  lib/sasl/test/systools_SUITE_data/d_replace_app/lib/gh-1.0/src/gh1.erl
Labels: fix, team:VM

#2972 crypto: disable EVP usage also for openssl-1.0.2
  lib/crypto/c_src/openssl_config.h
Labels: team:PS

#2933 tls_connection: spread RAM/CPU spike induced by flow control
  lib/ssl/src/tls_connection.erl
  lib/ssl/src/tls_connection_1_3.erl
Labels: team:PS, testing

#2953 Refine Mnesia guide Chapter 1
  lib/mnesia/doc/src/Mnesia_chap1.xml
  lib/mnesia/info
  system/doc/system_architecture_intro/sys_arch_intro.xml
Labels: team:PS

#2825 filter makedep_side_effect
  lib/stdlib/src/erl_abstract_code.erl
  lib/stdlib/test/beam_lib_SUITE.erl
Labels: fix, team:VM, testing

#2980 Add extended error information for the os module
  erts/emulator/beam/erl_bif_os.c
  lib/kernel/src/erl_kernel_errors.erl
  lib/kernel/src/os.erl
  lib/kernel/test/Makefile
  lib/kernel/test/error_info_lib.erl
  lib/kernel/test/os_SUITE.erl
Labels: enhancement, team:VM, testing

#2983 io_lib_format:fwrite_g/1 benchmarks
  lib/stdlib/test/stdlib_bench_SUITE.erl
Labels: enhancement, team:VM, testing

#2991 Allow h4,h5 and h6 headers in application/erlang+html EEP-48 documentation
  lib/erl_docgen/doc/src/doc_storage.xml
  lib/erl_docgen/src/docgen_xml_to_chunk.erl
  lib/kernel/doc/src/application.xml
  lib/stdlib/doc/src/array.xml
  lib/stdlib/doc/src/shell_docs.xml
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/src/shell_docs.erl
  lib/stdlib/test/shell_docs_SUITE.erl
Labels: enhancement, team:VM

#2986 More security recommendations in binary_to_term/2 docs
  erts/doc/src/erlang.xml
Labels: enhancement, team:VM

#2998 httpd: Fix typos
  lib/inets/doc/src/httpd.xml
Labels: team:PS

#2956 gen: init_it given atom as parent PID
  lib/stdlib/src/gen.erl
Labels: team:VM, testing

#2977 wxNotificationMessage support
  lib/wx/api_gen/interface/wx/notifmsg.h
  lib/wx/api_gen/wx_gen_cpp.erl
  lib/wx/api_gen/wx_gen_nif.erl
  lib/wx/api_gen/wxapi.conf
  lib/wx/c_src/gen/wxe_derived_dest.h
  lib/wx/c_src/gen/wxe_events.cpp
  lib/wx/c_src/gen/wxe_func_table.cpp
  lib/wx/c_src/gen/wxe_init.cpp
  lib/wx/c_src/gen/wxe_macros.h
  lib/wx/c_src/gen/wxe_wrapper_1.cpp
  lib/wx/c_src/gen/wxe_wrapper_2.cpp
  lib/wx/c_src/gen/wxe_wrapper_3.cpp
  lib/wx/c_src/gen/wxe_wrapper_4.cpp
  lib/wx/c_src/gen/wxe_wrapper_5.cpp
  lib/wx/c_src/gen/wxe_wrapper_6.cpp
  lib/wx/c_src/gen/wxe_wrapper_7.cpp
  lib/wx/c_src/gen/wxe_wrapper_8.cpp
  lib/wx/doc/src/wxNotificationMessage.xml
  lib/wx/examples/demo/Makefile
  lib/wx/examples/demo/ex_notificationMessage.erl
  lib/wx/include/wx.hrl
  lib/wx/src/gen/wxCommandEvent.erl
  lib/wx/src/gen/wxNotificationMessage.erl
  lib/wx/src/gen/wxe_funcs.hrl
Labels: team:PS, testing

#3004 beam_validator: Ignore 'fcheckerror' / 'fclearerror'
  lib/compiler/src/beam_validator.erl
  lib/compiler/test/beam_validator_SUITE.erl
  lib/compiler/test/beam_validator_SUITE_data/freg_state.S
  lib/compiler/test/float_SUITE.erl
Labels: team:VM, testing

#2999 erts: Stop using MADV_DONTNEED when MADV_FREE is unavailable
  erts/emulator/sys/common/erl_mmap.h
Labels: team:VM, testing

#2988 Implement handling of early data in ssl server
  lib/ssl/doc/src/ssl_app.xml
  lib/ssl/doc/src/standards_compliance.xml
  lib/ssl/doc/src/using_ssl.xml
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_config.erl
  lib/ssl/src/ssl_gen_statem.erl
  lib/ssl/src/ssl_internal.hrl
  lib/ssl/src/ssl_record.erl
  lib/ssl/src/ssl_record.hrl
  lib/ssl/src/tls_connection_1_3.erl
  lib/ssl/src/tls_gen_connection.erl
  lib/ssl/src/tls_handshake_1_3.erl
  lib/ssl/src/tls_record.erl
  lib/ssl/src/tls_record_1_3.erl
  lib/ssl/src/tls_server_session_ticket.erl
  lib/ssl/src/tls_socket.erl
  lib/ssl/test/openssl_session_ticket_SUITE.erl
  lib/ssl/test/ssl_api_SUITE.erl
  lib/ssl/test/ssl_session_ticket_SUITE.erl
  lib/ssl/test/ssl_test_lib.erl
  lib/ssl/test/tls_1_3_record_SUITE.erl
Labels: team:PS, testing

#2997 Fix cover bug when there is an export named clauses
  lib/tools/src/cover.erl
  lib/tools/test/cover_SUITE.erl
Labels: fix, team:VM, testing

#2674 EDoc: Allow user defined macros to be functions
  lib/edoc/src/edoc_macros.erl
Labels: team:VM, waiting
