Repository erlang/otp, pull requests merged in 2022-07, with the labels that each got.

#6108 Allow the timezone part of the string to contain only an hour
  lib/stdlib/doc/src/calendar.xml
  lib/stdlib/src/calendar.erl
  lib/stdlib/test/calendar_SUITE.erl
Labels: team:VM, enhancement, testing

#6115 JIT: Improve code generation for the is_ge instruction
  erts/emulator/beam/jit/arm/beam_asm.hpp
  erts/emulator/beam/jit/arm/instr_common.cpp
  erts/emulator/beam/jit/arm/ops.tab
  erts/emulator/beam/jit/x86/instr_common.cpp
  erts/emulator/beam/jit/x86/ops.tab
  erts/emulator/test/op_SUITE.erl
Labels: team:VM, enhancement, testing

#6120 Slightly improve the compiler's type analysis and optimisations
  lib/compiler/src/beam_bounds.erl
  lib/compiler/src/beam_call_types.erl
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/test/beam_bounds_SUITE.erl
  lib/compiler/test/beam_type_SUITE.erl
Labels: team:VM, enhancement, testing

#6110 inets: Add a helper function for client ssl connections
  lib/inets/doc/src/http_client.xml
  lib/inets/doc/src/httpc.xml
  lib/inets/src/http_client/httpc.erl
  lib/inets/src/inets_app/inets.app.src
  lib/inets/test/httpc_SUITE.erl
Labels: team:PS, testing

#6124 Specify in docs that the beam uses 64-bit floats
  system/doc/reference_manual/data_types.xml
Labels: team:VM

#6131 kernel: Fix gen_tcp:connect spec
  lib/kernel/src/gen_tcp.erl
Labels: team:VM, testing, bug

#6130 compiler: Add missing bs_create_bin prim_op() to type definition
  lib/compiler/src/beam_ssa.erl
Labels: team:VM, fix, testing

#6137 Fix links in Install guide to work with patch releases
  HOWTO/INSTALL.md
Labels: team:VM, documentation, bug

#6118 peer: Add detached and post_process_args
  erts/etc/common/erlexec.c
  lib/common_test/src/test_server.erl
  lib/kernel/src/user_sup.erl
  lib/stdlib/doc/src/peer.xml
  lib/stdlib/src/peer.erl
  lib/stdlib/test/peer_SUITE.erl
Labels: team:VM, enhancement

#6140 Optimize and extend GH actions testing
  .github/dockerfiles/Dockerfile.64-bit
  .github/dockerfiles/Dockerfile.ubuntu-base
  .github/dockerfiles/init.sh
  .github/scripts/base-tag
  .github/scripts/build-base-image.sh
  .github/scripts/restore-otp-image.sh
  .github/workflows/main.yaml
  .github/workflows/update-base.yaml
  lib/common_test/src/test_server_node.erl
Labels: team:VM, enhancement

#6133 Yielding adjustments of large message queues
  erts/emulator/beam/atom.names
  erts/emulator/beam/beam_bif_load.c
  erts/emulator/beam/bif.c
  erts/emulator/beam/bif.h
  erts/emulator/beam/erl_alloc.types
  erts/emulator/beam/erl_bif_info.c
  erts/emulator/beam/erl_bif_port.c
  erts/emulator/beam/erl_message.c
  erts/emulator/beam/erl_message.h
  erts/emulator/beam/erl_proc_sig_queue.c
  erts/emulator/beam/erl_proc_sig_queue.h
  erts/emulator/beam/erl_process.c
  erts/emulator/beam/erl_process.h
  erts/emulator/beam/erl_process_dump.c
  erts/emulator/beam/global.h
  erts/emulator/test/bif_SUITE.erl
  erts/emulator/test/literal_area_collector_test.erl
  erts/emulator/test/nif_SUITE.erl
  erts/emulator/test/port_SUITE.erl
  erts/emulator/test/process_SUITE.erl
  erts/emulator/test/signal_SUITE.erl
  erts/etc/unix/etp-commands.in
  erts/preloaded/ebin/erts_literal_area_collector.beam
  erts/preloaded/src/erts_literal_area_collector.erl
Labels: team:VM, enhancement, testing

#6114 Fix distributed spawn_request() bug
  erts/emulator/beam/dist.c
  erts/emulator/beam/erl_node_tables.c
  erts/emulator/beam/erl_proc_sig_queue.c
  erts/emulator/beam/erl_proc_sig_queue.h
  erts/emulator/beam/erl_process.c
  erts/emulator/test/process_SUITE.erl
Labels: team:VM, fix, testing

#6150 Unlink issues
  erts/emulator/beam/erl_proc_sig_queue.c
  erts/emulator/beam/erl_process.c
  erts/emulator/beam/io.c
  erts/emulator/test/process_SUITE.erl
  erts/emulator/test/signal_SUITE.erl
Labels: team:VM, fix, testing

#6135 Fix reds counting in execute_sys_tasks()/cleanup_sys_tasks()
  erts/emulator/beam/erl_process.c
Labels: team:VM, fix, testing

#6134 Fix process_info(Pid, message_queue_len) on other process
  erts/emulator/beam/erl_bif_info.c
  erts/emulator/test/process_SUITE.erl
Labels: team:VM, fix, testing

#6142 Fix permanent prio elevation at process termination
  erts/emulator/beam/erl_process.c
Labels: team:VM, fix, testing

#6019 ssl: Fix stateless ticket in_window comparison
  lib/ssl/doc/src/ssl.xml
  lib/ssl/doc/src/using_ssl.xml
  lib/ssl/src/tls_server_session_ticket.erl
  lib/ssl/test/ssl_session_ticket_SUITE.erl
  lib/ssl/test/tls_server_session_ticket_SUITE.erl
Labels: team:PS, testing, in progress

#6170 compiler: Add missing operations to beam_ssa:prim_op() type
  lib/compiler/src/beam_ssa.erl
Labels: team:VM, testing

#6148 inets: fix dialyzer warnings for inets/httd examples
  lib/inets/examples/httpd_load_test/hdlt_ctrl.erl
  lib/inets/examples/httpd_load_test/hdlt_slave.erl
  lib/ssh/src/ssh_sftp.erl
Labels: team:PS, testing

#6172 Eliminate compiler crash in beam_clean
  lib/compiler/src/beam_call_types.erl
  lib/compiler/test/beam_type_SUITE.erl
Labels: team:VM, testing

#6173 Fix crash in beam_ssa_bool
  lib/compiler/src/beam_ssa_bool.erl
  lib/compiler/test/guard_SUITE.erl
Labels: team:VM, fix, testing

#6168 Fix internal consistency error
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/test/float_SUITE.erl
Labels: team:VM, fix, testing

#6161 ssl: improve table checks ssl_pem_cache_SUITE
  lib/ssl/test/ssl_pem_cache_SUITE.erl
Labels: team:PS

#6182 ssl: internal doc and code comments for PEM, cert cache
  lib/ssl/internal_doc/pem_and_cert_cache.md
  lib/ssl/src/ssl_manager.erl
  lib/ssl/src/ssl_pem_cache.erl
  lib/ssl/test/ssl_pem_cache_SUITE.erl
Labels: team:PS, enhancement
