Repository erlang/otp, pull requests merged in 2022-11, with the labels that each got.

#6389 sasl: add error for duplicate atoms in app parameters
  lib/sasl/src/sasl.app.src
  lib/sasl/src/systools_make.erl
  lib/sasl/test/systools_SUITE.erl
Labels: team:VM, testing, bug

#6405 emulator: mtx_SUITE runtime limit scale on #no schedulers.
  erts/emulator/test/mtx_SUITE.erl
Labels: team:VM, testing, bug

#6407 erts: on windows \E[J does not work after we called break
  erts/emulator/beam/break.c
Labels: team:VM, testing, bug

#5831 stdlib: optimize gen_server by caching callback functions
  lib/stdlib/src/gen_server.erl
Labels: team:VM, testing

#6411 Eliminate compiler crash in the beam_ssa_type pass
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/test/bs_match_SUITE.erl
Labels: team:VM, fix, testing

#6417 compiler: Eliminate crash in the beam_ssa_bsm pass
  lib/compiler/src/beam_ssa_bsm.erl
  lib/compiler/test/bs_match_SUITE.erl
Labels: team:VM, fix, testing

#6404 Optimize encoding of utf8 segments in the binary syntax
  erts/emulator/beam/erl_bits.c
  erts/emulator/beam/erl_bits.h
  erts/emulator/beam/jit/arm/beam_asm.hpp
  erts/emulator/beam/jit/arm/beam_asm_global.hpp.pl
  erts/emulator/beam/jit/arm/instr_bs.cpp
  erts/emulator/beam/jit/x86/beam_asm.hpp
  erts/emulator/beam/jit/x86/beam_asm_global.hpp.pl
  erts/emulator/beam/jit/x86/instr_bs.cpp
  erts/emulator/test/bs_utf_SUITE.erl
Labels: team:VM, enhancement, testing

#6370 On-halt and delayed halt support for NIFs
  erts/doc/src/erl_nif.xml
  erts/doc/src/erlang.xml
  erts/emulator/beam/break.c
  erts/emulator/beam/erl_db.c
  erts/emulator/beam/erl_init.c
  erts/emulator/beam/erl_lock_check.c
  erts/emulator/beam/erl_nif.c
  erts/emulator/beam/erl_nif.h
  erts/emulator/beam/erl_nif_api_funcs.h
  erts/emulator/beam/erl_process.c
  erts/emulator/beam/erl_process.h
  erts/emulator/beam/global.h
  erts/emulator/beam/io.c
  erts/emulator/test/dirty_nif_SUITE.erl
  erts/emulator/test/dirty_nif_SUITE_data/Makefile.src
  erts/emulator/test/dirty_nif_SUITE_data/dirty_nif_SUITE.c
  erts/emulator/test/dirty_nif_SUITE_data/on_halt_a.c
  erts/emulator/test/dirty_nif_SUITE_data/on_halt_b.c
  erts/emulator/test/dirty_nif_SUITE_data/on_halt_c.c
  erts/emulator/test/dirty_nif_SUITE_data/on_halt_d.c
  erts/emulator/test/dirty_nif_SUITE_data/on_halt_e.c
  erts/emulator/test/dirty_nif_SUITE_data/on_halt_f.c
  erts/emulator/test/dirty_nif_SUITE_data/on_halt_nif.c
  erts/preloaded/src/erlang.erl
Labels: team:VM, enhancement, feature, testing

#6423 compiler: Eliminate crash in beam_ssa_type
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/test/beam_type_SUITE.erl
Labels: team:VM, fix, testing

#6377 [MnesiaTM] Lightweight method for obtaining an active mnesia transactions counters
  lib/mnesia/src/mnesia_tm.erl
  lib/mnesia/test/mnesia_trans_access_test.erl
Labels: team:PS, testing

#6429 Eliminate Dialyzer crash for ill-typed code
  lib/dialyzer/src/dialyzer_dataflow.erl
  lib/dialyzer/src/dialyzer_typesig.erl
  lib/dialyzer/test/small_SUITE_data/results/bs_fail_constr
  lib/dialyzer/test/small_SUITE_data/src/bs_fail_constr.erl
Labels: team:VM, fix, testing

#6431 compiler: Eliminate internal error in sub pass ssa_opt_bsm_shortcut
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/test/bs_match_SUITE.erl
Labels: team:VM, fix, testing

#6430 Eliminate internal error in sub pass ssa_opt_ranges
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/test/beam_type_SUITE.erl
Labels: team:VM, fix, testing

#6436 beam_types: Increment `#t_bitstring.size_unit` in decode
  lib/compiler/src/beam_types.erl
Labels: team:VM

#6401 dec_term: must use unsigned for BINARY_EXT size
  erts/emulator/beam/erl_binary.h
  erts/emulator/beam/external.c
  erts/emulator/test/binary_SUITE.erl
Labels: team:VM, fix, testing

#6447 beam_disasm: Fix bs_create_bin/6 resolution
  lib/compiler/src/beam_disasm.erl
Labels: team:VM, fix

#6442 emulator: scale limit in mtx_SUTIE for machines with many cores
  erts/emulator/test/mtx_SUITE.erl
Labels: team:VM, testing

#6441 dialyzer: Correct interpretation of [none()]
  lib/dialyzer/src/erl_types.erl
  lib/dialyzer/test/small_SUITE_data/results/stack
  lib/dialyzer/test/small_SUITE_data/src/list_none.erl
  lib/dialyzer/test/small_SUITE_data/src/stack.erl
Labels: team:VM, fix, testing

#6385 os_mon: allow check intervals smaller than 1 minute
  lib/os_mon/doc/src/disksup.xml
  lib/os_mon/src/disksup.erl
  lib/os_mon/test/disksup_SUITE.erl
Labels: team:VM, testing

#6384 Add support for `disksup:get_disk_info/[0,1]`
  lib/os_mon/doc/src/disksup.xml
  lib/os_mon/src/disksup.erl
  lib/os_mon/test/disksup_SUITE.erl
Labels: team:VM, feature, testing

#6456 Adjust documentation of erlang:module_loaded()
  erts/doc/src/erlang.xml
Labels: team:VM, enhancement, fix, testing, documentation

#6451 beam_disasm: Resolve commands for bs_match/3 instruction
  lib/compiler/src/beam_disasm.erl
Labels: team:VM

#6452 beam_disasm: Decode field flags
  lib/compiler/src/beam_disasm.erl
Labels: team:VM

#6446 logger_common_h: remove extraneous space in mode_change msg
  lib/kernel/src/logger_h_common.erl
Labels: team:VM

#6472 Eliminate crash in sub pass ssa_opt_bc_size
  lib/compiler/src/beam_ssa_bc_size.erl
  lib/compiler/test/bs_bincomp_SUITE.erl
Labels: team:VM, fix, testing

#6478 Eliminate infinite loop in the Erlang compiler
  lib/compiler/src/beam_ssa_bc_size.erl
  lib/compiler/test/compilation_SUITE_data/infinite_loop.erl
Labels: team:VM, enhancement, testing

#6450 beam_lib: Fix spec for all_chunks/1
  lib/stdlib/src/beam_lib.erl
Labels: team:VM, fix, testing

#6457 empty containers: more precise specs
  lib/stdlib/src/gb_sets.erl
  lib/stdlib/src/gb_trees.erl
  lib/stdlib/src/orddict.erl
  lib/stdlib/src/queue.erl
  lib/stdlib/src/sets.erl
Labels: team:VM, testing

#6471 Make list_to_atom reject all negative code points
  erts/emulator/beam/utils.c
  erts/emulator/test/bif_SUITE.erl
Labels: team:VM, fix, testing

#6310 wx: fix build issue when GL/glu.h is not present
  lib/wx/c_src/egl_impl.h
Labels: team:PS, testing

#6440 dec_term: avoid integer overflow for LIST_EXT
  erts/emulator/beam/external.c
Labels: team:VM, fix, testing

#6484 graceful shutdown of ssh_conection_handler when connection is closedv
  lib/ssh/src/ssh_connection_handler.erl
Labels: team:PS

#6391 ftp: add missing case nlist
  lib/ftp/src/ftp.erl
  lib/ftp/test/ftp_SUITE.erl
Labels: team:PS

#6483 Eliminate crash in dialyzer_typesig
  lib/dialyzer/src/dialyzer_typesig.erl
  lib/dialyzer/test/small_SUITE_data/results/bs_fail_constr
  lib/dialyzer/test/small_SUITE_data/src/bs_fail_constr.erl
Labels: team:VM, fix, testing

#6469 Fix mistranslations in beam_disasm
  lib/compiler/src/beam_disasm.erl
Labels: team:VM

#6489 Fix typo in code snippet for supervisor example
  system/doc/design_principles/sup_princ.xml
Labels: team:VM

#6464 ssl: add ssl_trace module
  lib/ssl/src/Makefile
  lib/ssl/src/ssl.app.src
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_gen_statem.erl
  lib/ssl/src/ssl_trace.erl
  lib/ssl/test/Makefile
  lib/ssl/test/ssl_test_lib.erl
  lib/ssl/test/ssl_trace_SUITE.erl
Labels: team:PS

#6482 Don't allow local calls from record init in guards
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/test/erl_lint_SUITE.erl
Labels: team:VM, fix, testing

#6479 Fix sending bug to infant process
  erts/emulator/beam/erl_process.c
  erts/emulator/test/process_SUITE.erl
Labels: team:VM, fix, testing

#6432 Improve pg_SUITE
  lib/kernel/test/pg_SUITE.erl
Labels: team:VM, enhancement, testing

#6434 [nif] Add support for UTF-8 in atom and string NIF functions.
  erts/doc/src/erl_nif.xml
  erts/emulator/beam/bif.c
  erts/emulator/beam/erl_nif.c
  erts/emulator/beam/erl_nif.h
  erts/emulator/beam/erl_nif_api_funcs.h
  erts/emulator/beam/global.h
  erts/emulator/beam/jit/beam_jit_common.cpp
  erts/emulator/beam/utils.c
  erts/emulator/test/nif_SUITE.erl
  erts/emulator/test/nif_SUITE_data/nif_SUITE.c
Labels: team:VM, enhancement, testing

#6408 Add new XML tag <change>
  erts/doc/src/erlang.xml
  lib/erl_docgen/priv/css/otp_doc.css
  lib/erl_docgen/priv/dtd/application.dtd
  lib/erl_docgen/priv/dtd/book.dtd
  lib/erl_docgen/priv/dtd/chapter.dtd
  lib/erl_docgen/priv/dtd/common.dtd
  lib/erl_docgen/priv/dtd/common.refs.dtd
  lib/erl_docgen/priv/dtd/part.dtd
  lib/erl_docgen/priv/xsl/db_html.xsl
  lib/erl_docgen/priv/xsl/db_man.xsl
  lib/erl_docgen/priv/xsl/db_pdf.xsl
  lib/erl_docgen/src/docgen_xml_to_chunk.erl
Labels: team:VM, enhancement, testing, documentation

#6420 ct: prevent documentation errors and ease maintenance
  lib/common_test/doc/src/ct.xml
  lib/common_test/src/ct.erl
Labels: team:PS, testing

#6512 Fix internal consistency failure
  lib/compiler/src/beam_ssa_pre_codegen.erl
  lib/compiler/test/bs_match_SUITE.erl
Labels: team:VM, fix, testing

#6502 Fix compiler crash when using a record as LC filter
  lib/stdlib/src/erl_expand_records.erl
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/test/erl_expand_records_SUITE.erl
Labels: team:VM, testing, bug

#6481 Refuse usage of SO_REUSEADDR on non-UDP sockets on Windows
  lib/kernel/doc/src/inet.xml
Labels: team:VM, team:PS, testing, bug

#6517 Fix compiler crash for named fun expression with convoluted scoping
  lib/compiler/src/v3_core.erl
  lib/compiler/test/fun_SUITE.erl
Labels: team:VM, fix, testing

#6503 Reject invalid use of caret notation
  lib/stdlib/src/erl_scan.erl
  lib/stdlib/test/erl_scan_SUITE.erl
  system/doc/reference_manual/data_types.xml
Labels: team:VM, enhancement, testing

#6449 Add missing type specs in http library and replace `essl` option by `ssl`
  lib/inets/doc/specs/.gitignore
  lib/inets/doc/src/Makefile
  lib/inets/doc/src/httpc.xml
  lib/inets/doc/src/httpd.xml
  lib/inets/doc/src/specs.xml
  lib/inets/src/http_client/httpc.erl
  lib/inets/src/http_lib/http_transport.erl
  lib/inets/src/http_server/httpd.erl
  lib/inets/src/http_server/httpd_conf.erl
  lib/inets/src/http_server/httpd_sup.erl
  lib/inets/test/httpc_SUITE.erl
  lib/inets/test/httpd_SUITE.erl
Labels: team:PS, testing

#6480 Kuba/ssl/hibernate tls sender/otp 18314
  lib/ssl/src/tls_gen_connection.erl
  lib/ssl/src/tls_sender.erl
  lib/ssl/test/ssl_api_SUITE.erl
  lib/ssl/test/ssl_test_lib.erl
Labels: team:PS

#6414 ssl: VerifyFun can now get the der cert as argument
  lib/ssl/doc/src/ssl.xml
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/test/ssl_cert_SUITE.erl
Labels: team:PS, stalled, testing

#6396 Fix open_port spawn with spaces in PATH on windows
  erts/emulator/sys/win32/sys.c
Labels: team:VM, fix, testing

#6521 Fix decode hashmap with unsorted smallmap as keys
  erts/emulator/beam/external.c
  erts/emulator/test/binary_SUITE.erl
Labels: team:VM, fix, testing
