Repository erlang/otp, pull requests merged in 2022-08, with the labels that each got.

#6107 Fix certificate_authorities misspelling
  lib/ssl/src/tls_handshake_1_3.erl
Labels: team:PS, testing

#6186 Correct bug in CSE optimization
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/test/map_SUITE.erl
Labels: team:VM, fix, testing

#6066 Option to skip SSH authentication for some niche cases
  lib/ssh/doc/src/ssh.xml
  lib/ssh/src/ssh.hrl
  lib/ssh/src/ssh_auth.erl
  lib/ssh/src/ssh_fsm_userauth_server.erl
  lib/ssh/src/ssh_options.erl
  lib/ssh/test/ssh_options_SUITE.erl
Labels: team:PS, enhancement, testing, in progress

#6187 ssl: increase pem cache interval for problematic test case
  lib/ssl/test/ssl_pem_cache_SUITE.erl
Labels: team:PS

#6126 Dialyzer: Fix checking of behaviours
  lib/dialyzer/src/dialyzer.erl
  lib/dialyzer/src/dialyzer_behaviours.erl
  lib/dialyzer/test/behaviour_SUITE_data/results/gen_server_not_exported
  lib/dialyzer/test/behaviour_SUITE_data/src/gen_server_not_exported.erl
Labels: team:VM, fix, testing

#6190 Eliminate crash in beam_ssa_bool
  lib/compiler/src/beam_ssa_bool.erl
  lib/compiler/test/guard_SUITE.erl
Labels: team:VM, fix, testing

#6178 Enhance creation of maps with literal keys
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/cerl.erl
  lib/compiler/test/map_SUITE.erl
Labels: team:VM, enhancement, testing

#6177 Optimize comparison of equal terms
  erts/emulator/beam/beam_common.c
  erts/emulator/beam/erl_map.c
  erts/emulator/beam/jit/arm/instr_common.cpp
  erts/emulator/beam/jit/x86/instr_common.cpp
Labels: team:VM, enhancement, testing

#5997 dialyzer: Add incremental analysis mode
  lib/dialyzer/README
  lib/dialyzer/doc/src/dialyzer.xml
  lib/dialyzer/src/Makefile
  lib/dialyzer/src/dialyzer.app.src
  lib/dialyzer/src/dialyzer.erl
  lib/dialyzer/src/dialyzer.hrl
  lib/dialyzer/src/dialyzer_analysis_callgraph.erl
  lib/dialyzer/src/dialyzer_callgraph.erl
  lib/dialyzer/src/dialyzer_cl.erl
  lib/dialyzer/src/dialyzer_cl_parse.erl
  lib/dialyzer/src/dialyzer_contracts.erl
  lib/dialyzer/src/dialyzer_coordinator.erl
  lib/dialyzer/src/dialyzer_cplt.erl
  lib/dialyzer/src/dialyzer_gui_wx.erl
  lib/dialyzer/src/dialyzer_incremental.erl
  lib/dialyzer/src/dialyzer_iplt.erl
  lib/dialyzer/src/dialyzer_options.erl
  lib/dialyzer/src/dialyzer_plt.erl
  lib/dialyzer/src/dialyzer_succ_typings.erl
  lib/dialyzer/src/dialyzer_utils.erl
  lib/dialyzer/src/dialyzer_worker.erl
  lib/dialyzer/src/erl_types.erl
  lib/dialyzer/src/typer.erl
  lib/dialyzer/src/typer_core.erl
  lib/dialyzer/test/Makefile
  lib/dialyzer/test/cplt_SUITE.erl
  lib/dialyzer/test/cplt_SUITE_data/type_deps.erl
  lib/dialyzer/test/dialyzer_SUITE.erl
  lib/dialyzer/test/dialyzer_common.erl
  lib/dialyzer/test/incremental_SUITE.erl
  lib/dialyzer/test/incremental_SUITE_data/fix.erl
  lib/dialyzer/test/incremental_SUITE_data/got_fixed.erl
  lib/dialyzer/test/incremental_SUITE_data/m1.erl
  lib/dialyzer/test/incremental_SUITE_data/m2.erl
  lib/dialyzer/test/incremental_SUITE_data/m3.erl
  lib/dialyzer/test/incremental_SUITE_data/m4.erl
  lib/dialyzer/test/incremental_SUITE_data/m5.erl
  lib/dialyzer/test/incremental_SUITE_data/m6.erl
  lib/dialyzer/test/iplt_SUITE.erl
  lib/dialyzer/test/iplt_SUITE_data/type_deps.erl
  lib/dialyzer/test/opaque_SUITE_data/src/recrec/dialyzer.hrl
  lib/dialyzer/test/options2_SUITE_data/results/unknown_function
  lib/dialyzer/test/options2_SUITE_data/src/unknown_function.erl
  lib/dialyzer/test/typer_SUITE.erl
Labels: team:VM, testing

#6189 Eliminate internal consistency failure
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/src/beam_types.erl
  lib/compiler/test/beam_type_SUITE.erl
Labels: team:VM, fix, testing

#6193 compiler: Start all potential nif functions with a nif_start
  lib/compiler/src/v3_core.erl
  lib/compiler/test/core_SUITE.erl
  lib/compiler/test/core_SUITE_data/nif.erl
Labels: team:VM, testing

#6199 gen_event: eliminate selective-receive in fetch_msg/6
  lib/stdlib/src/gen_event.erl
Labels: team:VM, enhancement, testing, in progress

#6205 inets: Remove documentation of no longer supported callback
  lib/inets/doc/src/mod_esi.xml
Labels: team:PS, testing

#6194 Change SSH options in a running server
  lib/ssh/doc/src/ssh.xml
  lib/ssh/src/ssh.erl
  lib/ssh/src/ssh_options.erl
  lib/ssh/src/ssh_system_sup.erl
  lib/ssh/test/ssh_options_SUITE.erl
Labels: team:PS, feature, testing, in progress

#6196 crypto: Fix AES and Blowfish names for OpenSSL 3.0
  lib/crypto/c_src/cipher.c
Labels: team:PS, testing, in progress, bug

#6204 ssl: Enhance client certificate selection
  lib/ssl/src/tls_handshake_1_3.erl
  lib/ssl/test/ssl_cert_SUITE.erl
  lib/ssl/test/ssl_cert_tests.erl
Labels: team:PS, testing

#5996 fix(crl): insert the CRLs individually when an URI is provided
  lib/ssl/src/ssl_crl_cache.erl
  lib/ssl/src/ssl_pkix_db.erl
  lib/ssl/test/ssl_crl_SUITE.erl
Labels: team:PS, testing, in progress

#6167 otp: fix compilation - deprecated OpenSSL APIs
  lib/crypto/c_src/engine.c
  lib/crypto/c_src/info.c
  lib/crypto/c_src/otp_test_engine.c
Labels: team:PS, enhancement

#5881 Fix space and unicode characters in release/install path
  .github/dockerfiles/Dockerfile.64-bit
  .github/dockerfiles/Dockerfile.ubuntu-base
  .github/dockerfiles/init.sh
  .github/workflows/main.yaml
  HOWTO/DEVELOPMENT.md
  erts/emulator/Makefile.in
  erts/etc/common/ct_run.c
  lib/common_test/test_server/.gitignore
  lib/inets/test/inets_socketwrap_SUITE.erl
  lib/parsetools/test/leex_SUITE.erl
  lib/parsetools/test/yecc_SUITE.erl
  lib/sasl/test/Makefile
  lib/ssh/src/.gitignore
  lib/ssl/src/.gitignore
  make/doc.mk
  make/test_target_script.sh
  system/doc/design_principles/Makefile
  system/doc/efficiency_guide/Makefile
  system/doc/embedded/Makefile
  system/doc/general_info/Makefile
  system/doc/getting_started/Makefile
  system/doc/installation_guide/Makefile
  system/doc/oam/Makefile
  system/doc/programming_examples/Makefile
  system/doc/reference_manual/Makefile
  system/doc/system_architecture_intro/Makefile
  system/doc/system_principles/Makefile
  system/doc/top/Makefile
  system/doc/top/src/erl_html_tools.erl
  system/doc/tutorial/Makefile
Labels: team:VM, enhancement, testing

#5878 kernel: Reject .app files with invalid parameters
  lib/kernel/src/application_controller.erl
  lib/kernel/test/application_SUITE.erl
Labels: team:VM, bug

#6143 Add dbg:tracer(file, Filename)
  lib/runtime_tools/doc/src/dbg.xml
  lib/runtime_tools/src/dbg.erl
  lib/runtime_tools/test/dbg_SUITE.erl
Labels: team:VM, feature

#6206 dialyzer: Parallelise hashing of source files
  lib/dialyzer/src/dialyzer_iplt.erl
  lib/dialyzer/src/dialyzer_utils.erl
  lib/dialyzer/test/Makefile
  lib/dialyzer/test/dialyzer_utils_SUITE.erl
Labels: team:VM, enhancement, testing

#6207 dialyzer: Fix missing incremental analysis type option
  lib/dialyzer/src/dialyzer.hrl
  lib/dialyzer/test/opaque_SUITE_data/src/recrec/dialyzer.hrl
Labels: team:VM, fix, testing

#6208 dialyzer: Use more compression in incremental PLTs
  lib/dialyzer/src/dialyzer_iplt.erl
Labels: team:VM, testing

#6224 JIT: Correct code generation for huge match in binary tail
  erts/emulator/beam/jit/arm/beam_asm.hpp
  erts/emulator/beam/jit/arm/instr_bs.cpp
  erts/emulator/beam/jit/x86/instr_bs.cpp
  erts/emulator/test/bs_match_tail_SUITE.erl
Labels: team:VM, fix, testing

#6209 Fix monitor/3 BIF in noproc scenarios
  erts/emulator/beam/bif.c
  erts/emulator/beam/break.c
  erts/emulator/beam/erl_bif_info.c
  erts/emulator/beam/erl_monitor_link.c
  erts/emulator/beam/erl_monitor_link.h
  erts/emulator/beam/erl_proc_sig_queue.c
  erts/emulator/beam/erl_process.c
  erts/emulator/beam/global.h
  erts/emulator/test/monitor_SUITE.erl
Labels: team:VM, fix, testing

#6216 Fix deadlock caused by net_kernel:setopts(new, _)
  lib/kernel/src/net_kernel.erl
  lib/kernel/test/erl_distribution_SUITE.erl
Labels: team:VM, fix, testing

#6232 ets:lookup_element badarg for Pos
  lib/stdlib/doc/src/ets.xml
Labels: team:VM

#6230 JIT: Correct building of non-byte-sized little-endian segments
  erts/emulator/beam/jit/arm/instr_bs.cpp
  erts/emulator/beam/jit/x86/instr_bs.cpp
  erts/emulator/test/bs_construct_SUITE.erl
Labels: team:VM, fix, testing

#6099 observer_sys_wx.erl: fix grammar
  lib/observer/src/observer_sys_wx.erl
Labels: team:PS

#6121 Documentation about debugging NIFs & drivers
  erts/doc/src/erl_cmd.xml
  erts/doc/src/erl_nif.xml
  system/doc/tutorial/complex6.erl
  system/doc/tutorial/debugging.xml
  system/doc/tutorial/nif.xmlsrc
  system/doc/tutorial/part.xml
  system/doc/tutorial/xmlfiles.mk
Labels: team:VM, documentation

#6154 Specify encoding when running javadoc
  lib/jinterface/doc/src/Makefile
Labels: team:VM, fix, testing, documentation

#6225 Extend map_SUITE:t_map_compare for atom keys
  erts/emulator/test/map_SUITE.erl
Labels: team:VM, testing

#6231 Add timeout for an incoming ssh connection that does not open a channel after completed authentication
  lib/ssh/doc/src/Makefile
  lib/ssh/doc/src/hardening.xml
  lib/ssh/doc/src/ssh.xml
  lib/ssh/doc/src/ssh_timeouts.jpg
  lib/ssh/doc/src/ssh_timeouts.odp
  lib/ssh/src/ssh.hrl
  lib/ssh/src/ssh_connection_handler.erl
  lib/ssh/src/ssh_fsm_userauth_server.erl
  lib/ssh/src/ssh_options.erl
  lib/ssh/test/ssh_basic_SUITE.erl
Labels: team:PS, enhancement

#6238 Eliminate false warnings when using the inline_list_funcs option
  lib/compiler/src/sys_core_fold_lists.erl
  lib/compiler/test/warnings_SUITE.erl
Labels: team:VM, fix, testing

#6240 Ensure that is_binary(BigNum) does not return true
  erts/emulator/beam/jit/arm/instr_common.cpp
  erts/emulator/beam/jit/x86/instr_common.cpp
  erts/emulator/test/binary_SUITE.erl
Labels: team:VM, fix, testing

#6197 Regular expression replacement with a function
  lib/stdlib/doc/src/re.xml
  lib/stdlib/src/re.erl
  lib/stdlib/test/re_SUITE.erl
Labels: team:VM, testing

#6229 ct: Fix surefire without debug_info
  lib/common_test/src/cth_surefire.erl
Labels: team:VM, testing, bug

#6036 Fix `logger_formatter` about `msg` by making templates linear before split
  lib/kernel/src/logger_formatter.erl
  lib/kernel/test/logger_formatter_SUITE.erl
Labels: team:VM, testing, bug

#6250 gh: Test that FLAVOR=emu builds and installs
  .github/dockerfiles/Dockerfile.clang
  .github/workflows/main.yaml
Labels: team:VM

#6253 logger: Print to stderr if printing to stdout failed
  lib/kernel/src/logger_std_h.erl
Labels: team:VM

#6254 erts: Print string that failed to eval
  erts/preloaded/ebin/init.beam
  erts/preloaded/src/init.erl
Labels: team:VM, enhancement

#6212 kernel: Fix Logger filter removal if message format is atom or binary
  lib/kernel/src/logger_internal.hrl
  lib/kernel/test/logger_SUITE.erl
Labels: team:VM, testing, bug

#5936 reltool: Add option for selective beam stripping
  lib/reltool/doc/src/reltool.xml
  lib/reltool/src/reltool.app.src
  lib/reltool/src/reltool.hrl
  lib/reltool/src/reltool_server.erl
  lib/reltool/src/reltool_target.erl
  lib/stdlib/src/beam_lib.erl
Labels: team:VM, testing
