Repository erlang/otp, pull requests merged in 2022-09, with the labels that each got.

#5891 changes to fix erlang hung issue on IPv6 setup
  erts/emulator/drivers/common/inet_drv.c
Labels: team:PS, in progress

#6248 erts: Fix large read/writes on macOS
  erts/emulator/beam/erl_nif.c
  erts/emulator/nifs/unix/unix_prim_file.c
  lib/kernel/test/file_SUITE.erl
Labels: team:VM, testing, bug

#6259 Optimize binary matching for fixed-width segments
  .gitignore
  bootstrap/lib/compiler/ebin/compiler.appup
  erts/.gitignore
  erts/emulator/beam/atom.names
  erts/emulator/beam/emu/beam_emu.c
  erts/emulator/beam/emu/bs_instrs.tab
  erts/emulator/beam/emu/generators.tab
  erts/emulator/beam/emu/ops.tab
  erts/emulator/beam/jit/arm/beam_asm.hpp
  erts/emulator/beam/jit/arm/generators.tab
  erts/emulator/beam/jit/arm/instr_bs.cpp
  erts/emulator/beam/jit/arm/ops.tab
  erts/emulator/beam/jit/x86/beam_asm.hpp
  erts/emulator/beam/jit/x86/beam_asm_global.hpp.pl
  erts/emulator/beam/jit/x86/generators.tab
  erts/emulator/beam/jit/x86/instr_bs.cpp
  erts/emulator/beam/jit/x86/ops.tab
  erts/emulator/test/Makefile
  erts/emulator/test/bs_construct_SUITE.erl
  erts/emulator/test/bs_match_bin_SUITE.erl
  erts/emulator/test/bs_match_int_SUITE.erl
  erts/emulator/utils/beam_makeops
  lib/compiler/src/beam_asm.erl
  lib/compiler/src/beam_disasm.erl
  lib/compiler/src/beam_jump.erl
  lib/compiler/src/beam_ssa.erl
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/beam_ssa_pre_codegen.erl
  lib/compiler/src/beam_utils.erl
  lib/compiler/src/beam_validator.erl
  lib/compiler/src/compile.erl
  lib/compiler/src/genop.tab
  lib/compiler/test/Makefile
  lib/compiler/test/bs_bincomp_SUITE.erl
  lib/compiler/test/bs_construct_SUITE.erl
  lib/compiler/test/bs_match_SUITE.erl
  lib/compiler/test/bs_utf_SUITE.erl
  lib/compiler/test/compile_SUITE.erl
  lib/compiler/test/test_lib.erl
Labels: team:VM, enhancement, testing

#6267 Inline creation of small maps with literal keys
  erts/emulator/beam/jit/arm/beam_asm_global.hpp.pl
  erts/emulator/beam/jit/arm/instr_map.cpp
  erts/emulator/beam/jit/x86/beam_asm.hpp
  erts/emulator/beam/jit/x86/beam_asm_global.hpp.pl
  erts/emulator/beam/jit/x86/instr_map.cpp
Labels: team:VM, enhancement, testing

#6274 base64: Optimize encoding and decoding of binaries
  lib/stdlib/src/base64.erl
Labels: team:VM, enhancement, testing

#6157 eunit: exact execution option
  lib/eunit/src/eunit.erl
  lib/eunit/src/eunit_data.erl
  lib/eunit/src/eunit_internal.hrl
  lib/eunit/src/eunit_proc.erl
  lib/eunit/src/eunit_server.erl
  lib/eunit/test/Makefile
  lib/eunit/test/eunit_SUITE.erl
  lib/eunit/test/eunit_test_listener.erl
Labels: team:PS, in progress

#6278 Eliminate another crash when optimization passes are disabled
  lib/compiler/src/beam_block.erl
  lib/compiler/test/map_SUITE.erl
Labels: team:VM, fix, testing

#6249 ssl: Correct middle_box negotiation
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_handshake.hrl
  lib/ssl/src/ssl_session.erl
  lib/ssl/src/tls_connection.erl
  lib/ssl/src/tls_connection_1_3.erl
  lib/ssl/src/tls_dtls_connection.erl
  lib/ssl/src/tls_handshake_1_3.erl
  lib/ssl/test/tls_1_3_version_SUITE.erl
Labels: team:PS, testing

#6269 Fix typo of min/max for +Q option
  erts/emulator/beam/erl_init.c
Labels: team:VM, fix, testing

#6270 ssl: Avoid partial connection trees
  lib/ssl/src/tls_gen_connection.erl
  lib/ssl/test/ssl_api_SUITE.erl
  lib/ssl/test/ssl_basic_SUITE.erl
Labels: team:PS, testing

#6243 dialyzer: Fix unsound behaviour subtype checks
  lib/dialyzer/src/dialyzer.erl
  lib/dialyzer/src/dialyzer_behaviours.erl
  lib/dialyzer/test/behaviour_SUITE_data/results/callbacks_and_specs
  lib/dialyzer/test/behaviour_SUITE_data/results/gen_server_incorrect_args
  lib/dialyzer/test/behaviour_SUITE_data/results/otp_6221
  lib/dialyzer/test/behaviour_SUITE_data/results/sample_behaviour
  lib/dialyzer/test/behaviour_SUITE_data/results/sample_behaviour_old
  lib/dialyzer/test/behaviour_SUITE_data/src/callbacks_and_specs/my_callbacks_wrong.erl
  lib/dialyzer/test/behaviour_SUITE_data/src/otp_6221/my_behaviour.erl
  lib/dialyzer/test/behaviour_SUITE_data/src/otp_6221/my_callbacks_correct.erl
  lib/dialyzer/test/indent_SUITE_data/results/callbacks_and_specs
  lib/dialyzer/test/indent_SUITE_data/results/sample_behaviour
  lib/dialyzer/test/indent_SUITE_data/src/callbacks_and_specs/my_callbacks_wrong.erl
  lib/dialyzer/test/small_SUITE_data/results/behaviour_info
Labels: team:VM, testing, team:PO

#6271 dialyzer: Improve error messages for invalid specs
  lib/dialyzer/src/dialyzer.erl
  lib/dialyzer/src/dialyzer_contracts.erl
  lib/dialyzer/test/cplt_SUITE.erl
  lib/dialyzer/test/dialyzer_common.erl
  lib/dialyzer/test/incremental_SUITE.erl
  lib/dialyzer/test/indent_SUITE_data/results/contracts_with_subtypes
  lib/dialyzer/test/indent_SUITE_data/results/record_update
  lib/dialyzer/test/indent_SUITE_data/results/simple
  lib/dialyzer/test/iplt_SUITE.erl
  lib/dialyzer/test/map_SUITE_data/results/contract_violation
  lib/dialyzer/test/map_SUITE_data/results/opaque_key
  lib/dialyzer/test/opaque_SUITE_data/results/int
  lib/dialyzer/test/opaque_SUITE_data/results/multiple_wrong_opaques
  lib/dialyzer/test/opaque_SUITE_data/results/para
  lib/dialyzer/test/opaque_SUITE_data/results/simple
  lib/dialyzer/test/small_SUITE_data/results/binary_nonempty
  lib/dialyzer/test/small_SUITE_data/results/binary_redef2
  lib/dialyzer/test/small_SUITE_data/results/chars
  lib/dialyzer/test/small_SUITE_data/results/contract5
  lib/dialyzer/test/small_SUITE_data/results/contracts_with_subtypes
  lib/dialyzer/test/small_SUITE_data/results/empty_list_infimum
  lib/dialyzer/test/small_SUITE_data/results/invalid_spec_2
  lib/dialyzer/test/small_SUITE_data/results/invalid_specs
  lib/dialyzer/test/small_SUITE_data/results/maps_sum
  lib/dialyzer/test/small_SUITE_data/results/predef
  lib/dialyzer/test/small_SUITE_data/results/record_update
  lib/dialyzer/test/small_SUITE_data/results/tuple_set_crash
  lib/dialyzer/test/small_SUITE_data/results/types_arity
Labels: team:VM, enhancement, testing

#6264 Disconnect of a node from a cluster of global nodes
  lib/kernel/doc/src/global.xml
  lib/kernel/src/global.erl
  lib/kernel/src/net_kernel.erl
  lib/kernel/test/global_SUITE.erl
  lib/kernel/test/global_group_SUITE.erl
Labels: team:VM, enhancement, fix, testing

#6288 option for customizing test nodename with variable
  make/test_target_script.sh
Labels: team:PS

#6287 ssl: adjust cacertfile option
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_manager.erl
  lib/ssl/src/ssl_pem_cache.erl
  lib/ssl/src/ssl_pkix_db.erl
  lib/ssl/test/ssl_pem_cache_SUITE.erl
Labels: team:PS

#6276 ssl: ssl_pem_cache_SUITE test cuddle
  lib/ssl/test/ssl_pem_cache_SUITE.erl
Labels: team:PS

#6258 Fix DistEntry corruption at node shutdown
  erts/emulator/beam/dist.c
Labels: team:VM, fix, testing

#6284 Fix port communication with win32sysinfo.exe
  lib/os_mon/c_src/win32sysinfo.c
  lib/os_mon/src/os_mon_sysinfo.erl
Labels: team:VM, testing

#6227 kernel: invoke init:run_on_load_handlers/0 after code_server start
  lib/ssl/Makefile
  lib/ssl/src/inet_tls_dist.erl
  lib/ssl/test/ssl_dist_SUITE.erl
Labels: team:VM

#6280 Add selectable alphabets (standard vs urlsafe) to base64
  lib/stdlib/doc/src/base64.xml
  lib/stdlib/src/base64.erl
  lib/stdlib/test/base64_SUITE.erl
  lib/stdlib/test/base64_property_test_SUITE.erl
  lib/stdlib/test/property_test/base64_prop.erl
Labels: team:VM, feature, testing

#6298 JIT: Minor optimizations
  erts/emulator/beam/jit/arm/beam_asm.hpp
  erts/emulator/beam/jit/arm/beam_asm_module.cpp
  erts/emulator/beam/jit/arm/generators.tab
  erts/emulator/beam/jit/arm/instr_bif.cpp
  erts/emulator/beam/jit/arm/instr_bs.cpp
  erts/emulator/beam/jit/arm/ops.tab
  erts/emulator/beam/jit/x86/beam_asm.hpp
  erts/emulator/beam/jit/x86/beam_asm_module.cpp
  erts/emulator/beam/jit/x86/generators.tab
  erts/emulator/beam/jit/x86/instr_arith.cpp
  erts/emulator/beam/jit/x86/instr_bif.cpp
  erts/emulator/beam/jit/x86/instr_bs.cpp
  erts/emulator/beam/jit/x86/instr_fun.cpp
  erts/emulator/beam/jit/x86/instr_map.cpp
  erts/emulator/beam/jit/x86/ops.tab
Labels: team:VM, enhancement, testing

#5982 Add option to configure encryption seed for TLS 1.3 stateless tickets
  lib/ssl/doc/src/ssl.xml
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_internal.hrl
  lib/ssl/src/tls_server_session_ticket.erl
  lib/ssl/src/tls_socket.erl
  lib/ssl/test/ssl_api_SUITE.erl
  lib/ssl/test/ssl_session_ticket_SUITE.erl
Labels: team:PS, testing, in progress

#6314 ct: Don't use compile server for peer compilation
  lib/common_test/src/test_server.erl
Labels: team:VM, bug

#6316 jit: Fix erts_beamasm symbols
  erts/emulator/beam/jit/beam_jit_common.cpp
Labels: team:VM, bug

#6281 dialyzer: Document the meaning of specs
  lib/dialyzer/doc/src/dialyzer_chapter.xml
Labels: team:VM

#6319 ssl: Clarify warning
  lib/ssl/src/ssl.erl
Labels: team:PS, testing

#6296 dialyzer: Fix literal value being used instead of type
  lib/dialyzer/src/dialyzer_dataflow.erl
  lib/dialyzer/test/typer_SUITE.erl
Labels: team:VM, fix, testing

#5924 stdlib: enhances the shell completion
  .github/dockerfiles/Dockerfile.ubuntu-base
  .github/workflows/main.yaml
  HOWTO/DEVELOPMENT.md
  erts/doc/src/tty.xml
  lib/common_test/src/test_server_ctrl.erl
  lib/common_test/src/test_server_node.erl
  lib/kernel/src/code.erl
  lib/kernel/src/group.erl
  lib/kernel/src/prim_tty.erl
  lib/kernel/src/user.erl
  lib/kernel/src/user_drv.erl
  lib/kernel/test/interactive_shell_SUITE.erl
  lib/kernel/test/rtnode.erl
  lib/public_key/.gitignore
  lib/stdlib/doc/src/Makefile
  lib/stdlib/doc/src/edlin_expand.xml
  lib/stdlib/doc/src/io.xml
  lib/stdlib/doc/src/ref_man.xml
  lib/stdlib/doc/src/specs.xml
  lib/stdlib/src/Makefile
  lib/stdlib/src/edlin.erl
  lib/stdlib/src/edlin_context.erl
  lib/stdlib/src/edlin_expand.erl
  lib/stdlib/src/edlin_type_suggestion.erl
  lib/stdlib/src/io.erl
  lib/stdlib/src/shell.erl
  lib/stdlib/src/shell_default.erl
  lib/stdlib/src/stdlib.app.src
  lib/stdlib/test/Makefile
  lib/stdlib/test/edlin_context_SUITE.erl
  lib/stdlib/test/edlin_expand_SUITE.erl
  lib/stdlib/test/edlin_expand_SUITE_data/.hidden file
  lib/stdlib/test/edlin_expand_SUITE_data/.hidden_file
  lib/stdlib/test/edlin_expand_SUITE_data/.hidden😀_file
  lib/stdlib/test/edlin_expand_SUITE_data/complete_function_parameter.erl
  lib/stdlib/test/edlin_expand_SUITE_data/visible file
  lib/stdlib/test/edlin_expand_SUITE_data/visible_file
  lib/stdlib/test/edlin_expand_SUITE_data/visible😀_file
  lib/stdlib/test/shell_SUITE.erl
  lib/wx/.gitignore
Labels: team:VM, enhancement, testing

#6326 Dialyzer: Eliminate crash for code generated by Elixir
  lib/dialyzer/src/dialyzer_dataflow.erl
Labels: team:VM, enhancement, testing

#6256 Improve interval timer handling
  lib/stdlib/doc/src/timer.xml
  lib/stdlib/src/timer.erl
  lib/stdlib/test/timer_simple_SUITE.erl
Labels: team:VM, testing

#6228 Allow disabling `certificate_authorities` extension on server with `verify_peer`
  lib/ssl/doc/src/ssl.xml
  lib/ssl/src/ssl.erl
  lib/ssl/src/tls_handshake_1_3.erl
  lib/ssl/test/ssl_cert_SUITE.erl
Labels: team:PS, testing, waiting

#6322 eunit: Fix `$ rebar3 eunit` error on OTP 25.1
  lib/eunit/src/eunit_data.erl
  lib/eunit/test/eunit_SUITE.erl
Labels: team:PS, testing

#6330 ssl: fix for symlink resolving to relative path with CA certs
  lib/ssl/src/ssl.erl
  lib/ssl/test/ssl_pem_cache_SUITE.erl
Labels: team:PS

#6030 Improve observer nodes list menu
  lib/observer/src/observer_wx.erl
Labels: team:PS, testing, in progress

#6113 wx: Add `WX_MACOS_NON_GUI_APP`
  lib/wx/c_src/wxe_impl.cpp
Labels: team:PS, testing

#6104 [RFC] Introduce kernel TLS offload in inet_tls_dist
  lib/kernel/src/inet_tcp_dist.erl
  lib/kernel/src/net_kernel.erl
  lib/ssl/src/inet_tls_dist.erl
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_gen_statem.erl
  lib/ssl/src/ssl_internal.hrl
  lib/ssl/src/tls_connection_1_3.erl
  lib/ssl/src/tls_gen_connection.erl
  lib/ssl/test/inet_crypto_dist.erl
  lib/ssl/test/ssl_dist_SUITE.erl
Labels: team:PS

#6294 Adjust language around the usage of receive in a gen_statem.
  system/doc/design_principles/statem.xml
Labels: team:PS

#6334 ssl: Clarify doc
  lib/ssl/doc/src/ssl.xml
Labels: team:PS
