Repository erlang/otp, pull requests merged in 2022-04, with the labels that each got.

#5839 erts: Flush all signals on monitor_nodes down signal
  erts/emulator/beam/dist.c
  erts/emulator/beam/erl_proc_sig_queue.c
  erts/emulator/beam/erl_proc_sig_queue.h
  erts/emulator/beam/erl_time_sup.c
Labels: team:VM, fix, testing

#5844 Fix some minor compiler bugs
  lib/compiler/src/beam_call_types.erl
  lib/compiler/src/beam_ssa_bool.erl
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/test/beam_ssa_SUITE.erl
  lib/compiler/test/beam_type_SUITE.erl
  lib/compiler/test/bs_construct_SUITE.erl
  lib/compiler/test/guard_SUITE.erl
Labels: team:VM, fix, testing

#5824 inets: re-use connect_timeout option in TLS upgrade
  lib/inets/src/http_client/httpc_handler.erl
  lib/inets/test/httpc_proxy_SUITE.erl
  lib/ssl/test/ssl_test_lib.erl
  lib/ssl/test/tls_api_SUITE.erl
Labels: team:PS

#5849 JIT: Optimize `bsl` and `bxor` with known small operands
  erts/emulator/beam/jit/arm/beam_asm.hpp
  erts/emulator/beam/jit/arm/instr_arith.cpp
  erts/emulator/beam/jit/x86/beam_asm.hpp
  erts/emulator/beam/jit/x86/instr_arith.cpp
  erts/emulator/test/small_SUITE.erl
Labels: team:VM, enhancement, testing

#5851 Improve coverage of the compiler code
  lib/compiler/src/beam_call_types.erl
  lib/compiler/src/beam_disasm.erl
  lib/compiler/src/beam_ssa_pre_codegen.erl
  lib/compiler/src/compile.erl
  lib/compiler/test/beam_ssa_SUITE.erl
  lib/compiler/test/beam_type_SUITE.erl
  lib/compiler/test/bif_SUITE.erl
  lib/compiler/test/bs_match_SUITE.erl
  lib/compiler/test/compile_SUITE.erl
  lib/compiler/test/core_fold_SUITE.erl
  lib/compiler/test/map_SUITE.erl
  lib/compiler/test/misc_SUITE.erl
  lib/compiler/test/receive_SUITE.erl
  lib/compiler/test/receive_SUITE_data/ref_opt/yes_25.erl
  lib/compiler/test/receive_SUITE_data/ref_opt/yes_26.erl
  lib/compiler/test/receive_SUITE_data/ref_opt/yes_27.erl
  lib/compiler/test/receive_SUITE_data/ref_opt/yes_28.erl
  lib/compiler/test/test_lib.erl
  lib/compiler/test/trycatch_SUITE.erl
Labels: team:VM, enhancement, testing

#5842 Fix creation of small hashmaps in debug emulator
  erts/emulator/beam/copy.c
  erts/emulator/beam/erl_bif_atomics.c
  erts/emulator/beam/erl_term.h
  erts/emulator/beam/utils.c
Labels: team:VM, testing, bug

#5848 diffable: Allow input from external runtime
  scripts/diffable
Labels: team:VM

#5827 Remove deprecated `filename:safe_relative_path/1`
  bootstrap/lib/stdlib/ebin/otp_internal.beam
  lib/stdlib/doc/src/filename.xml
  lib/stdlib/src/filename.erl
  lib/stdlib/src/otp_internal.erl
  lib/stdlib/test/filename_SUITE.erl
Labels: team:VM, testing

#5857 Teach beam_lib:strip/* to retain new chunk types introduced in OTP 25
  lib/stdlib/doc/src/beam_lib.xml
  lib/stdlib/src/beam_lib.erl
  lib/stdlib/test/beam_lib_SUITE.erl
Labels: team:VM, fix, testing

#5855 Compiler: Improve bounds calculation for bitwise operators
  lib/compiler/src/Makefile
  lib/compiler/src/beam_bounds.erl
  lib/compiler/src/beam_call_types.erl
  lib/compiler/src/compiler.app.src
  lib/compiler/test/Makefile
  lib/compiler/test/beam_bounds_SUITE.erl
Labels: team:VM, enhancement, testing

#5856 beam_validator: Fix validation failure for failing apply
  lib/compiler/src/beam_validator.erl
  lib/compiler/test/beam_validator_SUITE.erl
Labels: team:VM, fix, testing

#4661 consistent sup_name() type
  lib/stdlib/src/supervisor.erl
Labels: team:VM, types

#5858 Cleanup old distribution handshake
  erts/doc/src/erl_dist_protocol.xml
  erts/emulator/beam/dist.c
  erts/preloaded/ebin/erlang.beam
  erts/preloaded/ebin/erts_internal.beam
  erts/preloaded/src/erlang.erl
  erts/preloaded/src/erts_internal.erl
  lib/erl_interface/src/connect/ei_connect.c
  lib/erl_interface/src/epmd/ei_epmd.h
  lib/erl_interface/src/epmd/epmd_publish.c
  lib/erl_interface/test/ei_tmo_SUITE.erl
  lib/jinterface/java_src/com/ericsson/otp/erlang/AbstractConnection.java
  lib/jinterface/java_src/com/ericsson/otp/erlang/AbstractNode.java
  lib/kernel/include/dist.hrl
  lib/kernel/src/dist_util.erl
  lib/kernel/test/erl_distribution_wb_SUITE.erl
Labels: team:VM, enhancement, testing

#5852 erts: Add init:get_argument(bindir) and use it for inet_gethost
  erts/etc/common/erlexec.c
  erts/preloaded/ebin/init.beam
  erts/preloaded/src/init.erl
  lib/kernel/src/inet_gethost_native.erl
Labels: team:VM, testing, bug

#5845 logger: Re-create folders for file logger if deleted
  lib/kernel/src/logger_std_h.erl
  lib/kernel/test/logger_std_h_SUITE.erl
Labels: team:VM, testing, bug

#5846 erts: Optimize make depend, especially on windows
  erts/emulator/Makefile.in
  erts/etc/win32/wsl_tools/vc/cc.sh
Labels: team:VM, enhancement, testing

#5847 erts: on macOS, prefer F_BARRIERFSYNC over of F_FULLFSYNC
  erts/emulator/nifs/unix/unix_prim_file.c
Labels: team:VM, testing

#5850 erts: Shrink ErlFunThing structure
  erts/emulator/beam/bif.c
  erts/emulator/beam/erl_fun.h
  erts/emulator/beam/jit/arm/instr_common.cpp
  erts/emulator/beam/jit/arm/instr_fun.cpp
  erts/emulator/beam/jit/x86/instr_common.cpp
  erts/emulator/beam/jit/x86/instr_fun.cpp
  erts/emulator/test/erts_debug_SUITE.erl
Labels: team:VM, enhancement, testing

#5864 erts: Remove unused CERL_DETACHED_PROG code
  erts/etc/common/erlexec.c
  lib/runtime_tools/src/system_information.erl
  lib/runtime_tools/test/system_information_SUITE_data/information_test_report.dat
Labels: team:VM, enhancement, testing

#5861 erts: Fix child_setup partial read
  erts/emulator/sys/unix/erl_child_setup.c
Labels: team:VM, testing, bug

#5836 Implement fast niche PRNGs
  lib/stdlib/doc/src/rand.xml
  lib/stdlib/src/rand.erl
  lib/stdlib/test/rand_SUITE.erl
Labels: team:PS, feature, in progress, priority:low

#5843 Ingela/ssl/select appropriate cert/gh 4143/otp 15993
  lib/ssl/doc/src/ssl.xml
  lib/ssl/doc/src/using_ssl.xml
  lib/ssl/src/dtls_connection.erl
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_certificate.erl
  lib/ssl/src/ssl_config.erl
  lib/ssl/src/ssl_connection.hrl
  lib/ssl/src/ssl_gen_statem.erl
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/src/ssl_internal.hrl
  lib/ssl/src/tls_connection.erl
  lib/ssl/src/tls_dtls_connection.erl
  lib/ssl/src/tls_handshake_1_3.erl
  lib/ssl/src/tls_v1.erl
  lib/ssl/test/ssl_api_SUITE.erl
  lib/ssl/test/ssl_cert_SUITE.erl
  lib/ssl/test/ssl_test_lib.erl
Labels: team:PS, testing

#5862 [features] Change format and argument order for options and directives
  erts/test/lux/bad_feature_erlc.lux
  erts/test/lux/feature_erlc.lux
  erts/test/lux/feature_erlcold.lux
  erts/test/lux/feature_ifnot.lux
  erts/test/lux/input/enable.hrl
  erts/test/lux/input/f_bad_ifnot.erl
  erts/test/lux/input/f_directives.erl
  erts/test/lux/input/f_directives_2.erl
  erts/test/lux/input/f_directives_3.erl
  erts/test/lux/input/f_disable.erl
  erts/test/lux/input/f_ifnot.erl
  erts/test/lux/input/f_include_1.erl
  erts/test/lux/input/f_include_2.erl
  erts/test/lux/input/f_include_3.erl
  erts/test/lux/input/f_incorrect_directives.erl
  erts/test/lux/input/f_incorrect_disable.erl
  erts/test/lux/input/feature_directive_maybe_ifn.erl
  erts/test/lux/input/maybe.hrl
  lib/compiler/src/compile.erl
  lib/compiler/test/compile_SUITE.erl
  lib/compiler/test/maybe_SUITE.erl
  lib/compiler/test/test_lib.erl
  lib/compiler/test/warnings_SUITE.erl
  lib/stdlib/src/epp.erl
  lib/stdlib/src/erl_compile.erl
  lib/stdlib/src/erl_features.erl
  lib/stdlib/test/epp_SUITE.erl
  lib/stdlib/test/erl_eval_SUITE.erl
  lib/stdlib/test/erl_lint_SUITE.erl
  lib/syntax_tools/test/syntax_tools_SUITE.erl
  lib/tools/src/cover.erl
  lib/tools/test/cover_SUITE.erl
Labels: team:PS, testing

#5809 Add option +IOs to disable scheduler thread polling
  erts/doc/src/erl_cmd.xml
  erts/emulator/beam/erl_bif_trace.c
  erts/emulator/beam/erl_bits.c
  erts/emulator/beam/erl_port_task.c
  erts/emulator/beam/erl_process.c
  erts/emulator/beam/sys.h
  erts/emulator/sys/common/erl_check_io.c
  erts/emulator/sys/common/erl_check_io.h
  erts/emulator/test/scheduler_SUITE.erl
  erts/etc/common/erlexec.c
Labels: team:VM, feature, testing

#5872 jit: Fix bs_match_string and an addition helper on ARM
  erts/emulator/beam/jit/arm/beam_asm.hpp
  erts/emulator/beam/jit/arm/instr_bs.cpp
  erts/emulator/test/bs_match_bin_SUITE.erl
Labels: team:VM, testing, bug

#5735 Document new net_kernel:get_state
  lib/kernel/doc/src/net_kernel.xml
  lib/kernel/src/net_kernel.erl
  lib/kernel/test/erl_distribution_SUITE.erl
Labels: team:VM, enhancement, testing

#5888 wx: Fix configure on win32 with newer wxWidgets
  lib/wx/c_src/wxe_gl.cpp
  lib/wx/configure
  lib/wx/configure.in
Labels: team:PS, testing

#5895 JIT: Slightly reduce code size for is_lt and is_ge
  erts/emulator/beam/jit/arm/instr_common.cpp
  erts/emulator/beam/jit/x86/instr_common.cpp
Labels: team:VM, testing

#5880 erts: Add etp-dist for listing all dist entries
  erts/etc/unix/etp-commands.in
Labels: team:VM, enhancement, testing

#5882 Improve documentation about the Erlang shell
  lib/kernel/doc/src/kernel_app.xml
  lib/stdlib/doc/src/c.xml
  lib/stdlib/doc/src/shell.xml
  lib/stdlib/doc/src/stdlib_app.xml
Labels: team:VM, testing, documentation

#5911 ssl: packet_size was not handled by ssl:setopts and ssl:getopts
  lib/ssl/src/ssl_gen_statem.erl
  lib/ssl/test/ssl_packet_SUITE.erl
Labels: team:PS, testing

#5866 Add OFB mode support for AES
  lib/crypto/c_src/cipher.c
  lib/crypto/doc/src/algorithm_details.xml
  lib/crypto/src/crypto.erl
  lib/crypto/test/crypto_SUITE.erl
Labels: team:PS, feature, testing

#5914 compiler: Refactor type analysis and improve tests
  lib/compiler/src/beam_bounds.erl
  lib/compiler/src/beam_call_types.erl
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/test/beam_bounds_SUITE.erl
Labels: team:VM, enhancement, testing

#5925 Eliminate crash when creating more than 33554431 atoms
  erts/emulator/beam/atom.c
Labels: team:VM, fix, testing

#5869 Don't parse map update syntax in patterns
  lib/stdlib/src/erl_parse.yrl
Labels: team:VM, testing

#5885 kernel|stdlib: Fix io:puts_char error with invalid binary
  lib/kernel/src/file_io_server.erl
  lib/stdlib/src/erl_stdlib_errors.erl
  lib/stdlib/test/io_SUITE.erl
Labels: team:VM, enhancement, testing

#5921 Show how to get the system word size
  system/doc/efficiency_guide/advanced.xml
Labels: team:VM

#5912 wx: Fix build problems with wxWidgets-3.1.6
  lib/wx/c_src/gen/wxe_wrapper_5.cpp
Labels: team:PS, testing

#5884 Change from using dicts in typer_core to using maps
  lib/dialyzer/src/typer_core.erl
Labels: team:VM, testing

#5919 ssl: Fix version mismatch
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/src/tls_gen_connection.erl
Labels: team:PS, testing

#5873 Generate header file for class BeamGlobalAssembler
  erts/emulator/Makefile.in
  erts/emulator/beam/jit/arm/beam_asm.hpp
  erts/emulator/beam/jit/arm/beam_asm_global.cpp
  erts/emulator/beam/jit/arm/beam_asm_global.hpp.pl
  erts/emulator/beam/jit/x86/beam_asm.hpp
  erts/emulator/beam/jit/x86/beam_asm_global.cpp
  erts/emulator/beam/jit/x86/beam_asm_global.hpp.pl
Labels: team:VM, testing

#5929 Mend and extend random_code_SUITE
  lib/compiler/test/property_test/compile_prop.erl
  lib/compiler/test/random_code_SUITE.erl
Labels: team:VM, enhancement, testing

#5927 Link to docs on heap sizing
  erts/doc/src/erlang.xml
Labels: team:VM

#5906 wx: Overload `OSXIsGUIApplication` with our own check
  lib/wx/c_src/wxe_impl.cpp
  lib/wx/c_src/wxe_impl.h
  lib/wx/c_src/wxe_nif.h
Labels: team:PS, testing

#5909 wx: Document `wx:subscribe_events/0`
  lib/wx/doc/src/wx.xml
Labels: team:PS, testing

#5910 inets: document inet6fb4 option for httpc
  lib/inets/doc/src/httpc.xml
Labels: team:PS
