Repository erlang/otp, pull requests merged in 2022-06, with the labels that each got.

#6034 beam_validator: Fix type inference for relational comparisons
  lib/compiler/src/beam_validator.erl
  lib/compiler/test/beam_validator_SUITE.erl
Labels: team:VM, fix, testing

#6028 Fix case clause errors in erl_erts_errors
  lib/kernel/src/erl_erts_errors.erl
Labels: team:VM, testing

#6013 Fix a bug that `mnesia:add_table_copy/3` could hold a read lock forever
  lib/mnesia/src/mnesia_loader.erl
  lib/mnesia/test/mnesia_evil_coverage_test.erl
Labels: team:PS, testing

#6044 erts: Improve internal hashing
  erts/emulator/Makefile.in
  erts/emulator/beam/erl_term_hashing.c
  erts/emulator/beam/erl_term_hashing.h
  erts/emulator/beam/erl_utils.h
  erts/emulator/beam/jit/arm/instr_map.cpp
  erts/emulator/beam/jit/x86/instr_map.cpp
  erts/emulator/beam/utils.c
Labels: team:VM, enhancement, testing

#6031 JIT: Optimize creation of binaries
  erts/emulator/beam/emu/bs_instrs.tab
  erts/emulator/beam/erl_bits.c
  erts/emulator/beam/erl_bits.h
  erts/emulator/beam/jit/arm/beam_asm.hpp
  erts/emulator/beam/jit/arm/beam_asm_global.hpp.pl
  erts/emulator/beam/jit/arm/generators.tab
  erts/emulator/beam/jit/arm/instr_bs.cpp
  erts/emulator/beam/jit/beam_jit_args.hpp
  erts/emulator/beam/jit/beam_jit_common.cpp
  erts/emulator/beam/jit/x86/beam_asm.hpp
  erts/emulator/beam/jit/x86/beam_asm_global.hpp.pl
  erts/emulator/beam/jit/x86/generators.tab
  erts/emulator/beam/jit/x86/instr_bs.cpp
  erts/emulator/test/bs_construct_SUITE.erl
Labels: team:VM, enhancement, testing

#6039 Correct default for dump_log_write_threshold in Mnesia docs
  lib/mnesia/doc/src/mnesia.xml
Labels: team:PS

#6046 Use multi time warp mode by default
  erts/doc/src/time_correction.xml
  erts/emulator/beam/erl_init.c
  system/doc/general_info/upcoming_incompatibilities.xml
Labels: team:VM, enhancement, testing

#6003 Fix spawn_reply signal order
  erts/doc/src/erlang.xml
  erts/emulator/beam/erl_proc_sig_queue.c
Labels: team:VM, fix, testing

#6018 dialyzer: Correct documentation for missing/extra_return
  lib/dialyzer/doc/src/dialyzer.xml
Labels: team:VM, fix, testing, documentation

#6032 is_alive fixes
  erts/emulator/beam/atom.names
  erts/emulator/beam/bif.c
  erts/emulator/beam/dist.c
  erts/emulator/beam/dist.h
  erts/emulator/beam/erl_bif_persistent.c
  erts/emulator/beam/global.h
  erts/emulator/test/distribution_SUITE.erl
  erts/preloaded/ebin/erlang.beam
  erts/preloaded/ebin/erts_internal.beam
  erts/preloaded/src/erlang.erl
  erts/preloaded/src/erts.app.src
  erts/preloaded/src/erts_internal.erl
  lib/kernel/src/kernel.app.src
  lib/kernel/src/net_kernel.erl
Labels: team:VM, fix

#6029 5719 - Adding Stacktrace to thrown
  lib/common_test/src/test_server.erl
  lib/common_test/test/ct_error_SUITE.erl
  lib/common_test/test/ct_test_support.erl
Labels: team:PS, testing

#6060 Fix public_key removed version
  lib/stdlib/scripts/update_deprecations
  system/doc/general_info/DEPRECATIONS
Labels: team:VM, testing, bug

#6075 ssl: turn off debug logging in tests
  lib/ssl/test/openssl_key_update_SUITE.erl
  lib/ssl/test/openssl_session_ticket_SUITE.erl
  lib/ssl/test/ssl_api_SUITE.erl
  lib/ssl/test/ssl_cert_SUITE.erl
  lib/ssl/test/ssl_key_update_SUITE.erl
  lib/ssl/test/ssl_session_ticket_SUITE.erl
  lib/ssl/test/ssl_sni_SUITE.erl
Labels: team:PS

#6069 beam_call_types: Fix type inference for erlang:min/2,max/2
  lib/compiler/src/beam_call_types.erl
  lib/compiler/test/beam_type_SUITE.erl
Labels: team:VM, testing, bug

#6072 Mandatory distribution features in OTP 26
  erts/doc/src/erl_dist_protocol.xml
  erts/doc/src/erl_ext_dist.xml
  erts/emulator/beam/dist.c
  erts/emulator/beam/dist.h
  erts/emulator/beam/erl_term_hashing.c
  erts/emulator/beam/external.c
  lib/erl_interface/src/connect/ei_connect.c
  lib/erl_interface/src/connect/ei_connect_int.h
  lib/erl_interface/test/ei_tmo_SUITE.erl
  lib/jinterface/java_src/com/ericsson/otp/erlang/AbstractConnection.java
  lib/jinterface/java_src/com/ericsson/otp/erlang/AbstractNode.java
  lib/kernel/include/dist.hrl
  lib/kernel/test/erl_distribution_wb_SUITE.erl
  system/doc/general_info/upcoming_incompatibilities.xml
Labels: team:VM, enhancement, testing

#5983 Extend timer tests
  lib/stdlib/src/timer.erl
  lib/stdlib/test/timer_simple_SUITE.erl
Labels: team:VM, testing

#6056 crypto: Ensure 'lib_bits' is set before used in configure.in
  lib/crypto/configure
  lib/crypto/configure.ac
Labels: team:PS, fix, testing

#6071 Remove duplicate word in mnesia docs
  lib/mnesia/doc/src/mnesia.xml
Labels: team:PS

#6068 dialyzer: Add no_extra_return and no_missing_return to warn_options type
  lib/dialyzer/src/dialyzer.hrl
  lib/dialyzer/src/dialyzer_cl_parse.erl
  lib/dialyzer/test/extra_return_SUITE_data/dialyzer_options
  lib/dialyzer/test/extra_return_SUITE_data/results/extra_return
  lib/dialyzer/test/extra_return_SUITE_data/src/extra_return.erl
  lib/dialyzer/test/missing_return_SUITE_data/dialyzer_options
  lib/dialyzer/test/missing_return_SUITE_data/results/missing_return
  lib/dialyzer/test/missing_return_SUITE_data/src/missing_return.erl
  lib/stdlib/src/erl_lint.erl
Labels: team:VM, fix, testing

#6082 Eliminate crash when optimization passes are disabled
  lib/compiler/src/beam_ssa_pre_codegen.erl
  lib/compiler/test/beam_ssa_SUITE.erl
Labels: team:VM, fix, testing

#6086 Improve the type-based optimizations
  erts/emulator/beam/beam_file.c
  erts/emulator/beam/beam_types.c
  erts/emulator/beam/beam_types.h
  erts/emulator/beam/jit/arm/beam_asm.hpp
  erts/emulator/beam/jit/arm/instr_arith.cpp
  erts/emulator/beam/jit/arm/instr_bs.cpp
  erts/emulator/beam/jit/arm/instr_common.cpp
  erts/emulator/beam/jit/arm/instr_guard_bifs.cpp
  erts/emulator/beam/jit/x86/beam_asm.hpp
  erts/emulator/beam/jit/x86/instr_arith.cpp
  erts/emulator/beam/jit/x86/instr_bs.cpp
  erts/emulator/beam/jit/x86/instr_common.cpp
  erts/emulator/beam/jit/x86/instr_guard_bifs.cpp
  erts/emulator/test/small_SUITE.erl
  lib/compiler/src/Makefile
  lib/compiler/src/beam_bounds.erl
  lib/compiler/src/beam_disasm.erl
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/src/beam_types.erl
  lib/compiler/src/beam_types.hrl
  lib/compiler/test/beam_bounds_SUITE.erl
  lib/compiler/test/compile_SUITE.erl
Labels: team:VM, enhancement, testing

#6088 Eliminate another crash when optimization passes are disabled
  lib/compiler/src/beam_block.erl
  lib/compiler/test/map_SUITE.erl
Labels: team:VM, fix, testing

#6063 observer: correct the units shown for memory data
  lib/observer/src/observer_lib.erl
Labels: team:PS, testing

#6092 gh: Bump Vampire/setup-wsl version
  .github/workflows/main.yaml
Labels: team:VM, bug

#6089 Forbid nonsensical module names
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/test/erl_lint_SUITE.erl
Labels: team:VM, fix, testing

#6093 Add proper and jsx for testing
  .github/dockerfiles/Dockerfile.64-bit
  .github/dockerfiles/Dockerfile.ubuntu-base
  lib/runtime_tools/Makefile
  lib/runtime_tools/test/system_information_SUITE.erl
Labels: team:VM, enhancement

#6091 Missing a curly bracket
  lib/inets/doc/src/httpc.xml
Labels: team:PS

#6080 Fix SEGV while crash dumping ETS ordered_set
  erts/emulator/beam/erl_db_catree.c
  erts/emulator/beam/erl_process.c
  erts/emulator/beam/erl_process.h
Labels: team:VM, fix, testing

#6101 Update windows configure cache
  erts/configure
  erts/configure.ac
  erts/emulator/beam/external.c
  make/autoconf/otp.m4
  make/autoconf/win32.config.cache.static
  make/autoconf/win64.config.cache.static
Labels: team:VM, enhancement, testing

#6103 Call `mach_clock_getres` only on initialized clocks
  erts/emulator/sys/unix/sys_time.c
Labels: team:VM, fix, testing

#6102 Handle AST nodes without location on *_opt_info
  lib/compiler/src/beam_ssa_bsm.erl
  lib/compiler/src/beam_ssa_recv.erl
  lib/compiler/test/warnings_SUITE.erl
Labels: team:VM, fix, testing

#6100 compiler: Add type info for bs_init_writable
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/src/beam_validator.erl
  lib/compiler/test/compile_SUITE.erl
  lib/compiler/test/compile_SUITE_data/bs_init_writable.erl
Labels: team:VM, enhancement, testing

#6040 Make specs for hd/1 and tl/1 more specific
  erts/doc/src/erlang.xml
  erts/preloaded/src/erlang.erl
Labels: team:VM, enhancement, testing

#6058 [pg] Implement group membership monitoring
  lib/kernel/doc/src/pg.xml
  lib/kernel/src/pg.erl
  lib/kernel/test/pg_SUITE.erl
Labels: team:VM, testing

#6094 Added `zip:zip_get_crc32/2` to read the CRC32 sums from an open zip handle
  lib/stdlib/doc/src/zip.xml
  lib/stdlib/src/zip.erl
  lib/stdlib/test/zip_SUITE.erl
Labels: team:VM, testing

#6090 Add category to unicode_util
  lib/stdlib/test/unicode_util_SUITE.erl
  lib/stdlib/test/unicode_util_SUITE_data/unicode_table.bin
  lib/stdlib/uc_spec/EastAsianWidth.txt
  lib/stdlib/uc_spec/gen_unicode_mod.escript
Labels: team:PS, testing, in progress

#6109 ssl: extend pem cache tests
  lib/ssl/test/ssl_pem_cache_SUITE.erl
Labels: team:PS

#6111 Add integer guard tests to some modules in STDLIB
  lib/stdlib/src/array.erl
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/src/erl_scan.erl
  lib/stdlib/src/filename.erl
  lib/stdlib/src/gb_sets.erl
  lib/stdlib/src/gb_trees.erl
  lib/stdlib/src/io_lib.erl
  lib/stdlib/src/string.erl
  lib/stdlib/test/erl_scan_SUITE.erl
  lib/stdlib/uc_spec/gen_unicode_mod.escript
Labels: team:VM, enhancement, testing
