Repository erlang/otp, pull requests merged in 2023-11, with the labels that each got.

#7675 Export multiline prompt functions
  lib/kernel/src/group.erl
  lib/kernel/src/prim_tty.erl
  lib/kernel/test/interactive_shell_SUITE.erl
  lib/stdlib/doc/src/shell.xml
  lib/stdlib/src/edlin.erl
  lib/stdlib/src/shell.erl
  lib/stdlib/test/shell_SUITE.erl
Labels: team:VM, testing

#7797 Fix keyboard configuration bugs
  lib/kernel/test/interactive_shell_SUITE.erl
  lib/kernel/test/interactive_shell_SUITE_data/valid_keymap.config
  lib/stdlib/src/edlin_key.erl
Labels: team:VM, fix, testing

#7783 ssl: Handle legacy scheme names
  lib/ssl/src/ssl_cipher.erl
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/src/tls_handshake.erl
  lib/ssl/test/openssl_client_cert_SUITE.erl
  lib/ssl/test/tls_1_3_version_SUITE.erl
Labels: team:PS, testing

#7784 Ingela/ssl/ext key usage check/otp 18739
  lib/public_key/src/pubkey_cert.erl
  lib/public_key/test/public_key_SUITE.erl
  lib/ssl/src/ssl_certificate.erl
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/src/tls_handshake_1_3.erl
Labels: team:PS, testing

#7777 inets: fix httpd_serve_SUITE on Windows
  lib/inets/test/httpd_serve_SUITE.erl
Labels: team:PS, testing

#7579 Ingela/public key/policies/otp 17844
  lib/public_key/asn1/Makefile
  lib/public_key/asn1/OTP-PKIX.asn1
  lib/public_key/doc/src/public_key.xml
  lib/public_key/doc/src/public_key_app.xml
  lib/public_key/include/public_key.hrl
  lib/public_key/src/Makefile
  lib/public_key/src/pubkey_cert.erl
  lib/public_key/src/pubkey_policy_tree.erl
  lib/public_key/src/public_key.app.src
  lib/public_key/src/public_key.erl
  lib/public_key/test/pkits_SUITE.erl
  lib/public_key/test/pubkey_cert_SUITE.erl
Labels: team:PS, testing

#7682 erl_types: Fix crash in contract checking
  lib/dialyzer/src/erl_types.erl
  lib/dialyzer/test/opaque_SUITE_data/results/crash
  lib/dialyzer/test/opaque_SUITE_data/src/crash/crash_2.erl
Labels: team:VM, fix, testing

#7798 Fix mixing loading from file or all files in a dir
  lib/public_key/src/pubkey_os_cacerts.erl
  lib/public_key/test/public_key_SUITE.erl
Labels: team:PS, testing

#7810 Fix restore disk_only with index
  lib/mnesia/src/mnesia_dumper.erl
  lib/mnesia/test/mnesia_evil_backup.erl
Labels: team:PS, testing

#7816 stdlib: add shell:multiline_prompt_func/1
  lib/kernel/src/kernel.app.src
  lib/kernel/test/interactive_shell_SUITE.erl
  lib/stdlib/doc/src/shell.xml
  lib/stdlib/doc/src/stdlib_app.xml
  lib/stdlib/src/shell.erl
  lib/stdlib/src/stdlib.app.src
Labels: team:VM, enhancement, testing

#7808 [pg] Fix typo potentially leading to crash
  lib/kernel/src/pg.erl
Labels: team:VM

#7817 Fix minor bugs and misfeatures in the compiler
  lib/compiler/src/beam_ssa_dead.erl
  lib/compiler/src/beam_ssa_lint.erl
  lib/compiler/src/compile.erl
Labels: team:VM, fix, testing

#7818 Postpone the removal of slave to OTP 29
  bootstrap/lib/stdlib/ebin/otp_internal.beam
  lib/stdlib/src/otp_internal.erl
  system/doc/general_info/DEPRECATIONS
Labels: team:VM, testing

#7833 beam/external: don't blow assert on encounter with a magic binary
  erts/emulator/beam/external.c
Labels: team:VM, testing

#7780 Fix erroneous EPL license headers with the correct Apache 2.0 license
  erts/emulator/test/alloc_SUITE_data/migration.c
  erts/emulator/test/nif_SUITE_data/nif_api_2_0/erl_drv_nif.h
  erts/emulator/test/nif_SUITE_data/nif_api_2_0/erl_nif.h
  erts/emulator/test/nif_SUITE_data/nif_api_2_0/erl_nif_api_funcs.h
  erts/emulator/test/nif_SUITE_data/nif_api_2_4/erl_drv_nif.h
  erts/emulator/test/nif_SUITE_data/nif_api_2_4/erl_nif.h
  erts/emulator/test/nif_SUITE_data/nif_api_2_4/erl_nif_api_funcs.h
  erts/emulator/test/property_test/phash2_properties.erl
  lib/crypto/doc/src/algorithm_details.xml
  lib/crypto/doc/src/engine_keys.xml
  lib/crypto/doc/src/engine_load.xml
  lib/crypto/doc/src/fips.xml
  lib/crypto/doc/src/new_api.xml
  lib/diameter/src/base/diameter_config_sup.erl
  lib/ftp/doc/src/introduction.xml
  lib/inets/doc/src/introduction.xml
  lib/kernel/src/erl_signal_handler.erl
  lib/ssh/test/ssh_protocol_SUITE.erl
  lib/ssh/test/ssh_trpt_test_lib.erl
  lib/ssl/src/dtls_packet_demux.erl
  lib/ssl/test/property_test/ssl_eqc_chain.erl
  lib/ssl/test/property_test/ssl_eqc_cipher_format.erl
  lib/ssl/test/property_test/ssl_eqc_handshake.erl
  lib/ssl/test/ssl_eqc_SUITE.erl
  lib/stdlib/test/tar_SUITE_data/no_fancy_stuff.tar
  lib/tftp/doc/src/introduction.xml
  make/install_dir_data.sh.in
Labels: testing, team:PO

#7814 public_key: pubkey_policy_tree_SUITE and tree visualization
  lib/public_key/test/Makefile
  lib/public_key/test/pubkey_policy_tree_SUITE.erl
Labels: team:PS, testing

#7841 ssl: Fix typespec for signature_algs/2 and export signature_algs/0 type
  lib/ssl/src/ssl.erl
Labels: team:PS, testing

#7812 Fix sni hostname lookup
  lib/ssl/src/ssl_gen_statem.erl
Labels: team:PS, testing

#7840 Ingela/ssl/clean up connection states
  lib/ssl/src/ssl_cipher.erl
  lib/ssl/src/ssl_connection.hrl
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/src/ssl_record.hrl
  lib/ssl/test/ssl_session_SUITE.erl
Labels: team:PS, testing

#7850 Fix #7811, SSL not working on FIPS enabled OTP 26.1
  lib/public_key/src/public_key.erl
Labels: team:PS, testing

#7803 inets: Copy ipfamily from state into requests & expand httpc IPv6 testing
  lib/inets/src/http_client/httpc_handler.erl
  lib/inets/test/httpc_SUITE.erl
Labels: team:PS, testing

#7853 Update statem.xml
  system/doc/design_principles/statem.xml
Labels: team:PS

#7782 runtime_tools: Add specs to dbg and dyntrace
  lib/et/src/et_collector.erl
  lib/et/src/et_selector.erl
  lib/ftp/src/ftp_internal.erl
  lib/runtime_tools/src/dbg.erl
  lib/runtime_tools/src/dyntrace.erl
  lib/tools/src/fprof.erl
Labels: team:VM, enhancement, testing

#7825 ct: Remove documentation for deprecated ?config
  lib/common_test/doc/src/config_file_chapter.xml
  lib/common_test/doc/src/ct.xml
  lib/common_test/doc/src/ct_suite.xml
  lib/common_test/doc/src/dependencies_chapter.xml
  lib/common_test/doc/src/example_chapter.xml
  lib/common_test/doc/src/write_test_chapter.xml
Labels: team:PS, testing

#7627 ssh: support dumb terminals in ssh client
  lib/kernel/src/group.erl
  lib/ssh/src/ssh_cli.erl
  lib/stdlib/src/edlin.erl
Labels: team:VM, testing

#7515 Gracefully handle bad validity dates in public_key:pkix_path_validation
  lib/public_key/doc/src/public_key.xml
  lib/public_key/src/pubkey_cert.erl
  lib/public_key/src/public_key.erl
  lib/public_key/test/public_key_SUITE.erl
  lib/public_key/test/public_key_SUITE_data/bad_date_certchain.pem
Labels: team:PS, testing, waiting

#7720 Set process label
  lib/kernel/test/logger_legacy_SUITE.erl
  lib/observer/doc/src/observer_ug.xml
  lib/observer/src/etop_txt.erl
  lib/observer/src/observer_pro_wx.erl
  lib/observer/src/observer_procinfo.erl
  lib/observer/src/observer_wx.erl
  lib/runtime_tools/src/appmon_info.erl
  lib/runtime_tools/src/observer_backend.erl
  lib/runtime_tools/src/runtime_tools.app.src
  lib/stdlib/doc/src/proc_lib.xml
  lib/stdlib/src/c.erl
  lib/stdlib/src/proc_lib.erl
  lib/stdlib/src/stdlib.app.src
  lib/stdlib/test/proc_lib_SUITE.erl
Labels: team:PS, testing

#7880 Fix port crash
  lib/runtime_tools/src/observer_backend.erl
Labels: team:PS, testing

#7849 Kuba/ssh/simplify connection handler startup
  lib/ssh/internal_doc/ssh_notes.md
  lib/ssh/src/ssh_connection_handler.erl
  lib/ssh/src/ssh_system_sup.erl
Labels: team:PS, testing

#7878 Fix partial record matching in map generator
  lib/compiler/test/mc_SUITE.erl
  lib/stdlib/src/erl_expand_records.erl
Labels: team:VM, fix, testing

#7745 Add higher/lower search functions in gb_trees and gb_sets
  lib/stdlib/doc/src/gb_sets.xml
  lib/stdlib/doc/src/gb_trees.xml
  lib/stdlib/src/gb_sets.erl
  lib/stdlib/src/gb_trees.erl
  lib/stdlib/test/gb_sets_property_test_SUITE.erl
  lib/stdlib/test/property_test/gb_sets_prop.erl
Labels: team:VM, testing

#7884 erl: Set -noshell when -S is used
  erts/doc/src/erl_cmd.xml
  erts/etc/common/erlexec.c
  lib/inets/src/http_server/httpd.erl
  lib/inets/test/httpd_serve_SUITE.erl
Labels: team:VM, team:PS, testing

#7879 Add string:jaro_similarity/2
  lib/stdlib/doc/src/string.xml
  lib/stdlib/src/string.erl
  lib/stdlib/test/string_SUITE.erl
Labels: team:PS, testing

#7892 Fix tty windows large write
  erts/emulator/nifs/common/prim_tty_nif.c
Labels: team:VM, fix, testing

#7761 inet_drv.c: mreq4.imr_ifindex value fix #7736
  erts/emulator/drivers/common/inet_drv.c
Labels: team:PS, fix, bug

#7824 Fix `ct_property_test` result handling for failing properties
  lib/common_test/src/ct_property_test.erl
Labels: team:PS, testing

#7891 ct: Introduce replace mode to cth_log_redirect
  lib/common_test/doc/src/ct_hooks_chapter.xml
  lib/common_test/src/cth_log_redirect.erl
  lib/common_test/test/ct_hooks_SUITE.erl
Labels: team:PS, testing, priority:low

#7894 erts: Share external funs globally
  erts/emulator/beam/beam_file.c
  erts/emulator/beam/bif.c
  erts/emulator/beam/erl_fun.c
  erts/emulator/beam/erl_fun.h
  erts/emulator/beam/erl_process_dump.c
  erts/emulator/beam/export.c
  erts/emulator/beam/export.h
  erts/emulator/beam/external.c
  erts/emulator/beam/global.h
Labels: team:VM, testing

#7804 Fix typo in unix_socket_syncio.c
  erts/emulator/nifs/unix/unix_socket_syncio.c
Labels: team:PS, testing

#7260 Fix a bug that prim_socket:cancel/3 could return `{error, select_sent|not_found}` while socket module expects `select_sent|not_found`
  erts/emulator/nifs/common/prim_socket_nif.c
Labels: team:PS, testing

#7910 Replace MD5 implementation used
  erts/emulator/Makefile.in
  erts/emulator/beam/beam_code.h
  erts/emulator/beam/erl_bif_chksum.c
  erts/emulator/beam/erl_bif_info.c
  erts/emulator/beam/erl_md5.c
  erts/emulator/beam/global.h
  erts/emulator/openssl/LICENSE.txt
  erts/emulator/openssl/README
  erts/emulator/openssl/crypto/md5/md5_dgst.c
  erts/emulator/openssl/crypto/md5/md5_local.h
  erts/emulator/openssl/include/crypto/md32_common.h
  erts/emulator/openssl/include/erl_md5.h
  erts/emulator/openssl/include/openssl/md5.h
  erts/emulator/openssl/openssl.diff
  erts/emulator/openssl/openssl.mk
  lib/erl_interface/src/Makefile.in
  lib/erl_interface/src/connect/ei_connect.c
  lib/erl_interface/src/misc/eimd5.c
  lib/erl_interface/src/misc/eimd5.h
  lib/erl_interface/src/openssl/LICENSE.txt
  lib/erl_interface/src/openssl/README
  lib/erl_interface/src/openssl/crypto/md5/md5_dgst.c
  lib/erl_interface/src/openssl/crypto/md5/md5_local.h
  lib/erl_interface/src/openssl/include/crypto/md32_common.h
  lib/erl_interface/src/openssl/include/erl_md5.h
  lib/erl_interface/src/openssl/include/openssl/md5.h
  lib/erl_interface/src/openssl/openssl.diff
  lib/erl_interface/src/openssl/openssl.mk
Labels: team:VM, enhancement, testing
