Repository erlang/otp, pull requests merged in 2023-12, with the labels that each got.

#7912 inets: Do not consider file errors as "500 - Internal server error"
  lib/inets/src/http_server/httpd_file.erl
  lib/inets/test/httpd_SUITE.erl
  lib/inets/test/inets_socketwrap_SUITE.erl
Labels: team:PS, testing

#7915 Fix memory leak and crash due to fragmented message to unaliased process
  erts/emulator/beam/dist.c
  erts/emulator/beam/erl_proc_sig_queue.c
  erts/emulator/test/process_SUITE.erl
Labels: team:VM, fix

#7913 Fix BodyFormat of spec
  lib/inets/src/http_client/httpc.erl
Labels: team:PS

#7844 stdlib: make it possible to list local functions and types
  lib/stdlib/doc/src/shell.xml
  lib/stdlib/src/edlin_expand.erl
  lib/stdlib/src/shell.erl
  lib/stdlib/src/shell_default.erl
  lib/stdlib/test/shell_SUITE.erl
Labels: team:VM, testing

#7922 Fix error message for invalid replacement args in `binary:replace/3,4`
  lib/stdlib/src/erl_stdlib_errors.erl
Labels: team:VM, fix, testing

#7902 compiler: Fix some vestigial +0.0/-0.0 issues
  lib/compiler/src/beam_types.erl
  lib/compiler/test/beam_type_SUITE.erl
Labels: team:VM, fix, testing

#7918 ssl: Error server options when no certs
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_cipher.erl
  lib/ssl/test/ssl_api_SUITE.erl
  lib/ssl/test/tls_api_SUITE.erl
Labels: team:PS, testing

#7939 inets: Fix httpc parallel tests failing on FreeBSD
  lib/inets/test/http_test_lib.erl
Labels: team:PS, testing

#7865 remove repeated words and small typos
  .github/scripts/sync-github-releases.sh
  HOWTO/DEVELOPMENT.md
  HOWTO/INSTALL-IOS.md
  HOWTO/MARKDOWN.md
  erts/doc/src/erl_dist_protocol.xml
  erts/doc/src/erlang.xml
  erts/doc/src/notes.xml
  erts/emulator/beam/big.c
  erts/emulator/beam/emu/instrs.tab
  erts/emulator/beam/erl_flxctr.h
  erts/emulator/beam/erl_msacc.h
  erts/emulator/beam/erl_node_tables.h
  erts/emulator/beam/erl_proc_sig_queue.h
  erts/emulator/beam/erl_process.h
  erts/emulator/beam/erl_term.h
  erts/emulator/beam/jit/arm/ops.tab
  erts/emulator/beam/jit/x86/ops.tab
  erts/emulator/internal_doc/AutomaticYieldingOfCCode.md
  erts/emulator/internal_doc/PTables.md
  erts/emulator/internal_doc/Tracing.md
  erts/emulator/internal_doc/beam_makeops.md
  erts/emulator/nifs/common/prim_net_nif.c
  erts/emulator/sys/common/erl_osenv.h
  erts/emulator/test/big_SUITE.erl
  erts/emulator/test/bs_match_int_SUITE.erl
  erts/emulator/test/bs_utf_SUITE.erl
  erts/emulator/test/code_SUITE.erl
  erts/emulator/test/dirty_nif_SUITE.erl
  erts/emulator/test/distribution_SUITE.erl
  erts/emulator/test/map_SUITE.erl
  erts/etc/unix/RELNOTES
  erts/etc/unix/etp-commands.in
  erts/test/parallel_messages_SUITE_data/visualize_throughput.html
  lib/asn1/doc/src/asn1_spec.xmlsrc
  lib/asn1/doc/src/notes.xml
  lib/asn1/src/asn1ct_check.erl
  lib/asn1/src/asn1ct_imm.erl
  lib/asn1/src/asn1ct_parser2.erl
  lib/common_test/doc/src/notes.xml
  lib/common_test/doc/src/write_test_chapter.xml
  lib/common_test/src/test_server.erl
  lib/common_test/src/test_server_ctrl.erl
  lib/common_test/test/erl2html2_SUITE_data/m1.erl
Labels: team:VM, testing

#7935 erts: Unify ErlSubBits with match contexts
  erts/emulator/beam/beam_bif_load.c
  erts/emulator/beam/copy.c
  erts/emulator/beam/emu/bs_instrs.tab
  erts/emulator/beam/erl_bits.c
  erts/emulator/beam/erl_bits.h
  erts/emulator/beam/erl_debug.c
  erts/emulator/beam/erl_etp.c
  erts/emulator/beam/erl_gc.c
  erts/emulator/beam/erl_gc.h
  erts/emulator/beam/erl_io_queue.c
  erts/emulator/beam/erl_map.c
  erts/emulator/beam/erl_nif.c
  erts/emulator/beam/erl_printf_term.c
  erts/emulator/beam/erl_proc_sig_queue.c
  erts/emulator/beam/erl_process_dump.c
  erts/emulator/beam/erl_term.c
  erts/emulator/beam/erl_term.h
  erts/emulator/beam/erl_trace.c
  erts/emulator/beam/external.c
  erts/emulator/beam/jit/arm/beam_asm.hpp
  erts/emulator/beam/jit/arm/beam_asm_global.cpp
  erts/emulator/beam/jit/arm/instr_bs.cpp
  erts/emulator/beam/jit/arm/instr_common.cpp
  erts/emulator/beam/jit/arm/instr_guard_bifs.cpp
  erts/emulator/beam/jit/arm/instr_trace.cpp
  erts/emulator/beam/jit/beam_jit_common.cpp
  erts/emulator/beam/jit/x86/instr_bs.cpp
  erts/emulator/beam/jit/x86/instr_common.cpp
  erts/emulator/beam/jit/x86/instr_guard_bifs.cpp
  erts/emulator/test/bs_bincomp_SUITE.erl
  erts/emulator/test/erts_debug_SUITE.erl
Labels: team:VM, testing

#7845 Paging in shell for autocompletion and search
  lib/kernel/src/group.erl
  lib/kernel/src/prim_tty.erl
  lib/kernel/src/user_drv.erl
  lib/kernel/test/interactive_shell_SUITE.erl
  lib/ssh/src/ssh_cli.erl
  lib/stdlib/doc/src/stdlib_app.xml
  lib/stdlib/src/edlin.erl
  lib/stdlib/src/edlin_key.erl
Labels: team:VM, testing

#7898 Ingela/ssl/custom sign fun
  lib/public_key/doc/src/public_key.xml
  lib/public_key/src/public_key.erl
  lib/public_key/test/public_key_SUITE.erl
  lib/ssl/doc/src/ssl.xml
  lib/ssl/src/ssl.app.src
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_config.erl
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/test/ssl_api_SUITE.erl
  lib/ssl/test/ssl_cert_SUITE.erl
  lib/ssl/test/ssl_cert_tests.erl
Labels: team:PS, testing

#7757 zlib: Fix negative Adler32 checksums
  erts/emulator/nifs/common/zlib_nif.c
  lib/kernel/test/zlib_SUITE.erl
Labels: team:VM, testing

#7899 inets: Remove obsolete code from httpd_serve_SUITE
  lib/inets/test/httpd_serve_SUITE.erl
Labels: team:PS, testing, priority:low

#7947 compiler: Rewrite swap to move
  lib/compiler/src/beam_block.erl
  lib/compiler/src/beam_clean.erl
  lib/compiler/src/beam_flatten.erl
  lib/compiler/src/beam_trim.erl
Labels: team:VM, enhancement, testing

#7945 Report arguments in the order given
  lib/stdlib/doc/src/argparse.xml
  lib/stdlib/src/argparse.erl
  lib/stdlib/test/argparse_SUITE.erl
Labels: team:VM, testing

#7953 inets: Fix httpd_serve_SUITE failing on OpenBSD
  lib/inets/test/httpd_serve_SUITE.erl
Labels: team:PS, testing

#7960 Fix error message for erlang:phash*/2
  lib/kernel/src/erl_erts_errors.erl
Labels: team:VM, fix, testing

#7846 stdlib: display help output in expand area
  erts/doc/src/tty.xml
  lib/kernel/src/group.erl
  lib/kernel/src/prim_tty.erl
  lib/kernel/test/interactive_shell_SUITE.erl
  lib/stdlib/doc/src/edlin.xml
  lib/stdlib/src/c.erl
  lib/stdlib/src/edlin.erl
  lib/stdlib/src/edlin_context.erl
  lib/stdlib/src/edlin_expand.erl
  lib/stdlib/src/edlin_key.erl
  lib/stdlib/test/edlin_context_SUITE.erl
Labels: team:VM

#7948 jit: Optimize reference counting of local funs
  erts/emulator/beam/beam_common.c
  erts/emulator/beam/beam_file.c
  erts/emulator/beam/beam_load.c
  erts/emulator/beam/code_ix.h
  erts/emulator/beam/copy.c
  erts/emulator/beam/emu/emu_load.c
  erts/emulator/beam/emu/instrs.tab
  erts/emulator/beam/emu/load.h
  erts/emulator/beam/erl_bif_info.c
  erts/emulator/beam/erl_db_util.c
  erts/emulator/beam/erl_debug.c
  erts/emulator/beam/erl_etp.c
  erts/emulator/beam/erl_fun.c
  erts/emulator/beam/erl_fun.h
  erts/emulator/beam/erl_gc.c
  erts/emulator/beam/erl_gc.h
  erts/emulator/beam/erl_map.c
  erts/emulator/beam/erl_message.c
  erts/emulator/beam/erl_node_tables.c
  erts/emulator/beam/erl_printf_term.c
  erts/emulator/beam/erl_process_dump.c
  erts/emulator/beam/erl_term.c
  erts/emulator/beam/erl_term.h
  erts/emulator/beam/erl_term_hashing.c
  erts/emulator/beam/export.c
  erts/emulator/beam/external.c
  erts/emulator/beam/generators.tab
  erts/emulator/beam/global.h
  erts/emulator/beam/jit/arm/instr_fun.cpp
  erts/emulator/beam/jit/asm_load.c
  erts/emulator/beam/jit/load.h
  erts/emulator/beam/jit/x86/instr_fun.cpp
  erts/emulator/beam/utils.c
  erts/emulator/test/erts_debug_SUITE.erl
  erts/emulator/test/fun_SUITE.erl
  erts/etc/unix/etp-commands.in
  erts/etc/unix/etp.py
  lib/observer/src/crashdump_viewer.erl
Labels: team:VM, enhancement, testing

#7829 erts: Fix large select instructions on ARM
  erts/emulator/beam/jit/arm/instr_select.cpp
  erts/emulator/test/beam_SUITE.erl
Labels: team:VM, testing

#7755 Fix regressions in code:ensure_loaded/1
  lib/kernel/src/code.erl
  lib/kernel/src/code_server.erl
  lib/kernel/test/code_SUITE.erl
Labels: team:VM, testing

#7930 Fix enif_binary_to_term function declaration mismatch warning
  erts/doc/src/erl_nif.xml
  erts/emulator/beam/erl_nif.c
  erts/emulator/test/nif_SUITE_data/nif_SUITE.c
Labels: team:VM, testing, bug

#7932 Fix invalid conversion compilation error (#7903)
  erts/emulator/beam/erl_nif_api_funcs.h
Labels: team:VM, fix, testing

#7857 Add `ets:update_element/4` to accept a default object
  erts/emulator/beam/bif.tab
  erts/emulator/beam/erl_db.c
  lib/stdlib/doc/src/ets.xml
  lib/stdlib/src/erl_stdlib_errors.erl
  lib/stdlib/src/ets.erl
  lib/stdlib/test/ets_SUITE.erl
Labels: team:VM, feature, testing

#7959 Add hidden functions to chunks
  lib/erl_docgen/src/docgen_xml_to_chunk.erl
Labels: team:VM, enhancement, testing

#7943 Eliminate memory leak in the native coverage feature
  erts/emulator/beam/jit/asm_load.c
Labels: team:VM, fix, testing

#7933 kernel: Short-circuit when casting from list to list
  lib/kernel/src/group.erl
Labels: team:VM, fix

#7956 Do some minor enhancements of the code generation in the JIT
  erts/emulator/beam/jit/arm/beam_asm.hpp
  erts/emulator/beam/jit/arm/beam_asm_global.hpp.pl
  erts/emulator/beam/jit/arm/instr_arith.cpp
  erts/emulator/beam/jit/arm/instr_bs.cpp
  erts/emulator/beam/jit/arm/instr_call.cpp
  erts/emulator/beam/jit/arm/instr_common.cpp
  erts/emulator/beam/jit/arm/ops.tab
  erts/emulator/beam/jit/beam_jit_args.hpp
  erts/emulator/beam/jit/beam_jit_common.cpp
  erts/emulator/beam/jit/beam_jit_common.hpp
  erts/emulator/beam/jit/x86/beam_asm.hpp
  erts/emulator/beam/jit/x86/beam_asm_global.hpp.pl
  erts/emulator/beam/jit/x86/instr_arith.cpp
  erts/emulator/beam/jit/x86/instr_bs.cpp
  erts/emulator/beam/jit/x86/instr_common.cpp
  erts/emulator/test/bs_match_bin_SUITE.erl
  erts/emulator/test/op_SUITE.erl
Labels: team:VM, enhancement, testing

#7983 Fix timeout overflow
  erts/emulator/beam/time.c
  erts/emulator/sys/common/erl_poll.c
  erts/emulator/sys/win32/erl_poll.c
  erts/emulator/test/timer_bif_SUITE.erl
  erts/include/internal/erl_errno.h
  erts/lib_src/pthread/ethr_event.c
  erts/lib_src/win/ethr_event.c
Labels: team:VM, fix

#7847 stdlib: add auto formatting to the shell
  lib/kernel/src/group.erl
  lib/kernel/test/interactive_shell_SUITE.erl
  lib/stdlib/doc/src/shell.xml
  lib/stdlib/doc/src/stdlib_app.xml
  lib/stdlib/src/edlin.erl
  lib/stdlib/src/edlin_key.erl
  lib/stdlib/src/shell.erl
Labels: team:VM, testing
