Repository erlang/otp, pull requests merged in 2023-08, with the labels that each got.

#7518 Fix crash when compiling is_list/1 call
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/test/beam_type_SUITE.erl
Labels: team:VM, fix, testing

#7519 beam_ssa_bool: Fix miscompilation
  lib/compiler/src/beam_ssa_bool.erl
  lib/compiler/test/guard_SUITE.erl
Labels: team:VM, fix, testing

#7388 ft: increase default process limit
  erts/doc/src/erl_cmd.xml
  erts/emulator/beam/erl_process.h
  erts/emulator/test/node_container_SUITE.erl
  system/doc/efficiency_guide/advanced.xml
Labels: team:VM, testing, waiting

#7405 ssl: Doc enhancement
  lib/ssl/doc/src/using_ssl.xml
Labels: team:PS, testing

#7508 Reword warning around `process_flag/2`
  lib/stdlib/test/shell_docs_SUITE_data/unknown_erlang_process_flag_2_func.txt
Labels: team:VM, fix

#7520 inets: httpc - enhance error handling
  lib/inets/src/http_client/httpc_request.erl
  lib/inets/src/http_lib/http_request.erl
  lib/inets/test/httpc_SUITE.erl
Labels: team:PS, testing

#7522 ssl: Handle that inet:getopts may return {ok, []}
  lib/ssl/src/ssl_gen_statem.erl
Labels: team:PS, testing

#7411 inets: Document sending status with mod_esi
  lib/inets/doc/src/mod_esi.xml
Labels: team:PS

#7526 Guard against negative Length in `ssl:recv/3`
  lib/ssl/src/ssl.erl
  lib/ssl/test/ssl_api_SUITE.erl
Labels: team:PS, enhancement, in progress, priority:medium, types

#7532 beam_jump: Eliminate unsafe sharing of blocks
  lib/compiler/src/beam_jump.erl
  lib/compiler/test/trycatch_SUITE.erl
Labels: team:VM, fix, testing

#7529 Clarify `gen_statem:start_link/3,4` semantics
  lib/stdlib/doc/src/gen_event.xml
  lib/stdlib/doc/src/gen_server.xml
  lib/stdlib/doc/src/gen_statem.xml
Labels: team:VM, team:PS, documentation, in progress, priority:medium

#7453 Use `ct_proper_ext` generators in `queue` property tests
  lib/stdlib/test/property_test/queue_prop.erl
Labels: team:VM, enhancement, testing

#7536 Kuba/inets/adjust error type/otp 18704
  lib/inets/src/http_server/httpd_logger.erl
  lib/inets/src/http_server/httpd_request_handler.erl
  lib/inets/src/http_server/mod_esi.erl
Labels: team:PS, testing

#7538 Correct evaluation order for binary comprehensions
  lib/compiler/src/beam_ssa_bc_size.erl
  lib/compiler/test/bs_bincomp_SUITE.erl
Labels: team:VM, fix, testing

#7545 ssl: Handle an active socket in pre TLS-1.3 renegotiation rejection
  lib/ssl/src/ssl_gen_statem.erl
  lib/ssl/test/ssl_renegotiate_SUITE.erl
Labels: team:PS, testing

#7528 Speed up alias analysis
  lib/compiler/src/beam_ssa_alias.erl
  lib/compiler/test/compile_SUITE.erl
Labels: team:VM, enhancement, testing

#7535 Export documented and exposed type erl_syntax:annotation_or_location/0
  lib/syntax_tools/src/erl_syntax.erl
Labels: team:VM, testing

#7521 erl_lint: Warn on matching float 0.0
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/test/erl_lint_SUITE.erl
Labels: team:VM, testing

#6985 inet_dns support for UPDATE, NOTIFY and TSIG
  .github/dockerfiles/Dockerfile.ubuntu-base
  lib/kernel/src/Makefile
  lib/kernel/src/inet_dns.erl
  lib/kernel/src/inet_dns.hrl
  lib/kernel/src/inet_dns_tsig.erl
  lib/kernel/src/inet_res.erl
  lib/kernel/src/kernel.app.src
  lib/kernel/test/inet_res_SUITE.erl
  lib/kernel/test/inet_res_SUITE_data/otptest/knot_inc.conf
  lib/kernel/test/inet_res_SUITE_data/otptest/nsd_inc.conf
  lib/kernel/test/inet_res_SUITE_data/otptest/otptest.zone
  lib/kernel/test/inet_res_SUITE_data/run-ns
Labels: team:PS, feature

#7229 Update ei_users_guide.xml
  lib/erl_interface/doc/src/ei_users_guide.xml
Labels: team:VM

#7527 compiler: Fix crash in beam_ssa_private_append
  lib/compiler/src/beam_ssa_private_append.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/private_append.erl
Labels: team:VM, fix, testing

#7462 Observer: Fix exit command button to allow window to close correctly; Fix for #7461
  lib/observer/src/observer_trace_wx.erl
Labels: team:PS, testing

#7544 mnesia: Delay old backup deletion
  lib/mnesia/src/mnesia_backup.erl
  lib/mnesia/test/mnesia_evil_backup.erl
Labels: team:PS, testing

#7562 Fix unsafe range calculation for the `bnot` operator
  lib/compiler/src/beam_bounds.erl
  lib/compiler/src/beam_call_types.erl
  lib/compiler/test/beam_bounds_SUITE.erl
Labels: team:VM, testing

#7541 Use <c>...</c> (in xml docs) instead of `...`
  lib/stdlib/doc/src/proc_lib.xml
  system/doc/reference_manual/expressions.xml
  system/doc/reference_manual/typespec.xml
Labels: team:VM, testing

#7430 inets: Speed up test suite by ~ 2 minutes
  lib/inets/test/httpc_SUITE.erl
  lib/inets/test/httpd_SUITE.erl
  lib/inets/test/httpd_basic_SUITE.erl
  lib/inets/test/inets_SUITE.erl
  lib/inets/test/inets_socketwrap_SUITE.erl
Labels: team:PS, testing

#7563 Enhance type analysis
  lib/compiler/src/beam_bounds.erl
  lib/compiler/src/beam_call_types.erl
  lib/compiler/test/beam_bounds_SUITE.erl
Labels: team:VM, enhancement, testing

#7554 public_key: Fix case insensitive match for countryname
  lib/public_key/src/pubkey_cert.erl
  lib/public_key/test/pkits_SUITE.erl
  lib/public_key/test/pkits_SUITE_data/pkits/smime-pem/RolloverfromPrintableStringtoUTF8StringCACert.pem
  lib/public_key/test/public_key_SUITE.erl
Labels: team:PS, testing

#7565 public_key: Add check for duplicate certificates
  lib/public_key/src/public_key.erl
  lib/public_key/test/public_key_SUITE.erl
Labels: team:PS, testing

#7547 inets: testcode cleanup
  lib/inets/test/httpc_SUITE.erl
  lib/inets/test/inets_SUITE.erl
Labels: team:PS, testing

#7487 ct: update auto skip stats when error in suite handled
  lib/common_test/src/ct_framework.erl
  lib/common_test/test/ct_misc_1_SUITE.erl
  lib/common_test/test/ct_misc_1_SUITE_data/bad_groups_SUITE.erl
Labels: team:PS, testing

#7567 Fix incorrect fusion of `div` and `rem`
  erts/emulator/beam/jit/arm/instr_arith.cpp
  erts/emulator/test/small_SUITE.erl
Labels: team:VM, fix, testing

#7570 Eliminate consistency failure for non-matching binary pattern
  lib/compiler/src/beam_validator.erl
  lib/compiler/test/bs_match_SUITE.erl
Labels: team:VM, fix, testing

#7568 `gb_sets`: group aliased functions in documentation
  lib/stdlib/doc/src/gb_sets.xml
Labels: team:VM, enhancement, testing, documentation

#7256 Property-based tests for `sets`, `ordsets` and `gb_sets`
  lib/stdlib/test/Makefile
  lib/stdlib/test/property_test/sets_prop.erl
  lib/stdlib/test/sets_property_test_SUITE.erl
Labels: team:VM, testing

#7553 Optimize integer arithmetic
  erts/emulator/beam/big.c
  erts/emulator/beam/big.h
  erts/emulator/beam/erl_arith.c
  erts/emulator/beam/global.h
  erts/emulator/beam/jit/arm/beam_asm.hpp
  erts/emulator/beam/jit/arm/beam_asm_global.hpp.pl
  erts/emulator/beam/jit/arm/instr_arith.cpp
  erts/emulator/beam/jit/arm/ops.tab
  erts/emulator/beam/jit/beam_jit_common.cpp
  erts/emulator/beam/jit/beam_jit_common.hpp
  erts/emulator/beam/jit/x86/beam_asm_global.hpp.pl
  erts/emulator/beam/jit/x86/instr_arith.cpp
  erts/emulator/beam/jit/x86/ops.tab
  erts/emulator/test/big_SUITE.erl
  erts/emulator/test/big_SUITE_data/karatsuba.dat
  erts/emulator/test/small_SUITE.erl
Labels: team:VM, enhancement, testing

#7575 asn1: Fix handling of SIZE constraints
  lib/asn1/src/asn1ct_check.erl
  lib/asn1/test/asn1_SUITE_data/ConstraintEquivalence.asn1
Labels: team:VM, fix, testing

#7574 Property-based tests for the `gb_sets` module
  lib/stdlib/test/Makefile
  lib/stdlib/test/gb_sets_property_test_SUITE.erl
  lib/stdlib/test/property_test/gb_sets_prop.erl
Labels: team:VM, enhancement, testing

#7458 Fix reference counting of magic refs in ETS compressed
  erts/emulator/beam/erl_bif_info.c
  erts/emulator/beam/erl_db_util.c
  erts/emulator/beam/erl_db_util.h
  erts/emulator/beam/erl_node_tables.c
  erts/emulator/beam/external.c
  erts/emulator/beam/external.h
  lib/stdlib/test/ets_SUITE.erl
Labels: team:VM, fix

#7564 Make multiline prompt invert-colored spaces.
  lib/kernel/test/interactive_shell_SUITE.erl
  lib/stdlib/src/edlin.erl
Labels: team:VM, testing

#7533 erts: Fix prim_tty nif to compile with GNU termcap
  erts/emulator/nifs/common/prim_tty_nif.c
Labels: team:VM, testing, bug

#7581 Fix heap allocation for matching out short bitstrings
  erts/emulator/beam/emu/generators.tab
  erts/emulator/beam/erl_bits.c
  erts/emulator/beam/erl_bits.h
  erts/emulator/beam/jit/arm/instr_bs.cpp
  erts/emulator/beam/jit/x86/instr_bs.cpp
  erts/emulator/test/bs_match_bin_SUITE.erl
Labels: team:VM, fix, testing

#7589 ssl: Document enhancement
  lib/ssl/doc/src/ssl.xml
Labels: team:PS, enhancement, testing

#7578 Rewrite RR cache access time update to preserve table insert order
  lib/kernel/src/inet_db.erl
Labels: team:PS, fix, bug, priority:medium

#7585 Improve documentation of the `binary` module
  lib/stdlib/doc/src/binary.xml
Labels: team:VM, team:PS, testing

#7590 Binary replacement with a function
  lib/stdlib/doc/src/binary.xml
  lib/stdlib/src/binary.erl
  lib/stdlib/test/binary_module_SUITE.erl
  lib/stdlib/test/binref.erl
Labels: team:VM, enhancement, testing

#7597 dialyzer: Handle definition of type product/0
  lib/dialyzer/src/dialyzer_utils.erl
  lib/dialyzer/test/small_SUITE_data/src/test_product_app.erl
Labels: team:VM, fix, testing
