Repository erlang/otp, pull requests merged in 2023-01, with the labels that each got.

#6609 fix typo
  system/doc/system_principles/system_principles.xml
Labels: team:VM

#6621 beam_validator: Bail on impossible sizes in bs_get_integer
  lib/compiler/src/beam_validator.erl
  lib/compiler/test/beam_validator_SUITE.erl
Labels: team:VM, testing

#6623 beam_ssa_codegen: Don't break bs_match sequences by mixing registers
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/test/bs_match_SUITE.erl
Labels: team:VM, testing

#6616 jit: Fix type check in add/subtract on aarch64
  erts/emulator/beam/jit/arm/instr_arith.cpp
Labels: team:VM, testing

#6624 sys_core_fold: Eliminate crash in beam_kernel_to_ssa, again
  lib/compiler/src/sys_core_fold.erl
  lib/compiler/test/core_fold_SUITE.erl
Labels: team:VM, testing

#6622 beam_call_types: Handle more boolean ops in will_succeed/3
  lib/compiler/src/beam_call_types.erl
  lib/compiler/test/beam_type_SUITE.erl
Labels: team:VM, testing

#6523 named_fun_expr annotate bindings fix
  lib/syntax_tools/src/erl_syntax_lib.erl
  lib/syntax_tools/test/syntax_tools_SUITE.erl
Labels: team:VM, testing

#6626 beam_bounds: Don't choke on division by zero
  lib/compiler/src/beam_bounds.erl
  lib/compiler/test/beam_bounds_SUITE.erl
Labels: team:VM, testing

#6585 Fix race receiving fragmented messages on terminating connection
  erts/emulator/beam/dist.c
Labels: team:VM, fix, testing

#6631 sys_core_fold: Always optimize bodies in move_let_into_expr
  lib/compiler/src/sys_core_fold.erl
  lib/compiler/test/core_fold_SUITE.erl
Labels: team:VM, testing

#6577 Optimize the `node/1` BIF in the JIT
  erts/emulator/beam/bif.c
  erts/emulator/beam/dist.c
  erts/emulator/beam/erl_bif_guard.c
  erts/emulator/beam/erl_map.c
  erts/emulator/beam/jit/arm/beam_asm_global.hpp.pl
  erts/emulator/beam/jit/arm/instr_guard_bifs.cpp
  erts/emulator/beam/jit/arm/ops.tab
  erts/emulator/beam/jit/x86/beam_asm_global.hpp.pl
  erts/emulator/beam/jit/x86/instr_guard_bifs.cpp
  erts/emulator/beam/jit/x86/ops.tab
  erts/emulator/test/bif_SUITE.erl
  lib/compiler/src/beam_call_types.erl
  lib/compiler/src/beam_types.erl
  lib/compiler/src/beam_types.hrl
  lib/compiler/test/property_test/beam_types_prop.erl
Labels: team:VM, enhancement, testing

#6596 lib/crypto: autoconf: Add missing ',' in an AC_IF
  lib/crypto/configure.ac
Labels: team:VM, testing

#6576 JIT: Optimize matching of utf8 segments
  erts/emulator/beam/jit/arm/beam_asm_global.hpp.pl
  erts/emulator/beam/jit/arm/instr_bs.cpp
  erts/emulator/beam/jit/x86/beam_asm_global.hpp.pl
  erts/emulator/beam/jit/x86/instr_bs.cpp
  erts/emulator/test/bs_utf_SUITE.erl
  erts/emulator/test/bs_utf_SUITE_data/NormalizationTest.txt
Labels: team:VM, enhancement, testing

#6615 system: Clarify documentation for enabling 'maybe'
  system/doc/reference_manual/expressions.xml
Labels: team:VM, enhancement, testing

#6637 Fix failed assertion in debug build
  erts/emulator/beam/jit/x86/instr_common.cpp
  erts/emulator/test/guard_SUITE.erl
Labels: team:VM, fix, testing

#6579 Improve specs and docs for maps:groups_from_list/2,3
  lib/stdlib/doc/src/maps.xml
  lib/stdlib/src/maps.erl
Labels: team:VM, enhancement

#6620 Augment CONTRIBUTING.md
  CONTRIBUTING.md
Labels: team:VM

#6644 beam_ssa_opt: Don't optimize constants larger than 1<<24 bits
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/test/bs_construct_SUITE.erl
Labels: team:VM, testing, bug

#6646 jit: Fix buggy assertion in bs_get_float2
  erts/emulator/beam/jit/arm/instr_bs.cpp
  erts/emulator/beam/jit/x86/instr_bs.cpp
Labels: team:VM, testing

#6500 Kuba/ssl/add trace profiles/otp 18312
  lib/ssl/src/dtls_connection.erl
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_certificate.erl
  lib/ssl/src/ssl_gen_statem.erl
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/src/ssl_trace.erl
  lib/ssl/src/tls_connection.erl
  lib/ssl/src/tls_connection_1_3.erl
  lib/ssl/src/tls_dtls_connection.erl
  lib/ssl/src/tls_sender.erl
  lib/ssl/src/tls_server_session_ticket.erl
  lib/ssl/src/tls_v1.erl
  lib/ssl/test/ssl_test_lib.erl
  lib/ssl/test/ssl_trace_SUITE.erl
Labels: team:PS, enhancement, testing

#6642 sys_core_fold: Remove problematic optimization
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/sys_core_fold.erl
  lib/compiler/test/core_fold_SUITE.erl
Labels: team:VM, fix, testing

#6652 Fix more buggy assertions
  erts/emulator/beam/jit/arm/beam_asm.hpp
  erts/emulator/beam/jit/arm/beam_asm_global.cpp
  erts/emulator/beam/jit/arm/instr_bif.cpp
  erts/emulator/beam/jit/arm/instr_bs.cpp
  erts/emulator/beam/jit/arm/instr_call.cpp
  erts/emulator/beam/jit/arm/instr_common.cpp
  erts/emulator/beam/jit/arm/instr_fun.cpp
  erts/emulator/beam/jit/arm/instr_map.cpp
  erts/emulator/beam/jit/arm/instr_msg.cpp
  erts/emulator/beam/jit/arm/instr_trace.cpp
  erts/emulator/beam/jit/x86/beam_asm.hpp
  erts/emulator/beam/jit/x86/beam_asm_global.cpp
  erts/emulator/beam/jit/x86/instr_bif.cpp
  erts/emulator/beam/jit/x86/instr_bs.cpp
  erts/emulator/beam/jit/x86/instr_call.cpp
  erts/emulator/beam/jit/x86/instr_common.cpp
  erts/emulator/beam/jit/x86/instr_fun.cpp
  erts/emulator/beam/jit/x86/instr_map.cpp
  erts/emulator/beam/jit/x86/instr_msg.cpp
  erts/emulator/beam/jit/x86/instr_trace.cpp
Labels: team:VM, enhancement, testing

#6647 public_key: fix pre2000 test with change of year 2023
  lib/public_key/test/pubkey_cert_SUITE.erl
Labels: team:PS, testing

#6654 Sets overloaded domains/contracts as an opt-in flag
  lib/dialyzer/src/dialyzer.erl
  lib/dialyzer/src/dialyzer.hrl
  lib/dialyzer/src/dialyzer_cl.erl
  lib/dialyzer/src/dialyzer_cl_parse.erl
  lib/dialyzer/src/dialyzer_contracts.erl
  lib/dialyzer/src/dialyzer_options.erl
  lib/dialyzer/test/default_ignore_overlapping_contract_SUITE_data/dialyzer_options
  lib/dialyzer/test/default_ignore_overlapping_contract_SUITE_data/results/default_ignore_overlapping_contract
  lib/dialyzer/test/default_ignore_overlapping_contract_SUITE_data/src/default_ignore_overlapping_contract.erl
  lib/dialyzer/test/indent_SUITE_data/dialyzer_options
  lib/dialyzer/test/indent_SUITE_data/results/contract3
  lib/dialyzer/test/overlapping_contract_SUITE_data/dialyzer_options
  lib/dialyzer/test/overlapping_contract_SUITE_data/results/overlapping_contract
  lib/dialyzer/test/overlapping_contract_SUITE_data/src/overlapping_contract.erl
  lib/dialyzer/test/small_SUITE_data/dialyzer_options
  lib/dialyzer/test/small_SUITE_data/results/contract3
  lib/stdlib/src/erl_lint.erl
Labels: team:VM, team:PS, testing, bug

#6611 Fix `ssh_connection_handler` logging of atoms
  lib/ssh/src/ssh_connection_handler.erl
  lib/ssh/src/ssh_transport.erl
Labels: team:PS, testing

#6663 Fix unsafe optimization of try...after
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/test/bs_match_SUITE.erl
Labels: team:VM, fix, testing

#6659 Fix crash in binary construction
  erts/emulator/beam/jit/arm/beam_asm.hpp
  erts/emulator/beam/jit/arm/instr_bs.cpp
  erts/emulator/beam/jit/x86/beam_asm.hpp
  erts/emulator/beam/jit/x86/instr_bs.cpp
  erts/emulator/test/bs_construct_SUITE.erl
Labels: team:VM, fix, testing

#6657 Do not allocate a new map when the value is the same encore
  erts/emulator/beam/beam_common.c
  erts/emulator/test/map_SUITE.erl
Labels: team:VM, enhancement, testing

#6670 inets: replace calls `size/1` to `XXX_size/1`
  lib/inets/src/http_client/httpc.erl
  lib/inets/src/http_client/httpc_handler.erl
  lib/inets/src/http_client/httpc_request.erl
  lib/inets/src/http_client/httpc_response.erl
  lib/inets/src/http_lib/http_chunk.erl
  lib/inets/src/http_lib/http_transport.erl
  lib/inets/src/http_server/httpd_request.erl
  lib/inets/src/http_server/mod_cgi.erl
  lib/inets/test/httpc_SUITE.erl
  lib/inets/test/httpd_bench_SUITE.erl
  lib/inets/test/httpd_poll.erl
  lib/inets/test/httpd_test_lib.erl
  lib/inets/test/httpd_time_test.erl
Labels: team:PS, enhancement, testing

#6673 public_key: replace calls to `size/1` function by `XXX_size/1`
  lib/public_key/src/public_key.erl
Labels: testing, bug

#6671 eunit: replace call to `size/1` function by `XXX_size/1`
  lib/eunit/src/eunit_data.erl
Labels: team:PS, enhancement

#6674 xmerl: replace calls `size/1` to `XXX_size/1`
  lib/xmerl/doc/examples/test_html.erl
Labels: team:PS, testing, bug

#6685 Include timing on -init_debug to further aid debugging
  erts/preloaded/src/init.erl
Labels: team:VM, enhancement

#6666 stdlib: remove unnecessary undefined from records
  lib/stdlib/src/supervisor.erl
Labels: team:PS, testing, documentation, bug

#6495 avoid crash when tracer = erts_tracer_nil
  erts/emulator/beam/erl_trace.c
Labels: team:VM, testing

#6649 dtls re-connections
  lib/ssl/src/dtls_connection.erl
  lib/ssl/src/dtls_gen_connection.erl
  lib/ssl/src/dtls_packet_demux.erl
  lib/ssl/src/dtls_record.erl
  lib/ssl/test/dtls_api_SUITE.erl
  lib/ssl/test/ssl_test_lib.erl
Labels: team:PS

#6695 mnesia: replace size/1 by XXX_size/1
  lib/mnesia/test/mnesia_consistency_test.erl
Labels: team:PS, enhancement, testing

#6632 Support for fully asynchronous distributed signaling
  erts/doc/src/erl_cmd.xml
  erts/doc/src/erlang.xml
  erts/emulator/beam/atom.names
  erts/emulator/beam/bif.c
  erts/emulator/beam/dist.c
  erts/emulator/beam/dist.h
  erts/emulator/beam/erl_bif_info.c
  erts/emulator/beam/erl_init.c
  erts/emulator/beam/erl_node_tables.c
  erts/emulator/beam/erl_node_tables.h
  erts/emulator/beam/erl_process.c
  erts/emulator/beam/erl_process.h
  erts/emulator/test/distribution_SUITE.erl
  erts/etc/common/erlexec.c
  erts/preloaded/ebin/erlang.beam
  erts/preloaded/src/erlang.erl
Labels: team:VM, enhancement, feature, testing

#6669 ct: Replace size/1 with either tuple_size/1 or byte_size/1
  lib/common_test/src/ct_framework.erl
  lib/common_test/src/ct_groups.erl
  lib/common_test/src/ct_netconfc.erl
  lib/common_test/src/ct_ssh.erl
  lib/common_test/src/ct_testspec.erl
  lib/common_test/src/ct_util.erl
  lib/common_test/test/test_server_SUITE.erl
Labels: team:PS, enhancement, testing

#6691 sasl: Replace calls to size/1 with tuple_size/1
  lib/sasl/src/systools_rc.erl
Labels: team:VM, enhancement, testing

#6625 kernel: Accept ver5 distribution connection setup
  erts/doc/src/erl_dist_protocol.xml
  lib/erl_interface/src/connect/ei_connect.c
  lib/erl_interface/src/epmd/ei_epmd.h
  lib/erl_interface/test/ei_tmo_SUITE.erl
  lib/jinterface/java_src/com/ericsson/otp/erlang/AbstractConnection.java
  lib/kernel/src/dist_util.erl
  lib/kernel/test/erl_distribution_wb_SUITE.erl
Labels: team:VM, fix, testing

#6507 stdlib/timer: better resolution control
  lib/stdlib/doc/src/timer.xml
  lib/stdlib/src/timer.erl
  lib/stdlib/test/timer_simple_SUITE.erl
Labels: team:VM, testing

#6713 Eliminate compiler crash in binary construction
  lib/compiler/src/v3_core.erl
  lib/compiler/test/bs_construct_SUITE.erl
Labels: team:VM, fix, testing

#6714 Fix crash in garbage collection
  erts/emulator/beam/beam_debug.c
  erts/emulator/beam/emu/bs_instrs.tab
  erts/emulator/beam/erl_gc.c
  erts/emulator/beam/erl_gc.h
  erts/emulator/test/bs_match_int_SUITE.erl
Labels: team:VM, fix, testing

#6590 BEAM SSA checker
  lib/compiler/doc/src/Makefile
  lib/compiler/doc/src/compile.xml
  lib/compiler/doc/src/internal.xml
  lib/compiler/internal_doc/ssa_checks.md
  lib/compiler/src/Makefile
  lib/compiler/src/beam_kernel_to_ssa.erl
  lib/compiler/src/beam_ssa_check.erl
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/src/cerl.erl
  lib/compiler/src/cerl_trees.erl
  lib/compiler/src/compile.erl
  lib/compiler/src/compiler.app.src
  lib/compiler/src/core_parse.hrl
  lib/compiler/src/core_pp.erl
  lib/compiler/src/sys_core_fold.erl
  lib/compiler/src/v3_core.erl
  lib/compiler/src/v3_kernel.erl
  lib/compiler/src/v3_kernel.hrl
  lib/compiler/src/v3_kernel_pp.erl
  lib/compiler/test/Makefile
  lib/compiler/test/beam_ssa_check_SUITE.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/annotations.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/gen_bs_size_unit_checks.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/sanity_checks.erl
  lib/stdlib/doc/src/epp.xml
  lib/stdlib/doc/src/erl_scan.xml
  lib/stdlib/src/epp.erl
  lib/stdlib/src/erl_expand_records.erl
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/src/erl_parse.yrl
  lib/stdlib/src/erl_scan.erl
Labels: team:VM, enhancement, testing

#6684 dialyzer: replace size/1 by XXX_size/1
  lib/dialyzer/test/indent_SUITE_data/src/map_galore.erl
  lib/dialyzer/test/opaque_SUITE_data/src/ewgi/ewgi.hrl
  lib/dialyzer/test/opaque_SUITE_data/src/ewgi2/ewgi.hrl
  lib/dialyzer/test/options1_SUITE_data/src/compiler/cerl.erl
  lib/dialyzer/test/options1_SUITE_data/src/compiler/cerl_inline.erl
  lib/dialyzer/test/user_SUITE_data/src/wsp_pdu.erl
Labels: team:VM, team:PS, enhancement, testing, bug

#6705 Use code:del_path/1 on erl_compile_server
  lib/kernel/src/erl_compile_server.erl
Labels: team:VM, enhancement, testing

#6151 Use in-memory atom ordering for map ordering
  erts/emulator/beam/beam_common.c
  erts/emulator/beam/beam_transform_helpers.c
  erts/emulator/beam/dist.c
  erts/emulator/beam/erl_map.c
  erts/emulator/beam/erl_map.h
  erts/emulator/beam/erl_utils.h
  erts/emulator/beam/external.c
  erts/emulator/beam/utils.c
  erts/emulator/test/map_SUITE.erl
  lib/kernel/test/logger_formatter_SUITE.erl
  lib/stdlib/test/io_SUITE.erl
Labels: team:VM, enhancement, testing

#6688 Also normalize expand_fun when set via io:setopts
  lib/kernel/src/group.erl
Labels: team:VM, fix, testing

#6651 compiler: Various type-related fixes and improvements
  lib/compiler/src/beam_bounds.erl
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/src/beam_types.erl
  lib/compiler/src/beam_validator.erl
  lib/compiler/test/beam_bounds_SUITE.erl
  lib/compiler/test/beam_type_SUITE.erl
  lib/compiler/test/bs_match_SUITE.erl
Labels: team:VM, testing

#6700 kernel: replace calls to size/1 by XXX_size/1
  lib/kernel/test/gen_udp_SUITE.erl
Labels: team:VM, enhancement, testing

#6726 jit: Fix float negation on x64
  erts/emulator/beam/emu/float_instrs.tab
  erts/emulator/beam/jit/arm/instr_float.cpp
  erts/emulator/beam/jit/x86/instr_float.cpp
  erts/emulator/test/float_SUITE.erl
Labels: team:VM, fix, testing

#6735 Fix failed matching of integer with unoptimized code
  erts/emulator/beam/jit/arm/instr_bs.cpp
  erts/emulator/beam/jit/x86/instr_bs.cpp
  erts/emulator/test/bs_match_int_SUITE.erl
Labels: team:VM, fix, testing

#6734 Remove dead code from code module
  lib/kernel/src/code.erl
Labels: team:VM, enhancement, testing

#6696 ssh: replace size/1 by XXX_size/1
  lib/ssh/src/ssh.erl
  lib/ssh/src/ssh_dbg.erl
  lib/ssh/src/ssh_options.erl
  lib/ssh/test/ssh_basic_SUITE.erl
Labels: team:PS, feature, testing

#6694 snmp: replace size/1 by XXX_size/1
  lib/snmp/src/agent/snmpa_net_if.erl
  lib/snmp/test/snmp_agent_SUITE.erl
  lib/snmp/test/snmp_test_lib.erl
  lib/snmp/test/snmp_test_mgr.erl
  lib/snmp/test/snmp_test_mgr_misc.erl
Labels: team:PS, enhancement, testing

#6738 jit: Turn various type hint bugs into compile-time errors
  erts/emulator/beam/beam_types.c
  erts/emulator/beam/beam_types.h
  erts/emulator/beam/jit/arm/beam_asm.hpp
  erts/emulator/beam/jit/arm/beam_asm_module.cpp
  erts/emulator/beam/jit/arm/instr_arith.cpp
  erts/emulator/beam/jit/arm/instr_bs.cpp
  erts/emulator/beam/jit/arm/instr_common.cpp
  erts/emulator/beam/jit/arm/instr_float.cpp
  erts/emulator/beam/jit/arm/instr_fun.cpp
  erts/emulator/beam/jit/arm/instr_guard_bifs.cpp
  erts/emulator/beam/jit/arm/instr_map.cpp
  erts/emulator/beam/jit/arm/instr_select.cpp
  erts/emulator/beam/jit/beam_jit_common.hpp
  erts/emulator/beam/jit/x86/beam_asm.hpp
  erts/emulator/beam/jit/x86/instr_arith.cpp
  erts/emulator/beam/jit/x86/instr_bs.cpp
  erts/emulator/beam/jit/x86/instr_common.cpp
  erts/emulator/beam/jit/x86/instr_float.cpp
  erts/emulator/beam/jit/x86/instr_fun.cpp
  erts/emulator/beam/jit/x86/instr_guard_bifs.cpp
  erts/emulator/beam/jit/x86/instr_map.cpp
  erts/emulator/beam/jit/x86/instr_select.cpp
Labels: team:VM, enhancement, testing

#6741 Fix typo in lib/stdlib/test/erl_lint_SUITE.erl
  lib/stdlib/test/erl_lint_SUITE.erl
Labels: team:VM

#6718 Add maps:iterator/2 with ~k and ~K format options for printing ordered maps.
  erts/emulator/beam/erl_map.c
  erts/preloaded/src/erts_internal.erl
  lib/stdlib/doc/src/io.xml
  lib/stdlib/doc/src/io_lib.xml
  lib/stdlib/doc/src/maps.xml
  lib/stdlib/src/erl_stdlib_errors.erl
  lib/stdlib/src/io_lib.erl
  lib/stdlib/src/io_lib_format.erl
  lib/stdlib/src/io_lib_pretty.erl
  lib/stdlib/src/maps.erl
  lib/stdlib/test/io_SUITE.erl
  lib/stdlib/test/maps_SUITE.erl
Labels: team:VM, feature, testing

#6743 Deprecate `file:pid2name/1`
  bootstrap/lib/stdlib/ebin/otp_internal.beam
  lib/kernel/doc/src/file.xml
  lib/kernel/src/file.erl
  lib/stdlib/src/otp_internal.erl
  system/doc/general_info/DEPRECATIONS
Labels: team:VM, testing

#6731 JIT: Miscellaneous optimizations
  erts/emulator/beam/erl_bif_guard.c
  erts/emulator/beam/jit/arm/beam_asm.hpp
  erts/emulator/beam/jit/arm/instr_call.cpp
  erts/emulator/beam/jit/arm/instr_common.cpp
  erts/emulator/beam/jit/arm/instr_guard_bifs.cpp
  erts/emulator/beam/jit/arm/ops.tab
  erts/emulator/beam/jit/x86/beam_asm.hpp
  erts/emulator/beam/jit/x86/instr_common.cpp
  erts/emulator/beam/jit/x86/instr_guard_bifs.cpp
  erts/emulator/beam/jit/x86/ops.tab
  erts/emulator/test/bif_SUITE.erl
Labels: team:VM, enhancement

#6702 diameter: replace size/1 by XXX_size/1
  lib/diameter/src/base/diameter_codec.erl
  lib/diameter/src/base/diameter_lib.erl
  lib/diameter/src/base/diameter_types.erl
  lib/diameter/src/info/diameter_info.erl
  lib/diameter/test/diameter_codec_test.erl
  lib/diameter/test/diameter_gen_tcp_SUITE.erl
Labels: team:VM, enhancement, testing

#6750 Add reversed iterators for maps
  lib/stdlib/doc/src/io.xml
  lib/stdlib/doc/src/io_lib.xml
  lib/stdlib/doc/src/maps.xml
  lib/stdlib/src/io_lib_format.erl
  lib/stdlib/src/maps.erl
  lib/stdlib/test/io_SUITE.erl
  lib/stdlib/test/maps_SUITE.erl
Labels: team:VM, testing

#6753 erl_lint: Support the new modifiers for ordered maps
  bootstrap/lib/stdlib/ebin/erl_lint.beam
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/test/erl_lint_SUITE.erl
  lib/stdlib/test/io_SUITE.erl
Labels: team:VM, fix, testing

#6754 dialyzer: Print map entries in deterministic (sorted) order
  lib/dialyzer/src/dialyzer_utils.erl
Labels: team:VM, fix, testing

#6756 Don't break bs_match sequences by mixing registers (again)
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/test/bs_match_SUITE.erl
Labels: team:VM, fix, testing

#6746 ssh: reduce log length
  lib/ssh/src/ssh_connection_handler.erl
Labels: team:PS
