Repository erlang/otp, pull requests merged in 2023-02, with the labels that each got.

#6716 prim_file:read_file_info/2 avoid copying the record for posix time read
  erts/preloaded/src/prim_file.erl
Labels: team:VM

#6628 erts: Add current stack trace to tracing
  erts/doc/src/match_spec.xml
  erts/emulator/beam/erl_db_util.c
  erts/emulator/test/match_spec_SUITE.erl
Labels: team:VM, testing

#6767 Update list of map functions consuming iterators
  lib/stdlib/doc/src/maps.xml
Labels: team:VM

#6760 Simplify some calls to application:get_env/2
  lib/kernel/src/error_logger.erl
  lib/kernel/src/group_history.erl
  lib/stdlib/src/shell.erl
Labels: team:VM, enhancement, testing

#6762 Simplify implementation of maps:to_list/1 for iterators
  lib/stdlib/src/maps.erl
  lib/stdlib/test/maps_SUITE.erl
Labels: team:VM, enhancement, testing

#6759 dialyzer: Do some minor optimizations and clean ups
  lib/dialyzer/src/dialyzer_callgraph.erl
  lib/dialyzer/src/dialyzer_codeserver.erl
  lib/dialyzer/src/dialyzer_coordinator.erl
  lib/dialyzer/src/dialyzer_dataflow.erl
  lib/dialyzer/src/dialyzer_typesig.erl
Labels: team:VM, enhancement, testing

#6749 [#6748] Unknown posix errors should include the error reason
  lib/kernel/src/erl_erts_errors.erl
  lib/kernel/src/erl_kernel_errors.erl
  lib/ssl/src/ssl.erl
  lib/stdlib/src/erl_posix_msg.erl
  lib/stdlib/src/erl_stdlib_errors.erl
Labels: team:VM, testing

#6698 [stdlib] Optimize gen_server:multi_call()
  lib/stdlib/src/gen_server.erl
  lib/stdlib/test/gen_server_SUITE.erl
Labels: team:VM, enhancement, testing

#6711 base64: allow skipping padding = characters
  lib/stdlib/doc/src/base64.xml
  lib/stdlib/src/base64.erl
  lib/stdlib/test/base64_SUITE.erl
  lib/stdlib/test/property_test/base64_prop.erl
Labels: team:VM

#6683 Default -code_path_choice to strict
  erts/preloaded/src/init.erl
Labels: team:VM, enhancement, testing

#6397 Observer Improvements
  lib/observer/doc/src/observer.xml
  lib/observer/src/observer.erl
  lib/observer/src/observer_wx.erl
  lib/observer/test/observer_SUITE.erl
Labels: team:PS, testing

#6744 jit: Issue ISBs on all schedulers when loading code
  erts/config.h.in
  erts/configure
  erts/emulator/beam/beam_bif_load.c
  erts/emulator/beam/beam_bp.c
  erts/emulator/beam/bif.c
  erts/emulator/beam/code_ix.c
  erts/emulator/beam/code_ix.h
  erts/emulator/beam/emu/beam_emu.c
  erts/emulator/beam/erl_bif_trace.c
  erts/emulator/beam/erl_nfunc_sched.c
  erts/emulator/beam/erl_nfunc_sched.h
  erts/emulator/beam/erl_nif.c
  erts/emulator/beam/erl_thr_progress.c
  erts/emulator/beam/erl_threads.h
  erts/emulator/beam/export.c
  erts/emulator/beam/jit/arm/beam_asm.hpp
  erts/emulator/beam/jit/arm/beam_asm_module.cpp
  erts/emulator/beam/jit/arm/instr_bif.cpp
  erts/emulator/beam/jit/arm/instr_common.cpp
  erts/emulator/beam/jit/arm/instr_msg.cpp
  erts/emulator/beam/jit/arm/instr_trace.cpp
  erts/emulator/beam/jit/asm_load.c
  erts/emulator/beam/jit/beam_asm.h
  erts/emulator/beam/jit/beam_jit_common.cpp
  erts/emulator/beam/jit/beam_jit_main.cpp
  erts/emulator/beam/jit/x86/beam_asm.hpp
  erts/emulator/beam/jit/x86/beam_asm_global.cpp
  erts/emulator/beam/jit/x86/beam_asm_global.hpp.pl
  erts/emulator/beam/jit/x86/beam_asm_module.cpp
  erts/emulator/beam/jit/x86/instr_bif.cpp
  erts/emulator/beam/jit/x86/instr_call.cpp
  erts/emulator/beam/jit/x86/instr_common.cpp
  erts/emulator/beam/jit/x86/instr_msg.cpp
  erts/emulator/beam/jit/x86/instr_trace.cpp
  erts/emulator/internal_doc/BeamAsm.md
  erts/include/internal/ethread.h
  erts/include/internal/ethread_header_config.h.in
  erts/include/internal/gcc/ethr_membar.h
  erts/include/internal/i386/ethr_membar.h
  erts/include/internal/win/ethr_membar.h
  erts/lib_src/common/ethr_aux.c
Labels: team:VM, fix

#6739 Optimize gen:send_request/3 + gen:wait_response/2 sequences
  lib/compiler/src/beam_ssa_recv.erl
  lib/compiler/test/receive_SUITE.erl
  lib/stdlib/src/gen.erl
Labels: team:VM, enhancement, testing

#6761 compiler: Print map entries in deterministic order
  lib/compiler/src/beam_listing.erl
  lib/compiler/src/beam_ssa_check.erl
  lib/compiler/src/beam_ssa_pp.erl
  lib/compiler/src/compiler.app.src
  lib/compiler/src/v3_kernel_pp.erl
Labels: team:VM, fix, testing

#6768 crypto: replace size/1 by byte_size/1
  lib/crypto/src/crypto.erl
Labels: team:PS, enhancement, testing

#6769 diameter: replace size/1 by xxx_size/1
  lib/diameter/src/base/diameter_peer_fsm.erl
  lib/diameter/src/info/diameter_dbg.erl
Labels: team:PS, enhancement, testing

#6784 inets: replace size/1 by xxx_size/1
  lib/inets/src/http_server/httpd_request_handler.erl
  lib/inets/src/http_server/httpd_util.erl
Labels: team:PS, enhancement

#6587 Update various file and installer properties
  erts/etc/common/Makefile.in
  erts/etc/win32/erl.rc
  erts/etc/win32/nsis/Makefile
  erts/etc/win32/nsis/erlang20.nsi
  erts/etc/win32/nsis/vsn_number.escript
  erts/etc/win32/version.h.src
Labels: team:PS, testing

#6785 mnesia: replace size/1 by xxx_size/1
  lib/mnesia/src/mnesia_index.erl
  lib/mnesia/src/mnesia_lib.erl
  lib/mnesia/src/mnesia_loader.erl
  lib/mnesia/src/mnesia_schema.erl
  lib/mnesia/src/mnesia_snmp_hook.erl
Labels: team:PS, enhancement

#6787 megaco: replace size/1 by xxx_size/1
  lib/megaco/src/engine/megaco_filter.erl
  lib/megaco/src/engine/megaco_messenger_misc.erl
  lib/megaco/src/engine/megaco_trans_sender.erl
  lib/megaco/src/flex/megaco_flex_scanner.erl
  lib/megaco/src/tcp/megaco_tcp.erl
  lib/megaco/src/tcp/megaco_tcp_connection.erl
  lib/megaco/src/udp/megaco_udp.erl
  lib/megaco/src/udp/megaco_udp_server.erl
Labels: team:PS, enhancement

#6777 Document -code_path_choice is scheduled for removal in OTP 27
  erts/doc/src/init.xml
  lib/kernel/doc/src/code.xml
  system/doc/general_info/scheduled_for_removal_27.inc
Labels: team:VM, testing

#6766 maps: always raise a `badmap` error if an iterator fails
  lib/stdlib/src/erl_stdlib_errors.erl
  lib/stdlib/src/maps.erl
  lib/stdlib/test/maps_SUITE.erl
Labels: team:VM, testing

#6715 Remove the file_io_servers ETS table
  lib/kernel/src/file.erl
  lib/kernel/src/file_io_server.erl
  lib/kernel/src/file_server.erl
  lib/kernel/test/file_SUITE.erl
  lib/stdlib/test/error_logger_h_SUITE.erl
Labels: team:VM, testing

#6727 Implement map comprehensions (EEP-58)
  erts/doc/src/absform.xml
  erts/preloaded/ebin/erts_internal.beam
  erts/preloaded/src/erts_internal.erl
  lib/compiler/src/v3_core.erl
  lib/compiler/test/Makefile
  lib/compiler/test/bs_bincomp_SUITE.erl
  lib/compiler/test/lc_SUITE.erl
  lib/compiler/test/mc_SUITE.erl
  lib/compiler/test/record_SUITE.erl
  lib/stdlib/examples/erl_id_trans.erl
  lib/stdlib/src/erl_eval.erl
  lib/stdlib/src/erl_expand_records.erl
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/src/erl_parse.yrl
  lib/stdlib/src/erl_pp.erl
  lib/stdlib/test/erl_eval_SUITE.erl
  lib/stdlib/test/erl_pp_SUITE.erl
  lib/syntax_tools/src/erl_prettypr.erl
  lib/syntax_tools/src/erl_syntax.erl
  lib/syntax_tools/test/syntax_tools_SUITE_data/syntax_tools_SUITE_test_module.erl
  system/doc/reference_manual/expressions.xml
Labels: team:VM, enhancement, testing

#6793 ftp: replace size/1 by XXX_size/1
  lib/ftp/src/ftp.erl
  lib/ftp/src/ftp_response.erl
Labels: team:PS, enhancement

#6794 crypto: fix error bit_size/1 by byte_size/1
  lib/crypto/src/crypto.erl
Labels: team:PS, enhancement, testing

#6774 erts: Add `+JPperf no_fp` option to suppress frame pointers
  erts/doc/src/erl_cmd.xml
  erts/emulator/beam/erl_init.c
  erts/emulator/beam/jit/beam_asm.h
  erts/emulator/beam/jit/beam_jit_main.cpp
Labels: team:VM, testing

#6797 ssh: replace size/1 by xxx_size/1
  lib/ssh/src/ssh.hrl
  lib/ssh/src/ssh_agent.erl
  lib/ssh/src/ssh_bits.erl
  lib/ssh/src/ssh_client_channel.erl
  lib/ssh/src/ssh_connection.erl
  lib/ssh/src/ssh_connection_handler.erl
  lib/ssh/src/ssh_file.erl
  lib/ssh/src/ssh_sftp.erl
  lib/ssh/src/ssh_transport.erl
  lib/ssh/src/ssh_xfer.erl
Labels: team:PS, enhancement, testing

#6796 xmerl: replace size/1 by xxx_size/1
  lib/xmerl/src/xmerl_eventp.erl
Labels: team:PS, enhancement, testing

#6522 [erts, kernel] reuseaddr/reuseport/exclusiveaddruse support/fixes
  erts/emulator/drivers/common/inet_drv.c
  erts/preloaded/ebin/prim_inet.beam
  erts/preloaded/src/erts.app.src
  erts/preloaded/src/prim_inet.erl
  lib/kernel/doc/src/inet.xml
  lib/kernel/src/gen_sctp.erl
  lib/kernel/src/gen_tcp.erl
  lib/kernel/src/gen_udp.erl
  lib/kernel/src/inet.erl
  lib/kernel/src/inet_int.hrl
  lib/kernel/src/kernel.app.src
  lib/kernel/test/inet_sockopt_SUITE.erl
Labels: team:PS, enhancement, fix, testing

#6752 ets:insert/2 insert order preserved when list with same keys for bag table
  erts/emulator/beam/erl_db.c
  erts/emulator/beam/erl_db_catree.c
  erts/emulator/beam/erl_db_hash.c
  erts/emulator/beam/erl_db_tree.c
  erts/emulator/beam/erl_db_tree_util.h
  erts/emulator/beam/erl_db_util.h
  lib/stdlib/doc/src/ets.xml
  lib/stdlib/test/ets_SUITE.erl
Labels: team:VM, fix, testing

#6798 ssl: replace size/1 by xxx_size/1
  lib/ssl/src/ssl_cipher.erl
Labels: team:PS, enhancement, testing

#6799 tftp: replace size/1 by xxx_size/1
  lib/tftp/src/tftp_binary.erl
  lib/tftp/src/tftp_engine.erl
  lib/tftp/src/tftp_file.erl
  lib/tftp/src/tftp_lib.erl
Labels: team:PS, enhancement, testing

#6800 snmp: replace size/1 by xxx_size/1
  lib/snmp/src/agent/snmp_generic_mnesia.erl
  lib/snmp/src/agent/snmp_index.erl
  lib/snmp/src/agent/snmpa_local_db.erl
  lib/snmp/src/agent/snmpa_mib_data_ttln.erl
  lib/snmp/src/agent/snmpa_mib_data_tttn.erl
  lib/snmp/src/agent/snmpa_mpd.erl
  lib/snmp/src/manager/snmpm_net_if.erl
  lib/snmp/src/misc/snmp_pdus.erl
Labels: team:PS, enhancement, testing

#6801 Fix compiler crash for literal map generator patterns
  lib/compiler/src/v3_core.erl
  lib/compiler/test/mc_SUITE.erl
Labels: team:VM, fix, testing

#6790 Remove HiPE info from system_information.erl
  lib/runtime_tools/src/system_information.erl
  lib/runtime_tools/test/system_information_SUITE.erl
Labels: team:VM, testing

#6802 cover: Support map comprehensions
  lib/tools/src/cover.erl
  lib/tools/test/cover_SUITE.erl
Labels: team:VM, enhancement, testing

#6814 ssl: replace size/1 by xxx_size/1
  lib/ssl/src/ssl_trace.erl
  lib/ssl/src/tls_gen_connection.erl
Labels: enhancement

#6815 erts_internal: Avoiding breaking opacity for iterators
  erts/preloaded/ebin/erts_internal.beam
  erts/preloaded/src/erts_internal.erl
Labels: team:VM, fix, testing

#6803 Simplify some compiler code by using map comprehensions
  lib/compiler/src/beam_clean.erl
  lib/compiler/src/beam_ssa.erl
  lib/compiler/src/beam_ssa_bc_size.erl
  lib/compiler/src/beam_ssa_bool.erl
  lib/compiler/src/beam_ssa_check.erl
  lib/compiler/src/beam_ssa_dead.erl
  lib/compiler/src/beam_ssa_lint.erl
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/beam_ssa_pp.erl
  lib/compiler/src/beam_ssa_pre_codegen.erl
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/src/beam_trim.erl
  lib/compiler/src/cerl.erl
  lib/compiler/src/compile.erl
  lib/compiler/src/core_pp.erl
  lib/compiler/src/sys_core_fold.erl
Labels: team:VM, enhancement, testing

#6351 [erts] Implement call_memory tracing
  erts/doc/src/erlang.xml
  erts/emulator/beam/atom.names
  erts/emulator/beam/beam_bp.c
  erts/emulator/beam/beam_bp.h
  erts/emulator/beam/beam_common.c
  erts/emulator/beam/beam_common.h
  erts/emulator/beam/emu/beam_emu.c
  erts/emulator/beam/emu/ops.tab
  erts/emulator/beam/emu/trace_instrs.tab
  erts/emulator/beam/erl_bif_trace.c
  erts/emulator/beam/erl_gc.c
  erts/emulator/beam/erl_message.c
  erts/emulator/beam/erl_process.c
  erts/emulator/beam/erl_process.h
  erts/emulator/beam/erl_trace.h
  erts/emulator/beam/erl_vm.h
  erts/emulator/beam/jit/arm/instr_trace.cpp
  erts/emulator/beam/jit/arm/ops.tab
  erts/emulator/beam/jit/beam_jit_common.cpp
  erts/emulator/beam/jit/beam_jit_main.cpp
  erts/emulator/beam/jit/x86/instr_trace.cpp
  erts/emulator/beam/jit/x86/ops.tab
  erts/emulator/internal_doc/Tracing.md
  erts/emulator/test/Makefile
  erts/emulator/test/trace_call_memory_SUITE.erl
  erts/emulator/test/trace_call_time_SUITE.erl
  erts/etc/unix/etp.py
  erts/preloaded/src/erlang.erl
Labels: team:VM, feature, testing

#6693 Remove archives fallback in code path
  lib/kernel/doc/src/code.xml
  lib/kernel/src/code_server.erl
  lib/kernel/test/code_SUITE.erl
  system/doc/general_info/scheduled_for_removal_26.inc
Labels: team:VM, testing

#6786 Update inet_res et.al. for RFC6891; EDNS with DNSSEC OK bit
  lib/kernel/src/inet_db.erl
  lib/kernel/src/inet_dns.erl
  lib/kernel/src/inet_dns.hrl
  lib/kernel/src/inet_dns_record_adts.pl
  lib/kernel/src/inet_res.erl
Labels: team:PS

#6812 diameter: update appup files
  lib/diameter/src/diameter.appup.src
Labels: team:PS, enhancement, testing

#6035 Add application:get_supervisor/1
  lib/kernel/doc/src/application.xml
  lib/kernel/src/application.erl
  lib/kernel/src/application_master.erl
  lib/kernel/test/application_SUITE.erl
Labels: team:VM, testing

#6830 diameter: remove duplicate entries in appup
  lib/diameter/src/diameter.appup.src
Labels: team:PS, testing, bug

#6822 dialyzer: make -Wunknown a default; add -Wno_unknown flag
  lib/dialyzer/doc/src/dialyzer.xml
  lib/dialyzer/src/dialyzer.hrl
  lib/dialyzer/src/dialyzer_cl_parse.erl
  lib/dialyzer/src/dialyzer_options.erl
  lib/dialyzer/test/cplt_SUITE.erl
  lib/dialyzer/test/dialyzer_cl_SUITE.erl
  lib/dialyzer/test/dialyzer_common.erl
  lib/dialyzer/test/incremental_SUITE.erl
  lib/dialyzer/test/indent2_SUITE_data/dialyzer_options
  lib/dialyzer/test/indent_SUITE_data/dialyzer_options
  lib/dialyzer/test/iplt_SUITE.erl
  lib/dialyzer/test/line_SUITE_data/dialyzer_options
  lib/dialyzer/test/map_SUITE_data/dialyzer_options
  lib/dialyzer/test/opaque_SUITE_data/dialyzer_options
  lib/dialyzer/test/options1_SUITE_data/dialyzer_options
  lib/dialyzer/test/options2_SUITE_data/dialyzer_options
  lib/dialyzer/test/r9c_SUITE_data/dialyzer_options
  lib/dialyzer/test/small_SUITE_data/dialyzer_options
  lib/dialyzer/test/underspecs_SUITE_data/dialyzer_options
  lib/dialyzer/test/user_SUITE_data/dialyzer_options
  lib/stdlib/src/erl_lint.erl
Labels: team:VM, team:PS, enhancement, testing

#6819 STDLIB tests: Fix falling map iterator tests in debug build
  lib/stdlib/test/io_SUITE.erl
  lib/stdlib/test/maps_SUITE.erl
Labels: team:VM, fix, testing

#6818 dialyzer: Fix ordinal for numbers over twenty
  lib/dialyzer/src/dialyzer.erl
Labels: team:VM, fix, testing

#6810 Do not emit "unexpected" message on shutdown
  lib/ssl/src/inet_tls_dist.erl
Labels: team:PS

#6833 ftp: fix forgotten guard
  lib/ftp/src/ftp.erl
Labels: team:PS, bug

#6827 60-bit process/port identifiers on 64-bit runtime
  erts/emulator/beam/erl_node_container_utils.h
  erts/emulator/beam/erl_ptab.c
  erts/emulator/beam/erl_ptab.h
  erts/emulator/beam/erl_term.h
  erts/emulator/test/a_SUITE.erl
  erts/emulator/test/erts_test_utils.erl
  erts/emulator/test/hash_SUITE.erl
  erts/emulator/test/monitor_SUITE.erl
  erts/emulator/test/node_container_SUITE.erl
  erts/emulator/test/process_SUITE.erl
Labels: team:VM, enhancement, testing

#6736 Reduce contention on the code_server
  lib/kernel/src/code.erl
  lib/kernel/src/code_server.erl
Labels: team:VM, testing

#6737 Start children applications concurrently
  lib/kernel/doc/src/application.xml
  lib/kernel/src/application.erl
  lib/kernel/src/application_controller.erl
  lib/kernel/test/application_SUITE.erl
Labels: team:VM, testing

#6841 diameter: replace size/1 by xxx_size/1
  lib/diameter/src/info/diameter_dbg.erl
Labels: team:PS, enhancement

#6834 Make emacs handle map-comprehensions
  lib/tools/emacs/erlang.el
  lib/tools/test/emacs_SUITE_data/comprehensions
Labels: testing

#6795 ssl: Maximize compatibility
  lib/ssl/src/tls_connection_1_3.erl
Labels: team:PS, testing

#6840 ssl: Mitigate memory usage from large certificate chains
  lib/ssl/src/ssl_handshake.hrl
Labels: team:PS, testing

#6729 Add code path caching
  erts/preloaded/src/erl_prim_loader.erl
  lib/kernel/doc/src/code.xml
  lib/kernel/src/code.erl
  lib/kernel/src/code_server.erl
  lib/kernel/test/code_SUITE.erl
Labels: team:VM, testing

#6832 Revert #6683 and #6777
  erts/doc/src/init.xml
  erts/preloaded/ebin/erlang.beam
  erts/preloaded/ebin/erts_internal.beam
  erts/preloaded/ebin/prim_inet.beam
  erts/preloaded/src/init.erl
  lib/kernel/doc/src/code.xml
  lib/kernel/src/code_server.erl
  lib/kernel/test/code_SUITE.erl
  system/doc/general_info/scheduled_for_removal_26.inc
  system/doc/general_info/scheduled_for_removal_27.inc
Labels: team:VM, fix, testing

#6838 Fix crash when matching out empty binaries
  erts/emulator/beam/jit/arm/instr_bs.cpp
  erts/emulator/beam/jit/x86/instr_bs.cpp
  erts/emulator/test/bs_match_bin_SUITE.erl
Labels: team:VM, fix, testing

#6804 `private_append` optimization for binaries
  lib/compiler/src/Makefile
  lib/compiler/src/beam_ssa_alias.erl
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/beam_ssa_pp.erl
  lib/compiler/src/beam_ssa_private_append.erl
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/src/beam_types.erl
  lib/compiler/src/beam_types.hrl
  lib/compiler/src/compile.erl
  lib/compiler/src/compiler.app.src
  lib/compiler/test/beam_ssa_check_SUITE.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/alias.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/appendable.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/gen_bs_size_unit_checks.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/private_append.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/ret_annotation.erl
  lib/compiler/test/beam_types_SUITE.erl
  lib/compiler/test/compile_SUITE.erl
  lib/compiler/test/compile_SUITE_data/annotations_pp.erl
  lib/compiler/test/property_test/beam_types_prop.erl
Labels: team:VM, enhancement

#6831 Don't require compile-time features to be enabled in the runtime
  erts/preloaded/ebin/erlang.beam
  erts/preloaded/src/erlang.erl
  erts/test/erlc_SUITE.erl
  lib/stdlib/src/erl_features.erl
Labels: team:VM, enhancement, testing

#6816 Minor gc fixes related to max_heap_size
  erts/emulator/beam/bif.h
  erts/emulator/beam/erl_gc.c
  erts/emulator/beam/erl_process.c
  erts/emulator/test/gc_SUITE.erl
Labels: team:VM, fix, testing

#6392 ssl: implement use_srtp hello extension with options
  lib/ssl/doc/src/ssl.xml
  lib/ssl/doc/src/standards_compliance.xml
  lib/ssl/src/dtls_handshake.hrl
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/src/ssl_handshake.hrl
  lib/ssl/test/Makefile
  lib/ssl/test/property_test/ssl_eqc_handshake.erl
  lib/ssl/test/ssl_api_SUITE.erl
  lib/ssl/test/ssl_test_lib.erl
  lib/ssl/test/ssl_use_srtp_SUITE.erl
Labels: team:PS, testing

#6839 AArch64 JIT: Fix crash in bxor/2
  erts/emulator/beam/jit/arm/instr_arith.cpp
  erts/emulator/test/small_SUITE.erl
Labels: team:VM, fix, testing

#6821 Ingela/ssl/no sha1 per default and doc enhancments/gh 6679/otp 18438
  lib/inets/test/httpc_SUITE.erl
  lib/inets/test/httpc_proxy_SUITE.erl
  lib/inets/test/httpd_SUITE.erl
  lib/ssl/doc/src/ssl.xml
  lib/ssl/doc/src/standards_compliance.xml
  lib/ssl/src/ssl.erl
  lib/ssl/src/tls_v1.erl
  lib/ssl/test/openssl_cipher_suite_SUITE.erl
  lib/ssl/test/property_test/ssl_eqc_chain.erl
  lib/ssl/test/ssl_api_SUITE.erl
  lib/ssl/test/ssl_basic_SUITE.erl
  lib/ssl/test/ssl_cert_SUITE.erl
  lib/ssl/test/ssl_cert_tests.erl
  lib/ssl/test/ssl_cipher_suite_SUITE.erl
  lib/ssl/test/ssl_dist_SUITE.erl
  lib/ssl/test/ssl_dist_bench_SUITE.erl
  lib/ssl/test/ssl_pem_cache_SUITE.erl
  lib/ssl/test/ssl_sni_SUITE.erl
  lib/ssl/test/ssl_test_lib.erl
Labels: team:PS, testing

#6860 Remove HiPE note about module MD5 checksum
  system/doc/reference_manual/modules.xml
Labels: team:VM, fix

#6861 ssl: Adjust assert of middlebox change_cipher_spec for better interop
  lib/ssl/src/tls_client_connection_1_3.erl
Labels: team:PS, testing

#6689 os_mon: Close cpu_sup and memsup port on terminate
  lib/os_mon/c_src/memsup.c
  lib/os_mon/c_src/memsup.h
  lib/os_mon/include/memsup.hrl
  lib/os_mon/src/cpu_sup.erl
  lib/os_mon/src/memsup.erl
Labels: team:VM, testing

#6878 Fix erts/test/erlc_SUITE.erl testcase warnings
  erts/test/erlc_SUITE.erl
Labels: team:VM

#6733 jit: Fix type hint error in emit_is_lt
  erts/emulator/beam/jit/arm/instr_common.cpp
  erts/emulator/beam/jit/x86/instr_common.cpp
  erts/emulator/test/op_SUITE.erl
Labels: team:VM, fix

#6806 process_info(Pid, status) fix
  erts/emulator/beam/erl_bif_info.c
Labels: team:VM, testing, bug

#6855 compiler: Don't generate unsafe code for binary append
  lib/compiler/src/beam_ssa_private_append.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/private_append.erl
Labels: team:VM, fix, testing

#6862 compiler: Avoid crash in private-append optimization
  lib/compiler/src/beam_ssa_private_append.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/private_append.erl
Labels: team:VM, fix, testing

#6876 compiler: Remove dead code from alias analysis pass
  lib/compiler/src/beam_ssa_alias.erl
Labels: team:VM, enhancement, testing

#6872 Cover more code in the compiler application
  lib/compiler/test/Makefile
  lib/compiler/test/andor_SUITE.erl
  lib/compiler/test/beam_block_SUITE.erl
  lib/compiler/test/beam_jump_SUITE.erl
  lib/compiler/test/beam_ssa_SUITE.erl
  lib/compiler/test/bs_bincomp_SUITE.erl
  lib/compiler/test/bs_match_SUITE.erl
  lib/compiler/test/core_alias_SUITE.erl
  lib/compiler/test/core_fold_SUITE.erl
  lib/compiler/test/fun_SUITE.erl
  lib/compiler/test/map_SUITE.erl
  lib/compiler/test/match_SUITE.erl
Labels: team:VM, enhancement, testing

#6869 binary: Polish the hex encoding and decoding functions
  lib/stdlib/src/binary.erl
  lib/stdlib/src/erl_stdlib_errors.erl
  lib/stdlib/test/binary_module_SUITE.erl
Labels: team:VM, enhancement, testing

#6877 Eliminate "mutable variables"
  lib/compiler/src/v3_core.erl
  lib/compiler/test/match_SUITE.erl
  lib/compiler/test/warnings_SUITE.erl
Labels: team:VM, fix, testing

#6875 compiler: Remove dead code from private-append optimization
  lib/compiler/src/beam_ssa_private_append.erl
Labels: team:VM, testing

#6880 otp_SUITE: Update tests for non-recommended functions
  erts/test/otp_SUITE.erl
Labels: team:VM, enhancement, testing

#6661 inets: add type specifications
  lib/inets/src/http_client/httpc_handler.erl
  lib/inets/src/http_client/httpc_internal.hrl
Labels: team:PS, feature, testing, documentation

#6891 Fix bad exception in map_get/2
  erts/emulator/beam/jit/arm/instr_guard_bifs.cpp
  erts/emulator/beam/jit/x86/instr_guard_bifs.cpp
  erts/emulator/test/map_SUITE.erl
Labels: team:VM, fix, testing

#6864 dialyzer: fix singleton type var in union types
  lib/common_test/src/ct_release_test.erl
  lib/kernel/src/wrap_log_reader.erl
  lib/ssl/src/ssl.erl
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/test/erl_lint_SUITE.erl
  lib/tools/src/xref.erl
Labels: team:VM, team:PS, testing, types

#6884 Removed unnecessary <em> tags
  lib/syntax_tools/src/erl_syntax_lib.erl
Labels: team:VM

#6894 Reference Manual: Use the change tag for clarity
  system/doc/reference_manual/character_set.xml
  system/doc/reference_manual/code_loading.xml
  system/doc/reference_manual/data_types.xml
  system/doc/reference_manual/distributed.xml
  system/doc/reference_manual/expressions.xml
  system/doc/reference_manual/features.xml
  system/doc/reference_manual/macros.xml
  system/doc/reference_manual/modules.xml
  system/doc/reference_manual/opaques.xml
  system/doc/reference_manual/ports.xml
  system/doc/reference_manual/processes.xml
  system/doc/reference_manual/records.xml
  system/doc/reference_manual/typespec.xml
Labels: team:VM, enhancement, testing

#6895 stdlib: Hibernate static supervisors
  lib/stdlib/src/supervisor.erl
  lib/stdlib/test/supervisor_SUITE.erl
Labels: team:PS, testing

#6904 inets: refactor code to improve readability
  lib/inets/src/http_client/httpc_handler.erl
Labels: team:PS, enhancement, testing

#6902 Ensure that the bs_match instruction can be extended
  erts/emulator/beam/beam_load.c
  erts/emulator/beam/emu/generators.tab
  erts/emulator/beam/emu/ops.tab
  erts/emulator/beam/jit/arm/generators.tab
  erts/emulator/beam/jit/arm/ops.tab
  erts/emulator/beam/jit/x86/generators.tab
  erts/emulator/beam/jit/x86/ops.tab
  erts/emulator/test/bs_match_misc_SUITE.erl
Labels: team:VM, enhancement, testing

#6823 Add del_paths/1, clear_cache/0, and cache arg
  lib/kernel/doc/src/code.xml
  lib/kernel/src/code.erl
  lib/kernel/src/code_server.erl
  lib/kernel/test/code_SUITE.erl
Labels: team:VM, testing

#6845 ssh: accept PKCS#8 host key
  lib/ssh/doc/src/ssh_file.xml
  lib/ssh/src/ssh_file.erl
  lib/ssh/test/ssh_pubkey_SUITE.erl
  lib/ssh/test/ssh_pubkey_SUITE_data/pkcs8/id_rsa
  lib/ssh/test/ssh_pubkey_SUITE_data/pkcs8/id_rsa.pub
  lib/ssh/test/ssh_pubkey_SUITE_data/pkcs8/ssh_host_rsa_key
  lib/ssh/test/ssh_pubkey_SUITE_data/pkcs8/ssh_host_rsa_key.pub
Labels: team:PS

#6879 Fix release_docs for GNU make 4.3
  system/doc/top/Makefile
Labels: team:VM, testing

#6545 ftp: fix types in ftp module
  lib/ftp/doc/specs/.gitignore
  lib/ftp/doc/src/Makefile
  lib/ftp/doc/src/ftp.xml
  lib/ftp/doc/src/specs.xml
  lib/ftp/src/Makefile
  lib/ftp/src/ftp.app.src
  lib/ftp/src/ftp.erl
  lib/ftp/src/ftp_internal.erl
  lib/ftp/src/ftp_sup.erl
  lib/ftp/test/ftp_SUITE.erl
Labels: team:PS, testing, documentation, bug

#6888 Add best practice for atoms in NIFs
  erts/doc/src/erl_nif.xml
Labels: team:VM, enhancement, testing, documentation

#6854 dialyzer: Fix crash when adding multiple PLTs
  lib/dialyzer/src/dialyzer_cl.erl
  lib/dialyzer/test/dialyzer_cl_SUITE.erl
Labels: team:VM, testing

#6881 Fix a bug that `file:read(standard_io, ..)` unexpectedly returns `eof`
  lib/kernel/src/group.erl
  lib/stdlib/src/io_lib.erl
Labels: team:VM, testing

#6842 beam_call_types: Infer range of various arithmetic operations
  lib/compiler/src/beam_call_types.erl
Labels: team:VM, testing

#6836 Remove archives support in reltool
  lib/reltool/doc/src/reltool.xml
  lib/reltool/doc/src/reltool_examples.xml
  lib/reltool/src/reltool.hrl
  lib/reltool/src/reltool_server.erl
  lib/reltool/src/reltool_target.erl
  lib/reltool/test/reltool_server_SUITE.erl
Labels: team:VM, testing

#6874 Fix map compare bug
  erts/emulator/beam/utils.c
  erts/emulator/test/map_SUITE.erl
Labels: team:VM, fix, testing

#6844 Improvements to ensure_modules_loaded/1
  lib/kernel/src/code.erl
Labels: team:VM, testing

#6901 Ingela/inets/remove legacy ssl option handling/gh 6380/otp 18476
  lib/inets/src/http_client/httpc.erl
  lib/inets/src/http_client/httpc_handler.erl
  lib/inets/src/http_lib/http_internal.hrl
  lib/inets/src/http_lib/http_transport.erl
  lib/inets/src/http_server/httpd.erl
  lib/inets/src/http_server/httpd_conf.erl
  lib/inets/src/http_server/httpd_example.erl
  lib/inets/src/http_server/httpd_request_handler.erl
  lib/inets/src/http_server/httpd_script_env.erl
  lib/inets/src/http_server/httpd_sup.erl
  lib/inets/src/http_server/mod_alias.erl
  lib/inets/test/httpc_SUITE.erl
  lib/inets/test/httpd_SUITE.erl
  lib/inets/test/httpd_bench_SUITE.erl
  lib/inets/test/httpd_time_test.erl
  lib/inets/test/inets_test_lib.erl
Labels: team:PS, testing

#6910 inets: refactor code for consistency
  lib/inets/src/http_client/httpc_handler.erl
Labels: team:PS, enhancement, testing

#6883 public_key: Move decode of CRLDistributionPoints extension
  lib/public_key/src/pubkey_cert.erl
  lib/public_key/src/pubkey_cert_records.erl
  lib/public_key/test/public_key_SUITE.erl
Labels: team:PS, testing

#6911 init: Avoid outputting non-ASCII characters from -init_debug
  erts/preloaded/ebin/init.beam
  erts/preloaded/src/init.erl
Labels: team:VM, fix, testing

#6908 compiler: Improve code coverage in alias analysis
  lib/compiler/test/beam_ssa_check_SUITE.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/alias_non_convergence.erl
Labels: team:VM, enhancement, testing

#6882 leex column number support
  lib/parsetools/doc/src/leex.xml
  lib/parsetools/include/leexinc.hrl
  lib/parsetools/src/leex.erl
  lib/parsetools/test/leex_SUITE.erl
Labels: team:VM, feature, testing

#6897 list_to_integer() & friends: Don't crash for overlong lists
  erts/emulator/beam/bif.c
  erts/emulator/beam/big.c
  erts/emulator/beam/big.h
  erts/emulator/test/list_bif_SUITE.erl
  erts/emulator/test/num_bif_SUITE.erl
Labels: team:VM, fix, testing

#6843 Implement synchronous init failure for gen processes
  lib/kernel/src/logger_olp.erl
  lib/kernel/test/logger_SUITE.erl
  lib/stdlib/doc/src/proc_lib.xml
  lib/stdlib/src/gen.erl
  lib/stdlib/src/gen_fsm.erl
  lib/stdlib/src/gen_server.erl
  lib/stdlib/src/gen_statem.erl
  lib/stdlib/src/proc_lib.erl
  lib/stdlib/test/gen_server_SUITE.erl
  lib/stdlib/test/gen_statem_SUITE.erl
  lib/stdlib/test/supervisor_SUITE.erl
  system/doc/design_principles/spec_proc.xml
Labels: team:PS

#6865 Improve the `lists:merge` family of functions
  lib/stdlib/src/lists.erl
  lib/stdlib/test/lists_SUITE.erl
  lib/stdlib/test/lists_property_test_SUITE.erl
  lib/stdlib/test/property_test/lists_prop.erl
Labels: team:VM, enhancement, testing

#6914 Compiler: alias analysis speedup
  lib/compiler/src/beam_ssa_alias.erl
  lib/compiler/test/beam_ssa_check_SUITE.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/alias_chain.erl
Labels: team:VM, enhancement, testing

#6918 Fix factual errors and omissions for the bit syntax
  system/doc/reference_manual/expressions.xml
Labels: team:VM, testing

#6272 Optimize the copy that occurs in ets:lookup_element
  erts/emulator/beam/copy.c
  erts/emulator/beam/erl_db_hash.c
  erts/emulator/beam/erl_db_tree.c
  erts/emulator/beam/erl_db_util.c
  erts/emulator/beam/erl_db_util.h
  erts/emulator/beam/erl_term.h
  erts/emulator/beam/global.h
  lib/stdlib/test/ets_SUITE.erl
Labels: team:VM, enhancement, testing

#6924 ms_transform: allow caller_line and current_stacktrace action functions
  lib/stdlib/src/ms_transform.erl
  lib/stdlib/test/ms_transform_SUITE.erl
Labels: team:VM

#6929 Address a few omissions in documentation of comprehensions
  system/doc/reference_manual/expressions.xml
Labels: team:VM, enhancement, testing

#6937 Fixes bug in shell completion
  lib/stdlib/src/edlin_expand.erl
  lib/stdlib/test/edlin_expand_SUITE.erl
Labels: team:VM, fix, testing

#6936 Fix multi_load_SUITE, by updating verify_prepared
  lib/kernel/src/code.erl
Labels: team:VM, fix
