Repository erlang/otp, pull requests merged in 2023-04, with the labels that each got.

#6958 Preserve applications order on ensure_all_started
  lib/kernel/src/application.erl
Labels: team:VM, testing

#7084 Fix since tag in application:ensure_all_started/3
  lib/kernel/doc/src/application.xml
Labels: team:VM, documentation

#7044 beam_disasm: Deserialize the version 1 type table format
  lib/compiler/src/beam_disasm.erl
  lib/compiler/src/beam_types.erl
Labels: team:VM, testing

#7078 Remove --enable-sanitizers configure options
  erts/configure
  erts/configure.ac
  erts/lib_src/yielding_c_fun/main_target.mk
  lib/erl_interface/configure
  lib/erl_interface/configure.ac
  lib/megaco/configure
  lib/megaco/configure.ac
  lib/odbc/configure
  lib/odbc/configure.ac
  lib/wx/configure
  lib/wx/configure.ac
  make/configure
  make/configure.ac
Labels: team:VM, fix, testing

#7000 Allow larger column sizes than 8001 in case DB supports it
  lib/odbc/c_src/odbcserver.c
Labels: team:PS, testing

#6900 Enable decoding URIs with ipv6 address in host.
  erts/config.h.in
  erts/configure
  erts/configure.ac
  erts/doc/src/erlang.xml
  erts/emulator/beam/packet_parser.c
  erts/emulator/beam/sys.h
  erts/emulator/test/decode_packet_SUITE.erl
Labels: team:VM, feature, testing

#7059 ssl: Enhance warning alert handling
  lib/ssl/src/ssl_gen_statem.erl
Labels: team:PS

#7039 asn1: fix RELATIVE-OID validation
  lib/asn1/src/asn1ct_check.erl
  lib/asn1/test/asn1_SUITE_data/ValueTest.asn
  lib/asn1/test/error_SUITE.erl
Labels: team:VM, testing

#7083 JIT: Avoid mixing AVX and SSE instructions
  erts/emulator/beam/jit/x86/beam_asm.hpp
  erts/emulator/beam/jit/x86/instr_common.cpp
  erts/emulator/beam/jit/x86/instr_float.cpp
  erts/emulator/beam/jit/x86/instr_map.cpp
Labels: team:VM, enhancement, testing

#7077 jinterface docs: add some missing spaces
  lib/jinterface/doc/src/jinterface_users_guide.xml
Labels: team:VM, testing

#7089 Ingela/kernel/disk log/deprecate inc wrap file/otp 18331
  bootstrap/lib/stdlib/ebin/otp_internal.beam
  lib/kernel/src/disk_log.erl
  lib/stdlib/src/otp_internal.erl
  system/doc/general_info/DEPRECATIONS
Labels: team:PS

#7079 Change apache-like config files to proplist file
  lib/inets/examples/server_root/conf/8080.conf
  lib/inets/examples/server_root/conf/8888.conf
  lib/inets/examples/server_root/conf/httpd.conf
  lib/inets/examples/server_root/conf/ssl.conf
Labels: team:PS

#7087 Remove unused argument
  lib/stdlib/src/erl_parse.yrl
Labels: team:VM, testing

#7071 os_mon: Plug memory leak in cpu_sup:util/0,1 on FreeBSD
  lib/os_mon/c_src/cpu_sup.c
Labels: team:VM, testing

#7065 ssl: replace hardcoded numbers by macros
  lib/ssl/src/dtls_gen_connection.erl
  lib/ssl/src/dtls_handshake.erl
  lib/ssl/src/dtls_handshake.hrl
  lib/ssl/src/dtls_record.erl
  lib/ssl/src/dtls_v1.erl
  lib/ssl/src/inet_tls_dist.erl
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_certificate.erl
  lib/ssl/src/ssl_cipher.erl
  lib/ssl/src/ssl_gen_statem.erl
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/src/ssl_logger.erl
  lib/ssl/src/ssl_record.erl
  lib/ssl/src/ssl_record.hrl
  lib/ssl/src/ssl_session.erl
  lib/ssl/src/tls_client_connection_1_3.erl
  lib/ssl/src/tls_connection.erl
  lib/ssl/src/tls_dtls_connection.erl
  lib/ssl/src/tls_gen_connection.erl
  lib/ssl/src/tls_handshake.erl
  lib/ssl/src/tls_handshake_1_3.erl
  lib/ssl/src/tls_record.erl
  lib/ssl/src/tls_record.hrl
  lib/ssl/src/tls_record_1_3.erl
  lib/ssl/src/tls_record_1_3.hrl
  lib/ssl/src/tls_sender.erl
  lib/ssl/src/tls_server_connection_1_3.erl
  lib/ssl/src/tls_socket.erl
  lib/ssl/src/tls_v1.erl
  lib/ssl/test/cryptcookie.erl
  lib/ssl/test/property_test/ssl_eqc_handshake.erl
  lib/ssl/test/ssl_ECC_SUITE.erl
  lib/ssl/test/ssl_api_SUITE.erl
  lib/ssl/test/ssl_cert_SUITE.erl
  lib/ssl/test/ssl_cert_tests.erl
  lib/ssl/test/ssl_cipher_SUITE.erl
  lib/ssl/test/ssl_handshake_SUITE.erl
  lib/ssl/test/ssl_mfl_SUITE.erl
  lib/ssl/test/ssl_npn_hello_SUITE.erl
  lib/ssl/test/ssl_reject_SUITE.erl
  lib/ssl/test/ssl_renegotiate_SUITE.erl
  lib/ssl/test/ssl_session_SUITE.erl
  lib/ssl/test/ssl_test_lib.erl
  lib/ssl/test/tls_1_3_record_SUITE.erl
  lib/ssl/test/tls_api_SUITE.erl
  lib/ssl/test/tls_server_session_ticket_SUITE.erl
Labels: team:PS, enhancement, testing

#7092 kernel: make printing strings with ANSI SGR escapes faster
  lib/kernel/src/prim_tty.erl
Labels: team:VM, testing, bug

#7106 Remove code:is_module_native/1 and code:rehash/0
  bootstrap/lib/stdlib/ebin/otp_internal.beam
  lib/kernel/doc/src/code.xml
  lib/kernel/src/code.erl
  lib/stdlib/src/otp_internal.erl
  system/doc/general_info/deprecations_24.inc
Labels: team:VM, enhancement, testing

#6973 Avoid truncating thread names for better runtime observability
  erts/emulator/beam/erl_async.c
  erts/emulator/beam/erl_drv_thread.c
  erts/emulator/beam/erl_process.c
  erts/emulator/beam/erl_threads.h
  erts/emulator/beam/erl_trace.c
  erts/emulator/sys/unix/sys.c
  erts/include/internal/ethread.h
  erts/lib_src/pthread/ethread.c
  erts/test/ethread_SUITE.erl
  erts/test/ethread_SUITE_data/ethread_tests.c
Labels: team:VM, testing

#7102 erts: Fix warning about set but unused variable
  erts/emulator/beam/hash.c
Labels: team:VM

#7101 compiler: Ignore generated file
  lib/compiler/src/.gitignore
Labels: team:VM

#7097 Document the scoping rules for try/catch/of/after expressions
  system/doc/reference_manual/expressions.xml
Labels: team:VM, testing

#7115 Remove obsolete defines
  erts/emulator/beam/erl_term.h
Labels: team:VM, testing

#7100 erts: Modernize K&R-style functions
  erts/emulator/beam/beam_file.c
  erts/emulator/beam/code_ix.c
  erts/emulator/beam/erl_arith.c
  erts/emulator/beam/erl_db.c
  erts/emulator/beam/erl_md5.c
  erts/emulator/beam/erl_nif.c
  erts/emulator/beam/erl_posix_str.c
  erts/emulator/beam/erl_trace.c
  erts/emulator/beam/erl_vm.h
  erts/emulator/beam/io.c
  erts/emulator/beam/packet_parser.c
  erts/emulator/beam/utils.c
  erts/emulator/drivers/common/inet_drv.c
  erts/emulator/nifs/common/socket_util.c
  erts/emulator/sys/unix/erl_unix_sys.h
  erts/emulator/sys/unix/sys_env.c
  erts/emulator/utils/make_driver_tab
  erts/epmd/src/epmd_srv.c
  erts/etc/common/heart.c
Labels: team:VM, testing

#7099 Eliminate make warning about ignored old recipe
  lib/compiler/Makefile
  lib/stdlib/Makefile
  make/app_targets.mk
Labels: team:VM, testing

#7095 asn1: Fix warning about mismatched allocation function
  lib/asn1/c_src/asn1_erl_nif.c
Labels: team:VM, testing

#7088 [erl_lint] Recurse with cheaper function in pattern checks
  lib/stdlib/src/erl_lint.erl
Labels: team:VM, testing

#7122 beam_ssa_alias: Fix alias analysis for funs
  lib/compiler/src/beam_ssa_alias.erl
  lib/compiler/test/bs_construct_SUITE.erl
Labels: team:VM, testing, bug

#7126 Update `perf` workflow for OTP26
  erts/emulator/internal_doc/BeamAsm.md
Labels: team:VM, testing

#7091 ei_users_guide: fix examples, correctly pass ec as pointer
  lib/erl_interface/doc/src/ei_users_guide.xml
Labels: team:VM

#7124 crypto: dh.c change len type to ErlNifUInt64
  lib/crypto/c_src/dh.c
Labels: team:PS, bug

#7129 Fix failure to load module with disabled optimizations
  lib/compiler/src/beam_ssa_pre_codegen.erl
  lib/compiler/test/beam_ssa_SUITE.erl
Labels: team:VM, fix, testing

#7135 Fix broken `make clean && make`
  lib/compiler/src/Makefile
Labels: team:VM, testing

#6852 [argparse] Command line parser for Erlang
  lib/dialyzer/doc/src/dialyzer.xml
  lib/dialyzer/src/dialyzer.hrl
  lib/dialyzer/src/dialyzer_cl_parse.erl
  lib/dialyzer/src/dialyzer_options.erl
  lib/dialyzer/src/typer.erl
  lib/stdlib/doc/src/Makefile
  lib/stdlib/doc/src/argparse.xml
  lib/stdlib/doc/src/ref_man.xml
  lib/stdlib/doc/src/specs.xml
  lib/stdlib/src/Makefile
  lib/stdlib/src/argparse.erl
  lib/stdlib/src/stdlib.app.src
  lib/stdlib/test/Makefile
  lib/stdlib/test/argparse_SUITE.erl
Labels: team:VM, testing

#7107 Kuba/inets/fix httpc remote socket close/otp 18545
  lib/inets/src/http_client/httpc_handler.erl
  lib/inets/test/http_test_lib.erl
  lib/inets/test/httpc_SUITE.erl
  lib/inets/test/inets_test_lib.erl
  lib/inets/test/make_certs.erl
Labels: team:PS, bug

#7093 Handle empty target host name
  lib/kernel/src/inet_db.erl
  lib/kernel/src/inet_parse.erl
  lib/kernel/src/inet_res.erl
  lib/kernel/test/gen_sctp_SUITE.erl
  lib/kernel/test/gen_tcp_api_SUITE.erl
  lib/kernel/test/gen_udp_SUITE.erl
  lib/kernel/test/inet_SUITE.erl
Labels: team:PS, fix, bug, priority:medium, types

#7080 os_mon: Implement cpu_sup:util/0,1 for OpenBSD
  lib/os_mon/c_src/cpu_sup.c
  lib/os_mon/doc/src/cpu_sup.xml
  lib/os_mon/src/cpu_sup.erl
  lib/os_mon/test/cpu_sup_SUITE.erl
Labels: team:VM, testing

#7141 LCNT: fix port parser for V4_PORT_EXT
  lib/tools/src/lcnt.erl
Labels: team:VM, fix, testing

#7155 jit: Fix metadata registration for empty modules
  erts/emulator/beam/jit/beam_jit_common.cpp
Labels: team:VM, fix, testing

#7157 beam_bounds: Make 'bnot' converge faster
  lib/compiler/src/beam_bounds.erl
  lib/compiler/src/beam_validator.erl
  lib/compiler/test/beam_bounds_SUITE.erl
Labels: team:VM, fix, testing

#7143 beam_ssa_private_append: Fix crash on oddly structured code
  lib/compiler/src/beam_ssa_private_append.erl
  lib/compiler/test/bs_construct_SUITE.erl
Labels: team:VM, testing

#7163 Fix two type-related bugs
  lib/compiler/src/beam_ssa.erl
  lib/compiler/src/beam_validator.erl
  lib/compiler/test/beam_ssa_SUITE.erl
  lib/compiler/test/beam_type_SUITE.erl
Labels: team:VM, fix, testing

#7154 dialyzer: Expand Dialyzer config file options
  lib/dialyzer/doc/src/dialyzer.xml
  lib/dialyzer/src/dialyzer_analysis_callgraph.erl
  lib/dialyzer/src/dialyzer_cl_parse.erl
  lib/dialyzer/src/dialyzer_options.erl
  lib/dialyzer/test/incremental_SUITE.erl
  lib/dialyzer/test/incremental_SUITE_data/extra_modules/ebin/.gitignore
  lib/dialyzer/test/incremental_SUITE_data/extra_modules/src/extra_module.erl
  lib/dialyzer/test/incremental_SUITE_data/extra_modules/src/extra_modules.app.src
Labels: team:VM, enhancement, testing

#7167 diameter: remove optional call to deprecated fn and update appup
  erts/test/otp_SUITE.erl
  lib/diameter/src/diameter.appup.src
Labels: team:PS, testing

#7161 dialyzer: Fix crash on formatting warning containing unicode text
  lib/dialyzer/src/dialyzer.erl
  lib/dialyzer/test/small_SUITE_data/results/gh_7153
  lib/dialyzer/test/small_SUITE_data/src/gh_7153.erl
Labels: team:VM, fix, testing

#7160 dialyzer: Fix crash on weird segment sizes
  lib/dialyzer/src/dialyzer_dataflow.erl
  lib/dialyzer/test/small_SUITE_data/results/bs_segments
  lib/dialyzer/test/small_SUITE_data/src/bs_segments.erl
Labels: team:VM, fix, testing

#7173 beam_validator: Improve arithmetic range inference
  lib/compiler/src/beam_validator.erl
  lib/compiler/test/beam_validator_SUITE.erl
Labels: team:VM, fix, testing

#7027 jit: Fix hd/1 and tl/1 BIF specialization
  erts/emulator/beam/jit/arm/ops.tab
  erts/emulator/beam/jit/x86/instr_guard_bifs.cpp
  erts/emulator/beam/jit/x86/ops.tab
  lib/compiler/test/bif_SUITE.erl
Labels: team:VM, testing

#7113 erts: Fix overlapping blocking code barriers in the same tick
  erts/emulator/beam/code_ix.c
Labels: team:VM

#7123 erts: Fix ic/dc config tests and usage
  erts/configure
  erts/configure.ac
  erts/emulator/beam/jit/beam_jit_main.cpp
  lib/erl_interface/configure
  make/autoconf/otp.m4
Labels: team:VM, bug

#7131 Alias fix
  erts/emulator/beam/bif.c
  erts/emulator/beam/erl_bif_unique.c
  erts/emulator/beam/erl_proc_sig_queue.c
  erts/emulator/test/process_SUITE.erl
Labels: team:VM, fix, testing

#7159 [erts] Fix build without native atomics
  erts/emulator/beam/erl_process_lock.h
Labels: team:VM, fix, testing

#7049 driver call callback fix
  erts/emulator/beam/io.c
Labels: team:VM, fix, testing
