Repository erlang/otp, pull requests merged in 2023-03, with the labels that each got.

#6926 Correct unsafe optimization of binary matching
  lib/compiler/src/v3_kernel.erl
  lib/compiler/test/bs_match_SUITE.erl
Labels: team:VM, fix, testing

#6930 compiler: Avoid unsafe rewrite to bs_create_bin private_append
  lib/compiler/src/beam_ssa_alias.erl
  lib/compiler/src/beam_ssa_private_append.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/alias.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/private_append.erl
Labels: team:VM, fix, testing

#6934 beam_call_types: Fix inconsistency
  lib/compiler/src/beam_call_types.erl
  lib/compiler/test/beam_type_SUITE.erl
Labels: team:VM, fix, testing

#6939 Document optimizations for appending to binaries
  system/doc/efficiency_guide/binaryhandling.xml
Labels: team:VM, testing

#6917 Eliminate a valgrind warning
  erts/emulator/beam/jit/x86/instr_bs.cpp
Labels: team:VM, fix, testing

#6931 erts: Fix process_info(_, garbage_collection) for max_heap_size
  erts/emulator/beam/erl_bif_info.c
  erts/emulator/test/process_SUITE.erl
Labels: team:VM, fix, testing

#6948 Use map comprehensions
  lib/asn1/src/asn1ct_check.erl
  lib/asn1/src/asn1ct_gen_check.erl
  lib/asn1/src/asn1ct_gen_jer.erl
  lib/asn1/src/asn1rtt_ext.erl
  lib/compiler/src/beam_ssa_alias.erl
  lib/dialyzer/src/dialyzer_codeserver.erl
  lib/dialyzer/src/dialyzer_incremental.erl
  lib/dialyzer/src/dialyzer_iplt.erl
  lib/dialyzer/src/dialyzer_plt.erl
  lib/dialyzer/src/dialyzer_typegraph.erl
  lib/dialyzer/src/dialyzer_utils.erl
  lib/dialyzer/src/erl_types.erl
  lib/kernel/src/erts_debug.erl
  lib/kernel/src/global_group.erl
  lib/kernel/src/pg.erl
  lib/stdlib/src/epp.erl
  lib/stdlib/src/erl_expand_records.erl
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/src/proplists.erl
  lib/stdlib/src/qlc.erl
Labels: team:VM, enhancement, testing

#6944 Windows reuseaddr/reuseport fix
  erts/emulator/drivers/common/inet_drv.c
  lib/kernel/test/inet_sockopt_SUITE.erl
  lib/kernel/test/inet_sockopt_SUITE_data/sockopt_helper.c
Labels: team:VM, fix, testing

#6953 Alias cleanup fix
  erts/emulator/beam/erl_bif_info.c
  erts/emulator/beam/erl_bif_unique.c
  erts/emulator/beam/erl_bif_unique.h
  erts/emulator/beam/erl_monitor_link.c
  erts/emulator/test/process_SUITE.erl
Labels: team:VM, fix, testing

#6943 Add `lists:enumerate/3`
  lib/stdlib/doc/src/lists.xml
  lib/stdlib/src/lists.erl
  lib/stdlib/test/lists_SUITE.erl
  lib/stdlib/test/lists_property_test_SUITE.erl
  lib/stdlib/test/property_test/lists_prop.erl
Labels: team:VM, feature, testing

#6940 Improve `lists:nth/2` and `nthtail/2`
  lib/stdlib/src/lists.erl
Labels: team:VM, enhancement, testing

#6941 dialyzer: Add the --no_spec option for ignoring specs
  lib/dialyzer/doc/src/dialyzer.xml
  lib/dialyzer/src/dialyzer_cl_parse.erl
  lib/dialyzer/src/dialyzer_options.erl
  lib/dialyzer/src/dialyzer_typegraph.erl
  lib/dialyzer/test/options3_SUITE_data/dialyzer_options
  lib/dialyzer/test/options3_SUITE_data/results/bad_specs
  lib/dialyzer/test/options3_SUITE_data/src/bad_specs.erl
Labels: team:VM, feature, testing

#6946 fix instrument:carriers spec
  lib/runtime_tools/src/instrument.erl
Labels: team:VM, testing

#6974 Fix compilation error with disabled optimizations
  lib/compiler/src/beam_ssa_pre_codegen.erl
  lib/compiler/test/beam_ssa_SUITE.erl
Labels: team:VM, fix, testing

#6968 compiler: Cache use/def sets in alias analysis pass
  lib/compiler/src/beam_ssa_alias.erl
Labels: team:VM, enhancement, testing

#6964 beam_validator: Fix inference on singleton types in registers
  lib/compiler/src/beam_validator.erl
  lib/compiler/test/beam_validator_SUITE.erl
  lib/compiler/test/beam_validator_SUITE_data/singleton_inference.erl
Labels: team:VM, testing

#6949 Make maps_order optional in io_lib:format_spec()
  lib/stdlib/src/io_lib.erl
  lib/stdlib/src/io_lib_format.erl
  lib/stdlib/test/io_SUITE.erl
Labels: team:VM, testing

#6963 erts: Reintroduce literal fun optimization
  erts/doc/src/erlang.xml
  erts/emulator/beam/beam_file.c
  erts/emulator/beam/beam_file.h
  erts/emulator/beam/emu/emu_load.c
  erts/emulator/beam/emu/generators.tab
  erts/emulator/beam/emu/load.h
  erts/emulator/beam/generators.tab
  erts/emulator/beam/jit/arm/beam_asm.hpp
  erts/emulator/beam/jit/arm/beam_asm_module.cpp
  erts/emulator/beam/jit/arm/generators.tab
  erts/emulator/beam/jit/asm_load.c
  erts/emulator/beam/jit/beam_asm.h
  erts/emulator/beam/jit/beam_jit_main.cpp
  erts/emulator/beam/jit/load.h
  erts/emulator/beam/jit/x86/beam_asm.hpp
  erts/emulator/beam/jit/x86/beam_asm_module.cpp
  erts/emulator/beam/jit/x86/generators.tab
  erts/emulator/test/fun_SUITE.erl
  erts/emulator/test/trace_call_time_SUITE.erl
  system/doc/general_info/upcoming_incompatibilities.xml
Labels: team:VM, testing

#6966 Update the documentation about the maybe feature
  system/doc/general_info/upcoming_incompatibilities.xml
  system/doc/reference_manual/introduction.xml
Labels: team:VM, testing

#6959 Speedup valgrind_beamasm_update script
  scripts/valgrind_beamasm_update.escript
Labels: team:VM, testing

#6983 Kuba/ssl/ocsp code format cleanup/otp 16875
  lib/public_key/src/pubkey_ocsp.erl
  lib/public_key/src/public_key.erl
  lib/ssl/src/dtls_connection.erl
  lib/ssl/src/dtls_handshake.erl
  lib/ssl/src/ssl_certificate.erl
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/src/tls_connection.erl
  lib/ssl/src/tls_dtls_connection.erl
  lib/ssl/src/tls_handshake.erl
  lib/ssl/src/tls_handshake_1_3.erl
Labels: team:PS

#6977 compiler: Use map comprehensions instead of maps:filter/2
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/beam_ssa_pre_codegen.erl
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/src/beam_types.erl
  lib/compiler/src/beam_validator.erl
  lib/compiler/src/v3_kernel.erl
Labels: team:VM, enhancement, testing

#6992 Eliminate assertion failure in beam_ssa_codegen
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/test/beam_except_SUITE.erl
Labels: team:VM, fix, testing

#6988 Document the bit order of the bit syntax
  system/doc/reference_manual/expressions.xml
Labels: team:VM, enhancement, testing

#6965 Fix lost exception from map update
  lib/compiler/src/sys_core_fold.erl
  lib/compiler/test/core_fold_SUITE.erl
Labels: team:VM, fix

#6913 ssl: fix keylog mechanism
  lib/ssl/src/ssl_gen_statem.erl
  lib/ssl/src/tls_sender.erl
  lib/ssl/test/ssl_key_update_SUITE.erl
Labels: team:PS

#6991 Make term_to_binary encode atoms as UTF-8 by default
  erts/doc/src/erlang.xml
  erts/emulator/beam/dist.h
  erts/emulator/beam/external.c
  erts/emulator/test/binary_SUITE.erl
  lib/erl_interface/test/ei_decode_SUITE_data/ei_decode_test.c
  lib/kernel/test/disk_log_SUITE.erl
  system/doc/general_info/upcoming_incompatibilities.xml
Labels: team:VM, testing

#6982 Implement DNS LOC record (RFC 1876)
  lib/kernel/src/inet_dns.erl
  lib/kernel/src/inet_dns.hrl
  lib/kernel/test/inet_res_SUITE.erl
  lib/kernel/test/inet_res_SUITE_data/otptest/otptest.zone
Labels: team:PS, enhancement, in progress

#6984 Unicode 15
  lib/stdlib/test/unicode_util_SUITE_data/GraphemeBreakTest.txt
  lib/stdlib/test/unicode_util_SUITE_data/LineBreakTest.txt
  lib/stdlib/test/unicode_util_SUITE_data/NormalizationTest.txt
  lib/stdlib/test/unicode_util_SUITE_data/unicode_table.bin
  lib/stdlib/uc_spec/CaseFolding.txt
  lib/stdlib/uc_spec/CompositionExclusions.txt
  lib/stdlib/uc_spec/EastAsianWidth.txt
  lib/stdlib/uc_spec/GraphemeBreakProperty.txt
  lib/stdlib/uc_spec/PropList.txt
  lib/stdlib/uc_spec/README-UPDATE.txt
  lib/stdlib/uc_spec/SpecialCasing.txt
  lib/stdlib/uc_spec/UnicodeData.txt
  lib/stdlib/uc_spec/emoji-data.txt
  lib/stdlib/uc_spec/gen_unicode_mod.escript
Labels: team:PS, testing

#7014 Fix compiler crash in beam_ssa_private_append (#7011)
  lib/compiler/src/beam_ssa_private_append.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/private_append.erl
Labels: team:VM, fix, testing

#7003 sys_core_fold: Inline maps:get/3
  lib/compiler/src/sys_core_fold.erl
  lib/stdlib/test/maps_SUITE.erl
  system/doc/efficiency_guide/maps.xml
Labels: team:VM, testing

#7013 erl_parse: Update types
  lib/stdlib/src/erl_parse.yrl
Labels: team:VM, fix

#7006 Option 'local' of term_to_binary/2 and term_to_iovec/2
  erts/doc/src/erl_driver.xml
  erts/doc/src/erl_ext_dist.xml
  erts/doc/src/erlang.xml
  erts/emulator/beam/atom.c
  erts/emulator/beam/atom.names
  erts/emulator/beam/dist.h
  erts/emulator/beam/erl_init.c
  erts/emulator/beam/erl_term_hashing.c
  erts/emulator/beam/erl_term_hashing.h
  erts/emulator/beam/external.c
  erts/emulator/beam/external.h
  erts/emulator/beam/global.h
  erts/emulator/beam/sys.h
  erts/emulator/sys/unix/sys.c
  erts/emulator/sys/win32/sys.c
  erts/emulator/test/binary_SUITE.erl
  erts/emulator/test/binary_SUITE_data/Makefile.src
  erts/emulator/test/binary_SUITE_data/call_local_drv.c
  erts/emulator/test/binary_SUITE_data/send_term_local_drv.c
  erts/preloaded/ebin/erlang.beam
  erts/preloaded/src/erlang.erl
  lib/erl_interface/test/ei_decode_encode_SUITE_data/ei_decode_encode_test.c
Labels: team:VM, enhancement, feature, testing

#7012 New API eldap:info/1
  lib/eldap/doc/src/eldap.xml
  lib/eldap/src/eldap.erl
  lib/eldap/test/eldap_basic_SUITE.erl
Labels: team:PS, testing

#7020 sets: Improve subtract/2 performance for small sets
  lib/stdlib/src/sets.erl
Labels: team:VM, testing

#6998 Update zlib to 1.2.13
  HOWTO/INSTALL-RASPBERRYPI3.md
  erts/emulator/zlib/compress.c
  erts/emulator/zlib/crc32.c
  erts/emulator/zlib/deflate.c
  erts/emulator/zlib/deflate.h
  erts/emulator/zlib/inflate.c
  erts/emulator/zlib/inftrees.c
  erts/emulator/zlib/inftrees.h
  erts/emulator/zlib/trees.c
  erts/emulator/zlib/uncompr.c
  erts/emulator/zlib/zconf.h
  erts/emulator/zlib/zlib.h
  erts/emulator/zlib/zutil.c
  erts/emulator/zlib/zutil.h
Labels: team:VM, testing

#7016 Eliminate false warning for re-defined and unused type
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/test/erl_lint_SUITE.erl
Labels: team:VM, fix, testing

#7017 Add note about a new regular expression engine in OTP 27
  system/doc/general_info/upcoming_incompatibilities.xml
Labels: team:VM, testing

#6986 gen_statem: list comprehension with map generator instead of `maps:fold/3`
  lib/stdlib/src/gen_statem.erl
Labels: team:PS, testing

#7023 erl_lint: Stop raising warnings for underspecified opaques
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/test/erl_lint_SUITE.erl
Labels: team:VM, testing

#6993 EEP 61: Built-in dynamic type
  erts/preloaded/src/erlang.erl
  lib/dialyzer/src/erl_types.erl
  lib/stdlib/src/erl_internal.erl
  system/doc/reference_manual/typespec.xml
Labels: team:VM, testing

#7018 erts: Refactor code modification
  erts/emulator/beam/beam_bif_load.c
  erts/emulator/beam/beam_bp.c
  erts/emulator/beam/beam_bp.h
  erts/emulator/beam/beam_debug.c
  erts/emulator/beam/emu/emu_load.c
  erts/emulator/beam/erl_bif_trace.c
  erts/emulator/beam/erl_lock_check.c
  erts/emulator/beam/erl_nif.c
  erts/emulator/beam/jit/arm/beam_asm.hpp
  erts/emulator/beam/jit/arm/beam_asm_global.cpp
  erts/emulator/beam/jit/asm_load.c
  erts/emulator/beam/jit/beam_asm.h
  erts/emulator/beam/jit/beam_jit_common.cpp
  erts/emulator/beam/jit/beam_jit_main.cpp
  erts/emulator/beam/jit/load.h
  erts/emulator/beam/jit/x86/beam_asm.hpp
  erts/emulator/beam/jit/x86/beam_asm_global.cpp
  erts/emulator/beam/module.c
  erts/emulator/beam/module.h
  erts/emulator/internal_doc/BeamAsm.md
  erts/emulator/test/jit_SUITE.erl
Labels: team:VM, testing

#7022 Efficiency Guide: Add more examples for binaries
  system/doc/efficiency_guide/binaryhandling.xml
Labels: team:VM, enhancement, testing

#7004 Optimize maps:merge/2 of small maps
  erts/emulator/beam/erl_map.c
  erts/emulator/test/map_SUITE.erl
  system/doc/efficiency_guide/maps.xml
Labels: team:VM, enhancement, testing

#7025 [kernel] Reduce memory usage for volatile send in global
  lib/kernel/src/global.erl
Labels: team:VM, enhancement, testing

#6920 gh: Update GitHub actions setup
  .github/dockerfiles/Dockerfile.32-bit
  .github/dockerfiles/Dockerfile.64-bit
  .github/dockerfiles/Dockerfile.clang
  .github/dockerfiles/Dockerfile.cross-compile
  .github/workflows/actions-updater.yaml
  .github/workflows/add-to-project.yaml
  .github/workflows/main.yaml
  .github/workflows/pr-comment.yaml
  .github/workflows/sync-github-releases.yaml
  .github/workflows/update-base.yaml
  HOWTO/DEVELOPMENT.md
Labels: team:IS

#7038 beamasm: Add instructions for attaching perf to a running system
  erts/emulator/internal_doc/BeamAsm.md
Labels: team:VM, testing, documentation

#7026 Rename function `map/0` in `uri_string_recompose` property test
  lib/stdlib/test/property_test/uri_string_recompose.erl
Labels: team:PS, testing

#7062 Fixed typo.
  lib/crypto/doc/src/new_api.xml
Labels: team:VM

#7064 ssl:renegotiate/1should return error for tls1.3
  lib/ssl/doc/src/ssl.xml
  lib/ssl/src/ssl.erl
  lib/ssl/test/tls_1_3_version_SUITE.erl
Labels: team:PS, testing

#7034 orddict: add examples
  lib/stdlib/doc/src/orddict.xml
Labels: team:PS, enhancement, testing, documentation

#7032 queue: add examples
  lib/stdlib/doc/src/queue.xml
Labels: team:VM, enhancement, testing, documentation

#7069 orddict: fix XML error
  lib/stdlib/doc/src/orddict.xml
Labels: bug

#7056 inets: httpd - Use inet:ntoa to get ip address string format
  lib/inets/src/http_lib/http_transport.erl
Labels: team:PS, enhancement, testing

#7066 New log type 'rotate' for disk_log
  lib/kernel/doc/src/disk_log.xml
  lib/kernel/src/disk_log.erl
  lib/kernel/src/disk_log.hrl
  lib/kernel/src/disk_log_1.erl
  lib/kernel/test/disk_log_SUITE.erl
Labels: team:PS, testing

#7081 [stdlib] Remove gen_statem call proxy process
  lib/stdlib/doc/src/gen_statem.xml
  lib/stdlib/src/gen_statem.erl
Labels: team:VM, enhancement, testing

#7061 Misc improvements using async_dist
  erts/doc/src/erlang.xml
  lib/kernel/doc/src/erpc.xml
  lib/kernel/doc/src/rpc.xml
  lib/kernel/src/global.erl
  lib/kernel/src/global_group.erl
  lib/kernel/src/net_kernel.erl
  lib/stdlib/doc/src/gen_event.xml
  lib/stdlib/doc/src/gen_server.xml
  lib/stdlib/doc/src/gen_statem.xml
  system/doc/reference_manual/processes.xml
Labels: team:VM, enhancement, testing

#7046 erts: Support is_boolean/1 in match specs
  erts/doc/src/match_spec.xml
  erts/emulator/beam/erl_db_util.c
  erts/emulator/test/match_spec_SUITE.erl
Labels: team:VM, enhancement, testing
