Repository erlang/otp, pull requests merged in 2023-06, with the labels that each got.

#7335 Document squashing of smaller changes in CONTRIBUTING
  CONTRIBUTING.md
Labels: team:VM

#7334 Add link to appup manpage in release handling doc
  system/doc/design_principles/release_handling.xml
Labels: team:VM, testing

#7305 Return error if ssl is not started
  lib/ssl/src/tls_gen_connection.erl
  lib/ssl/test/ssl_api_SUITE.erl
Labels: team:PS, testing

#7329 compiler: Refine too strict assert in beam_ssa_pp:format_tuple_set_1/1
  lib/compiler/src/beam_ssa_pp.erl
Labels: team:VM, fix, testing

#7330 Avoid optimization that beam_validator might consider unsafe
  lib/compiler/src/beam_clean.erl
  lib/compiler/src/beam_ssa_dead.erl
  lib/compiler/src/compile.erl
  lib/compiler/test/beam_ssa_SUITE.erl
Labels: team:VM, fix, testing

#7331 Report an else_clause exception nicely in the shell
  lib/stdlib/src/erl_error.erl
Labels: team:VM, fix, testing

#7234 Drop references to -vts in ct_run
  lib/common_test/doc/src/ct_run_cmd.xml
  lib/common_test/priv/Makefile.in
  lib/common_test/priv/vts.tool
  lib/common_test/src/ct_run.erl
Labels: team:PS

#7341 Fix miscompilation of guard with `or`
  lib/compiler/src/beam_ssa_bool.erl
  lib/compiler/test/guard_SUITE.erl
Labels: team:VM, fix, testing

#7340 Fix exponential time algorithm
  lib/compiler/src/beam_ssa_bool.erl
  lib/compiler/test/andor_SUITE.erl
Labels: team:VM, fix, testing

#7333 compiler: Eliminate nondeterminism in beam_ssa_recv optimization
  lib/compiler/src/beam_ssa_recv.erl
Labels: team:VM, enhancement, testing

#7322 Drop support in the compiler for OTP 22/23
  erts/emulator/test/erts_test_utils.erl
  erts/test/upgrade_SUITE.erl
  lib/common_test/src/test_server_node.erl
  lib/compiler/src/beam_asm.erl
  lib/compiler/src/beam_block.erl
  lib/compiler/src/beam_clean.erl
  lib/compiler/src/beam_core_to_ssa.erl
  lib/compiler/src/beam_ssa.erl
  lib/compiler/src/beam_ssa_alias.erl
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/beam_ssa_pre_codegen.erl
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/src/beam_utils.erl
  lib/compiler/src/beam_validator.erl
  lib/compiler/src/beam_z.erl
  lib/compiler/src/compile.erl
  lib/compiler/src/v3_core.erl
  lib/compiler/test/Makefile
  lib/compiler/test/compile_SUITE.erl
  lib/compiler/test/property_test/compile_prop.erl
  lib/compiler/test/test_lib.erl
  lib/kernel/test/global_SUITE.erl
  lib/kernel/test/kernel_SUITE.erl
  lib/observer/test/crashdump_helper.erl
  lib/sasl/test/sasl_SUITE.erl
  lib/stdlib/test/stdlib_SUITE.erl
Labels: team:VM, testing

#7072 fix(supervisor): fix return value when process is already registered
  lib/stdlib/src/supervisor.erl
  lib/stdlib/test/supervisor_SUITE.erl
Labels: team:PS, testing

#7280 Fix shell:start_interactive/1 spec
  lib/stdlib/src/shell.erl
Labels: team:VM

#7150 Improve documentation for gen_tcp:recv/3
  lib/kernel/doc/src/gen_tcp.xml
Labels: team:PS, testing

#7275 fix ime not work in windows
  erts/emulator/nifs/common/prim_tty_nif.c
Labels: team:VM

#7351 kernel: Fix starting shell when termcap is not available
  lib/kernel/src/prim_tty.erl
Labels: team:VM, fix, testing

#7183 Add map/filtermap functions to `sets`, `ordsets` and `gb_sets`
  lib/stdlib/doc/src/gb_sets.xml
  lib/stdlib/doc/src/ordsets.xml
  lib/stdlib/doc/src/sets.xml
  lib/stdlib/src/gb_sets.erl
  lib/stdlib/src/ordsets.erl
  lib/stdlib/src/sets.erl
  lib/stdlib/test/sets_SUITE.erl
  lib/stdlib/test/sets_test_lib.erl
Labels: team:VM, enhancement, testing

#7358 docs: fix simple typos
  lib/stdlib/doc/src/gen_event.xml
  lib/stdlib/doc/src/gen_server.xml
  lib/stdlib/doc/src/gen_statem.xml
Labels: team:PS, testing

#7300 Fix incorrect DTLS retransmission timeout
  lib/ssl/src/dtls_connection.erl
Labels: team:PS, testing

#7350 erts: Fix 'init' crash slogan
  erts/emulator/beam/bif.c
  erts/emulator/beam/bif.tab
  erts/emulator/test/map_SUITE.erl
  erts/preloaded/ebin/atomics.beam
  erts/preloaded/ebin/counters.beam
  erts/preloaded/ebin/erl_init.beam
  erts/preloaded/ebin/erl_prim_loader.beam
  erts/preloaded/ebin/erl_tracer.beam
  erts/preloaded/ebin/erlang.beam
  erts/preloaded/ebin/erts_code_purger.beam
  erts/preloaded/ebin/erts_dirty_process_signal_handler.beam
  erts/preloaded/ebin/erts_internal.beam
  erts/preloaded/ebin/erts_literal_area_collector.beam
  erts/preloaded/ebin/init.beam
  erts/preloaded/ebin/persistent_term.beam
  erts/preloaded/ebin/prim_buffer.beam
  erts/preloaded/ebin/prim_eval.beam
  erts/preloaded/ebin/prim_file.beam
  erts/preloaded/ebin/prim_inet.beam
  erts/preloaded/ebin/prim_net.beam
  erts/preloaded/ebin/prim_socket.beam
  erts/preloaded/ebin/prim_zip.beam
  erts/preloaded/ebin/socket_registry.beam
  erts/preloaded/ebin/zlib.beam
  erts/preloaded/src/erts_internal.erl
  erts/preloaded/src/init.erl
  erts/test/erl_print_SUITE.erl
  lib/kernel/src/erts_debug.erl
Labels: team:VM, fix, testing

#7361 cerl: Fix crash on 'undefined' segment size
  lib/compiler/src/cerl.erl
  lib/dialyzer/test/small_SUITE_data/results/bs_segments
  lib/dialyzer/test/small_SUITE_data/src/bs_segments.erl
Labels: team:VM, testing

#7369 AArch64: Fix is_function/2 for arities >= 16
  erts/emulator/beam/jit/arm/instr_common.cpp
  erts/emulator/test/fun_SUITE.erl
Labels: team:VM, fix, testing

#7374 Cover more code in the compiler
  lib/compiler/test/beam_bounds_SUITE.erl
  lib/compiler/test/beam_ssa_SUITE.erl
  lib/compiler/test/bs_bincomp_SUITE.erl
  lib/compiler/test/bs_match_SUITE.erl
  lib/compiler/test/guard_SUITE.erl
Labels: team:VM, testing

#6564 beam_validator: Fix logic bug in '=/=' inference
  lib/compiler/src/beam_validator.erl
  lib/compiler/test/beam_validator_SUITE.erl
Labels: team:VM, testing, bug

#7359 erts: Fix -oldshell and -noshell on Windows
  bootstrap/lib/kernel/ebin/prim_tty.beam
  erts/emulator/nifs/common/prim_tty_nif.c
  lib/kernel/src/prim_tty.erl
Labels: team:VM, fix, testing

#7222 beam_call_types: Fix success check for 'bsl'
  lib/compiler/src/beam_call_types.erl
  lib/compiler/test/beam_type_SUITE.erl
Labels: team:VM, fix, testing

#7254 beam_bounds: Fix 'bnot' bounds on mixed finite/infinite ranges
  lib/compiler/src/beam_bounds.erl
  lib/compiler/test/beam_bounds_SUITE.erl
Labels: team:VM, fix, testing

#7270 erts: Fix misc reduction counting bugs
  erts/emulator/beam/erl_bif_binary.c
  erts/emulator/beam/jit/x86/instr_bs.cpp
Labels: team:VM, testing

#7345 erts: Remove buggy optimization in fun purging
  erts/emulator/beam/beam_bif_load.c
  erts/emulator/test/code_SUITE.erl
  erts/emulator/test/code_SUITE_data/call_purged_fun.erl
  erts/emulator/test/code_SUITE_data/call_purged_fun_altered.erl
  erts/emulator/test/code_SUITE_data/call_purged_fun_tester.erl
Labels: team:VM, testing

#6892 fix 6074 (mod_alias failed to handle re_write config)
  lib/inets/src/http_server/mod_alias.erl
  lib/inets/test/httpd_SUITE.erl
Labels: team:PS, bug

#7348 Compile escripts by default
  erts/doc/src/escript_cmd.xml
  lib/stdlib/src/escript.erl
  lib/stdlib/test/escript_SUITE.erl
Labels: team:VM, testing

#7232 Add equality check functions to `sets`, `ordsets` and `gb_sets`
  lib/stdlib/doc/src/gb_sets.xml
  lib/stdlib/doc/src/ordsets.xml
  lib/stdlib/doc/src/sets.xml
  lib/stdlib/src/gb_sets.erl
  lib/stdlib/src/ordsets.erl
  lib/stdlib/src/sets.erl
  lib/stdlib/test/sets_SUITE.erl
  lib/stdlib/test/sets_test_lib.erl
Labels: team:VM, feature, testing

#7378 Fix miscompilation of guard with `or`
  lib/compiler/src/beam_ssa_bool.erl
  lib/compiler/test/guard_SUITE.erl
Labels: team:VM, fix, testing

#7352 erts: Fix terminal delay info
  .github/scripts/restore-from-prebuilt.sh
  bootstrap/lib/kernel/ebin/prim_tty.beam
  erts/emulator/nifs/common/prim_tty_nif.c
  lib/kernel/src/prim_tty.erl
Labels: team:VM, fix, testing

#7353 [dialyzer] Simplify ets usage
  lib/dialyzer/src/dialyzer_cplt.erl
  lib/dialyzer/src/dialyzer_plt.erl
  lib/dialyzer/src/dialyzer_utils.erl
Labels: team:PS, enhancement, testing

#7386 Eliminate warnings for the debug build of the runtime system
  erts/emulator/beam/code_ix.c
  erts/emulator/beam/erl_term.h
  erts/emulator/beam/external.c
  erts/lib_src/yielding_c_fun/ycf_yield_fun.c
Labels: team:VM, enhancement, testing

#7376 common test: Fix typo in event handling chapter
  lib/common_test/doc/src/event_handler_chapter.xml
Labels: team:PS

#7327 mnesia: Fix test debug compile instructions
  lib/mnesia/test/README
Labels: team:PS

#7385 inets: Remove unused files in test suite
  lib/inets/test/Makefile
  lib/inets/test/httpd_all.erl
  lib/inets/test/httpd_mod.erl
  lib/inets/test/httpd_mod_SUITE.erl
  lib/inets/test/httpd_test_data/server_root/Makefile
  lib/inets/test/httpd_test_data/server_root/conf/8080.conf
  lib/inets/test/httpd_test_data/server_root/conf/8888.conf
  lib/inets/test/httpd_test_data/server_root/conf/httpd.conf
  lib/inets/test/httpd_test_data/server_root/conf/ssl.conf
Labels: team:PS, testing

#7387 emulator: Remove vestiges of special handling of x(0)
  erts/emulator/beam/beam_common.h
  erts/emulator/beam/emu/beam_emu.c
  erts/emulator/beam/emu/bif_instrs.tab
  erts/emulator/beam/emu/bs_instrs.tab
  erts/emulator/beam/emu/instrs.tab
  erts/emulator/beam/emu/msg_instrs.tab
  erts/emulator/beam/emu/trace_instrs.tab
  erts/emulator/utils/beam_makeops
Labels: team:VM, enhancement, testing

#7310 Document loading httpd mime_types from file
  lib/inets/doc/src/httpd.xml
Labels: team:PS

#7379 erts: Add docs for the multiline editing keybindings
  erts/doc/src/tty.xml
Labels: team:VM, documentation

#6805 Update docker build to work on non-Ubuntu hosts
  .github/dockerfiles/Dockerfile.ubuntu-base
  .github/dockerfiles/init.sh
  make/test_target_script.sh
Labels: team:IS

#7372 ssl: Add UG entry about signatue algorithm configuration
  lib/ssl/doc/src/using_ssl.xml
Labels: team:PS

#7383 erl_parse: Provide friendlier "head mismatch" errors
  lib/compiler/test/error_SUITE.erl
  lib/compiler/test/error_SUITE_data/head_mismatch_same_function_name.erl
  lib/stdlib/src/erl_parse.yrl
Labels: team:VM, enhancement, testing

#7395 debugger: Fix broken `int:no_break(Mod)`
  lib/debugger/src/dbg_icmd.erl
  lib/debugger/test/int_break_SUITE.erl
Labels: team:VM, fix, testing

#7408 Eliminate the temporary buffer for binary construction
  erts/emulator/beam/erl_alloc.c
  erts/emulator/beam/erl_bits.c
  erts/emulator/beam/erl_bits.h
  erts/emulator/beam/erl_init.c
  erts/emulator/beam/erl_process.c
  erts/emulator/beam/jit/arm/process_main.cpp
  erts/emulator/beam/jit/x86/process_main.cpp
  erts/emulator/valgrind/suppress.patched.3.6.0
Labels: team:VM, enhancement, testing

#7208 Fix `filelib:safe_relative_path/2`
  lib/stdlib/src/filelib.erl
  lib/stdlib/test/filelib_SUITE.erl
Labels: team:VM, testing

#7384 Fix problems when reading from stdin and "-noshell" was passed to erl (or used through an escript)
  bootstrap/lib/kernel/ebin/group.beam
  bootstrap/lib/kernel/ebin/prim_tty.beam
  bootstrap/lib/kernel/ebin/user_drv.beam
  bootstrap/lib/stdlib/ebin/io_lib.beam
  lib/kernel/doc/src/kernel_app.xml
  lib/kernel/src/group.erl
  lib/kernel/src/prim_tty.erl
  lib/kernel/src/user_drv.erl
  lib/kernel/test/Makefile
  lib/kernel/test/tty.cover
  lib/stdlib/src/io_lib.erl
  lib/stdlib/test/Makefile
  lib/stdlib/test/io_proto_SUITE.erl
  lib/stdlib/test/tty.cover
Labels: team:VM, testing, bug

#7404 kernel: code:get_doc/1 return missing, on missing preloaded
  lib/kernel/src/code.erl
Labels: team:VM, fix

#7242 kernel, stdlib, ssh: fix multiline editing bugs
  lib/kernel/src/group.erl
  lib/kernel/src/prim_tty.erl
  lib/kernel/src/user_drv.erl
  lib/kernel/test/interactive_shell_SUITE.erl
  lib/ssh/src/ssh_cli.erl
  lib/ssh/test/ssh_basic_SUITE.erl
  lib/ssh/test/ssh_test_lib.erl
  lib/stdlib/src/edlin.erl
Labels: team:VM, testing, bug

#7421 List code path choice strict and archive fallback as incompatibilities
  system/doc/general_info/upcoming_incompatibilities.xml
Labels: team:VM, documentation

#7380 common test: Synchronize capture start and stop
  lib/common_test/src/test_server.erl
  lib/common_test/src/test_server_gl.erl
  lib/tools/test/cover_SUITE.erl
Labels: team:PS, testing

#6112 erts: Remove `erts/etc/darwin/Info.plist`
  erts/emulator/Makefile.in
  erts/etc/darwin/Info.plist
Labels: team:VM

#7416 compiler: Fix bug in `nif_start` insertion
  lib/compiler/src/v3_core.erl
  lib/compiler/test/core_SUITE.erl
  lib/compiler/test/core_SUITE_data/nif.erl
Labels: team:VM, testing

#7406 ssl test debugging
  lib/ssl/src/ssl_manager.erl
  lib/ssl/test/ssl_pem_cache_SUITE.erl
  lib/ssl/test/ssl_session_SUITE.erl
  lib/ssl/test/ssl_session_cache_SUITE.erl
  lib/ssl/test/ssl_test_lib.erl
Labels: team:PS, testing

#7424 ct: add internal_doc and ct_notes.md
  lib/common_test/internal_doc/ct_notes.md
Labels: team:PS, testing

#7402 erts: Allow lack of optional fields when determining cgroup type
  erts/lib_src/common/erl_misc_utils.c
Labels: team:VM, testing

#7396 Drop support for OTP 22/23 in the runtime system
  erts/emulator/beam/beam_load.c
  erts/emulator/beam/emu/generators.tab
  erts/emulator/beam/emu/instrs.tab
  erts/emulator/beam/emu/ops.tab
  erts/emulator/beam/generators.tab
  erts/emulator/beam/jit/arm/generators.tab
  erts/emulator/beam/jit/arm/instr_common.cpp
  erts/emulator/beam/jit/arm/ops.tab
  erts/emulator/beam/jit/x86/generators.tab
  erts/emulator/beam/jit/x86/instr_common.cpp
  erts/emulator/beam/jit/x86/ops.tab
  erts/emulator/test/beam_literals_SUITE_data/unoptimized_literal_tests.S
  erts/emulator/test/tuple_SUITE_data/get_two_tuple_elements.S
  lib/compiler/src/beam_asm.erl
  lib/compiler/src/beam_validator.erl
  lib/compiler/src/genop.tab
  lib/compiler/test/beam_validator_SUITE.erl
  lib/compiler/test/beam_validator_SUITE_data/bad_catch_try.S
  lib/compiler/test/beam_validator_SUITE_data/bad_try_catch_nesting.S
  lib/compiler/test/beam_validator_SUITE_data/no_exception_in_catch.S
  lib/compiler/test/beam_validator_SUITE_data/overwrite_trytag.S
  lib/compiler/test/beam_validator_SUITE_data/receive_stacked.S
  lib/compiler/test/beam_validator_SUITE_data/safe_instructions.S
  lib/compiler/test/beam_validator_SUITE_data/stack.S
  lib/compiler/test/beam_validator_SUITE_data/uninit.S
  lib/compiler/test/beam_validator_SUITE_data/unsafe_catch.S
Labels: team:VM, enhancement, testing

#7437 Fix mis-evaluation of equality and non-equality tests
  erts/emulator/beam/jit/arm/instr_common.cpp
  erts/emulator/test/op_SUITE.erl
Labels: team:VM, fix, testing

#7440 Fix bit syntax creation of a bignum in a short non-aligned segment
  erts/emulator/beam/erl_bits.c
  erts/emulator/test/bs_construct_SUITE.erl
Labels: team:VM, fix, testing

#7422 `code`: reorder functions in docs
  lib/kernel/doc/src/code.xml
Labels: team:VM, testing

#7392 Make crypto run with FIPS on OpenSSL 3.0
  lib/crypto/c_src/Makefile.in
  lib/crypto/c_src/bn.c
  lib/crypto/c_src/bn.h
  lib/crypto/c_src/ec.c
  lib/crypto/c_src/ec.h
  lib/crypto/c_src/ecdh.c
  lib/crypto/c_src/openssl_config.h
  lib/crypto/c_src/pkey.c
  lib/crypto/doc/src/crypto_app.xml
  lib/crypto/src/crypto.erl
  lib/crypto/src/crypto_ec_curves.erl
  lib/crypto/test/crypto_SUITE.erl
  lib/crypto/test/engine_SUITE.erl
Labels: team:VM, fix

#7426 Optimize binary_to_integer/1 and friends
  erts/emulator/beam/bif.c
  erts/emulator/beam/bif.tab
  erts/emulator/beam/big.c
  erts/emulator/beam/big.h
  erts/emulator/beam/binary.c
  erts/emulator/beam/erl_arith.c
  erts/emulator/beam/erl_bif_info.c
  erts/emulator/beam/erl_term.h
  erts/emulator/test/big_SUITE.erl
  erts/emulator/test/big_SUITE_data/eq_big_mul_div.dat
  erts/emulator/test/big_SUITE_data/gen_data
  erts/emulator/test/big_SUITE_data/karatsuba.dat
  erts/emulator/test/exception_SUITE.erl
  erts/emulator/test/num_bif_SUITE.erl
  erts/preloaded/ebin/erlang.beam
  erts/preloaded/ebin/erts_internal.beam
  erts/preloaded/src/erlang.erl
  erts/preloaded/src/erts_internal.erl
  lib/stdlib/src/string.erl
  lib/stdlib/test/string_SUITE.erl
Labels: team:VM, enhancement, testing

#7445 Fixed wrong output for orddict:store code example
  lib/stdlib/doc/src/orddict.xml
Labels: team:VM

#7094 Minor refactor: use erts_cleanup_offheap_list in erl_db_util.c
  erts/emulator/beam/erl_db_util.c
Labels: team:VM, enhancement, testing

#7357 beam_ssa_throw: Exceptions may escape modules through funs
  lib/compiler/src/beam_ssa_throw.erl
  lib/compiler/test/trycatch_SUITE.erl
Labels: team:VM, fix, testing

#7443 Remove dialyzer --gui
  lib/dialyzer/Makefile
  lib/dialyzer/README
  lib/dialyzer/doc/src/dialyzer.xml
  lib/dialyzer/doc/src/dialyzer_chapter.xml
  lib/dialyzer/src/Makefile
  lib/dialyzer/src/dialyzer.app.src
  lib/dialyzer/src/dialyzer.erl
  lib/dialyzer/src/dialyzer_cl_parse.erl
  lib/dialyzer/src/dialyzer_explanation.erl
  lib/dialyzer/src/dialyzer_gui_wx.erl
  lib/dialyzer/src/dialyzer_gui_wx.hrl
  lib/dialyzer/src/dialyzer_plt.erl
Labels: team:VM, testing

#7446 Refine types for `min/2` and `max/2`
  lib/compiler/src/beam_bounds.erl
  lib/compiler/src/beam_call_types.erl
  lib/compiler/test/beam_bounds_SUITE.erl
  lib/compiler/test/bif_SUITE.erl
Labels: team:VM, enhancement, testing

#7452 Improve tutorial documentation
  system/doc/tutorial/complex6.erl
  system/doc/tutorial/debugging.xml
Labels: team:VM, enhancement, documentation

#7425 Handle seconds in `zip:dos_date_time_from_datetime/1`
  lib/stdlib/src/zip.erl
  lib/stdlib/test/zip_SUITE.erl
Labels: team:VM, testing

#7434 Clarify input behaviours on zip:create
  lib/stdlib/doc/src/zip.xml
Labels: team:VM, testing

#7450 crypto: Fix segv crash after purge and reload of crypto on musl libc
  lib/crypto/c_src/algorithms.c
  lib/crypto/c_src/algorithms.h
  lib/crypto/c_src/crypto.c
Labels: team:VM, fix, testing
