Repository erlang/otp, pull requests merged in 2023-09, with the labels that each got.

#7470 init: Introduce -S flag
  erts/doc/src/erl_cmd.xml
  erts/doc/src/init.xml
  erts/preloaded/src/init.erl
Labels: team:VM

#7551 Update configure_algos.xml
  lib/ssh/doc/src/configure_algos.xml
Labels: team:PS, testing, priority:low

#7610 Fix incorrect range calculation for operator `rem`
  erts/emulator/test/small_SUITE.erl
  lib/compiler/src/beam_bounds.erl
  lib/compiler/test/beam_bounds_SUITE.erl
Labels: team:VM, fix, testing

#7611 binary module: Always detect invalid patterns
  erts/emulator/beam/erl_bif_binary.c
  lib/stdlib/test/binary_module_SUITE.erl
Labels: team:VM, fix, testing

#7456 EEP 64: Emit warnings for triple-quoted strings
  bootstrap/lib/stdlib/ebin/epp.beam
  bootstrap/lib/stdlib/ebin/erl_parse.beam
  bootstrap/lib/stdlib/ebin/erl_scan.beam
  lib/stdlib/src/epp.erl
  lib/stdlib/src/erl_parse.yrl
  lib/stdlib/src/erl_scan.erl
  lib/stdlib/test/epp_SUITE.erl
Labels: team:VM, feature, in progress, priority:high, Planned

#7616 Properly handle BEAM files without the "Type" chunk
  erts/emulator/beam/beam_file.c
Labels: team:VM, fix, testing

#7603 Test BEAM files without type information
  erts/emulator/test/Makefile
  erts/emulator/test/bs_match_int_SUITE.erl
  erts/emulator/test/bs_utf_SUITE.erl
  lib/compiler/src/compile.erl
Labels: team:VM, enhancement, testing

#7587 Allow missing options in open() calls
  lib/kernel/src/inet.erl
  lib/kernel/test/inet_sockopt_SUITE.erl
Labels: team:PS, fix, in progress, priority:medium

#7623 Fix handling of binary data with address in UDP recv
  erts/preloaded/ebin/prim_inet.beam
  erts/preloaded/src/prim_inet.erl
  lib/kernel/test/gen_udp_SUITE.erl
Labels: team:PS, fix, in progress, priority:medium

#7622 Don't fail type assertion when BEAM file lacks types
  erts/emulator/beam/jit/arm/instr_fun.cpp
  erts/emulator/beam/jit/x86/instr_fun.cpp
Labels: team:VM, fix, testing

#7601 stdlib: make the shell multiline prompt configurable
  lib/kernel/src/group.erl
  lib/kernel/test/interactive_shell_SUITE.erl
  lib/stdlib/src/edlin.erl
Labels: team:VM, testing

#7604 stdlib: custom keybindings for the shell
  lib/kernel/src/group.erl
  lib/kernel/src/prim_tty.erl
  lib/kernel/src/user_drv.erl
  lib/kernel/test/interactive_shell_SUITE.erl
  lib/kernel/test/interactive_shell_SUITE_data/invalid_keymap.toml
  lib/kernel/test/interactive_shell_SUITE_data/valid_keymap.toml
  lib/stdlib/doc/src/Makefile
  lib/stdlib/doc/src/edlin.xml
  lib/stdlib/doc/src/ref_man.xml
  lib/stdlib/src/Makefile
  lib/stdlib/src/edlin.erl
  lib/stdlib/src/edlin_key.erl
  lib/stdlib/src/stdlib.app.src
Labels: team:VM

#7503 Reduce repeated work in concurrent code loading situations
  lib/kernel/src/code.erl
  lib/kernel/src/code_server.erl
  lib/kernel/test/code_SUITE.erl
Labels: team:VM, enhancement, testing

#7631 kernel: fix prim_tty xenl glitch
  lib/kernel/src/prim_tty.erl
Labels: team:VM

#7628 binary module: Always reject bitstrings
  erts/emulator/beam/erl_bif_binary.c
  lib/stdlib/test/binary_module_SUITE.erl
Labels: team:VM, fix, testing

#7633 Avoid unnecessary yielding when cleaning up signals
  erts/emulator/beam/erl_proc_sig_queue.c
Labels: team:VM, fix, testing

#7634 [erts] Fix local_node_hash
  erts/emulator/beam/external.c
Labels: team:VM, fix

#7607 Property-based tests for the `binary` module
  lib/stdlib/test/binary_property_test_SUITE.erl
  lib/stdlib/test/property_test/binary_prop.erl
Labels: team:VM, enhancement, testing

#7637 ASN.1 JER: Refactor type-information handling
  lib/asn1/src/asn1ct_gen.erl
  lib/asn1/src/asn1ct_gen_jer.erl
  lib/asn1/src/asn1rtt_jer.erl
  lib/asn1/test/Makefile
  lib/asn1/test/asn1_SUITE.erl
  lib/asn1/test/asn1_SUITE_data/Containing.asn1
  lib/asn1/test/testContaining.erl
Labels: team:VM, enhancement, testing

#7209 Libressl Adaptations
  lib/crypto/c_src/openssl_config.h
  lib/crypto/c_src/openssl_version.h
  lib/crypto/c_src/otp_test_engine.c
  lib/crypto/c_src/pkey.c
Labels: team:VM, fix

#7640 Fix ubuntu-base cache of old Erlang installs
  .github/dockerfiles/Dockerfile.ubuntu-base
  .github/workflows/main.yaml
  .github/workflows/pr-comment.yaml
Labels: team:VM, fix

#7646 Fix minor hprof issues
  lib/tools/src/tools.app.src
  lib/tools/test/hprof_SUITE.erl
Labels: team:VM, fix, testing

#7645 timer: Don't silently ignore errors when spawning processes
  lib/stdlib/src/timer.erl
Labels: team:VM, fix, testing

#7641 Export documented and exposed type binary:part/0
  lib/stdlib/src/binary.erl
Labels: team:VM, testing

#7299 inets: Implement simple command-line serving via httpd
  lib/inets/doc/src/http_server.xml
  lib/inets/src/http_server/httpd.erl
  lib/inets/test/Makefile
  lib/inets/test/httpd_serve_SUITE.erl
  lib/inets/test/httpd_serve_SUITE_data/aaa/info.txt
  lib/inets/test/httpd_serve_SUITE_data/index.html
  lib/inets/test/httpd_serve_SUITE_data/sample_file.html
  lib/inets/test/httpd_serve_SUITE_data/subdir/index.html
Labels: team:PS, priority:low

#7660 erl_lint: Don't emit spurious errors
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/test/erl_lint_SUITE.erl
Labels: team:VM, fix

#7647 stdlib: update the keymap configuration interface
  erts/doc/src/tty.xml
  lib/kernel/src/group.erl
  lib/kernel/test/interactive_shell_SUITE.erl
  lib/kernel/test/interactive_shell_SUITE_data/invalid_keymap.config
  lib/kernel/test/interactive_shell_SUITE_data/invalid_keymap.toml
  lib/kernel/test/interactive_shell_SUITE_data/valid_keymap.config
  lib/kernel/test/interactive_shell_SUITE_data/valid_keymap.toml
  lib/stdlib/doc/src/edlin.xml
  lib/stdlib/doc/src/shell.xml
  lib/stdlib/doc/src/specs.xml
  lib/stdlib/doc/src/stdlib_app.xml
  lib/stdlib/src/edlin.erl
  lib/stdlib/src/edlin_key.erl
Labels: team:VM, fix, documentation

#7639 erts: Fix -S and -extra to work as they should
  erts/doc/src/init.xml
  erts/etc/common/erlexec.c
  erts/preloaded/ebin/init.beam
  erts/preloaded/src/init.erl
  lib/kernel/test/init_SUITE.erl
Labels: team:VM, fix, testing

#7662 stdlib: update since tags in edlin.xml
  lib/stdlib/doc/src/edlin.xml
Labels: team:VM, fix, documentation

#7471 jit: Don't create heap binaries for non-binary bitstrings
  erts/emulator/beam/jit/arm/instr_bs.cpp
  erts/emulator/test/bs_construct_SUITE.erl
Labels: team:VM, testing

#7489 beam_ssa_type: Fix bugs relating to subtraction in type inference
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/test/beam_type_SUITE.erl
Labels: team:VM, fix, testing

#7656 Fix ct suite links
  lib/common_test/doc/src/basics_chapter.xml
  lib/common_test/doc/src/common_test_app.xml
  lib/common_test/doc/src/ct_cover.xml
  lib/common_test/doc/src/ct_hooks.xml
  lib/common_test/doc/src/getting_started_chapter.xml
  lib/common_test/doc/src/write_test_chapter.xml
Labels: team:VM, fix, testing, documentation

#7657 dialyzer: Fix parsing of --output for dialyzer
  lib/dialyzer/src/dialyzer_cl_parse.erl
Labels: team:VM, fix, testing

#7593 mnesia: Add figures for implementation documentation
  lib/mnesia/doc/misc/implementation_async_transaction.png
  lib/mnesia/doc/misc/implementation_async_transaction.puml
  lib/mnesia/doc/misc/implementation_table_loading.fig
  lib/mnesia/doc/misc/implementation_table_loading.png
Labels: team:PS

#7668 ssl: use log instead of pal in tests
  lib/ssl/test/ssl_alert_SUITE.erl
  lib/ssl/test/ssl_bench_test_lib.erl
Labels: team:PS, testing

#7670 Fix link problem with Xcode 15
  HOWTO/INSTALL-WIN32.md
  HOWTO/INSTALL.md
  lib/wx/c_src/Makefile.in
  lib/wx/configure
  lib/wx/configure.ac
Labels: team:VM, team:PS, fix, testing

#7665 Fix abs(-0.0) to return 0.0 instead of -0.0
  erts/emulator/beam/erl_bif_guard.c
Labels: team:VM, testing

#7672 Skip beam_ssa_alias for modules with huge functions
  lib/compiler/src/beam_ssa_alias.erl
Labels: team:VM, fix, testing

#7664 [doc update]: Module:init from wx_object behaviour should return wxWindow (and not …
  lib/wx/doc/src/wx_object.xml
  lib/wx/src/wx_object.erl
Labels: testing

#7110 [RFC] Allow dist input_handler to be added if the dist control is an internal port
  erts/doc/src/erlang.xml
  erts/emulator/beam/dist.c
  lib/ssl/test/inet_epmd_cryptcookie_inet_ktls.erl
  lib/ssl/test/ssl_dist_bench_SUITE.erl
Labels: team:VM, testing

#7681 ssh: format ssh_sup_SUITE
  lib/ssh/test/ssh_sup_SUITE.erl
  lib/ssh/test/ssh_test_lib.hrl
Labels: team:PS, testing

#7635 eunit: Add possibility to scale timeouts
  lib/eunit/src/eunit.erl
  lib/eunit/src/eunit_proc.erl
  lib/eunit/test/eunit_SUITE.erl
Labels: team:PS, enhancement, testing

#7630 erts: Restore console at exit on Windows
  erts/emulator/sys/win32/sys.c
Labels: team:VM, fix, testing

#7677 inets: Do not print test progress logs to terminal
  lib/inets/test/httpc_SUITE.erl
  lib/inets/test/httpd_SUITE.erl
  lib/inets/test/httpd_bench_SUITE.erl
  lib/inets/test/httpd_test_lib.erl
  lib/inets/test/inets_socketwrap_SUITE.erl
  lib/inets/test/inets_test_lib.erl
Labels: team:PS, testing

#7648 stdlib: garbage collect when saved shell history is reduced.
  lib/stdlib/doc/src/shell.xml
  lib/stdlib/src/shell.erl
Labels: team:VM, fix, testing

#7691 stdlib: garbage collect when saved shell history results are reduced.
  lib/stdlib/doc/src/shell.xml
  lib/stdlib/src/shell.erl
Labels: team:VM

#7596 inets: start ssl and dependencies by default
  lib/inets/src/inets_app/inets.erl
Labels: team:PS, fix, testing

#7556 Cache ebins found in escripts
  lib/kernel/src/code.erl
Labels: team:VM, testing

#7592 Add stacktrace in max heap size log
  erts/emulator/beam/erl_bif_info.c
  erts/emulator/beam/erl_gc.c
  erts/emulator/beam/erl_process.h
Labels: team:VM, feature, testing

#7626 Introduce a default state transition for "other" recv errors
  lib/kernel/src/gen_tcp_socket.erl
Labels: team:PS, fix, priority:medium

#7499 Fix SSH reverse search with CTRL+R
  lib/ssh/src/ssh_cli.erl
  lib/ssh/test/ssh_connection_SUITE.erl
Labels: team:PS, testing, Planned

#7674 ct: expand groups handle correct suite error
  lib/common_test/src/ct_framework.erl
  lib/common_test/test/ct_misc_1_SUITE.erl
  lib/common_test/test/ct_misc_1_SUITE_data/bad_groups_SUITE.erl
Labels: team:PS, testing

#7688 ssh: log not pal in ssh tests
  lib/common_test/src/ct_property_test.erl
  lib/ssh/test/ssh_options_SUITE.erl
  lib/ssh/test/ssh_protocol_SUITE.erl
  lib/ssh/test/ssh_sup_SUITE.erl
Labels: team:PS, testing, priority:low

#7704 gh: Refactor build base image
  .github/actions/build-base-image/action.yaml
  .github/workflows/main.yaml
  .github/workflows/update-base.yaml
Labels: team:VM, enhancement
