Repository erlang/otp, pull requests merged in 2024-12, with the labels that each got.

#9118 Fix deps
  lib/public_key/src/public_key.app.src
Labels: team:PS, testing

#9127 add connect_addr to Env in mod_esi callback
  lib/inets/src/http_server/httpd_script_env.erl
Labels: team:PS, testing

#9132 dialyzer: fix crash with nominal types
  lib/dialyzer/src/erl_types.erl
  lib/dialyzer/test/opaque_SUITE_data/src/union/union_nested_nominal.erl
Labels: team:VM, testing

#9143 common_test: cth_surefire don't fail on group skip
  lib/common_test/src/cth_surefire.erl
Labels: team:PS

#9144 dialyzer: fix issues related to opaques
  lib/dialyzer/src/dialyzer.hrl
  lib/dialyzer/src/dialyzer_contracts.erl
  lib/dialyzer/src/dialyzer_dataflow.erl
  lib/dialyzer/src/dialyzer_options.erl
  lib/dialyzer/test/opaque_SUITE_data/src/para/para6.erl
  lib/dialyzer/test/opaque_SUITE_data/src/para/para7.erl
Labels: team:VM, testing

#9099 fix redirection links in docs
  lib/kernel/doc/references/app.md
  lib/sasl/doc/references/appup.md
  lib/sasl/src/release_handler.erl
  lib/stdlib/src/gen_event.erl
  lib/stdlib/src/gen_fsm.erl
  lib/stdlib/src/gen_statem.erl
  system/doc/reference_manual/modules.md
  system/doc/system_principles/system_principles.md
Labels: team:VM

#9129 erts: Add BIFs `processes_iterator/0` and `processes_next/1`
  erts/emulator/beam/bif.c
  erts/emulator/beam/bif.tab
  erts/emulator/beam/erl_ptab.c
  erts/emulator/beam/erl_ptab.h
  erts/emulator/test/exception_SUITE.erl
  erts/emulator/test/process_SUITE.erl
  erts/preloaded/ebin/erlang.beam
  erts/preloaded/ebin/erts_internal.beam
  erts/preloaded/src/erlang.erl
  erts/preloaded/src/erts_internal.erl
  lib/kernel/src/erl_erts_errors.erl
  lib/tools/emacs/erlang.el
Labels: team:VM, testing

#9162 dialyzer: Fix slow Dialyzer run on Elixir source code
  lib/dialyzer/src/dialyzer_dataflow.erl
Labels: team:VM, testing

#9179 ssl: Fix testcase
  lib/ssl/test/ssl_upgrade_SUITE.erl
Labels: team:PS, testing

#9176 ssl: Move all configuration handling to ssl_config.erl
  lib/ssl/src/dtls_client_connection.erl
  lib/ssl/src/dtls_server_connection.erl
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_config.erl
  lib/ssl/src/ssl_gen_statem.erl
  lib/ssl/src/ssl_trace.erl
  lib/ssl/src/tls_client_connection.erl
  lib/ssl/src/tls_client_connection_1_3.erl
  lib/ssl/src/tls_dtls_gen_connection.erl
  lib/ssl/src/tls_server_connection.erl
  lib/ssl/src/tls_server_connection_1_3.erl
  lib/ssl/test/dtls_api_SUITE.erl
  lib/ssl/test/ssl_api_SUITE.erl
  lib/ssl/test/ssl_handshake_SUITE.erl
  lib/ssl/test/ssl_npn_hello_SUITE.erl
Labels: team:PS, testing

#9178 otp: move gdb-tools outside of erlang/otp repo
  .github/dockerfiles/Dockerfile.32-bit
  .github/dockerfiles/Dockerfile.clang
  .github/dockerfiles/Dockerfile.cross-compile
  .github/dockerfiles/Dockerfile.debian-base
  .github/workflows/main.yaml
  erts/etc/common/Makefile.in
  erts/etc/unix/cerl.src
  erts/etc/unix/jit-reader.c
  erts/etc/unix/jit-reader.h
  make/gdb_tools_link
  make/gdb_tools_vsn
  otp_build
Labels: team:VM, enhancement, testing

#9158 ssl: relax ssl_trace_SUITE
  lib/ssl/test/ssl_trace_SUITE.erl
Labels: team:PS, testing

#9161 ssh: fix connection_info result typespec
  lib/ssh/src/ssh.erl
Labels: team:PS, testing

#9170 ssl: Remove unnecessary code generalization
  lib/ssl/src/dtls_socket.erl
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_gen_statem.erl
  lib/ssl/src/ssl_trace.erl
  lib/ssl/src/tls_socket.erl
  lib/ssl/test/dtls_api_SUITE.erl
  lib/ssl/test/ssl_trace_SUITE.erl
Labels: team:PS, testing

#9121 beam_validator: Reject functions with more than MAX_ARG arguments
  lib/compiler/src/beam_validator.erl
  lib/compiler/test/beam_validator_SUITE.erl
  system/doc/efficiency_guide/system_limits.md
Labels: team:VM, testing

#8973 sasl: include appup files in release package
  lib/sasl/src/systools_make.erl
  lib/sasl/test/systools_SUITE.erl
Labels: team:VM, testing

#9181 lib/dialyzer/test: replace `random:uniform/1` by `rand:uniform/1`
  lib/dialyzer/test/indent_SUITE_data/src/map_galore.erl
  lib/dialyzer/test/indent_SUITE_data/src/simple/is_rec.erl
  lib/dialyzer/test/map_SUITE_data/src/map_galore.erl
  lib/dialyzer/test/opaque_SUITE_data/src/simple/is_rec.erl
  lib/dialyzer/test/options2_SUITE_data/src/kernel/global.erl
  lib/dialyzer/test/r9c_SUITE_data/src/asn1/asn1ct_value.erl
  lib/dialyzer/test/r9c_SUITE_data/src/mnesia/mnesia_lib.erl
  lib/dialyzer/test/small_SUITE_data/src/false_false.erl
Labels: team:VM, testing

#9139 ssh: avoid protocol error on userauth banner
  lib/ssh/src/ssh_fsm_userauth_client.erl
  lib/ssh/test/ssh_protocol_SUITE.erl
Labels: team:PS, testing

#9136 crypto: Make ed25519/x25519 available without ed448/x448
  lib/crypto/c_src/algorithms.c
  lib/crypto/c_src/atoms.c
  lib/crypto/c_src/atoms.h
  lib/crypto/c_src/eddsa.c
  lib/crypto/c_src/evp.c
  lib/crypto/c_src/openssl_config.h
Labels: team:VM, fix, testing

#9186 Improve strings with indent-region
  lib/tools/emacs/erlang.el
  lib/tools/test/emacs_SUITE_data/comprehensions
  lib/tools/test/emacs_SUITE_data/type_specs
Labels: team:PS, testing

#9195 erts: Fix -Werror to be passed to cl.exe
  erts/etc/win32/wsl_tools/vc/cc.sh
Labels: team:VM, fix, testing

#9151 stdlib: Fix argparse:format_help/2 crash on 'hidden' command
  lib/stdlib/src/argparse.erl
  lib/stdlib/test/argparse_SUITE.erl
Labels: team:VM, fix, testing

#9116 kernel: Update standard_error to use prim_tty nif
  bootstrap/lib/kernel/ebin/prim_tty.beam
  bootstrap/lib/kernel/ebin/standard_error.beam
  erts/emulator/nifs/common/prim_tty_nif.c
  lib/kernel/src/prim_tty.erl
  lib/kernel/src/standard_error.erl
Labels: team:VM, enhancement, testing

#9171 stdlib: Fix preorder and postorder traversals in `digraph_utils`
  lib/stdlib/src/digraph_utils.erl
  lib/stdlib/test/digraph_utils_SUITE.erl
Labels: team:VM, testing

#9147 stdlib: reduce test log on gh
  lib/common_test/src/cte_track.erl
  lib/stdlib/test/gen_event_SUITE.erl
  lib/stdlib/test/gen_server_SUITE.erl
  lib/stdlib/test/gen_server_SUITE_data/format_status_server.erl
  lib/stdlib/test/gen_statem_SUITE_data/format_status_statem.erl
  lib/stdlib/test/io_proto_SUITE.erl
  lib/stdlib/test/peer_SUITE.erl
  lib/stdlib/test/rand_SUITE.erl
  lib/stdlib/test/stdlib_gh.spec
Labels: team:PS, testing

#9192 Fix doc metadata conversion
  bootstrap/bin/no_dot_erlang.boot
  bootstrap/bin/start.boot
  bootstrap/bin/start_clean.boot
  bootstrap/lib/compiler/ebin/beam_asm.beam
  bootstrap/lib/compiler/ebin/beam_doc.beam
  bootstrap/lib/compiler/ebin/beam_ssa.beam
  bootstrap/lib/compiler/ebin/beam_ssa_destructive_update.beam
  bootstrap/lib/kernel/ebin/erl_erts_errors.beam
  bootstrap/lib/stdlib/ebin/argparse.beam
  bootstrap/lib/stdlib/ebin/erl_lint.beam
  bootstrap/lib/stdlib/ebin/erl_scan.beam
  bootstrap/lib/stdlib/ebin/gen_fsm.beam
  bootstrap/lib/stdlib/ebin/shell_docs.beam
  erts/doc/docs.exs
  erts/preloaded/src/erlang.erl
  lib/compiler/src/beam_doc.erl
  lib/compiler/test/beam_doc_SUITE.erl
  lib/compiler/test/beam_doc_SUITE_data/converted_metadata.erl
  lib/compiler/test/beam_doc_SUITE_data/converted_metadata_warnings.erl
  lib/kernel/doc/guides/eep48_chapter.md
  system/doc/reference_manual/documentation.md
Labels: team:VM, fix

#9197 ssh: refactor ssh_system_sup
  lib/ssh/src/ssh_system_sup.erl
Labels: team:PS, testing

#9082 os: Add exception_on_failure to os:cmd/2
  lib/kernel/src/os.erl
  lib/kernel/test/os_SUITE.erl
Labels: team:VM, testing

#9156 Michal/common_test/fix_compatiblity_between_otp27_and_earlier/ERIERL-1166/OTP-19385
  lib/common_test/src/ct_logs.erl
Labels: team:PS, testing

#9201 Michal/mnesia/disc based ext backend simulator
  lib/mnesia/test/Makefile
  lib/mnesia/test/ext_test.erl
  lib/mnesia/test/ext_test_server.erl
  lib/mnesia/test/ext_test_server.hrl
  lib/mnesia/test/mnesia.spec
  lib/mnesia/test/mnesia_config_test.erl
  lib/mnesia/test/mnesia_dirty_access_test.erl
  lib/mnesia/test/mnesia_evil_coverage_test.erl
  lib/mnesia/test/mnesia_external_backend_test.erl
  lib/mnesia/test/mnesia_test_lib.erl
  lib/mnesia/test/mnesia_test_lib.hrl
Labels: team:PS, testing

#9196 Michal/mnesia/polish_user_guide
  lib/mnesia/doc/guides/mnesia_app_a.md
  lib/mnesia/doc/guides/mnesia_app_b.md
  lib/mnesia/doc/guides/mnesia_app_c.md
  lib/mnesia/doc/guides/mnesia_chap2.md
  lib/mnesia/doc/guides/mnesia_chap3.md
  lib/mnesia/doc/guides/mnesia_chap4.md
  lib/mnesia/doc/guides/mnesia_chap5.md
  lib/mnesia/doc/guides/mnesia_chap7.md
  lib/mnesia/doc/src/bup.erl
  lib/mnesia/doc/src/company.erl
  lib/mnesia/doc/src/company_o.erl
  lib/mnesia/doc/src/company_o.hrl
  lib/mnesia/src/mnesia.erl
Labels: team:PS, testing

#8811 erl_syntax_lib: annotate `maybe_match_expr` and `else_expr` correctly
  lib/syntax_tools/src/erl_syntax_lib.erl
  lib/syntax_tools/test/syntax_tools_SUITE.erl
Labels: team:VM, testing

#9228 ssl: refactor related to CodeScene review
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_handshake.erl
Labels: team:PS, testing
