Repository erlang/otp, pull requests merged in 2024-07, with the labels that each got.

#8627 Fix cpool_delete()
  erts/emulator/beam/erl_alloc_util.c
Labels: team:VM, fix, testing

#7919 ct: Allow empty groups in test suites
  lib/common_test/src/ct_groups.erl
  lib/common_test/src/test_server_ctrl.erl
  lib/common_test/test/ct_groups_search_SUITE.erl
  lib/common_test/test/ct_misc_1_SUITE.erl
  lib/common_test/test/ct_misc_1_SUITE_data/empty_group_SUITE.erl
Labels: team:PS, testing, priority:low

#8637 Add warning to not use crypto:start/0 with FIPS
  lib/crypto/src/crypto.erl
Labels: team:VM, testing, documentation

#8590 crypto: Warning if FIPS supported but application 'crypto' not loaded
  lib/crypto/src/crypto.app.src
  lib/crypto/src/crypto.erl
Labels: team:VM, enhancement, testing

#7830 ct: Add dark mode support to coverage pages
  lib/common_test/src/test_server_ctrl.erl
  lib/tools/priv/styles.css
Labels: team:PS, testing

#8638 stdlib: fix completion bug
  lib/stdlib/src/edlin_context.erl
  lib/stdlib/test/edlin_context_SUITE.erl
Labels: fix, testing

#8573 Fix up the built-in help text in the shell
  lib/stdlib/src/c.erl
  lib/stdlib/src/shell.erl
  lib/stdlib/src/shell_default.erl
Labels: team:VM, testing

#8624 Ingela/ssl/default cert sign/gh 8588/otp 19152
  lib/ssl/src/dtls_handshake.erl
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/src/tls_handshake.erl
  lib/ssl/src/tls_handshake_1_3.erl
  lib/ssl/test/ssl_api_SUITE.erl
  lib/ssl/test/ssl_cert_SUITE.erl
  lib/ssl/test/ssl_test_lib.erl
Labels: team:PS, testing

#8647 ssl: Remove documentation of internal value
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_cipher_format.erl
Labels: team:PS, testing

#8628 [logger_olp] Avoid repeated calls to persistent_term:put
  lib/kernel/src/logger_olp.erl
Labels: team:VM, testing

#8636 Fix incorrect carrier count statistics after using instrument module
  erts/emulator/beam/erl_alloc_util.c
  erts/emulator/beam/erl_alloc_util.h
Labels: team:VM, fix, testing

#8655 Optimize process and port creation without tracing
  erts/emulator/beam/erl_bif_trace.c
  erts/emulator/beam/erl_process.c
  erts/emulator/beam/erl_trace.c
  erts/emulator/beam/erl_trace.h
  erts/emulator/beam/io.c
Labels: team:VM, enhancement

#8507 Bump ex_doc version and fix copyright year
  .github/scripts/build-base-image.sh
  .github/workflows/update-base.yaml
  make/ex_doc.exs
  make/ex_doc.sha1sum
  make/ex_doc.sha256sum
  make/ex_doc_link
  make/ex_doc_vsn
Labels: team:VM, testing

#8648 Use the pre cached callback_mode value for logger
  lib/stdlib/src/gen_statem.erl
  lib/stdlib/test/gen_statem_SUITE.erl
Labels: team:PS, fix, in progress, priority:medium

#8578 inets: Small fixes for httpd documentation
  lib/inets/src/http_server/httpd.erl
Labels: team:PS, testing, Planned

#8575 httpc: Fix percent-encoding of userinfo in URLs
  lib/inets/src/http_client/httpc_request.erl
  lib/inets/test/httpc_SUITE.erl
Labels: team:PS, testing, Planned

#8310 ssh: start monitor ConnPid before casting socket_control
  lib/ssh/src/ssh_connection_handler.erl
Labels: team:PS, testing

#8663 ssh: re-use try_listen for ssh:daemon with integer port number
  lib/ssh/src/ssh_acceptor.erl
Labels: team:PS, testing

#8665 Update README.md instructions to checkout latest stable branch
  README.md
Labels: team:VM

#8667 Fixed typo in `erlc` documentation
  erts/doc/references/erlc_cmd.md
Labels: team:VM

#8658 Fix typo in `maybe` expression documentation
  system/doc/reference_manual/expressions.md
Labels: team:VM

#8631 Fix atom_to_binary to use pre-allocated binary (Reopened)
  erts/emulator/beam/atom.c
  erts/emulator/beam/atom.h
  erts/emulator/beam/beam_file.c
  erts/emulator/beam/bif.c
  erts/emulator/beam/dist.c
  erts/emulator/beam/emu/generators.tab
  erts/emulator/beam/erl_alloc_util.c
  erts/emulator/beam/erl_bif_ddll.c
  erts/emulator/beam/erl_bif_info.c
  erts/emulator/beam/erl_bif_re.c
  erts/emulator/beam/erl_db_util.c
  erts/emulator/beam/erl_global_literals.c
  erts/emulator/beam/erl_global_literals.h
  erts/emulator/beam/erl_init.c
  erts/emulator/beam/erl_lock_check.c
  erts/emulator/beam/erl_nif.c
  erts/emulator/beam/erl_printf_term.c
  erts/emulator/beam/erl_process_dump.c
  erts/emulator/beam/erl_term.h
  erts/emulator/beam/erl_unicode.c
  erts/emulator/beam/erl_utils.h
  erts/emulator/beam/export.c
  erts/emulator/beam/external.c
  erts/emulator/beam/global.h
  erts/emulator/beam/jit/arm/generators.tab
  erts/emulator/beam/jit/beam_jit_common.cpp
  erts/emulator/beam/jit/x86/generators.tab
  erts/emulator/sys/common/erl_mmap.c
  erts/emulator/sys/common/erl_mmap.h
  erts/emulator/test/bif_SUITE.erl
  erts/etc/unix/etp-commands.in
Labels: team:VM, testing

#8577 Describe key combinations consistently
  HOWTO/INSTALL-RASPBERRYPI3.md
  erts/emulator/beam/break.c
  erts/emulator/beam/erl_init.c
  erts/emulator/nifs/common/prim_tty_nif.c
  erts/emulator/sys/unix/erl_child_setup.c
  erts/emulator/sys/unix/sys.c
  erts/emulator/sys/win32/sys_interrupt.c
  lib/debugger/test/dbg_ui_SUITE.erl
  lib/kernel/test/interactive_shell_SUITE_data/valid_keymap.config
  lib/observer/src/observer_port_wx.erl
  lib/observer/src/observer_pro_wx.erl
  lib/observer/src/observer_procinfo.erl
  lib/observer/src/observer_sock_wx.erl
  lib/observer/src/observer_sys_wx.erl
  lib/observer/src/observer_trace_wx.erl
  lib/observer/src/observer_tv_table.erl
  lib/observer/src/observer_tv_wx.erl
  lib/reltool/test/reltool_manual_gui_SUITE.erl
  lib/ssh/src/ssh_connect.hrl
  lib/ssl/test/dtls_api_SUITE.erl
  lib/stdlib/doc/stdlib_app.md
  lib/stdlib/src/edlin_key.erl
  lib/stdlib/src/erl_scan.erl
  lib/stdlib/src/shell.erl
  lib/wx/examples/simple/menu.erl
  lib/wx/src/gen/wxKeyEvent.erl
  lib/wx/src/gen/wxMenuBar.erl
  lib/wx/src/gen/wxNavigationKeyEvent.erl
Labels: team:VM, testing

#8678 compiler: Fix erroneous makefile dependency
  lib/compiler/src/Makefile
Labels: team:VM, testing

#8680 compiler tests: Correct bad timetrap limit
  lib/compiler/test/random_code_SUITE.erl
Labels: team:VM, testing
