Repository erlang/otp, pull requests merged in 2024-02, with the labels that each got.

#8067 Enable the maybe expression by default
  bootstrap/lib/stdlib/ebin/epp.beam
  bootstrap/lib/stdlib/ebin/erl_features.beam
  erts/preloaded/src/init.erl
  lib/asn1/src/asn1ct.erl
  lib/common_test/test/ct_config_SUITE_data/config/test/config_static_SUITE.erl
  lib/compiler/src/beam_doc.erl
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/test/beam_jump_SUITE.erl
  lib/compiler/test/beam_ssa_SUITE.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/alias.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/private_append.erl
  lib/compiler/test/core_fold_SUITE.erl
  lib/compiler/test/map_SUITE.erl
  lib/compiler/test/maybe_SUITE.erl
  lib/compiler/test/warnings_SUITE.erl
  lib/debugger/test/maybe_SUITE.erl
  lib/dialyzer/src/dialyzer_typesig.erl
  lib/dialyzer/test/indent_SUITE_data/src/guard_warnings.erl
  lib/dialyzer/test/opaque_SUITE_data/src/recrec/dialyzer.hrl
  lib/dialyzer/test/r9c_SUITE_data/src/asn1/asn1ct_constructed_ber.erl
  lib/dialyzer/test/r9c_SUITE_data/src/asn1/asn1ct_constructed_ber_bin_v2.erl
  lib/dialyzer/test/small_SUITE_data/src/comparisons.erl
  lib/dialyzer/test/small_SUITE_data/src/extra_range.erl
  lib/dialyzer/test/small_SUITE_data/src/guard_warnings.erl
  lib/kernel/src/inet_epmd_dist.erl
  lib/kernel/src/inet_epmd_socket.erl
  lib/kernel/src/inet_tcp_dist.erl
  lib/kernel/test/init_SUITE.erl
  lib/ssl/src/inet_tls_dist.erl
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/test/cryptcookie.erl
  lib/ssl/test/dist_cryptcookie.erl
  lib/ssl/test/inet_epmd_cryptcookie_inet_ktls.erl
  lib/ssl/test/inet_epmd_cryptcookie_socket_ktls.erl
  lib/ssl/test/inet_epmd_dist_cryptcookie_inet.erl
  lib/ssl/test/inet_epmd_dist_cryptcookie_socket.erl
  lib/ssl/test/ssl_dist_SUITE.erl
  lib/ssl/test/ssl_dist_bench_SUITE.erl
  lib/stdlib/src/epp.erl
  lib/stdlib/src/erl_features.erl
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/test/erl_eval_SUITE.erl
  lib/tools/test/cover_SUITE.erl
  system/doc/reference_manual/expressions.md
Labels: team:VM, testing

#8049 Produce less garbage on module lookup
  lib/kernel/src/code_server.erl
Labels: team:VM, enhancement, testing

#8076 logger: Fix add_handlers with config to work
  lib/kernel/src/logger.erl
Labels: team:VM, fix, testing

#8074 Fix termcap detection on solaris
  erts/config.h.in
  erts/configure
  erts/configure.ac
  erts/emulator/nifs/common/prim_tty_nif.c
Labels: team:VM, fix, testing

#8075 stdlib: Fix edlin_expand for invalid atoms
  lib/stdlib/src/edlin_context.erl
  lib/stdlib/src/edlin_expand.erl
  lib/stdlib/test/edlin_expand_SUITE.erl
Labels: team:VM, fix, testing

#7697 Remove erl_prim_loader fallback on module lookup
  lib/kernel/src/code_server.erl
  lib/kernel/test/code_SUITE.erl
Labels: team:VM, fix

#8068 zlib: Remove deprecated functions
  bootstrap/lib/stdlib/ebin/otp_internal.beam
  erts/emulator/nifs/common/zlib_nif.c
  erts/preloaded/ebin/zlib.beam
  erts/preloaded/src/zlib.erl
  lib/kernel/test/zlib_SUITE.erl
  lib/stdlib/src/otp_internal.erl
Labels: team:VM, testing

#8081 ssl: Correct default value
  lib/ssl/src/dtls_record.erl
Labels: team:PS, testing

#8080 ssl: Correct OTP-26 documentation
  lib/ssl/doc/src/ssl.xml
Labels: team:PS, testing

#8082 ssh: escalate sanity related test skips
  lib/ssh/test/ssh_connection_SUITE.erl
  lib/ssh/test/ssh_test_lib.erl
  lib/ssh/test/ssh_to_openssh_SUITE.erl
Labels: team:PS

#7427 ct: cte_track event handler
  lib/common_test/src/Makefile
  lib/common_test/src/common_test.app.src
  lib/common_test/src/cte_track.erl
  lib/inets/test/inets.spec
  lib/ssh/test/ssh.spec
  lib/ssl/test/ssl_gh.spec
Labels: team:PS, enhancement, testing, priority:low

#8034 dialyzer: document warning flag unknown
  lib/dialyzer/src/dialyzer_cl_parse.erl
Labels: team:VM, documentation, types

#8088 Dirty signal handling fix
  erts/emulator/beam/erl_proc_sig_queue.c
  erts/emulator/beam/erl_proc_sig_queue.h
  erts/emulator/beam/erl_process.c
  erts/emulator/beam/erl_process.h
  erts/emulator/test/signal_SUITE.erl
Labels: team:VM, fix, testing

#8086 Combine creation of a record with subsequent record updates
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/test/record_SUITE.erl
Labels: team:VM, enhancement, testing

#7975 ssl: Refactor pre TLS-1.3 to separate client/server state machines
  lib/ssl/src/Makefile
  lib/ssl/src/dtls_client_connection.erl
  lib/ssl/src/dtls_connection.erl
  lib/ssl/src/dtls_gen_connection.erl
  lib/ssl/src/dtls_server_connection.erl
  lib/ssl/src/ssl.app.src
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_config.erl
  lib/ssl/src/ssl_connection.hrl
  lib/ssl/src/ssl_gen_statem.erl
  lib/ssl/src/ssl_trace.erl
  lib/ssl/src/tls_client_connection.erl
  lib/ssl/src/tls_client_connection_1_3.erl
  lib/ssl/src/tls_connection.erl
  lib/ssl/src/tls_dtls_client_connection.erl
  lib/ssl/src/tls_dtls_connection.erl
  lib/ssl/src/tls_dtls_gen_connection.erl
  lib/ssl/src/tls_dtls_server_connection.erl
  lib/ssl/src/tls_dyn_connection_sup.erl
  lib/ssl/src/tls_gen_connection.erl
  lib/ssl/src/tls_gen_connection_1_3.erl
  lib/ssl/src/tls_sender.erl
  lib/ssl/src/tls_server_connection.erl
  lib/ssl/src/tls_server_connection_1_3.erl
  lib/ssl/test/ssl_renegotiate_SUITE.erl
  lib/ssl/test/ssl_trace_SUITE.erl
Labels: team:PS, testing

#7966 kernel: Fix group get_until to allow eof only in result
  lib/kernel/src/group.erl
Labels: team:VM, fix, testing

#8093 Make options in the `-compile` attribute take precedence
  lib/compiler/src/compile.erl
Labels: team:VM, testing

#8092 Remove deprecated file:pid2name/1
  bootstrap/lib/stdlib/ebin/otp_internal.beam
  lib/kernel/src/file.erl
  lib/kernel/src/file_io_server.erl
  lib/kernel/test/file_SUITE.erl
  lib/stdlib/src/otp_internal.erl
  lib/stdlib/test/error_logger_h_SUITE.erl
Labels: team:VM, testing

#8090 Destructive tuple update
  bootstrap/lib/compiler/ebin/compiler.app
  erts/emulator/beam/atom.names
  erts/emulator/beam/emu/generators.tab
  erts/emulator/beam/emu/instrs.tab
  erts/emulator/beam/emu/ops.tab
  erts/emulator/beam/jit/arm/beam_asm.hpp
  erts/emulator/beam/jit/arm/instr_common.cpp
  erts/emulator/beam/jit/arm/ops.tab
  erts/emulator/beam/jit/x86/instr_common.cpp
  erts/emulator/beam/jit/x86/ops.tab
  lib/compiler/src/Makefile
  lib/compiler/src/beam_digraph.erl
  lib/compiler/src/beam_ssa_alias.erl
  lib/compiler/src/beam_ssa_check.erl
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/src/beam_ssa_destructive_update.erl
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/beam_ssa_private_append.erl
  lib/compiler/src/beam_ssa_ss.erl
  lib/compiler/src/beam_ssa_type.erl
  lib/compiler/src/beam_validator.erl
  lib/compiler/src/compile.erl
  lib/compiler/src/compiler.app.src
  lib/compiler/test/beam_ssa_check_SUITE.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/alias.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/alias_chain.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/alias_non_convergence.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/private_append.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/sanity_checks.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/tuple_inplace_checks.erl
  lib/compiler/test/bs_construct_SUITE.erl
  lib/stdlib/src/erl_parse.yrl
Labels: team:VM, enhancement, testing

#8101 beam_types: Fix another +0.0/-0.0 issue
  lib/compiler/src/beam_types.erl
  lib/compiler/test/beam_type_SUITE.erl
Labels: team:VM, testing

#8102 compiler: Remove opaque type deps from doc type analysis
  bootstrap/lib/compiler/ebin/beam_doc.beam
  lib/compiler/src/beam_doc.erl
  lib/compiler/test/beam_doc_SUITE.erl
  lib/compiler/test/beam_doc_SUITE_data/private_types.erl
Labels: team:VM, fix

#8071 Kuba/ssh/add specs
  lib/ssh/src/ssh.erl
  lib/ssh/src/ssh_client_channel.erl
  lib/ssh/src/ssh_sftp.erl
  lib/ssh/src/ssh_system_sup.erl
Labels: team:PS

#7809 Various improvements to NIF/crypto upgrade and unload
  erts/doc/references/erl_nif.md
  erts/emulator/beam/code_ix.c
  erts/emulator/beam/erl_nif.c
  erts/emulator/beam/erl_nif.h
  erts/emulator/beam/erl_process.c
  erts/emulator/beam/erl_process.h
  erts/emulator/test/nif_SUITE.erl
  erts/emulator/test/nif_SUITE_data/nif_mod.c
  erts/emulator/test/nif_SUITE_data/nif_mod.erl
  erts/emulator/test/nif_SUITE_data/nif_mod.h
  lib/crypto/c_src/crypto.c
Labels: team:VM, enhancement

#7125 Remove Vanilla Drivers
  erts/emulator/beam/erl_bif_port.c
  erts/emulator/beam/global.h
  erts/emulator/beam/io.c
  erts/emulator/sys/unix/sys_drivers.c
  erts/emulator/sys/win32/sys.c
  erts/emulator/test/binary_SUITE.erl
  erts/emulator/test/fun_SUITE.erl
  erts/emulator/test/port_SUITE.erl
Labels: team:VM, testing, review_help_wanted

#8127 otp: Fix links and lists after markdown convertion
  lib/crypto/src/crypto.erl
  lib/inets/doc/notes.md
  lib/inets/src/http_client/httpc.erl
  lib/kernel/src/gen_sctp.erl
  lib/mnesia/doc/guides/mnesia_chap4.md
  lib/observer/doc/guides/etop_ug.md
  lib/odbc/doc/guides/databases.md
  lib/ssh/doc/guides/introduction.md
  lib/ssh/src/ssh.erl
  lib/ssh/src/ssh_client_channel.erl
  lib/ssh/src/ssh_client_key_api.erl
  lib/ssh/src/ssh_connection.erl
  lib/ssh/src/ssh_sftp.erl
  lib/ssl/src/ssl.erl
  lib/syntax_tools/src/erl_syntax_lib.erl
Labels: team:VM, fix

#8108 Make alias analysis less conservative with calls
  lib/compiler/src/beam_ssa_alias.erl
  lib/compiler/src/beam_ssa_ss.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/private_append.erl
Labels: team:VM, testing

#8125 compiler: Handle nested tuple updates in destructive update pass
  lib/compiler/src/beam_ssa_destructive_update.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/tuple_inplace_checks.erl
Labels: team:VM, testing

#8059 fix typo in comment of essio and esaio
  erts/emulator/nifs/common/socket_asyncio.h
  erts/emulator/nifs/unix/unix_socket_syncio.c
Labels: team:PS

#8135 Some ssl state refactoring
  lib/ssl/src/dtls_client_connection.erl
  lib/ssl/src/dtls_gen_connection.erl
  lib/ssl/src/dtls_record.erl
  lib/ssl/src/dtls_server_connection.erl
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_connection.hrl
  lib/ssl/src/ssl_gen_statem.erl
  lib/ssl/src/ssl_handshake.erl
  lib/ssl/src/ssl_logger.erl
  lib/ssl/src/ssl_record.erl
  lib/ssl/src/ssl_record.hrl
  lib/ssl/src/tls_client_connection.erl
  lib/ssl/src/tls_client_connection_1_3.erl
  lib/ssl/src/tls_dtls_client_connection.erl
  lib/ssl/src/tls_dtls_gen_connection.erl
  lib/ssl/src/tls_dtls_server_connection.erl
  lib/ssl/src/tls_gen_connection.erl
  lib/ssl/src/tls_gen_connection_1_3.erl
  lib/ssl/src/tls_handshake_1_3.erl
  lib/ssl/src/tls_record.erl
  lib/ssl/src/tls_record_1_3.erl
  lib/ssl/src/tls_record_1_3.hrl
  lib/ssl/src/tls_sender.erl
  lib/ssl/src/tls_server_connection.erl
  lib/ssl/src/tls_server_connection_1_3.erl
  lib/ssl/test/openssl_session_ticket_SUITE.erl
  lib/ssl/test/ssl_bench_SUITE.erl
  lib/ssl/test/ssl_npn_hello_SUITE.erl
  lib/ssl/test/ssl_session_SUITE.erl
  lib/ssl/test/tls_1_3_record_SUITE.erl
Labels: team:PS

#8123 compiler: Add warn_missing_doc_functions et all and enable in all docs
  bootstrap/lib/compiler/ebin/beam_doc.beam
  lib/common_test/proper_ext/ct_proper_ext.erl
  lib/common_test/src/cte_track.erl
  lib/compiler/src/beam_doc.erl
  lib/compiler/src/beam_ssa_ss.erl
  lib/compiler/src/cerl.erl
  lib/compiler/src/cerl_trees.erl
  lib/compiler/src/compile.erl
  lib/compiler/src/core_parse.yrl
  lib/compiler/test/beam_doc_SUITE.erl
  lib/dialyzer/src/dialyzer.erl
  lib/diameter/src/compiler/diameter_dict_parser.yrl
  lib/et/examples/Makefile
  lib/eunit/src/eunit_autoexport.erl
  lib/eunit/src/eunit_surefire.erl
  lib/inets/examples/httpd_load_test/Makefile
  lib/megaco/examples/simple/Makefile
  lib/observer/src/crashdump_viewer.erl
  lib/parsetools/include/yeccpre.hrl
  lib/snmp/examples/ex1/Makefile
  lib/snmp/examples/ex2/Makefile
  lib/ssl/examples/src/Makefile
  lib/ssl/src/dtls_client_connection.erl
  lib/ssl/src/dtls_server_connection.erl
  lib/ssl/src/tls_client_connection.erl
  lib/ssl/src/tls_dtls_client_connection.erl
  lib/ssl/src/tls_dtls_gen_connection.erl
  lib/ssl/src/tls_dtls_server_connection.erl
  lib/ssl/src/tls_server_connection.erl
  lib/stdlib/src/erl_parse.yrl
  lib/stdlib/uc_spec/gen_unicode_mod.escript
  lib/syntax_tools/src/merl_transform.erl
  lib/tools/src/xref_parser.yrl
  lib/wx/examples/demo/Makefile
  lib/wx/examples/simple/Makefile
  lib/wx/examples/sudoku/Makefile
  lib/wx/src/Makefile
  lib/xmerl/src/xmerl_b64Bin.yrl
  lib/xmerl/src/xmerl_sax_parser_latin1.erlsrc
  lib/xmerl/src/xmerl_sax_parser_list.erlsrc
  lib/xmerl/src/xmerl_sax_parser_utf16be.erlsrc
  lib/xmerl/src/xmerl_sax_parser_utf16le.erlsrc
  lib/xmerl/src/xmerl_sax_parser_utf8.erlsrc
  lib/xmerl/src/xmerl_xpath_parse.yrl
  make/otp.mk.in
Labels: team:VM

#8010 tprof: Fix memory tracing to work for modules loaded while profiling
  erts/emulator/beam/erl_bif_trace.c
  erts/emulator/test/trace_call_memory_SUITE.erl
  lib/tools/src/tprof.erl
  lib/tools/test/tprof_SUITE.erl
Labels: team:VM, fix, testing

#8152 AArch64: Eliminate assertion failure in debug builds
  erts/emulator/beam/jit/arm/beam_asm.hpp
Labels: team:VM, fix, testing

#8107 ssh: do not start acceptor for client
  lib/ssh/src/ssh_system_sup.erl
Labels: team:PS, testing

#8148 Consider total when computing tprof layout width
  lib/tools/src/tprof.erl
  lib/tools/test/tprof_SUITE.erl
Labels: team:VM

#8103 kernel: Log when tty reader/writer crashes
  lib/kernel/src/prim_tty.erl
  lib/kernel/src/user_drv.erl
Labels: team:VM, enhancement

#8128 Ingela/ssl/alert no curve
  lib/ssl/src/tls_client_connection.erl
  lib/ssl/src/tls_dtls_server_connection.erl
  lib/ssl/src/tls_server_connection.erl
  lib/ssl/test/ssl_ECC_SUITE.erl
Labels: team:PS, testing

#8126 ssh: prefer more secure algorithms
  lib/ssh/doc/references/ssh_app.md
  lib/ssh/src/ssh.hrl
  lib/ssh/src/ssh_transport.erl
Labels: team:PS, testing

#7750 GH: Update base OS images
  .github/dockerfiles/Dockerfile.32-bit
  .github/dockerfiles/Dockerfile.64-bit
  .github/dockerfiles/Dockerfile.clang
  .github/dockerfiles/Dockerfile.cross-compile
  .github/dockerfiles/Dockerfile.debian-base
  .github/dockerfiles/Dockerfile.ubuntu-base
  .github/scripts/build-base-image.sh
  .github/scripts/c-code-path-filters.sh
  .github/workflows/main.yaml
  erts/emulator/beam/erl_thr_progress.c
  erts/emulator/beam/erl_trace.c
  lib/wx/api_gen/wx_gen_nif.erl
  lib/wx/c_src/gen/wxe_macros.h
Labels: team:VM, testing

#8161 logger: Don't print stdinfo msg to stdout in simple logger
  lib/kernel/src/logger_simple_h.erl
  lib/kernel/test/logger_simple_h_SUITE.erl
Labels: team:VM, fix, testing

#8163 otp: Fix ts:smoke_test to pass in source tree
  erts/test/otp_SUITE.erl
  lib/megaco/examples/meas/megaco_codec_meas.erl
  lib/megaco/examples/meas/megaco_codec_transform.erl
Labels: team:VM, fix

#8165 stdlib: Polish documentation after markdown migration
  lib/stdlib/src/array.erl
  lib/stdlib/src/base64.erl
  lib/stdlib/src/beam_lib.erl
  lib/stdlib/src/binary.erl
  lib/stdlib/src/c.erl
  lib/stdlib/src/dict.erl
  lib/stdlib/src/digraph.erl
  lib/stdlib/src/digraph_utils.erl
  lib/stdlib/src/erl_error.erl
  lib/stdlib/src/erl_expand_records.erl
  lib/stdlib/src/erl_features.erl
  lib/stdlib/src/erl_pp.erl
  scripts/otp_check_html_links.exs
Labels: team:VM, documentation

#8156 ssl: Add more guards to api functions
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_gen_statem.erl
  lib/ssl/test/ssl_api_SUITE.erl
Labels: team:PS, testing

#8048 Optimise ets:fold* functions
  lib/stdlib/src/ets.erl
  lib/stdlib/test/ets_SUITE.erl
Labels: team:VM, enhancement, testing

#6658 Add support for sm3 hash algorithm
  lib/crypto/c_src/algorithms.c
  lib/crypto/c_src/check_openssl.cocci
  lib/crypto/c_src/digest.c
  lib/crypto/c_src/openssl_config.h
  lib/crypto/doc/guides/algorithm_details.md
  lib/crypto/src/crypto.erl
  lib/crypto/test/crypto_SUITE.erl
Labels: team:VM, testing

#8133 Exit process immediately when the max heap size is exceeded
  erts/emulator/beam/emu/bs_instrs.tab
  erts/emulator/beam/erl_bits.c
  erts/emulator/beam/jit/arm/beam_asm_global.hpp.pl
  erts/emulator/beam/jit/arm/instr_bs.cpp
  erts/emulator/beam/jit/beam_jit_common.cpp
  erts/emulator/beam/jit/x86/beam_asm_global.hpp.pl
  erts/emulator/beam/jit/x86/instr_bs.cpp
  erts/emulator/test/Makefile
  erts/emulator/test/process_SUITE.erl
  erts/emulator/test/process_max_heap_size_SUITE.erl
Labels: team:VM, fix, testing

#8153 Fix compiler slowdown
  lib/compiler/src/beam_ssa_alias.erl
  lib/compiler/src/beam_ssa_ss.erl
Labels: team:VM, testing

#8162 compiler: beam_ssa_ss: Enforce cutoff for list literals
  lib/compiler/src/beam_ssa_ss.erl
Labels: team:VM, testing

#8177 Update documentation about records
  system/doc/reference_manual/ref_man_records.md
Labels: team:VM, testing

#8164 stdlib: Fix math docs and enable windows support for all functions
  erts/emulator/sys/win32/erl_win_sys.h
  lib/stdlib/src/math.erl
Labels: team:VM, fix, testing

#8185 ssh: reduce KEX strict message verbosity
  lib/ssh/src/ssh_transport.erl
  lib/ssh/test/ssh_protocol_SUITE.erl
  lib/ssh/test/ssh_test_lib.erl
  lib/ssh/test/ssh_to_openssh_SUITE.erl
Labels: team:PS, testing

#8168 crypto: add support for SM4 block cipher algorithm
  lib/crypto/c_src/cipher.c
  lib/crypto/c_src/openssl_config.h
  lib/crypto/doc/guides/algorithm_details.md
  lib/crypto/src/crypto.erl
  lib/crypto/test/crypto_SUITE.erl
Labels: team:VM, feature, testing

#8129 Remove docs configure warning
  HOWTO/INSTALL.md
  configure
  configure.src
  erts/configure
  erts/configure.ac
  erts/doc/Makefile
  lib/edoc/doc/Makefile
  lib/jinterface/doc/Makefile
  lib/syntax_tools/doc/Makefile
  lib/wx/configure
  lib/xmerl/doc/Makefile
  lib/xmerl/doc/assets/Makefile
  lib/xmerl/doc/assets/stylesheet.css
  make/configure
  make/doc.mk
  make/ex_doc.sha1sum
  make/ex_doc.sha256sum
  make/ex_doc_link
  make/ex_doc_vsn
  make/ex_doc_wrapper
  make/install_dir_data.sh.in
  otp_build
  system/doc/Makefile
  system/doc/top/Makefile
Labels: team:VM, fix

#8193 Make a printout when env is misconfigured
  system/doc/top/src/otp_man_index.erl
Labels: testing

#8194 Fix type and thus docs for ttb
  lib/observer/src/ttb.erl
Labels: testing

#8189 Eliminate an unsafe optimization of list matching
  lib/compiler/src/beam_z.erl
  lib/compiler/test/bif_SUITE.erl
Labels: team:VM, fix, testing

#8181 erts: Fix dumping of persistent term funs
  erts/emulator/beam/erl_process_dump.c
Labels: team:VM, fix, testing

#8200 kernel: Fix io:get_password
  lib/kernel/src/group.erl
  lib/kernel/test/interactive_shell_SUITE.erl
Labels: team:VM, fix, testing
