Repository erlang/otp, pull requests merged in 2025-01, with the labels that each got.

#9188 ssh: fix callbacks_daemon_options() type spec
  lib/ssh/src/ssh.hrl
Labels: team:PS, testing

#9248 inet: Rephrase setopts docs
  lib/kernel/src/inet.erl
Labels: team:PS

#9263 otp: Fix shaNsum of ex_doc+jit-reader on FreeBSD
  otp_build
Labels: team:VM, fix, testing

#9219 Extend error to match the fuction type spec
  lib/tools/src/eprof.erl
Labels: team:VM

#9252 Updated doc for maps:foreach/2. Added example for maps:foreach/2.
  lib/stdlib/src/maps.erl
Labels: team:VM

#9253 Syntax tools reversion fixes
  lib/stdlib/src/erl_anno.erl
  lib/syntax_tools/src/erl_syntax.erl
Labels: team:VM, testing

#9236 jit: Allow forcing Windows ABI to help find Windows bugs under Linux
  .github/workflows/main.yaml
  erts/emulator/beam/jit/arm/beam_asm.hpp
  erts/emulator/beam/jit/arm/beam_asm_global.cpp
  erts/emulator/beam/jit/arm/beam_asm_global.hpp.pl
  erts/emulator/beam/jit/arm/beam_asm_module.cpp
  erts/emulator/beam/jit/arm/instr_arith.cpp
  erts/emulator/beam/jit/arm/instr_bif.cpp
  erts/emulator/beam/jit/arm/instr_bs.cpp
  erts/emulator/beam/jit/arm/instr_call.cpp
  erts/emulator/beam/jit/arm/instr_common.cpp
  erts/emulator/beam/jit/arm/instr_float.cpp
  erts/emulator/beam/jit/arm/instr_fun.cpp
  erts/emulator/beam/jit/arm/instr_guard_bifs.cpp
  erts/emulator/beam/jit/arm/instr_map.cpp
  erts/emulator/beam/jit/arm/instr_msg.cpp
  erts/emulator/beam/jit/arm/instr_trace.cpp
  erts/emulator/beam/jit/arm/process_main.cpp
  erts/emulator/beam/jit/beam_jit_main.cpp
  erts/emulator/beam/jit/x86/beam_asm.hpp
  erts/emulator/beam/jit/x86/beam_asm_global.cpp
  erts/emulator/beam/jit/x86/beam_asm_global.hpp.pl
  erts/emulator/beam/jit/x86/beam_asm_module.cpp
  erts/emulator/beam/jit/x86/instr_arith.cpp
  erts/emulator/beam/jit/x86/instr_bif.cpp
  erts/emulator/beam/jit/x86/instr_bs.cpp
  erts/emulator/beam/jit/x86/instr_call.cpp
  erts/emulator/beam/jit/x86/instr_common.cpp
  erts/emulator/beam/jit/x86/instr_float.cpp
  erts/emulator/beam/jit/x86/instr_fun.cpp
  erts/emulator/beam/jit/x86/instr_guard_bifs.cpp
  erts/emulator/beam/jit/x86/instr_map.cpp
  erts/emulator/beam/jit/x86/instr_msg.cpp
  erts/emulator/beam/jit/x86/instr_trace.cpp
  erts/emulator/beam/jit/x86/process_main.cpp
Labels: team:VM, testing

#9218 Fix a few minor issues in dialyzer
  lib/dialyzer/src/dialyzer_contracts.erl
  lib/dialyzer/src/erl_types.erl
  lib/dialyzer/test/small_SUITE_data/results/contract6
  lib/dialyzer/test/small_SUITE_data/src/contract6.erl
  lib/dialyzer/test/small_SUITE_data/src/contracts_with_subtypes.erl
Labels: team:VM, testing

#9231 ssl: Use supervisor:which_child/2 to improve start up
  lib/ssl/src/dtls_connection_sup.erl
  lib/ssl/src/ssl.app.src
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_gen_statem.erl
  lib/ssl/src/ssl_trace.erl
  lib/ssl/src/tls_dyn_connection_sup.erl
  lib/ssl/src/tls_gen_connection.erl
  lib/ssl/src/tls_socket.erl
Labels: team:PS, testing

#9185 ssl: Fix function_clause error in tls_server_connection_1_3:select_server_cert_key_pair function
  lib/ssl/src/tls_server_connection_1_3.erl
Labels: team:PS, testing

#9234 Make `poll()` test work with `gcc` 14
  erts/configure
  erts/configure.ac
Labels: team:VM, testing

#9220 Clean up and simplify bit syntax matching
  erts/emulator/beam/emu/bs_instrs.tab
  erts/emulator/beam/emu/generators.tab
  erts/emulator/beam/emu/ops.tab
  erts/emulator/beam/erl_bits.c
  erts/emulator/beam/erl_bits.h
  erts/emulator/beam/generators.tab
  erts/emulator/beam/jit/arm/beam_asm.hpp
  erts/emulator/beam/jit/arm/generators.tab
  erts/emulator/beam/jit/arm/instr_bs.cpp
  erts/emulator/beam/jit/arm/ops.tab
  erts/emulator/beam/jit/x86/beam_asm.hpp
  erts/emulator/beam/jit/x86/generators.tab
  erts/emulator/beam/jit/x86/instr_bs.cpp
  erts/emulator/beam/jit/x86/ops.tab
Labels: team:VM, enhancement, testing

#9225 Slightly optimize bit syntax construction
  erts/emulator/beam/erl_bits.c
  erts/emulator/beam/erl_bits.h
  erts/emulator/beam/jit/arm/instr_bs.cpp
  erts/emulator/beam/jit/beam_jit_common.cpp
  erts/emulator/beam/jit/beam_jit_common.hpp
  erts/emulator/beam/jit/x86/beam_asm.hpp
  erts/emulator/beam/jit/x86/instr_bs.cpp
Labels: team:VM, enhancement, testing

#9276 epp: Correct stringification of non-latin1 atoms
  lib/stdlib/src/epp.erl
  lib/stdlib/test/epp_SUITE.erl
Labels: team:VM, fix, testing

#9271 stdlib: cache code:get_docs calls when completing types in the shell
  lib/stdlib/src/edlin_type_suggestion.erl
Labels: team:VM, fix, testing

#9284 Fix typo in GarbageCollection.md
  erts/emulator/internal_doc/GarbageCollection.md
Labels: team:VM, testing

#9232 Ets and Dets code should not be printing to stdout
  lib/stdlib/src/dets.erl
  lib/stdlib/src/ets.erl
Labels: team:VM, team:PS, testing

#9246 Expand symbolic funs correctly
  lib/compiler/test/error_SUITE.erl
  lib/dialyzer/src/erl_types.erl
  lib/stdlib/src/erl_expand_records.erl
  lib/stdlib/src/erl_internal.erl
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/test/erl_lint_SUITE.erl
Labels: team:VM, fix, testing

#9148 Fix incompatible pointer type 'struct sockaddr_storage *'
  erts/emulator/drivers/common/inet_drv.c
Labels: team:PS, testing

#9247 Remove outdated lib/tools/emacs/erlang-pkg.el
  lib/tools/emacs/erlang-pkg.el
Labels: team:PS

#9281 ssh: add missing Terrapin credits
  lib/ssh/doc/notes.md
Labels: team:PS, testing

#9296 erl_lint: Fix edge cases in unknown export warnings
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/test/erl_lint_SUITE.erl
Labels: team:VM, fix, testing

#9313 Fix incompatible-pointer-type error in nif_SUITE.c
  erts/emulator/test/nif_SUITE_data/nif_SUITE.c
Labels: team:VM

#9280 Fix `calendar:rfc3339_to_system_time` handling of fractional seconds
  lib/stdlib/src/calendar.erl
  lib/stdlib/test/calendar_SUITE.erl
Labels: team:VM, testing

#9303 Fix `timer:sleep/1` spec
  lib/stdlib/src/timer.erl
Labels: team:VM

#9307 Relax invariants checked by erts_add_taint before initialization
  erts/emulator/beam/erl_nif.c
Labels: team:VM

#9309 ssh: remove adjust_window call from ssh_connection
  lib/ssh/src/ssh_connection.erl
  lib/ssh/test/ssh_connection_SUITE.erl
  lib/ssh/test/ssh_sftp_SUITE.erl
Labels: team:PS, testing

#8994 set proper triplets for Windows
  erts/emulator/utils/make_version
Labels: team:VM, testing

#9295 kernel: fixes socket.erl type spec
  lib/kernel/src/socket.erl
Labels: team:PS, testing

#9312 Fix formatting in system principles documentation table
  erts/doc/guides/tty.md
  lib/asn1/doc/guides/asn1_getting_started.md
  lib/common_test/doc/guides/ct_hooks_chapter.md
  lib/diameter/doc/guides/diameter_soc.md
  lib/edoc/doc/guides/chapter.md
  lib/kernel/doc/guides/socket_usage.md
  lib/megaco/doc/guides/megaco_performance.md
  lib/public_key/doc/guides/public_key_records.md
  lib/ssl/doc/guides/standards_compliance.md
  system/doc/efficiency_guide/maps.md
  system/doc/efficiency_guide/profiling.md
  system/doc/reference_manual/character_set.md
  system/doc/reference_manual/data_types.md
  system/doc/reference_manual/distributed.md
  system/doc/reference_manual/errors.md
  system/doc/reference_manual/expressions.md
  system/doc/reference_manual/ref_man_processes.md
  system/doc/reference_manual/typespec.md
  system/doc/system_principles/system_principles.md
Labels: team:VM

#9230 kernel: Fix race with prim_tty loading during starup
  bootstrap/lib/compiler/ebin/beam_validator.beam
  bootstrap/lib/kernel/ebin/os.beam
  bootstrap/lib/kernel/ebin/prim_tty.beam
  bootstrap/lib/kernel/ebin/standard_error.beam
  bootstrap/lib/kernel/ebin/user_drv.beam
  bootstrap/lib/stdlib/ebin/argparse.beam
  bootstrap/lib/stdlib/ebin/digraph_utils.beam
  lib/kernel/src/prim_tty.erl
  lib/kernel/src/standard_error.erl
  lib/kernel/src/user_drv.erl
Labels: team:VM, fix, testing

#9145 Fix `gen_tcp:send/2` docs
  lib/kernel/src/gen_tcp.erl
Labels: team:PS

#9308 ssl: Fix alert record bug
  lib/ssl/src/tls_server_connection_1_3.erl
Labels: team:PS, testing

#9305 Optimize tlsv1.3
  lib/ssl/src/ssl.app.src
  lib/ssl/src/ssl_cipher.erl
  lib/ssl/src/ssl_internal.hrl
  lib/ssl/src/ssl_record.erl
  lib/ssl/src/ssl_trace.erl
  lib/ssl/src/tls_client_connection_1_3.erl
  lib/ssl/src/tls_gen_connection.erl
  lib/ssl/src/tls_gen_connection_1_3.erl
  lib/ssl/src/tls_record.erl
  lib/ssl/src/tls_record_1_3.erl
  lib/ssl/src/tls_sender.erl
  lib/ssl/src/tls_server_connection_1_3.erl
  lib/ssl/test/Makefile
  lib/ssl/test/openssl_session_ticket_SUITE.erl
  lib/ssl/test/ssl_api_SUITE.erl
  lib/ssl/test/ssl_bench_test_lib.erl
  lib/ssl/test/ssl_cert_SUITE.erl
  lib/ssl/test/ssl_cipher_SUITE.erl
  lib/ssl/test/ssl_handshake_SUITE.erl
  lib/ssl/test/ssl_mfl_SUITE.erl
  lib/ssl/test/ssl_reject_SUITE.erl
  lib/ssl/test/ssl_renegotiate_SUITE.erl
  lib/ssl/test/ssl_session_SUITE.erl
  lib/ssl/test/ssl_session_cache_api_SUITE.erl
  lib/ssl/test/ssl_session_ticket_SUITE.erl
  lib/ssl/test/ssl_test_lib.erl
  lib/ssl/test/tls_server_session_ticket_SUITE.erl
Labels: team:PS, testing

#9288 ssl: Avoid unnecessary duplicates
  lib/ssl/src/ssl_cipher.erl
  lib/ssl/test/tls_api_SUITE.erl
Labels: team:PS, testing

#9318 erts: Fix reply to invalid requests in group
  lib/kernel/src/group.erl
  lib/stdlib/test/io_proto_SUITE.erl
Labels: team:VM, fix, testing

#9273 ssl: Handle user initiated cancelation during handshake
  lib/ssl/src/ssl_gen_statem.erl
  lib/ssl/src/tls_client_connection_1_3.erl
  lib/ssl/src/tls_gen_connection_1_3.erl
  lib/ssl/src/tls_server_connection.erl
  lib/ssl/src/tls_server_connection_1_3.erl
Labels: team:PS, testing

#9327 Michal/tftp/fix_specs_in_read_file_function/ERIERL-1179/OTP-19446
  lib/tftp/src/tftp.erl
Labels: team:PS, testing

#9322 ssl: Postpone verifying of server options when {handshake, hello} is used
  lib/ssl/src/ssl.erl
  lib/ssl/src/tls_server_connection.erl
  lib/ssl/src/tls_server_connection_1_3.erl
  lib/ssl/test/ssl_api_SUITE.erl
Labels: team:PS, testing

#9301 Deprecate old catches in edoc, eunit, and syntax_tools
  lib/edoc/src/Makefile
  lib/edoc/src/edoc_data.erl
  lib/edoc/src/edoc_doclet.erl
  lib/edoc/src/edoc_extract.erl
  lib/edoc/src/edoc_html_to_markdown.erl
  lib/edoc/src/edoc_layout_chunks.erl
  lib/edoc/src/edoc_lib.erl
  lib/edoc/src/edoc_macros.erl
  lib/edoc/src/edoc_run.erl
  lib/edoc/src/edoc_scanner.erl
  lib/edoc/src/edoc_tags.erl
  lib/edoc/src/edoc_wiki.erl
  lib/eunit/src/Makefile
  lib/eunit/src/eunit_server.erl
  lib/syntax_tools/src/Makefile
  lib/syntax_tools/src/epp_dodger.erl
  lib/syntax_tools/src/erl_comment_scan.erl
  lib/syntax_tools/src/erl_prettypr.erl
  lib/syntax_tools/src/erl_syntax.erl
  lib/syntax_tools/src/erl_syntax_lib.erl
Labels: team:VM, testing

#9340 ssl: Ensure that we get intended error handling
  lib/ssl/src/tls_client_connection_1_3.erl
  lib/ssl/src/tls_server_connection_1_3.erl
Labels: team:PS, testing

#9337 ssl: Termination needs to be best effort, can fail for DTLS
  lib/ssl/src/ssl_gen_statem.erl
Labels: team:PS, testing

#9323 stdlib: Add warning for inlined nifs without loading
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/test/erl_lint_SUITE.erl
Labels: team:VM, testing

#9346 Update ex_doc to v0.37.0-rc.0
  lib/stdlib/doc/guides/terminal_interface.md
  make/ex_doc.exs
  make/ex_doc.sha1sum
  make/ex_doc.sha256sum
  make/ex_doc_link
  make/ex_doc_vsn
Labels: team:VM

#9106 Make scanner accept based floating point literals
  lib/stdlib/src/erl_scan.erl
  lib/stdlib/test/erl_scan_SUITE.erl
  system/doc/reference_manual/data_types.md
Labels: team:VM, enhancement, testing

#9314 dialyzer: Fix opaque-related crash
  lib/dialyzer/src/erl_types.erl
  lib/dialyzer/test/opaque_SUITE_data/src/opaque/opaque_bug6.erl
  lib/dialyzer/test/opaque_SUITE_data/src/opaque/opaque_bug6_adt.erl
Labels: team:VM, fix

#9210 lib/{mnesia,stdlib}: replace `random` functions by `rand` functions
  lib/mnesia/examples/bench/bench_populate.erl
Labels: team:PS, waiting

#9354 Revert "stdlib: Add warning for inlined nifs without loading"
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/test/erl_lint_SUITE.erl
Labels: team:VM

#9342 Limit peak memory use while loading code on small systems
  erts/preloaded/ebin/erl_prim_loader.beam
  erts/preloaded/ebin/init.beam
  erts/preloaded/src/erl_prim_loader.erl
  erts/preloaded/src/init.erl
  lib/kernel/src/code.erl
Labels: team:VM, enhancement, testing

#9207 Fix local_to_universal time without dst + TZ on Windows
  erts/config.h.in
  erts/configure
  erts/configure.ac
  erts/emulator/beam/erl_time_sup.c
  erts/emulator/sys/unix/erl_unix_sys.h
  erts/emulator/sys/unix/sys_time.c
  erts/emulator/sys/win32/erl_win_sys.h
  erts/emulator/sys/win32/sys_time.c
  erts/emulator/test/time_SUITE.erl
  erts/etc/unix/cerl.src
Labels: team:VM, fix, testing

#9335 stdlib: Fix zip:unzip on read-only directory with content
  lib/stdlib/src/zip.erl
  lib/stdlib/test/zip_SUITE.erl
Labels: team:VM, fix, testing

#9083 lib/odbc: use iodbc when available
  lib/odbc/configure.ac
Labels: team:PS, testing, priority:low

#9347 erts: Fix download of gdb tools on bsd
  erts/etc/unix/cerl.src
Labels: fix, testing

#9328 Add .elp.toml file
  .elp.toml
Labels: team:PS, waiting

#9182 erts: Use `processes_iterator/0, processes_next/1`
  erts/emulator/beam/erl_ptab.c
  erts/preloaded/ebin/erts_code_purger.beam
  erts/preloaded/ebin/erts_literal_area_collector.beam
  erts/preloaded/ebin/init.beam
  erts/preloaded/src/erts_code_purger.erl
  erts/preloaded/src/erts_literal_area_collector.erl
  erts/preloaded/src/init.erl
Labels: team:VM, testing

#9341 Fix unsafe code generation for binary matching
  lib/compiler/src/beam_ssa.erl
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/src/beam_ssa_pre_codegen.erl
  lib/compiler/src/beam_validator.erl
  lib/compiler/test/beam_validator_SUITE.erl
  lib/compiler/test/bs_match_SUITE.erl
Labels: team:VM, fix, testing

#9338 beam_validator: Catch insufficient ensure_at_least/ensure_exactly in binary matching
  lib/compiler/src/beam_validator.erl
  lib/compiler/test/beam_validator_SUITE.erl
Labels: team:VM, enhancement, testing

#9006 kernel: Add basic password support for noshell raw
  lib/kernel/src/group.erl
  lib/kernel/test/interactive_shell_SUITE.erl
  lib/ssh/src/ssh_io.erl
  lib/stdlib/src/io.erl
  lib/stdlib/src/shell.erl
Labels: team:VM, feature, testing

#9349 erts: Make sure to tag orig with literal ptr
  erts/emulator/beam/erl_term.c
  erts/emulator/beam/global.h
  erts/emulator/test/persistent_term_SUITE.erl
  erts/etc/win32/erl.c
Labels: fix, testing

#9353 Improve register allocation for try ... catch constructs
  lib/compiler/src/beam_ssa_pre_codegen.erl
Labels: team:VM, enhancement, testing

#9358 stdlib: Fix map comprehension result when a key value is replaced
  lib/stdlib/src/erl_eval.erl
  lib/stdlib/test/erl_eval_SUITE.erl
Labels: team:VM, testing

#9315 Add basic support for doctests
  erts/emulator/beam/erl_bif_binary.c
  lib/stdlib/src/Makefile
  lib/stdlib/src/binary.erl
  lib/stdlib/src/lists.erl
  lib/stdlib/src/maps.erl
  lib/stdlib/src/shell_docs.erl
  lib/stdlib/src/shell_docs_test.erl
  lib/stdlib/src/stdlib.app.src
  lib/stdlib/test/binary_module_SUITE.erl
  lib/stdlib/test/lists_SUITE.erl
  lib/stdlib/test/maps_SUITE.erl
  lib/stdlib/test/shell_docs_SUITE.erl
Labels: team:VM, enhancement, testing

#9357 Simplify range check for element/2 on a known literal tuple
  erts/emulator/beam/jit/arm/instr_guard_bifs.cpp
  erts/emulator/beam/jit/x86/instr_guard_bifs.cpp
  erts/emulator/test/guard_SUITE.erl
Labels: team:VM, enhancement, testing

#9364 wx: Build docs when driver is not available
  lib/wx/api_gen/gl_gen_erl.erl
  lib/wx/doc/Makefile
  lib/wx/src/Makefile
  lib/wx/src/gen/gl.erl
Labels: team:VM, fix, testing

#9356 compiler alias analysis: Fix repeated argument bug
  lib/compiler/src/beam_ssa_alias.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/alias.erl
Labels: team:VM, fix
