Repository erlang/otp, pull requests merged in 2025-03, with the labels that each got.

#9504 Return the right type from ets:update_element/4 spec
  lib/stdlib/src/ets.erl
Labels: team:VM

#9514 Add write_concurrency auto to `ets:info/1` return spec
  lib/stdlib/src/ets.erl
Labels: team:VM

#9124 cover: Fix a race condition in how the server is started as part of a call
  lib/tools/src/cover.erl
Labels: team:VM, testing

#9488 Fix having `-O2` in path to otp repo
  erts/emulator/Makefile.in
  erts/emulator/zstd/zstd.mk
  erts/lib_src/Makefile.in
Labels: team:VM, testing

#9441 Enable OSSF compiler hardening flags by default
  .github/actions/ossf-compiler-flags-scanner/action.yaml
  .github/dockerfiles/Dockerfile.64-bit
  .github/workflows/main.yaml
  .github/workflows/ossf-compiler-flags-scanner.yaml
  HOWTO/INSTALL.md
  erts/configure
  erts/configure.ac
  erts/emulator/Makefile.in
  erts/emulator/beam/dist.c
  erts/emulator/beam/emu/beam_emu.c
  erts/emulator/beam/utils.c
  erts/etc/win32/wsl_tools/vc/emu_cc.sh
  lib/common_test/configure
  lib/crypto/configure
  lib/crypto/configure.ac
  lib/erl_interface/configure
  lib/erl_interface/configure.ac
  lib/megaco/configure
  lib/megaco/configure.ac
  lib/odbc/configure
  lib/odbc/configure.ac
  lib/public_key/c_src/Makefile
  lib/snmp/configure
  lib/wx/configure
  lib/wx/configure.ac
  make/autoconf/otp.m4
  make/configure
  make/configure.ac
Labels: team:VM, enhancement, testing

#9446 dets: Update all error_logger calls to be logger calls
  lib/stdlib/src/dets.erl
  lib/stdlib/src/dets_utils.erl
  lib/stdlib/src/dets_v9.erl
Labels: team:VM, team:PS, fix, testing

#9518 Update Unicode to version 16
  lib/stdlib/test/unicode_util_SUITE.erl
  lib/stdlib/test/unicode_util_SUITE_data/GraphemeBreakTest.txt
  lib/stdlib/test/unicode_util_SUITE_data/LineBreakTest.txt
  lib/stdlib/test/unicode_util_SUITE_data/NormalizationTest.txt
  lib/stdlib/test/unicode_util_SUITE_data/unicode_table.bin
  lib/stdlib/uc_spec/CaseFolding.txt
  lib/stdlib/uc_spec/CompositionExclusions.txt
  lib/stdlib/uc_spec/EastAsianWidth.txt
  lib/stdlib/uc_spec/GraphemeBreakProperty.txt
  lib/stdlib/uc_spec/IndicSyllabicCategory.txt
  lib/stdlib/uc_spec/PropList.txt
  lib/stdlib/uc_spec/README-UPDATE.txt
  lib/stdlib/uc_spec/SpecialCasing.txt
  lib/stdlib/uc_spec/UnicodeData.txt
  lib/stdlib/uc_spec/emoji-data.txt
  lib/stdlib/uc_spec/gen_unicode_mod.escript
Labels: team:PS, testing

#9516 inets: Document asynchronous httpc request body format
  lib/inets/src/http_client/httpc.erl
Labels: team:PS

#9510 compiler tests: Avoid running out of virtual address space
  lib/compiler/test/compile_SUITE.erl
  lib/compiler/test/test_lib.erl
Labels: team:VM, enhancement, testing

#9513 Polish documentation for the maps module
  lib/stdlib/src/maps.erl
Labels: team:VM, enhancement, testing

#9508 Add a configure chapter to the socket usage guide
  lib/kernel/doc/guides/socket_usage.md
Labels: team:PS, testing

#9540 Fix race condition in mnesia_evil_coverage_test:table_info
  lib/mnesia/test/mnesia_evil_coverage_test.erl
Labels: team:PS, testing

#9517 Don't include enabled_features tuple when there are none
  lib/compiler/src/compile.erl
Labels: team:VM, testing

#9546 [erts] Fix hibernate/0 instruction for emulator
  erts/emulator/beam/emu/trace_instrs.tab
Labels: fix, testing

#9430 doctest allow int/line-number prefix
  lib/stdlib/src/binary.erl
  lib/stdlib/src/lists.erl
  lib/stdlib/src/maps.erl
  lib/stdlib/src/shell_docs_test.erl
  lib/stdlib/src/zstd.erl
Labels: team:VM, testing

#9547 Polish documentation for the sets modules
  lib/stdlib/src/gb_sets.erl
  lib/stdlib/src/ordsets.erl
  lib/stdlib/src/sets.erl
  lib/stdlib/test/sets_SUITE.erl
Labels: team:VM, enhancement, testing

#9486 ssl: Fix filtering unassigned signature algorithms
  lib/ssl/src/ssl_cipher.erl
  lib/ssl/test/ssl_handshake_SUITE.erl
Labels: team:PS, testing

#9534 Michal/mnesia/schema_merge_on_ext_backend/OTP-19437
  lib/mnesia/src/mnesia_schema.erl
  lib/mnesia/test/mnesia_external_backend_test.erl
Labels: team:PS, testing

#9444 Michal/mnesia/add_tests_for_compare_storage_type
  lib/mnesia/test/mnesia_evil_coverage_test.erl
Labels: team:PS, testing

#9538 erts: Fix index type in `atomics` and `counters` modules
  erts/preloaded/src/atomics.erl
  erts/preloaded/src/counters.erl
Labels: team:VM, fix, testing

#9149 ssh: Add bannerfun to the server role
  lib/ssh/src/ssh.hrl
  lib/ssh/src/ssh_fsm_userauth_server.erl
  lib/ssh/src/ssh_options.erl
  lib/ssh/test/ssh_options_SUITE.erl
  lib/ssh/test/ssh_protocol_SUITE.erl
  lib/ssh/test/ssh_to_openssh_SUITE.erl
Labels: team:PS, enhancement, testing

#9572 Enhance doctests
  lib/stdlib/src/binary.erl
  lib/stdlib/src/gb_sets.erl
  lib/stdlib/src/lists.erl
  lib/stdlib/src/ordsets.erl
  lib/stdlib/src/sets.erl
  lib/stdlib/src/shell_docs_test.erl
  lib/stdlib/test/sets_SUITE.erl
Labels: team:VM, enhancement, testing

#9468 Use conventional FILE:LINE format for locations in stacktraces
  lib/stdlib/src/erl_error.erl
  lib/stdlib/test/shell_SUITE.erl
Labels: team:VM, enhancement, testing

#9287 Augment `gen_server` timeout handling
  lib/stdlib/src/gen_server.erl
  lib/stdlib/src/stdlib.app.src
  lib/stdlib/test/gen_server_SUITE.erl
  lib/stdlib/test/supervisor_SUITE.erl
Labels: team:PS

#9564 stdlib: Fix gen_server start documentation
  lib/stdlib/src/gen_server.erl
Labels: team:PS

#9563 Remove dead code
  lib/ssl/src/ssl_handshake.erl
Labels: team:PS, testing

#9193 system: Add descriptions about zip generators to documentation
  system/doc/programming_examples/list_comprehensions.md
  system/doc/reference_manual/expressions.md
Labels: team:VM, testing

#9575 math: Make the `exp/1` example portable
  lib/stdlib/src/math.erl
Labels: team:VM, fix, testing

#9532 Use ORT for license scanning instead of scan-code
  .github/workflows/license-scanner.yaml
  .github/workflows/main.yaml
  .ort/config/config.yml
  .ort/config/evaluator.rules.kts
  .ort/config/license-classifications.yml
  lib/stdlib/uc_spec/README-UPDATE.txt
  scripts/scan-code.escript
  scripts/scan-code/template.txt
Labels: team:VM, enhancement

#9587 kernel: Fix CNAME loop detection
  lib/kernel/src/inet_db.erl
  lib/kernel/test/inet_SUITE.erl
Labels: team:PS, in progress, bug, priority:high

#9542 compiler: Fix simultaneous binding of variables in zip generator
  lib/compiler/src/v3_core.erl
  lib/compiler/test/zlc_SUITE.erl
  lib/debugger/src/dbg_ieval.erl
  lib/debugger/test/zlc_SUITE.erl
  lib/stdlib/src/erl_eval.erl
  lib/stdlib/test/erl_eval_SUITE.erl
Labels: team:VM, testing

#9582 Upgrade PCRE2 from 10.44 to 10.45
  erts/emulator/pcre/LICENCE
  erts/emulator/pcre/README.pcre_update.md
  erts/emulator/pcre/pcre.mk
  erts/emulator/pcre/pcre2.h
  erts/emulator/pcre/pcre2_auto_possess.c
  erts/emulator/pcre/pcre2_chkdint.c
  erts/emulator/pcre/pcre2_compile.c
  erts/emulator/pcre/pcre2_compile.h
  erts/emulator/pcre/pcre2_compile_class.c
  erts/emulator/pcre/pcre2_config.c
  erts/emulator/pcre/pcre2_context.c
  erts/emulator/pcre/pcre2_error.c
  erts/emulator/pcre/pcre2_extuni.c
  erts/emulator/pcre/pcre2_find_bracket.c
  erts/emulator/pcre/pcre2_internal.h
  erts/emulator/pcre/pcre2_intmodedep.h
  erts/emulator/pcre/pcre2_match.c
  erts/emulator/pcre/pcre2_match_data.c
  erts/emulator/pcre/pcre2_ord2utf.c
  erts/emulator/pcre/pcre2_pattern_info.c
  erts/emulator/pcre/pcre2_study.c
  erts/emulator/pcre/pcre2_substring.c
  erts/emulator/pcre/pcre2_ucd.c
  erts/emulator/pcre/pcre2_ucp.h
  erts/emulator/pcre/pcre2_ucptables.c
  erts/emulator/pcre/pcre2_util.h
  erts/emulator/pcre/pcre2_xclass.c
  lib/stdlib/doc/src/re.md
  lib/stdlib/test/re_SUITE_data/old_pcre1/testoutput1
  lib/stdlib/test/re_SUITE_data/old_pcre1/testoutput2
  lib/stdlib/test/re_SUITE_data/testoutput1
  lib/stdlib/test/re_SUITE_data/testoutput10
  lib/stdlib/test/re_SUITE_data/testoutput2
  lib/stdlib/test/re_SUITE_data/testoutput4
  lib/stdlib/test/re_SUITE_data/testoutput5
  lib/stdlib/test/re_testoutput1_replacement_test.erl
  lib/stdlib/test/re_testoutput1_split_test.erl
  lib/stdlib/test/run_pcre_tests.erl
  system/COPYRIGHT
Labels: team:VM, testing

#9583 dialyzer: Fix test case in `behaviour_SUITE`
  lib/dialyzer/test/behaviour_SUITE_data/results/gen_server_incorrect_args
Labels: team:VM, testing

#9194 dialyzer: Add documentation for nominals
  system/doc/docs.exs
  system/doc/reference_manual/nominals.md
  system/doc/reference_manual/opaques.md
  system/doc/reference_manual/typespec.md
Labels: team:VM, testing

#9577 Fix delayed receive trace
  erts/emulator/beam/erl_process.c
  erts/emulator/test/trace_SUITE.erl
Labels: team:VM, fix, testing

#9576 Optimize receive trace handling
  erts/emulator/beam/erl_process.c
  erts/emulator/test/trace_SUITE.erl
Labels: team:VM, fix, testing

#9588 JER: Include sizes for OCTET STRINGs in type information
  lib/asn1/src/asn1ct_gen_jer.erl
  lib/asn1/src/asn1rtt_jer.erl
  lib/asn1/test/asn1_SUITE_data/PrimStrings.asn1
  lib/asn1/test/testCompactBitString.erl
Labels: team:VM, fix, testing

#9590 Priority message fixes
  erts/emulator/beam/erl_proc_sig_queue.c
  erts/emulator/test/signal_SUITE.erl
  erts/emulator/test/trace_SUITE.erl
Labels: team:VM, fix, testing

#9584 erts: Fix missing include of dtrace-wrapper.h
  erts/emulator/beam/bif.c
Labels: team:VM, testing

#9602 beam_debug_info: Emit a proper entry debug_line for funs
  lib/compiler/src/beam_asm.erl
  lib/compiler/src/beam_core_to_ssa.erl
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/src/sys_coverage.erl
  lib/compiler/src/v3_core.erl
  lib/compiler/test/beam_debug_info_SUITE.erl
Labels: team:VM, fix, testing

#9615 Fix `gen_server` plain timeouts being canceled by `system` messages
  lib/stdlib/src/gen_server.erl
  lib/stdlib/test/gen_server_SUITE.erl
Labels: team:PS, fix, testing, in progress, priority:high

#9613 Polish documentation for the sofs module
  lib/stdlib/doc/src/sofs.md
  lib/stdlib/src/sofs.erl
  lib/stdlib/test/sofs_SUITE.erl
Labels: team:VM, enhancement, testing

#9622 gh: Use data from reuse lint when scanning code
  .github/dockerfiles/.profile
  .github/dockerfiles/Dockerfile.64-bit
  .github/dockerfiles/Dockerfile.ubuntu-base
  .github/scripts/ort-scanner.es
  .github/scripts/otp-compliance.es
  .github/workflows/main.yaml
  .ort.yml
  scripts/licensedetection/licenses/apache-2.0-or-lgpl-2.1-or-later.LICENSE
  scripts/scan-code.escript
Labels: team:VM, enhancement

#9624 ssl: Add copyright
  lib/ssl/src/ssl_srp_primes.erl
Labels: team:PS

#9619 Add release notes doc section about bug fixes
  HOWTO/RELEASE-NOTES.md
Labels: team:VM, enhancement, documentation

#9596 Fix crash in initial_call
  lib/stdlib/src/proc_lib.erl
  lib/stdlib/test/proc_lib_SUITE.erl
Labels: team:PS, testing

#9612 ssl: Use unique identifier for CRL db
  lib/ssl/src/ssl_crl_cache.erl
  lib/ssl/test/make_certs.erl
  lib/ssl/test/openssl_stapling_SUITE.erl
  lib/ssl/test/ssl_crl_SUITE.erl
Labels: team:PS, testing

#9623 Add missing licenses and delete some old files
  .github/scripts/restore-from-prebuilt.sh
  .ort.yml
  bootstrap/lib/stdlib/ebin/otp_internal.beam
  lib/asn1/src/asn1ct_eval_ext.funcs
  lib/common_test/priv/ct_default.css
  lib/common_test/priv/tile1.jpg.license
  lib/common_test/src/ct_suite.erl
  lib/debugger/Makefile
  lib/debugger/priv/Makefile
  lib/debugger/priv/debugger.gif
  lib/debugger/priv/debugger.tool
  lib/debugger/priv/erlang_bug.png
  lib/dialyzer/src/dialyzer_typegraph.erl
  lib/inets/Makefile
  lib/inets/priv/Makefile
  lib/inets/priv/bin/runcgi.sh
  lib/inets/priv/plt/.gitignore
  lib/kernel/include/eep48.hrl
  lib/kernel/include/logger.hrl
  lib/observer/priv/bin/cdv
  lib/observer/priv/bin/cdv.bat
  lib/observer/priv/bin/etop
  lib/observer/priv/bin/etop.bat
  lib/observer/priv/erlang_observer.png.license
  lib/odbc/src/odbc_debug.erl
  lib/public_key/priv/convert.escript
  lib/public_key/priv/generate
  lib/runtime_tools/src/ttb_autostart.erl
  lib/ssh/src/ssh_fsm.hrl
  lib/stdlib/scripts/update_deprecations
  lib/stdlib/src/otp_internal.erl
  lib/tools/priv/styles.css
  lib/wx/priv/erlang-logo128.png.license
  lib/wx/priv/erlang-logo32.png.license
  lib/wx/priv/erlang-logo64.png.license
Labels: team:VM, enhancement

#9646 Extend the `debug_line_entry` instruction
  erts/emulator/beam/emu/ops.tab
  erts/emulator/beam/jit/arm/instr_common.cpp
  erts/emulator/beam/jit/arm/ops.tab
  erts/emulator/beam/jit/asm_load.c
  erts/emulator/beam/jit/x86/instr_common.cpp
  erts/emulator/beam/jit/x86/ops.tab
  lib/compiler/src/beam_asm.erl
  lib/compiler/src/beam_dict.erl
  lib/compiler/src/beam_disasm.erl
  lib/compiler/src/beam_flatten.erl
  lib/compiler/src/beam_validator.erl
  lib/compiler/src/genop.tab
  lib/compiler/test/beam_debug_info_SUITE.erl
Labels: team:VM, testing

#9650 compiler destructive update: Fix bug in nested patches
  lib/compiler/src/beam_ssa_destructive_update.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/tuple_inplace_checks.erl
Labels: team:VM, testing

#9629 erlang: Polish documentation for the Term group of BIFs
  erts/emulator/test/bif_SUITE.erl
  erts/preloaded/src/erlang.erl
  system/doc/efficiency_guide/system_limits.md
Labels: team:VM, enhancement, testing

#9621 Finish `gen_server` event time-outs
  lib/stdlib/src/gen_server.erl
  lib/stdlib/test/gen_server_SUITE.erl
Labels: team:PS, feature, testing, documentation, in progress, priority:medium

#9610 Optimize and test coverage of pcre2 yielding
  erts/emulator/beam/erl_bif_info.c
  erts/emulator/pcre/README.pcre_update.md
  erts/emulator/pcre/pcre.mk
  erts/emulator/pcre/pcre2_context.c
  erts/emulator/pcre/pcre2_internal.h
  erts/emulator/pcre/pcre2_match.c
  erts/emulator/pcre/pcre2_valid_utf.c
  lib/stdlib/test/re_SUITE.erl
Labels: team:VM, enhancement, testing
