Repository erlang/otp, pull requests merged in 2025-10, with the labels that each got.

#10233 Fix `erl_anno:is_anno/1` for end location
  lib/stdlib/src/erl_anno.erl
  lib/stdlib/test/erl_anno_SUITE.erl
Labels: team:VM, testing

#10248 Michal/kernel/fix-group-crashing-upon-receiving-unknown-message/OTP-19796
  lib/kernel/src/group.erl
  lib/kernel/test/Makefile
  lib/kernel/test/group_SUITE.erl
Labels: team:PS, testing

#10246 Fix ETP new fun arity format
  erts/emulator/beam/erl_etp.c
  erts/etc/unix/etp-commands.in
Labels: team:VM, fix, in progress, priority:low

#10241 Fix suspend_process() issue on processes in dirty schedulers
  erts/emulator/beam/erl_proc_sig_queue.c
  erts/emulator/test/dirty_bif_SUITE.erl
Labels: team:VM
