Repository erlang/otp, pull requests merged in 2025-05, with the labels that each got.

#9789 Fix unsafe insert of prio queue marker
  erts/emulator/beam/erl_proc_sig_queue.c
Labels: team:VM, fix, testing

#9793 [erts] Fix insert of prio message
  erts/emulator/beam/erl_proc_sig_queue.c
  erts/emulator/test/receive_SUITE.erl
  erts/etc/unix/etp-commands.in
Labels: team:VM, fix, testing

#9787 tprof added to tools.app.src
  lib/tools/src/tools.app.src
Labels: team:VM

#9794 eunit: Ensure failed setup is not silently ignored
  lib/eunit/src/eunit_serial.erl
  lib/eunit/test/eunit_SUITE.erl
Labels: team:VM, fix, testing

#9753 Add option to discard whitespace before xml tag
  lib/xmerl/src/xmerl_sax_parser.erl
  lib/xmerl/src/xmerl_sax_parser.hrl
  lib/xmerl/src/xmerl_sax_parser_base.erlsrc
  lib/xmerl/test/xmerl_sax_SUITE.erl
  lib/xmerl/test/xmerl_sax_SUITE_data/two_messages_with_ws_between.xml
Labels: team:PS, testing

#9811 Suppress bogus warning
  erts/emulator/beam/erl_debugger.c
Labels: team:VM, testing

#9727 Fix mermaid after ex_doc upgrade and bumb its version
  make/ex_doc.exs
Labels: team:VM, testing, bug

#9808 Remove filter of public_key as headers are now fixed
  lib/public_key/asn1/README
  scripts/license-header.es
Labels: team:VM

#9737 compiler: Fix bug with unloaded nifs in alias analysis
  lib/compiler/src/beam_ssa_alias.erl
  lib/compiler/test/core_alias_SUITE.erl
Labels: team:VM

#9696 erts: Fix crash when invoking non-existent error_handler
  erts/emulator/beam/beam_common.c
  erts/emulator/beam/emu/beam_emu.c
  erts/emulator/beam/jit/arm/beam_asm_global.cpp
  erts/emulator/beam/jit/x86/beam_asm_global.cpp
  erts/emulator/test/hello_SUITE_data/hello.erl
Labels: team:VM, fix

#9742 erts: fix incompatible pointer type
  erts/emulator/test/nif_SUITE_data/nif_SUITE.c
Labels: team:VM

#9724 erts: Check process registers during CLA check
  erts/emulator/beam/beam_bif_load.c
  erts/emulator/test/signal_SUITE.erl
Labels: team:VM, fix

#9821 wx: build fixup
  lib/wx/api_gen/gl_gen_erl.erl
  lib/wx/src/gen/gl.erl
Labels: team:PS

#9708 Add missing wx dependencies
  lib/debugger/src/Makefile
  lib/et/src/Makefile
  lib/observer/src/Makefile
  lib/reltool/src/Makefile
  lib/wx/examples/demo/Makefile
  lib/wx/examples/simple/Makefile
  lib/wx/examples/sudoku/Makefile
Labels: team:PS, testing

#9826 gh: Update ORT version to latest
  .github/workflows/main.yaml
Labels: team:VM, fix

#9784 erl_debugger: Add BIFs to list available line breakpoints and their status
  erts/emulator/beam/atom.names
  erts/emulator/beam/bif.tab
  erts/emulator/beam/erl_debugger.c
  erts/emulator/beam/erl_term.h
  erts/emulator/test/erl_debugger_SUITE.erl
  lib/kernel/src/erl_debugger.erl
Labels: team:VM, testing

#9818 ssh: add RUB credits for draft miller advisory
  lib/ssh/doc/notes.md
Labels: team:PS

#9825 Updated ex_doc version to v0.38.0
  .github/workflows/main.yaml
  lib/kernel/src/file.erl
  lib/megaco/src/app/megaco.erl
  lib/odbc/doc/guides/databases.md
  lib/odbc/src/odbc.erl
  lib/snmp/src/compile/snmpc.erl
  lib/stdlib/src/erl_pp.erl
  lib/stdlib/src/filename.erl
  lib/stdlib/src/shell_docs.erl
  lib/tools/doc/guides/xref_chapter.md
  lib/tools/src/xref.erl
  make/ex_doc.sha1sum
  make/ex_doc.sha256sum
  make/ex_doc_link
  make/ex_doc_vsn
  scripts/otp_check_html_links.exs
Labels: team:VM, fix, documentation

#9809 Shrink ErtsAtomTranslationTable to correct max size
  erts/emulator/beam/external.c
  erts/emulator/beam/external.h
Labels: team:VM, enhancement, testing

#9829 Fix typo: fqnds/fqdns
  lib/public_key/src/public_key.erl
Labels: team:PS

#9806 Fix typo in erts/erlang:system_flag/2 documentation comment
  erts/preloaded/src/erlang.erl
Labels: team:VM

#9834 compiler: Fix alias analysis bug (less conservative version of #9833)
  lib/compiler/src/beam_ssa_alias.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/alias.erl
Labels: team:VM, testing

#9839 public_key: Update included macros in public include file
  lib/public_key/include/public_key.hrl
  lib/public_key/src/Makefile
  lib/public_key/src/pubkey_pbe.erl
  lib/public_key/src/pubkey_pem.erl
  lib/public_key/src/pubkey_translation.erl
  lib/public_key/src/public_key.erl
  lib/public_key/src/public_key_internal.hrl
Labels: team:PS, testing

#9819 otp: sbom adds comment to license files
  .github/scripts/ort-scanner.es
  .github/scripts/otp-compliance.es
  .github/workflows/main.yaml
  .ort.yml
  .ort/config/license-classifications.yml
  CONTRIBUTING.md
  FILE-HEADERS/Apache-2.0-AND-LicenseRef-scancode-wxwindows-free-doc-3.txt
  FILE-HEADERS/Apache-2.0-OR-LGPL-2.1-or-later.txt
  FILE-HEADERS/Apache-2.0.txt
  FILE-HEADERS/README.md
  HOWTO/FILE-HEADERS.md
  HOWTO/SBOM.md
  LICENSES/LicenseRef-scancode-ietf-trust.txt
  LICENSES/LicenseRef-scancode-ietf.txt
  LICENSES/LicenseRef-scancode-w3c-docs-19990405.txt
  LICENSES/W3C-19980720.txt
  erts/autoconf/vendor.info
  erts/emulator/asmjit/vendor.info
  erts/emulator/openssl/vendor.info
  erts/emulator/pcre/README.pcre_update.md
  erts/emulator/pcre/vendor.info
  erts/emulator/ryu/vendor.info
  erts/emulator/ryu/xcharconv_ryu.h.sha.license
  erts/emulator/zlib/vendor.info
  erts/emulator/zstd/vendor.info
  lib/common_test/test_server/vendor.info
  lib/dialyzer/test/options1_SUITE_data/results/compiler
  lib/dialyzer/test/options1_SUITE_data/src/compiler/v3_core.erl
  lib/dialyzer/test/options1_SUITE_data/src/compiler/v3_kernel.erl
  lib/dialyzer/test/r9c_SUITE_data/results/mnesia
  lib/dialyzer/test/r9c_SUITE_data/src/mnesia/mnesia_log.erl
  lib/erl_interface/src/openssl/vendor.info
  lib/eunit/test/eunit_test_listener.erl
  lib/stdlib/test/json_SUITE_data/vendor.info
  lib/wx/src/wx.erl
  make/autoconf/vendor.info
  scripts/license-header.es
  scripts/otp_build_check
Labels: team:VM, bug

#9840 otp: Fix makefile deps with erlc -M for almost all application
  .gitignore
  erts/preloaded/src/Makefile
  lib/asn1/src/Makefile
  lib/common_test/src/Makefile
  lib/compiler/src/Makefile
  lib/crypto/src/Makefile
  lib/debugger/src/Makefile
  lib/dialyzer/src/Makefile
  lib/edoc/doc/Makefile
  lib/edoc/src/Makefile
  lib/edoc/src/files.mk
  lib/eldap/src/Makefile
  lib/et/src/Makefile
  lib/eunit/src/Makefile
  lib/ftp/src/Makefile
  lib/kernel/src/Makefile
  lib/mnesia/src/Makefile
  lib/observer/src/Makefile
  lib/odbc/src/Makefile
  lib/os_mon/src/Makefile
  lib/parsetools/src/Makefile
  lib/parsetools/src/yeccparser.erl
  lib/public_key/src/Makefile
  lib/reltool/src/Makefile
  lib/runtime_tools/src/Makefile
  lib/sasl/src/Makefile
  lib/ssh/src/Makefile
  lib/ssl/src/Makefile
  lib/stdlib/src/Makefile
  lib/syntax_tools/src/Makefile
  lib/tftp/src/Makefile
  lib/tools/src/Makefile
  lib/wx/src/Makefile
  lib/xmerl/src/Makefile
  make/dep.mk
Labels: team:VM, testing

#9849 ssl: hs_keylog callback properly handle alert in intial states
  lib/ssl/src/ssl_gen_statem.erl
  lib/ssl/src/tls_handshake_1_3.erl
  lib/ssl/test/tls_1_3_version_SUITE.erl
Labels: team:PS, testing

#9859 eldap: fix typespec
  lib/eldap/src/eldap.erl
Labels: team:PS
