Repository erlang/otp, pull requests merged in 2025-06, with the labels that each got.

#9888 Michal/eldap/fix-typespec/OTP-19658
  lib/eldap/src/eldap.erl
Labels: team:PS, testing

#9850 gh: Use renovate to update dependencies
  .github/dependabot.yml
  .github/scripts/renovate-vendored-deps.sh
  .github/scripts/update-gh-actions-versions.es
  .github/workflows/renovate-vendored-deps.yaml
  HOWTO/SBOM.md
  erts/emulator/pcre/vendor.info
  erts/emulator/ryu/README.ryu_update.md
  erts/emulator/ryu/update.sh
  erts/emulator/zstd/update.sh
  renovate.json5
Labels: team:VM

#9899 zip: Improve returned errors
  lib/stdlib/src/zip.erl
  lib/stdlib/test/zip_SUITE.erl
Labels: team:VM, fix, testing

#9865 public_key: Add missing macros
  lib/public_key/doc/guides/public_key_records.md
  lib/public_key/include/public_key.hrl
  lib/public_key/src/pubkey_cert_records.erl
  lib/public_key/src/public_key.erl
Labels: team:PS, testing

#9589 [dbg] make simple tracer() remsh-friendly
  lib/runtime_tools/src/dbg.erl
Labels: team:VM, testing

#9721 Add SHA2 512/224 and SHA2 512/256 truncated hashes
  lib/crypto/c_src/digest.c
  lib/crypto/c_src/openssl_config.h
  lib/crypto/doc/guides/algorithm_details.md
  lib/crypto/src/crypto.erl
  lib/crypto/test/crypto_SUITE.erl
Labels: team:VM, testing

#9896 stdlib: edlin_expand should not crash when trying to complete a map
  lib/stdlib/src/edlin_expand.erl
  lib/stdlib/test/edlin_expand_SUITE.erl
Labels: team:VM, fix

#9912 Remote shell should not terminate the remote node on EOF
  lib/kernel/src/user_drv.erl
  lib/kernel/test/interactive_shell_SUITE.erl
  lib/stdlib/src/shell.erl
Labels: team:VM, fix

#9862 common_test: order maps by key when printing anywhere
  lib/common_test/src/ct_framework.erl
  lib/common_test/src/test_server_ctrl.erl
Labels: team:PS, testing

#9870 kernel: Fix line_history to not be reset by io:setopts
  lib/kernel/src/group.erl
  lib/kernel/test/interactive_shell_SUITE.erl
Labels: team:VM, fix, testing

#9846 asn1: Suppress unmatched returns warnings from Dialyzer
  lib/asn1/src/asn1ct_gen_ber_bin_v2.erl
  lib/asn1/src/asn1ct_gen_jer.erl
  lib/asn1/src/asn1ct_gen_per.erl
Labels: team:VM

#9898 stdlib: support 'fun f/a' expressions in the shell
  lib/stdlib/src/shell.erl
  lib/stdlib/test/shell_SUITE.erl
Labels: team:VM, fix

#9939 fix typo
  lib/stdlib/src/gen_event.erl
Labels: team:VM

#9948 Rephrase note for the rpc module
  lib/kernel/src/rpc.erl
Labels: team:VM, fix, testing

#9949 Fix encoding of constrained BIT STRING for JER
  lib/asn1/src/asn1rtt_jer.erl
  lib/asn1/test/asn1_SUITE.erl
  lib/asn1/test/testPrimStrings.erl
Labels: team:VM, fix, testing

#9952 stdlib: Fix unicode characters in format string
  lib/stdlib/src/io_lib_format.erl
  lib/stdlib/test/io_SUITE.erl
Labels: team:PS, testing

#9954 Fix otp_build to respect TYPE and FLAVOR
  .github/workflows/main.yaml
  HOWTO/INSTALL.md
  otp_build
Labels: team:VM, fix

#9953 otp: Fix patch apply to work on vsn files with comments
  otp_patch_apply
Labels: team:VM, fix

#9969 otp: Fix all nif/driver loading to use win32 for windows
  lib/asn1/src/asn1rt_nif.erl
  lib/crypto/src/crypto.erl
  lib/os_mon/src/os_mon.erl
  lib/public_key/src/pubkey_os_cacerts.erl
  lib/runtime_tools/src/dbg.erl
  lib/runtime_tools/src/dyntrace.erl
  lib/wx/api_gen/gl_gen_erl.erl
  lib/wx/src/gen/gl.erl
  lib/wx/src/wxe_util.erl
Labels: team:VM, fix, testing

#9843 ssl: Allow empty psk identity
  lib/ssl/src/ssl_config.erl
  lib/ssl/test/ssl_api_SUITE.erl
Labels: team:PS, testing

#9990 compiler: Fix compiler crash with multiple phi patches
  lib/compiler/src/beam_ssa_check.erl
  lib/compiler/src/beam_ssa_destructive_update.erl
  lib/compiler/src/compile.erl
  lib/compiler/test/beam_ssa_check_SUITE.erl
  lib/compiler/test/beam_ssa_check_SUITE_data/phis.erl
Labels: team:VM, testing

#9994 Re-add priv dir
  lib/debugger/Makefile
Labels: team:PS, testing

#9900 crypto: Add Quantum Safe algorithms ML-DSA and ML-KEM
  lib/crypto/c_src/algorithms.c
  lib/crypto/c_src/algorithms.h
  lib/crypto/c_src/atoms.c
  lib/crypto/c_src/atoms.h
  lib/crypto/c_src/bn.c
  lib/crypto/c_src/bn.h
  lib/crypto/c_src/cipher.c
  lib/crypto/c_src/common.h
  lib/crypto/c_src/crypto.c
  lib/crypto/c_src/evp.c
  lib/crypto/c_src/evp.h
  lib/crypto/c_src/openssl_config.h
  lib/crypto/c_src/pkey.c
  lib/crypto/c_src/pkey.h
  lib/crypto/src/crypto.erl
  lib/crypto/test/crypto_SUITE.erl
Labels: team:VM, enhancement, testing

#9955 public_key: Adjust macros and records in public include and doc
  lib/public_key/doc/guides/public_key_records.md
  lib/public_key/doc/public_key_app.md
  lib/public_key/include/public_key.hrl
  lib/public_key/src/pubkey_pbe.erl
  lib/public_key/src/public_key.erl
  lib/public_key/src/public_key_internal.hrl
  lib/public_key/test/erl_make_certs.erl
  lib/public_key/test/public_key_SUITE.erl
Labels: team:PS, testing

#9993 Rebased nsis fix
  erts/etc/win32/nsis/erlang20.nsi
Labels: team:PS, testing, bug

#9879 Buffer data if needed when using socket send nowait
  lib/ssl/src/dtls_packet_demux.erl
  lib/ssl/src/dtls_socket.erl
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_config.erl
  lib/ssl/src/ssl_gen_statem.erl
  lib/ssl/src/tls_dtls_gen_connection.erl
  lib/ssl/src/tls_gen_connection.erl
  lib/ssl/src/tls_sender.erl
  lib/ssl/src/tls_socket.erl
  lib/ssl/src/tls_socket_tcp.erl
  lib/ssl/test/dtls_api_SUITE.erl
  lib/ssl/test/ssl_bench_SUITE.erl
  lib/ssl/test/ssl_payload_SUITE.erl
  lib/ssl/test/ssl_test_lib.erl
  lib/ssl/test/tls_api_SUITE.erl
Labels: team:PS, testing

#9930 CompletionStatus doc improvements
  lib/kernel/doc/guides/socket_usage.md
  lib/kernel/src/socket.erl
Labels: team:PS
