Repository erlang/otp, pull requests merged in 2025-08, with the labels that each got.

#10076 crypto: Fix segfault seen at init:restart with OpenSSL statically linked
  lib/crypto/c_src/mac.c
Labels: team:VM, fix, testing

#10083 Add repository field in renovate-vendored-deps workflow for actions/checkout
  .github/workflows/renovate-vendored-deps.yaml
Labels: team:PS

#10093 Restore broken optimization of unicode conversion function
  erts/emulator/beam/erl_unicode.c
  lib/stdlib/test/unicode_SUITE.erl
Labels: team:VM, fix, testing

#10069 Fix default opts for plugins
  lib/ssl/src/tls_socket.erl
Labels: team:PS, testing, waiting

#10108 Correct sockname handling for DTLS
  lib/ssl/src/dtls_socket.erl
  lib/ssl/test/dtls_api_SUITE.erl
Labels: team:PS, testing

#9790 otp scan PRs for vulnerabilities
  .github/scripts/otp-compliance.es
  .github/workflows/main.yaml
  .github/workflows/osv-scanner-scheduled.yml
  .github/workflows/reusable-vendor-vulnerability-scanner.yml
  HOWTO/SBOM.md
  erts/emulator/openssl/vendor.info
  erts/emulator/pcre/vendor.info
  erts/emulator/ryu/vendor.info
  erts/emulator/zlib/vendor.info
  erts/emulator/zstd/vendor.info
  lib/common_test/priv/vendor.info
  lib/erl_interface/src/openssl/vendor.info
  lib/wx/vendor.info
  make/openvex.table
  make/openvex.table.license
  system/doc/README.md
  system/doc/docs.exs
  system/doc/guides
  system/doc/guides.license
  system/doc/vulnerabilities/vulnerabilities.md
  vex/otp-26.openvex.json
  vex/otp-26.openvex.json.license
  vex/otp-27.openvex.json
  vex/otp-27.openvex.json.license
  vex/otp-28.openvex.json
  vex/otp-28.openvex.json.license
Labels: team:VM, testing, full-build-and-check

#10095 Fix for httpd CGI scripts
  lib/inets/examples/server_root/cgi-bin/printenv.bat
  lib/inets/examples/server_root/cgi-bin/printenv.sh
  lib/inets/src/http_server/httpd_script_env.erl
  lib/inets/test/httpd_SUITE.erl
Labels: team:PS, testing
