Repository erlang/otp, pull requests merged in 2025-02, with the labels that each got.

#9334 Add support for debug information for a native debugger
  erts/emulator/beam/atom.names
  erts/emulator/beam/beam_bif_load.c
  erts/emulator/beam/beam_code.h
  erts/emulator/beam/beam_file.c
  erts/emulator/beam/beam_file.h
  erts/emulator/beam/beam_load.c
  erts/emulator/beam/bif.tab
  erts/emulator/beam/emu/ops.tab
  erts/emulator/beam/jit/arm/instr_common.cpp
  erts/emulator/beam/jit/arm/ops.tab
  erts/emulator/beam/jit/asm_load.c
  erts/emulator/beam/jit/x86/instr_common.cpp
  erts/emulator/beam/jit/x86/ops.tab
  lib/compiler/src/beam_asm.erl
  lib/compiler/src/beam_block.erl
  lib/compiler/src/beam_core_to_ssa.erl
  lib/compiler/src/beam_dict.erl
  lib/compiler/src/beam_disasm.erl
  lib/compiler/src/beam_flatten.erl
  lib/compiler/src/beam_ssa.erl
  lib/compiler/src/beam_ssa_alias.erl
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/beam_ssa_pre_codegen.erl
  lib/compiler/src/beam_trim.erl
  lib/compiler/src/beam_validator.erl
  lib/compiler/src/beam_z.erl
  lib/compiler/src/compile.erl
  lib/compiler/src/core_pp.erl
  lib/compiler/src/genop.tab
  lib/compiler/src/sys_coverage.erl
  lib/compiler/src/v3_core.erl
  lib/compiler/test/Makefile
  lib/compiler/test/beam_debug_info_SUITE.erl
  lib/compiler/test/compile_SUITE.erl
  lib/compiler/test/compile_SUITE_data/small.erl
  lib/compiler/test/test_lib.erl
  lib/dialyzer/src/dialyzer_dataflow.erl
  lib/dialyzer/src/dialyzer_typesig.erl
  lib/kernel/src/code.erl
  lib/kernel/src/erl_kernel_errors.erl
  lib/kernel/test/code_coverage_SUITE.erl
  lib/stdlib/src/erl_expand_records.erl
  lib/stdlib/src/erl_pp.erl
Labels: team:VM, feature, testing

#9286 public_key: Adjust certificate key usage compatible check
  lib/public_key/src/pubkey_cert.erl
Labels: team:PS

#9229 Fix windows pdb
  .github/workflows/main.yaml
  erts/emulator/Makefile.in
  erts/emulator/beam/erl_bif_coverage.c
  erts/epmd/src/Makefile.in
  erts/etc/common/Makefile.in
  erts/etc/win32/wsl_tools/vc/cc.sh
  erts/lib_src/Makefile.in
  lib/sasl/src/systools_make.erl
  lib/sasl/test/systools_SUITE.erl
  otp_build
Labels: team:VM, fix, testing

#9377 Fix global reconnect
  lib/kernel/src/global.erl
Labels: team:VM, fix

#9371 stdlib: Fix jaro_similarity for matching strings of length 1
  lib/stdlib/src/string.erl
  lib/stdlib/test/string_SUITE.erl
Labels: team:PS, testing

#9331 Support long PATH values in erlexec
  erts/etc/common/erlexec.c
  erts/test/erlexec_SUITE.erl
Labels: team:VM, fix, testing

#9365 ssh: increase timetrap for read_6GB
  lib/ssh/test/ssh_sftp_SUITE.erl
Labels: team:PS

#9379 socket: fix typespecs
  lib/kernel/src/socket.erl
Labels: team:VM, testing

#9251 Optimize json object encoding
  lib/stdlib/src/json.erl
Labels: team:PS, testing, waiting

#9333 Restructure `gen_server` functions and calls
  lib/stdlib/src/gen_server.erl
Labels: team:VM, team:PS, enhancement, testing

#9397 Add SBOM generation
  .github/scripts/otp-compliance.es
  .github/workflows/main.yaml
  .ort.yml
  .ort/config/config.yml
Labels: team:VM, enhancement

#9344 Socket option {otp,select_read}
  erts/emulator/nifs/common/prim_socket_int.h
  erts/emulator/nifs/common/prim_socket_nif.c
  erts/emulator/nifs/unix/unix_socket_syncio.c
  erts/preloaded/ebin/prim_socket.beam
  erts/preloaded/src/prim_socket.erl
  lib/kernel/src/inet_epmd_socket.erl
  lib/kernel/src/socket.erl
  lib/ssl/test/ssl_dist_bench_SUITE.erl
Labels: team:PS, feature

#9396 Renable optimization for appending 0 bits to a binary
  erts/emulator/beam/erl_bits.c
  erts/emulator/test/bs_construct_SUITE.erl
Labels: team:VM, enhancement, testing

#9330 erts: Remove erl.ini from Windows release
  erts/etc/win32/Install.c
  lib/sasl/test/systools_SUITE.erl
Labels: team:VM, enhancement, testing

#9403 Build debug emulator with -Og instead of -O0
  erts/configure
  erts/configure.ac
  erts/emulator/beam/bif.c
  erts/emulator/beam/erl_db_tree.c
  erts/emulator/beam/erl_nif.c
  erts/emulator/beam/erl_proc_sig_queue.c
  erts/emulator/beam/erl_rbtree.h
  erts/emulator/beam/erl_trace.c
Labels: team:VM, enhancement

#9399 Handle load_binary result in debugger int:load
  lib/debugger/src/int.erl
Labels: team:VM, testing

#9387 ssl: Improve error handling of sni_fun
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_gen_statem.erl
  lib/ssl/test/ssl_sni_SUITE.erl
Labels: team:PS, testing

#9398 Make socket useable directly
  lib/ssl/src/Makefile
  lib/ssl/src/ssl.app.src
  lib/ssl/src/ssl.erl
  lib/ssl/src/ssl_config.erl
  lib/ssl/src/ssl_gen_statem.erl
  lib/ssl/src/ssl_server_session_cache.erl
  lib/ssl/src/tls_client_connection.erl
  lib/ssl/src/tls_client_connection_1_3.erl
  lib/ssl/src/tls_dtls_gen_connection.erl
  lib/ssl/src/tls_gen_connection.erl
  lib/ssl/src/tls_record.erl
  lib/ssl/src/tls_record_1_3.erl
  lib/ssl/src/tls_sender.erl
  lib/ssl/src/tls_server_connection.erl
  lib/ssl/src/tls_server_connection_1_3.erl
  lib/ssl/src/tls_server_session_ticket.erl
  lib/ssl/src/tls_socket.erl
  lib/ssl/src/tls_socket_tcp.erl
  lib/ssl/test/openssl_cipher_suite_SUITE.erl
  lib/ssl/test/openssl_client_cert_SUITE.erl
  lib/ssl/test/openssl_renegotiate_SUITE.erl
  lib/ssl/test/openssl_server_cert_SUITE.erl
  lib/ssl/test/openssl_session_SUITE.erl
  lib/ssl/test/openssl_session_ticket_SUITE.erl
  lib/ssl/test/openssl_sni_SUITE.erl
  lib/ssl/test/openssl_stapling_SUITE.erl
  lib/ssl/test/openssl_tls_1_3_version_SUITE.erl
  lib/ssl/test/ssl_ECC_SUITE.erl
  lib/ssl/test/ssl_alpn_SUITE.erl
  lib/ssl/test/ssl_api_SUITE.erl
  lib/ssl/test/ssl_app_env_SUITE.erl
  lib/ssl/test/ssl_cert_SUITE.erl
  lib/ssl/test/ssl_cipher_suite_SUITE.erl
  lib/ssl/test/ssl_key_update_SUITE.erl
  lib/ssl/test/ssl_mfl_SUITE.erl
  lib/ssl/test/ssl_packet_SUITE.erl
  lib/ssl/test/ssl_payload_SUITE.erl
  lib/ssl/test/ssl_reject_SUITE.erl
  lib/ssl/test/ssl_renegotiate_SUITE.erl
  lib/ssl/test/ssl_session_SUITE.erl
  lib/ssl/test/ssl_session_ticket_SUITE.erl
  lib/ssl/test/ssl_sni_SUITE.erl
  lib/ssl/test/ssl_socket_SUITE.erl
  lib/ssl/test/ssl_test_lib.erl
  lib/ssl/test/tls_1_3_version_SUITE.erl
  lib/ssl/test/tls_api_SUITE.erl
Labels: team:PS

#9372 erts: Disable unsafe optimization in bs_append
  erts/emulator/beam/erl_bits.c
  erts/emulator/test/bs_construct_SUITE.erl
Labels: team:VM

#9420 Enable warn_missing_spec_documented in xmerl
  lib/xmerl/src/Makefile
  lib/xmerl/src/xmerl.erl
Labels: team:PS, testing

#9424 Reduce memory usage in io proxy process
  lib/common_test/src/test_server_gl.erl
Labels: team:PS, testing

#9431 Replace "on the form" with "of the form"
  erts/doc/guides/alt_dist.md
  erts/doc/references/epmd_cmd.md
  erts/emulator/beam/erl_driver.h
  erts/emulator/beam/erl_process.c
  erts/preloaded/src/erlang.erl
  lib/common_test/doc/guides/run_test_chapter.md
  lib/common_test/doc/guides/write_test_chapter.md
  lib/common_test/test_server/ts_run.erl
  lib/compiler/src/cerl.erl
  lib/compiler/src/cerl_trees.erl
  lib/compiler/src/compile.erl
  lib/dialyzer/test/options1_SUITE_data/src/compiler/sys_expand_pmod.erl
  lib/edoc/doc/guides/chapter.md
  lib/eunit/src/eunit_test.erl
  lib/kernel/doc/guides/logger_chapter.md
  lib/kernel/src/inet.erl
  lib/kernel/src/logger_formatter.erl
  lib/kernel/src/rpc.erl
  lib/kernel/src/socket.erl
  lib/mnesia/src/mnesia_index.erl
  lib/snmp/src/agent/snmpa_agent.erl
  lib/snmp/src/agent/snmpa_notification_delivery_info_receiver.erl
  lib/snmp/test/snmp_test_mgr_misc.erl
  lib/stdlib/src/erl_eval.erl
  lib/stdlib/src/gen_event.erl
  lib/stdlib/src/gen_fsm.erl
  lib/stdlib/src/gen_server.erl
  lib/stdlib/src/gen_statem.erl
  lib/stdlib/src/qlc_pt.erl
  lib/stdlib/src/rand.erl
  lib/stdlib/src/sys.erl
  lib/stdlib/test/ets_tough_SUITE.erl
  lib/syntax_tools/src/erl_syntax.erl
  lib/syntax_tools/src/prettypr.erl
  lib/tools/doc/references/erlang.el.md
  lib/tools/src/xref.erl
  system/doc/reference_manual/ref_man_processes.md
  system/doc/system_principles/versions.md
Labels: team:VM, fix, testing

#9409 otp: fix broken sarif generation
  scripts/scan-code.escript
Labels: team:VM

#9407 inets: fix httpd startup sequence
  lib/inets/src/http_server/httpd_instance_sup.erl
  lib/inets/src/http_server/httpd_request_handler.erl
Labels: team:PS, testing

#9442 gh: Update docker builds to use inline cache
  .github/scripts/build-base-image.sh
Labels: team:VM, enhancement

#8209 Fix BEAM crash from from port/NIF thread
  erts/emulator/beam/erl_process.c
  erts/emulator/beam/erl_process.h
Labels: team:VM, fix, testing

#9440 Mix format and windows CC fixes
  .formatter.exs
  Makefile.in
  erts/etc/win32/cygwin_tools/vc/cc.sh
  erts/etc/win32/msys_tools/vc/cc.sh
  erts/etc/win32/wsl_tools/vc/cc.sh
  lib/compiler/scripts/smoke-mix.exs
  lib/observer/doc/docs.exs
  lib/ssh/doc/docs.exs
  lib/stdlib/doc/docs.exs
  make/ex_doc.exs
  scripts/otp_check_html_links.exs
Labels: team:VM, fix, testing

#9421 erts: Minor spring cleaning
  erts/emulator/beam/beam_common.c
  erts/emulator/beam/beam_common.h
  erts/emulator/beam/erl_io_queue.c
  erts/emulator/beam/erl_io_queue.h
  erts/emulator/beam/erl_nif.c
  erts/emulator/beam/global.h
  erts/emulator/beam/jit/arm/beam_asm.hpp
  erts/emulator/beam/jit/arm/beam_asm_module.cpp
  erts/emulator/beam/jit/arm/instr_bif.cpp
  erts/emulator/beam/jit/arm/instr_bs.cpp
  erts/emulator/beam/jit/arm/instr_call.cpp
  erts/emulator/beam/jit/arm/instr_common.cpp
  erts/emulator/beam/jit/arm/instr_select.cpp
  erts/emulator/beam/jit/arm/instr_trace.cpp
  erts/emulator/beam/jit/beam_jit_args.hpp
  erts/emulator/beam/jit/beam_jit_main.cpp
  erts/emulator/beam/jit/beam_jit_register_cache.hpp
  erts/emulator/beam/jit/x86/beam_asm_module.cpp
  erts/emulator/beam/jit/x86/instr_arith.cpp
  erts/emulator/beam/jit/x86/instr_bif.cpp
  erts/emulator/beam/jit/x86/instr_bs.cpp
  erts/emulator/beam/jit/x86/instr_common.cpp
  erts/emulator/beam/jit/x86/instr_map.cpp
  erts/emulator/beam/jit/x86/instr_select.cpp
Labels: team:VM, testing

#9410 Add 'fips_provider_buildinfo' to crypto:info() map
  lib/crypto/c_src/crypto.c
  lib/crypto/c_src/info.c
  lib/crypto/src/crypto.erl
  lib/crypto/test/crypto_SUITE.erl
Labels: team:VM, enhancement, testing

#9119 fix(crypto): mac_context_dtor should free MAC
  lib/crypto/c_src/crypto.c
  lib/crypto/c_src/mac.c
  lib/crypto/c_src/mac.h
Labels: team:VM, enhancement, fix, testing

#9417 erts: Suppress various NULL-pointer warnings
  erts/emulator/beam/dist.c
  erts/emulator/beam/io.c
  erts/emulator/beam/sys.h
Labels: team:VM, testing

#9450 Fix debug emulator bugs for AArch64
  erts/emulator/beam/jit/arm/instr_bs.cpp
  erts/emulator/beam/jit/arm/instr_common.cpp
Labels: team:VM, fix, testing

#9447 zstd: Fix copy of dict binary to environment
  erts/emulator/nifs/common/zstd_nif.c
  erts/emulator/zstd/zstd.mk
  lib/stdlib/test/zstd_SUITE.erl
Labels: team:VM, fix, testing

#9418 ssl: Handle defaults on version change
  lib/ssl/src/ssl_config.erl
  lib/ssl/src/tls_v1.erl
Labels: team:PS, testing

#9451 erts: Remove faulty assert checking for DELAYED_DEL_PROC flag
  erts/emulator/beam/erl_process.c
Labels: team:VM, fix, testing

#9463 Fix a tail recursion bug
  lib/xmerl/src/xmerl_eventp.erl
  lib/xmerl/src/xmerl_regexp.erl
  lib/xmerl/src/xmerl_sax_parser_base.erlsrc
  lib/xmerl/src/xmerl_scan.erl
  lib/xmerl/src/xmerl_simple.erl
  lib/xmerl/src/xmerl_validate.erl
  lib/xmerl/src/xmerl_xpath_pred.erl
  lib/xmerl/src/xmerl_xsd.erl
  lib/xmerl/src/xmerl_xsd_type.erl
Labels: team:PS, testing

#9469 asn1: Fix several bugs in encoding and decoding of REALs
  lib/asn1/doc/guides/asn1_getting_started.md
  lib/asn1/src/asn1ct_gen_ber_bin_v2.erl
  lib/asn1/src/asn1rtt_real_common.erl
  lib/asn1/test/testPrim.erl
Labels: team:VM, fix, testing

#9406 erts: Introduce hibernate/0 and simplify hibernate/3
  erts/emulator/beam/beam_common.c
  erts/emulator/beam/bif.c
  erts/emulator/beam/emu/ops.tab
  erts/emulator/beam/emu/trace_instrs.tab
  erts/emulator/beam/erl_gc.c
  erts/emulator/beam/global.h
  erts/emulator/beam/jit/arm/instr_trace.cpp
  erts/emulator/beam/jit/arm/ops.tab
  erts/emulator/beam/jit/x86/instr_trace.cpp
  erts/emulator/beam/jit/x86/ops.tab
  erts/emulator/test/hello_SUITE_data/hello.erl
  erts/emulator/test/hibernate_SUITE.erl
  erts/preloaded/ebin/erlang.beam
  erts/preloaded/src/erlang.erl
Labels: team:VM, feature, testing

#9445 Feat: calendar:(universal/local)_time_to_system_time/1,2
  lib/stdlib/src/calendar.erl
  lib/stdlib/test/calendar_prop_SUITE.erl
  lib/stdlib/test/property_test/calendar_prop.erl
Labels: team:VM, testing

#9485 Fix updated runtime deps
  lib/xmerl/src/xmerl.app.src
Labels: team:PS, testing

#9489 Fix update_deprecations script
  lib/stdlib/scripts/update_deprecations
Labels: fix

#9432 Turn on no_opaque_union option by default in Dialyzer
  lib/dialyzer/src/dialyzer.hrl
  lib/dialyzer/src/dialyzer_cl_parse.erl
  lib/dialyzer/src/dialyzer_options.erl
  lib/dialyzer/test/opaque_SUITE_data/dialyzer_options
  lib/dialyzer/test/overspecs_SUITE_data/dialyzer_options
  lib/dialyzer/test/r9c_SUITE_data/dialyzer_options
  lib/dialyzer/test/underspecs_SUITE_data/dialyzer_options
  lib/dialyzer/test/user_SUITE_data/dialyzer_options
  scripts/run-dialyzer
Labels: team:VM, testing

#9269 Priority Messages
  .ort.yml
  bootstrap/lib/kernel/include/dist.hrl
  erts/doc/guides/erl_dist_protocol.md
  erts/emulator/beam/atom.names
  erts/emulator/beam/bif.c
  erts/emulator/beam/bif.h
  erts/emulator/beam/bif.tab
  erts/emulator/beam/break.c
  erts/emulator/beam/dist.c
  erts/emulator/beam/dist.h
  erts/emulator/beam/erl_alloc.types
  erts/emulator/beam/erl_bif_info.c
  erts/emulator/beam/erl_etp.c
  erts/emulator/beam/erl_gc.c
  erts/emulator/beam/erl_message.h
  erts/emulator/beam/erl_monitor_link.c
  erts/emulator/beam/erl_monitor_link.h
  erts/emulator/beam/erl_nif.c
  erts/emulator/beam/erl_node_tables.c
  erts/emulator/beam/erl_proc_sig_queue.c
  erts/emulator/beam/erl_proc_sig_queue.h
  erts/emulator/beam/erl_process.c
  erts/emulator/beam/erl_process.h
  erts/emulator/beam/erl_time_sup.c
  erts/emulator/beam/external.c
  erts/emulator/beam/io.c
  erts/emulator/test/exception_SUITE.erl
  erts/emulator/test/receive_SUITE.erl
  erts/emulator/test/signal_SUITE.erl
  erts/etc/unix/etp-commands.in
  erts/preloaded/ebin/erlang.beam
  erts/preloaded/src/erlang.erl
  lib/kernel/include/dist.hrl
  lib/kernel/src/dist_util.erl
  lib/kernel/src/erl_erts_errors.erl
  lib/stdlib/src/erl_internal.erl
  system/doc/Makefile
  system/doc/assets/.gitignore
  system/doc/efficiency_guide/eff_guide_processes.md
  system/doc/general_info/deprecations_28.md
  system/doc/general_info/scheduled_for_removal_30.md
  system/doc/reference_manual/assets/prio-msg-recv.png
  system/doc/reference_manual/expressions.md
  system/doc/reference_manual/ref_man_processes.md
Labels: team:VM, feature, testing

#9408 Use eep48 "group" to group functions in OTP documentation and shell completion
  HOWTO/DOCUMENTATION.md
  erts/preloaded/src/erl_tracer.erl
  lib/common_test/src/ct_hooks.erl
  lib/common_test/src/ct_suite.erl
  lib/compiler/test/compile_SUITE_data/ssh.erl
  lib/compiler/test/compile_SUITE_data/ssh.hrl
  lib/crypto/src/crypto.erl
  lib/ftp/src/ftp.erl
  lib/inets/src/http_server/httpd.erl
  lib/inets/src/http_server/mod_esi.erl
  lib/kernel/src/application.erl
  lib/kernel/src/gen_sctp.erl
  lib/kernel/src/inet.erl
  lib/kernel/src/inet_res.erl
  lib/kernel/src/logger.erl
  lib/kernel/src/logger_formatter.erl
  lib/kernel/test/interactive_shell_SUITE.erl
  lib/odbc/src/odbc.erl
  lib/parsetools/src/leex.erl
  lib/public_key/src/public_key.erl
  lib/sasl/src/release_handler.erl
  lib/snmp/src/agent/snmpa_mib_data.erl
  lib/snmp/src/agent/snmpa_mib_storage.erl
  lib/ssh/src/ssh.erl
  lib/ssh/src/ssh.hrl
  lib/ssh/src/ssh_agent.erl
  lib/ssh/src/ssh_connection.erl
  lib/ssh/src/ssh_file.erl
  lib/ssh/src/ssh_sftp.erl
  lib/ssl/src/ssl.erl
  lib/stdlib/src/edlin_expand.erl
  lib/stdlib/src/gen_fsm.erl
  lib/stdlib/src/queue.erl
  lib/stdlib/src/rand.erl
  lib/stdlib/src/string.erl
  lib/stdlib/src/sys.erl
  lib/stdlib/src/zip.erl
  lib/stdlib/test/edlin_expand_SUITE.erl
  lib/tftp/src/tftp.erl
  lib/tools/src/lcnt.erl
  make/ex_doc.exs
Labels: team:VM, testing

#9499 mnesia: Discard old irrelevant msgs
  lib/mnesia/src/mnesia_controller.erl
Labels: team:PS

#9464 Polish documentation for the lists module
  lib/stdlib/src/lists.erl
Labels: team:VM, enhancement

#9484 Improve json decode error messages
  lib/stdlib/src/erl_stdlib_errors.erl
  lib/stdlib/src/json.erl
  lib/stdlib/test/json_SUITE.erl
Labels: team:PS, testing

#9478 erts: fix sub binary bug in erl_bif_re
  erts/emulator/beam/erl_bif_re.c
  lib/stdlib/test/re_SUITE.erl
Labels: team:VM, fix, testing

#9496 gh: Enable running on freebsd
  .github/workflows/main.yaml
Labels: team:VM

#9465 stdlib: Fix linter crash from invalid zip generators
  lib/stdlib/src/erl_lint.erl
  lib/stdlib/test/erl_lint_SUITE.erl
Labels: team:VM, testing

#9506 Make sure gcov-emulator produce results
  HOWTO/DEVELOPMENT.md
  erts/emulator/beam/erl_init.c
Labels: team:VM, testing

#7970 `ets`: add ability to suppress heir/gift data
  erts/emulator/beam/erl_db.c
  erts/emulator/beam/erl_db_util.h
  lib/stdlib/src/ets.erl
  lib/stdlib/test/ets_SUITE.erl
Labels: team:VM, enhancement, testing

#9433 kernel: Fix `code:get_doc/1,2` when cover_compiled
  lib/compiler/test/beam_doc_SUITE.erl
  lib/compiler/test/beam_doc_SUITE_data/cover_compiled.erl
  lib/kernel/src/code.erl
Labels: team:VM, testing

#9505 Fix documented return value
  erts/emulator/sys/win32/sys.c
Labels: team:VM, fix, testing

#9474 spelling: "hopeful"
  erts/emulator/beam/dist.h
  erts/emulator/beam/external.c
  erts/emulator/test/distribution_SUITE.erl
Labels: team:VM, fix, testing
