Repository erlang/otp, pull requests merged in 2025-09, with the labels that each got.

#10113 Optional MADV_DONTNEED
  erts/doc/references/erts_alloc.md
  erts/emulator/beam/erl_alloc.c
  erts/emulator/beam/erl_alloc_util.c
  erts/emulator/beam/erl_alloc_util.h
  erts/emulator/sys/common/erl_mmap.c
  erts/emulator/sys/common/erl_mmap.h
  erts/etc/common/erlexec.c
Labels: team:VM, feature, testing

#9815 diameter: Call message_cb 'ack' with updated callback
  lib/diameter/src/transport/diameter_sctp.erl
  lib/diameter/src/transport/diameter_tcp.erl
  lib/diameter/test/diameter_transport_SUITE.erl
Labels: team:PS, testing

#10112 Introduce option list for `inet res` functions
  lib/kernel/src/inet_res.erl
  lib/kernel/test/inet_res_SUITE.erl
Labels: team:PS, feature, in progress, priority:medium

#10144 Eliminate the set_tuple_element instruction
  erts/emulator/beam/jit/arm/instr_common.cpp
  erts/emulator/beam/jit/x86/instr_common.cpp
  lib/compiler/src/beam_ssa_opt.erl
  lib/compiler/src/beam_ssa_pre_codegen.erl
  lib/compiler/src/beam_validator.erl
  lib/compiler/src/genop.tab
  lib/compiler/test/beam_validator_SUITE.erl
  lib/compiler/test/beam_validator_SUITE_data/bad_dsetel.S
  lib/compiler/test/bif_SUITE.erl
  lib/compiler/test/bif_SUITE_data/test_setelement.erl
Labels: team:VM, testing

#10070 [mnesia] Slave module deprecation: Replace slave to peer in code and comments
  lib/mnesia/examples/bench/README
  lib/mnesia/examples/bench/bench.erl
  lib/mnesia/test/README
Labels: team:PS

#10122 Fix debug crash in erts_validate_stack()
  erts/emulator/beam/beam_bp.c
  erts/emulator/beam/beam_bp.h
  erts/emulator/beam/erl_gc.c
  erts/emulator/beam/erl_gc.h
  erts/emulator/beam/erl_trace.c
  erts/emulator/beam/erl_trace.h
  erts/emulator/beam/jit/arm/beam_asm.hpp
  erts/emulator/beam/jit/arm/instr_call.cpp
  erts/emulator/beam/jit/arm/instr_trace.cpp
  erts/emulator/beam/jit/x86/beam_asm.hpp
  erts/emulator/beam/jit/x86/instr_call.cpp
  erts/emulator/beam/jit/x86/instr_trace.cpp
Labels: team:VM, fix, testing

#10154 Minor fixes to our PCRE2 integration
  erts/emulator/pcre/README.pcre_update.md
  erts/emulator/pcre/pcre2_serialize.c
Labels: team:VM, testing, documentation

#10145 Verification of GH Securities included in OpenVEX statements
  .github/scripts/otp-compliance.es
  .github/workflows/main.yaml
  .github/workflows/osv-scanner-scheduled.yml
  .github/workflows/reusable-vendor-vulnerability-scanner.yml
  make/openvex.table
  vex/otp-26.openvex.json
  vex/otp-27.openvex.json
Labels: team:VM

#10153 Fix minor `beam_debug_info` issues
  lib/compiler/src/beam_core_to_ssa.erl
  lib/compiler/src/beam_ssa_codegen.erl
  lib/compiler/src/v3_core.erl
Labels: team:VM, testing

#10166 fix detection of modified vendor files
  .github/workflows/main.yaml
Labels: team:VM, bug

#10115 Use the standard kex-strict-* identifier in the kex_algorithms field
  lib/ssh/src/ssh_transport.erl
  lib/ssh/src/ssh_transport.hrl
  lib/ssh/test/ssh_protocol_SUITE.erl
Labels: team:PS, testing

#10148 michal/observer/fix-zero-fault-issue-in-etop-suite
  lib/observer/src/etop.erl
  lib/observer/test/etop_SUITE.erl
Labels: team:PS, testing

#10156 ssh: dummy commit for dummy PR
  lib/ssh/src/ssh_sftpd.erl
Labels: team:PS

#10118 syntax_tools: Backport fix for annotating maybe to OTP-27
  lib/syntax_tools/src/erl_syntax_lib.erl
  lib/syntax_tools/test/syntax_tools_SUITE.erl
Labels: team:VM

#10186 michal/mnesia/add-missing-documentation-about-activity/OTP-19769
  lib/mnesia/src/mnesia.erl
Labels: team:PS, testing

#10201 ssl: Correct connection state handling in TLS sender
  lib/ssl/src/tls_gen_connection.erl
  lib/ssl/src/tls_record.erl
  lib/ssl/src/tls_sender.erl
Labels: team:PS

#10226 fix scanner and vex statements for next release
  .github/scripts/otp-compliance.es
  .github/workflows/reusable-vendor-vulnerability-scanner.yml
  make/openvex.table
  vex/otp-28.openvex.json
  vex/otp-29.openvex.json
  vex/otp-29.openvex.json.license
Labels: team:VM

#8309 stdlib: keep leading slash in absolute ustar filename prefixes
  lib/stdlib/src/erl_tar.erl
  lib/stdlib/test/tar_SUITE.erl
Labels: team:VM, fix, testing

#10228 compiler: Add +to_abstr flag to match +from_abstr
  lib/compiler/src/compile.erl
  lib/compiler/test/compile_SUITE.erl
Labels: team:VM, testing

#10134 Refactor kernel_load_completed clause for conciseness
  erts/preloaded/src/init.erl
Labels: team:VM, testing

#10239 Use wxwidgets 3.2.8.1 for CI MacOS build for it has fp.h problem fixed
  .github/scripts/build-macos-wxwidgets.sh
  .github/workflows/main.yaml
Labels: team:PS

#9983 erts: fix static function prototypes
  erts/emulator/test/nif_SUITE_data/nif_SUITE.c
  erts/emulator/test/port_SUITE_data/port_test.c
  erts/emulator/test/port_bif_SUITE_data/port_test.c
Labels: team:VM

#10149 Michal/diameter/fix-inheriting-of-indirect-inherits/otp-19626
  lib/diameter/bin/diameterc
  lib/diameter/doc/references/diameter_dict.md
  lib/diameter/doc/references/diameterc_cmd.md
  lib/diameter/src/compiler/diameter_codegen.erl
  lib/diameter/src/compiler/diameter_dict_util.erl
  lib/diameter/src/compiler/diameter_make.erl
  lib/diameter/test/diameter_codegen_SUITE.erl
  lib/diameter/test/diameter_compiler_SUITE.erl
  lib/diameter/test/diameter_indirect_inherits_SUITE.erl
  lib/diameter/test/modules.mk
Labels: team:PS, testing
